<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Professor Davi Moreira ">
  <title>QM 67000: Business Analytics –  QM 67000: Business Analytics </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-8fc47a4fdcba9931a3aa90ef56f89358.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="font-size: 100%;"> QM 67000: Business Analytics </span></h1>
  <p class="subtitle"><span style="font-size: 150%;"> Hypothesis Testing I: Inference About One Population </span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor<br>Davi Moreira<br> 
</div>
</div>
</div>

</section>
<section id="overview" class="slide level2 center">
<h2>Overview</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Case Spotlight: A/B Testing at Vungle</li>
<li>From estimating to <strong>testing</strong> a claim</li>
<li>Developing <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_a\)</span>; the skeptic’s burden of proof</li>
<li>Type I and Type II errors; the level of significance <span class="math inline">\(\alpha\)</span></li>
<li>The <span class="math inline">\(p\)</span>-value and critical-value approaches</li>
</ul>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li><strong>Lecture 1:</strong> one-sample <span class="math inline">\(t\)</span> about a <strong>mean</strong> (is B’s eRPM above $3.30?)</li>
<li><strong>Lecture 2:</strong> one-sample <span class="math inline">\(z\)</span> about a <strong>proportion</strong> (does B clear the conversion target?)</li>
<li>Reading <span class="math inline">\(p\)</span>-values like a manager</li>
<li>The rule that sets up Topic 9: testing <strong>two</strong> populations</li>
</ul>
</div></div>
</section>
<section>
<section id="case-spotlight-ab-testing-at-vungle" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Case Spotlight: A/B Testing at Vungle</h1>

</section>
<section id="june-2014-one-month-of-data-one-funding-decision" class="slide level2 center">
<h2>June 2014: One Month of Data, One Funding Decision</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Vungle</strong> is a mobile ad-tech startup: it serves 15-second video ads inside other companies’ apps and earns revenue mainly when a viewer <strong>installs</strong> the advertised app (cost-per-install).</p></li>
<li class="fragment"><p>Two analysts built a new ad-serving algorithm (<strong>B</strong>) and ran it head-to-head against the existing one (<strong>A</strong>) for the entire month of June 2014. The metric that pays the bills is <strong>eRPM</strong>, effective revenue per 1,000 impressions.</p></li>
<li class="fragment"><p>We have already <strong>described</strong> the data (Topics 1–2) and <strong>estimated</strong> B’s true mean eRPM with a confidence interval (Topic 7). Now, as Vungle’s manager, you need a <strong>yes/no decision</strong>.</p></li>
<li class="fragment"><p>Up to now we asked <em>“what is B’s true eRPM?”</em> Today we ask a sharper question: <em>“is it above a line we care about?”</em>, and we answer with a <strong>test</strong>.</p></li>
</ul>
</section>
<section id="the-brief-roll-out-b-or-stay-with-a" class="slide level2 center">
<h2>The Brief: Roll Out B, or Stay With A?</h2>
<p><br></p>
<blockquote>
<p>“We fund <strong>algorithm B</strong> only if its mean eRPM clears the historical <strong>$3.30 benchmark</strong> that algorithm A has long delivered. B’s 30-day average looks like $3.46, but is that <strong>really</strong> above $3.30, or could a sample of 30 noisy days land there by luck? <strong>Test it.</strong>”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p>The big call is <em>roll out B, or stay with A?</em> This topic answers the first piece of it. <strong>Today’s question:</strong> <em>is the mean really above the benchmark?</em></p></li>
<li class="fragment"><p>This is the canonical one-population question in business: <strong>is a parameter on the right side of a line?</strong> A benchmark, a target, a contractual threshold.</p></li>
<li class="fragment"><p><strong>How today’s studio runs:</strong> I demo each test on a textbook example, then a good analyst’s work goes up for you to reproduce and interrogate, then we debrief the funding call together. Two lectures, two tests.</p></li>
<li class="fragment"><p>By the end, <strong>you</strong> make the funding recommendation, with the statistics to back it up.</p></li>
</ul>
</section>
<section id="estimation-vs.-testing-two-jobs-for-the-same-sample" class="slide level2 center">
<h2>Estimation vs.&nbsp;Testing: Two Jobs for the Same Sample</h2>
<p><br></p>
<ul>
<li class="fragment"><p>In Topic 7 we <strong>estimated</strong>: built a confidence interval, a range of plausible values for B’s true mean eRPM.</p></li>
<li class="fragment"><p>Today we <strong>test</strong>: weigh the evidence for a <strong>specific claim</strong> about that mean.</p></li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Interval estimation (Topic 7)</th>
<th>Hypothesis testing (today)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Question</td>
<td>What is the parameter?</td>
<td>Is the parameter on one side of a line?</td>
</tr>
<tr class="even">
<td>Output</td>
<td>A range (the CI)</td>
<td>A decision: reject <span class="math inline">\(H_0\)</span> or not</td>
</tr>
<tr class="odd">
<td>Knob you set</td>
<td>Confidence level <span class="math inline">\(1-\alpha\)</span></td>
<td>Significance level <span class="math inline">\(\alpha\)</span> (the risk you accept)</td>
</tr>
<tr class="even">
<td>The “answer”</td>
<td>Margin of error</td>
<td><span class="math inline">\(p\)</span>-value / critical value</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment">They are two views of the <strong>same</strong> sampling logic, and we will see at the end they agree.</li>
</ul>
</section></section>
<section>
<section id="developing-the-hypotheses" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Developing the Hypotheses</h1>

</section>
<section id="h_0-is-on-trial-the-skeptics-position" class="slide level2 center">
<h2><span class="math inline">\(H_0\)</span> Is on Trial: the Skeptic’s Position</h2>

<img data-src="figs/h0_courtroom.png" class="quarto-figure quarto-figure-center r-stretch" style="width:72.0%"><ul>
<li>The <strong>null hypothesis</strong> <span class="math inline">\(H_0\)</span> is the status quo: <em>“nothing new here, B is no better than the $3.30 line.”</em> It is assumed true until the data overturn it.</li>
<li>The <strong>alternative</strong> <span class="math inline">\(H_a\)</span> is the research claim (<em>“B beats $3.30”</em>), accepted <strong>only</strong> with strong evidence. The data carry the burden of proof.</li>
</ul>
</section>
<section id="which-claim-goes-where" class="slide level2 center">
<h2>Which Claim Goes Where?</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Rule:</strong> put what you <strong>want to prove</strong> in <span class="math inline">\(H_a\)</span>; the equality always lives in <span class="math inline">\(H_0\)</span>.</p></li>
<li class="fragment"><p>Two ways the question arrives in business:</p>
<ul>
<li class="fragment"><strong>Research hypothesis:</strong> gather evidence <em>for</em> something new (new algorithm, new bonus plan, new drug). Start with <span class="math inline">\(H_a\)</span>: <em>“the new thing works.”</em></li>
<li class="fragment"><strong>Challenge an assumption:</strong> test whether a long-held claim still holds (a label says 67.6 oz; a goal is 12 minutes). Start with <span class="math inline">\(H_0\)</span>: <em>“the claim is true.”</em></li>
</ul></li>
<li class="fragment"><p>Vungle is a <strong>research</strong> case: we want evidence that B clears $3.30, so that claim is <span class="math inline">\(H_a\)</span>.</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
H_0: \mu \leq 3.30 \qquad \text{vs.} \qquad H_a: \mu &gt; 3.30
\]</span></p>
</div>
</section>
<section id="a-question-that-often-comes-up" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">We are hoping B beats $3.30, so why is “B beats $3.30” the alternative and not the null?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> the test makes the data earn the conclusion. We start by assuming B is <strong>no better</strong> (<span class="math inline">\(H_0\)</span>) and only fund B if the evidence is strong enough to overturn that. Putting the claim we want in <span class="math inline">\(H_a\)</span> means a “fund B” verdict survives a skeptic’s challenge, not just a hopeful read of one good month.</p>
</div>
</div>
</section>
<section id="three-forms-the-business-question-picks-the-tail" class="slide level2 center">
<h2>Three Forms: the Business Question Picks the Tail</h2>

<img data-src="figs/hypothesis_forms.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><ul>
<li><strong>Upper-tail</strong> (Vungle): we only act if B is <strong>better</strong>; “worse” and “same” lead to the same decision (don’t fund).</li>
<li><strong>Lower-tail</strong>: we act if the parameter falls <strong>below</strong> a line (a defect rate above a ceiling, response time over a goal).</li>
<li><strong>Two-tailed</strong>: any <strong>difference</strong> matters (a fill weight that is too high <em>or</em> too low).</li>
</ul>
</section>
<section id="the-three-forms-in-symbols" class="slide level2 center">
<h2>The Three Forms in Symbols</h2>
<p><br></p>
<ul>
<li class="fragment">For a population <strong>mean</strong> <span class="math inline">\(\mu\)</span> against a hypothesized value <span class="math inline">\(\mu_0\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\begin{aligned}
\text{Lower-tail:} \quad &amp; H_0: \mu \geq \mu_0 \quad &amp;&amp;H_a: \mu &lt; \mu_0 \\
\text{Upper-tail:} \quad &amp; H_0: \mu \leq \mu_0 \quad &amp;&amp;H_a: \mu &gt; \mu_0 \\
\text{Two-tailed:} \quad &amp; H_0: \mu = \mu_0 \quad &amp;&amp;H_a: \mu \neq \mu_0
\end{aligned}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>The <strong>equality</strong> (<span class="math inline">\(=\)</span>, <span class="math inline">\(\leq\)</span>, <span class="math inline">\(\geq\)</span>) is always part of <span class="math inline">\(H_0\)</span>: it is the value we compute the test statistic <em>against</em>.</p></li>
<li class="fragment"><p>The direction of <span class="math inline">\(H_a\)</span> comes from the <strong>business decision</strong>, not from peeking at the data.</p></li>
</ul>
</section></section>
<section>
<section id="two-ways-to-be-wrong" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Two Ways to Be Wrong</h1>

</section>
<section id="type-i-and-type-ii-errors" class="slide level2 center">
<h2>Type I and Type II Errors</h2>

<img data-src="figs/type_I_II_errors_studio.png" class="quarto-figure quarto-figure-center r-stretch" style="width:62.0%"><ul>
<li><strong>Type I error:</strong> reject <span class="math inline">\(H_0\)</span> when it is true (fund B though it really <em>isn’t</em> above $3.30, a costly false alarm).</li>
<li><strong>Type II error:</strong> fail to reject <span class="math inline">\(H_0\)</span> when it is false (<em>miss</em> a genuinely better B, a missed opportunity).</li>
</ul>
</section>
<section id="you-control-alpha-beta-follows" class="slide level2 center">
<h2>You Control <span class="math inline">\(\alpha\)</span>; <span class="math inline">\(\beta\)</span> Follows</h2>
<p><br></p>
<ul>
<li class="fragment"><p>The <strong>level of significance</strong> <span class="math inline">\(\alpha\)</span> = the probability of a <strong>Type I error</strong> you are willing to tolerate. You set it <strong>before</strong> seeing the data; usually <span class="math inline">\(\alpha = 0.05\)</span> (sometimes <span class="math inline">\(0.01\)</span> or <span class="math inline">\(0.10\)</span>).</p></li>
<li class="fragment"><p><span class="math inline">\(\beta\)</span> = the probability of a <strong>Type II error</strong>. You do <strong>not</strong> set it directly; it follows from <span class="math inline">\(\alpha\)</span>, the sample size, and how far the truth is from <span class="math inline">\(H_0\)</span>.</p></li>
<li class="fragment"><p><strong>The trade-off:</strong> for a fixed sample, lowering <span class="math inline">\(\alpha\)</span> (fewer false alarms) <strong>raises</strong> <span class="math inline">\(\beta\)</span> (more missed effects). The only way to shrink both is a <strong>larger sample</strong>.</p></li>
<li class="fragment"><p><strong>Language rule:</strong> when the evidence is weak we say <em>“fail to reject <span class="math inline">\(H_0\)</span>,”</em> never <em>“accept <span class="math inline">\(H_0\)</span>.”</em> Absence of proof is not proof of absence; we just did not gather enough evidence to overturn the skeptic.</p></li>
</ul>
</section>
<section id="why-the-asymmetry-matters-for-vungle" class="slide level2 center">
<h2>Why the Asymmetry Matters for Vungle</h2>
<p><br></p>
<ul>
<li class="fragment"><p>A <strong>Type I error</strong> funds an algorithm that is not actually better: the company spends on a non-improvement and the analyst’s credibility takes the hit.</p></li>
<li class="fragment"><p>A <strong>Type II error</strong> walks away from a real improvement: money left on the table, but no bad rollout.</p></li>
<li class="fragment"><p>As the manager you decide which mistake is worse and set <span class="math inline">\(\alpha\)</span> accordingly. Here a false “fund it” is the headline risk, so we hold <span class="math inline">\(\alpha = 0.05\)</span>.</p></li>
<li class="fragment"><p>This is why <span class="math inline">\(H_0\)</span> is conservative: the test protects the <strong>status quo</strong> until the evidence is strong enough to justify the change.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-1" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If a Type I error funds a dud algorithm, why not set <span class="math inline">\(\alpha\)</span> to something tiny like 0.001 and never have a false alarm?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> because shrinking <span class="math inline">\(\alpha\)</span> raises <span class="math inline">\(\beta\)</span>. Demand near-impossible evidence and you will also miss a B that genuinely beats $3.30 (a real improvement left unfunded). With June’s 30 days fixed, you cannot drive both risks to zero; <span class="math inline">\(\alpha = 0.05\)</span> is the balance Vungle is choosing between a false “fund it” and a missed winner.</p>
</div>
</div>
</section></section>
<section>
<section id="lecture-1-one-sample-test-about-a-mean" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 1: One-Sample Test About a Mean</h1>

</section>
<section id="the-brief-is-the-mean-really-above-the-benchmark" class="slide level2 center">
<h2>The Brief: Is the Mean Really Above the Benchmark?</h2>
<p><br></p>
<ul>
<li class="fragment"><p>The big call is <em>roll out B, or stay with A?</em> <strong>Lecture 1’s piece:</strong> <em>is B’s mean eRPM really above the $3.30 benchmark, or could a noisy 30-day sample land there by luck?</em></p></li>
<li class="fragment"><p>We do <strong>not</strong> know the true population standard deviation <span class="math inline">\(\sigma\)</span> of B’s daily eRPM, so we estimate it from the sample with <span class="math inline">\(s\)</span> and use the <strong><span class="math inline">\(t\)</span>-distribution</strong>.</p></li>
<li class="fragment"><p>The decision is asymmetric (fund only if <strong>better</strong>), so it is an <strong>upper-tail</strong> test:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
H_0: \mu \leq 3.30 \qquad \text{vs.} \qquad H_a: \mu &gt; 3.30 \qquad \alpha = 0.05
\]</span></p>
</div>
<ul>
<li class="fragment"><p><span class="math inline">\(\mu\)</span> = the <strong>true</strong> mean daily eRPM B would deliver across <em>all</em> future traffic; the 30 June days are our sample.</p></li>
<li class="fragment"><p><strong>Today’s plan:</strong> demo the mechanics on a textbook airport-rating case, then a good analyst’s work on Vungle goes up for you to reproduce and stress-test.</p></li>
</ul>
</section>
<section id="how-every-class-runs" class="slide level2 center">
<h2>How Every Class Runs</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/lecture_dynamic.png" class="quarto-figure quarto-figure-center" style="width:90.0%"></p>
</figure>
</div>
<p>The class <strong>ends on the Team Sprint</strong>, your group’s graded submission: a decision plus your read of the analysis, one PDF before you leave.</p>
</section>
<section id="the-test-statistic-how-many-standard-errors-above-the-line" class="slide level2 center">
<h2>The Test Statistic: How Many Standard Errors Above the Line?</h2>
<p><br></p>
<ul>
<li class="fragment">The <span class="math inline">\(t\)</span> statistic measures how far the sample mean sits from <span class="math inline">\(\mu_0\)</span>, in <strong>standard-error units</strong>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}}, \qquad df = n - 1
\]</span></p>
</div>
<ul>
<li class="fragment"><p><span class="math inline">\(\bar{x}\)</span> = sample mean · <span class="math inline">\(\mu_0\)</span> = the benchmark in <span class="math inline">\(H_0\)</span> · <span class="math inline">\(s\)</span> = sample standard deviation · <span class="math inline">\(n\)</span> = sample size.</p></li>
<li class="fragment"><p>A <strong>big</strong> <span class="math inline">\(t\)</span> means the sample mean is many standard errors above the line: hard to explain as luck if <span class="math inline">\(H_0\)</span> were true.</p></li>
<li class="fragment"><p>Because <span class="math inline">\(\sigma\)</span> is unknown and replaced by <span class="math inline">\(s\)</span>, the statistic follows a <strong><span class="math inline">\(t\)</span> distribution</strong> with <span class="math inline">\(n-1\)</span> degrees of freedom (slightly heavier tails than the normal).</p></li>
</ul>
</section>
<section id="if-sigma-were-known-the-z-version-of-the-same-test" class="slide level2 center">
<h2>If <span class="math inline">\(\sigma\)</span> Were Known: the <span class="math inline">\(z\)</span> Version of the Same Test</h2>
<p><br></p>
<ul>
<li class="fragment">Sometimes a long process history pins down the <strong>true</strong> standard deviation <span class="math inline">\(\sigma\)</span>. Then you do not estimate the spread, so there is no extra uncertainty and the statistic is a <strong><span class="math inline">\(z\)</span></strong> on the standard normal:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Same five steps, same two roads, only the reference curve changes. Excel: <code>=NORM.S.INV(1-α)</code> for the critical <span class="math inline">\(z\)</span> (<span class="math inline">\(z_{0.05} = 1.645\)</span>); <code>=1-NORM.S.DIST(z, TRUE)</code> for an upper-tail <span class="math inline">\(p\)</span>-value.</p></li>
<li class="fragment"><p><strong>The decision rule:</strong> is <span class="math inline">\(\sigma\)</span> known? If yes (and <span class="math inline">\(n \geq 30\)</span> or the data look normal), use <span class="math inline">\(z\)</span>. If no, estimate it with <span class="math inline">\(s\)</span> and use <span class="math inline">\(t\)</span> with <span class="math inline">\(df = n-1\)</span>. In practice <span class="math inline">\(\sigma\)</span> is almost never known, so B’s eRPM test uses <span class="math inline">\(t\)</span>; we show <span class="math inline">\(z\)</span> so the textbook formula is on the record.</p></li>
</ul>
</section>
<section id="two-roads-to-the-same-decision" class="slide level2 center">
<h2>Two Roads to the Same Decision</h2>
<p><br></p>
<ul>
<li class="fragment"><strong>Critical-value approach:</strong> compare <span class="math inline">\(t\)</span> to a cutoff <span class="math inline">\(t_{\alpha, n-1}\)</span> from the <span class="math inline">\(t\)</span>-distribution.</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\begin{aligned}
\text{Lower-tail:} \;&amp; \text{reject } H_0 \text{ if } t \leq -t_{\alpha,\,n-1} \\
\text{Upper-tail:} \;&amp; \text{reject } H_0 \text{ if } t \geq t_{\alpha,\,n-1} \\
\text{Two-tailed:} \;&amp; \text{reject } H_0 \text{ if } |t| \geq t_{\alpha/2,\,n-1}
\end{aligned}
\]</span></p>
</div>
<ul>
<li class="fragment"><p><strong><span class="math inline">\(p\)</span>-value approach:</strong> compute the probability, <em>if <span class="math inline">\(H_0\)</span> were true</em>, of a test statistic at least this extreme, then reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p \leq \alpha\)</span>.</p></li>
<li class="fragment"><p>Both always agree. Excel: <code>=T.INV(1-α, df)</code> for the critical value, <code>=T.DIST.RT(t, df)</code> for an upper-tail <span class="math inline">\(p\)</span>-value.</p></li>
</ul>
</section>
<section id="what-the-p-value-actually-means" class="slide level2 center">
<h2>What the <span class="math inline">\(p\)</span>-Value Actually Means</h2>
<p><br></p>
<ul>
<li class="fragment"><p>The <span class="math inline">\(p\)</span>-value is <strong><span class="math inline">\(P(\text{evidence this extreme} \mid H_0 \text{ true})\)</span></strong>, <em>not</em> the probability that <span class="math inline">\(H_0\)</span> is true.</p></li>
<li class="fragment"><p>Read it as: <em>“if B were really only at the $3.30 line, how often would 30 days look this good by luck?”</em> Small <span class="math inline">\(p\)</span> <span class="math inline">\(\Rightarrow\)</span> that luck is implausible <span class="math inline">\(\Rightarrow\)</span> doubt <span class="math inline">\(H_0\)</span>.</p></li>
<li class="fragment"><p>A manager’s verbal scale for the strength of evidence against <span class="math inline">\(H_0\)</span>:</p></li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\(p\)</span>-value</th>
<th>Strength of evidence against <span class="math inline">\(H_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p \leq 0.01\)</span></td>
<td><strong>Overwhelming</strong></td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.01 &lt; p \leq 0.05\)</span></td>
<td><strong>Strong</strong></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0.05 &lt; p \leq 0.10\)</span></td>
<td><strong>Weak / suggestive</strong></td>
</tr>
<tr class="even">
<td><span class="math inline">\(p &gt; 0.10\)</span></td>
<td><strong>Insufficient</strong></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="a-question-that-often-comes-up-2" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If B’s test gives <span class="math inline">\(p = 0.009\)</span>, doesn’t that mean there’s only a 0.9% chance B is no better than $3.30?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> no, and this is the slip to avoid. The 0.9% is the chance of seeing 30 days <strong>this good or better</strong> <em>if</em> B were really only at $3.30. It is <span class="math inline">\(P(\text{data} \mid H_0)\)</span>, not <span class="math inline">\(P(H_0 \mid \text{data})\)</span>. The data are the random thing here, not the truth about B. A small <span class="math inline">\(p\)</span> makes “no better” hard to believe; it does not put a probability on the claim itself.</p>
</div>
</div>
</section>
<section id="anchor-example-heathrow-superior-service-rating" class="slide level2 center">
<h2>Anchor Example: Heathrow Superior-Service Rating</h2>
<p><br></p>
<p>A travel magazine rates airports 0–10; an airport is labeled <strong>“superior service”</strong> only if its <strong>true mean</strong> rating exceeds <strong>7</strong>. A sample of <strong>60</strong> business travelers at London Heathrow gives <span class="math inline">\(\bar{x} = 7.25\)</span>, <span class="math inline">\(s = 1.052\)</span>.</p>
<p><br></p>
<ul>
<li class="fragment">We want evidence that the mean <strong>exceeds 7</strong> <span class="math inline">\(\rightarrow\)</span> upper-tail, <span class="math inline">\(\sigma\)</span> unknown <span class="math inline">\(\rightarrow\)</span> one-sample <span class="math inline">\(t\)</span>.</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
H_0: \mu \leq 7 \qquad H_a: \mu &gt; 7 \qquad \alpha = 0.05
\]</span></p>
</div>
</section>
<section id="heathrow-the-five-steps" class="slide level2 center">
<h2>Heathrow: the Five Steps</h2>
<div class="r-fit-text">
<p><strong>1. Business context.</strong> Classify the airport; only a true mean above 7 earns the “superior service” badge.</p>
<p><strong>2. Hypotheses</strong> (upper-tail): <span class="math inline">\(H_0: \mu \leq 7\)</span> vs.&nbsp;<span class="math inline">\(H_a: \mu &gt; 7\)</span>, <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p><strong>3. Test statistic.</strong></p>
<p><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s/\sqrt{n}} = \frac{7.25 - 7}{1.052/\sqrt{60}} = \frac{0.25}{0.1358} = 1.84, \qquad df = 59
\]</span></p>
<p><strong>4. Decision.</strong> Critical value: <span class="math inline">\(t_{0.05,\,59} = 1.671\)</span>; since <span class="math inline">\(1.84 \geq 1.671\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>reject <span class="math inline">\(H_0\)</span></strong>. Equivalently, <span class="math inline">\(p\text{-value} = 0.035 \leq 0.05\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>reject <span class="math inline">\(H_0\)</span></strong>.</p>
<p><strong>5. Manager’s Translation.</strong> <em>The data give us at least 95% confidence that Heathrow’s mean traveler rating tops 7, so classify it “superior service.” The evidence is strong but not overwhelming (<span class="math inline">\(p \approx 0.035\)</span>).</em></p>
</div>
</section>
<section id="now-the-spine-case-bs-erpm-in-numbers" class="slide level2 center">
<h2>Now the Spine Case: B’s eRPM in Numbers</h2>

<img data-src="figs/erpm_B_vs_benchmark.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><ul>
<li>23 of 30 days clear the $3.30 line, and the sample mean sits well above it, but a noisy 30-day sample <em>could</em> land here even if the true mean were exactly $3.30. The test settles it.</li>
</ul>
</section>
<section id="do-it-in-excel-descriptive-statistics" class="slide level2 center">
<h2>Do It in Excel: Descriptive Statistics</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along</strong> (this feeds the <span class="math inline">\(t\)</span> test):</p>
<ol type="1">
<li class="fragment">Select the 30 <code>erpm</code> values for B</li>
<li class="fragment"><strong>Data -&gt; Data Analysis -&gt; Descriptive Statistics</strong></li>
<li class="fragment">Input range = the B column; check <strong>Labels in first row</strong> and <strong>Summary statistics</strong></li>
<li class="fragment">Click OK; read <strong>Mean = 3.4590</strong>, <strong>Standard Deviation = 0.3444</strong>, <strong>Count = 30</strong> (the ToolPak’s “Standard Error 0.0629” is already <span class="math inline">\(s/\sqrt{n}\)</span>)</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_desc_erpm_B.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="step-3-compute-the-test-statistic" class="slide level2 center">
<h2>Step 3: Compute the Test Statistic</h2>
<p><br></p>
<p>From the 30 daily eRPM values for Algorithm B in <code>data/vungle_daily.csv</code>:</p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(n\)</span> (days)</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\bar{x}\)</span> (mean eRPM)</td>
<td style="text-align: right;"><strong>$3.4590</strong></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(s\)</span></td>
<td style="text-align: right;">0.3444</td>
</tr>
<tr class="even">
<td><span class="math inline">\(SE = s/\sqrt{30}\)</span></td>
<td style="text-align: right;">0.0629</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mu_0\)</span> (benchmark)</td>
<td style="text-align: right;">3.3000</td>
</tr>
<tr class="even">
<td><span class="math inline">\(t = (\bar{x}-\mu_0)/SE\)</span></td>
<td style="text-align: right;"><strong>2.529</strong></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(df\)</span></td>
<td style="text-align: right;">29</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p><span class="math display">\[
t = \frac{3.4590 - 3.30}{0.3444/\sqrt{30}} = \frac{0.1590}{0.0629} = 2.529
\]</span></p>
</div>
</section>
<section id="step-4-decision-critical-value" class="slide level2 center">
<h2>Step 4: Decision (Critical Value)</h2>

<img data-src="figs/t_dist_critical_vungle.png" class="quarto-figure quarto-figure-center r-stretch" style="width:74.0%"><ul>
<li><strong>Critical value:</strong> <span class="math inline">\(t_{0.05,\,29} = 1.699\)</span>. Since <span class="math inline">\(t = 2.529 \geq 1.699\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>reject <span class="math inline">\(H_0\)</span></strong>.</li>
<li>The observed <span class="math inline">\(t\)</span> lands deep in the gold rejection region; a sample mean this far above $3.30 is hard to explain as luck.</li>
</ul>
</section>
<section id="step-4-decision-p-value" class="slide level2 center">
<h2>Step 4: Decision (<span class="math inline">\(p\)</span>-Value)</h2>

<img data-src="figs/t_dist_pvalue_vungle.png" class="quarto-figure quarto-figure-center r-stretch" style="width:74.0%"><ul>
<li><strong><span class="math inline">\(p\)</span>-value:</strong> <span class="math inline">\(P(T_{29} &gt; 2.529) = 0.009\)</span>. Since <span class="math inline">\(0.009 \leq 0.05\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>reject <span class="math inline">\(H_0\)</span></strong>.</li>
<li>On the manager’s scale, <span class="math inline">\(p \leq 0.01\)</span> is <strong>overwhelming</strong> evidence against the $3.30 line.</li>
</ul>
</section>
<section id="the-threshold-matters-a-teaching-moment" class="slide level2 center">
<h2>The Threshold Matters: a Teaching Moment</h2>
<p><br></p>
<ul>
<li class="fragment"><p>At <span class="math inline">\(\alpha = 0.05\)</span> the call is clear: <span class="math inline">\(p = 0.009 \leq 0.05\)</span>, reject.</p></li>
<li class="fragment"><p>At a stricter <span class="math inline">\(\alpha = 0.01\)</span>? The critical value rises to <span class="math inline">\(t_{0.01,\,29} = 2.462\)</span>. Our <span class="math inline">\(t = 2.529\)</span> still clears it, but <strong>just barely</strong>.</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
t = 2.529 \;&gt;\; t_{0.01,\,29} = 2.462 \quad\Rightarrow\quad \text{reject } H_0 \text{ even at } \alpha = 0.01
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>Lesson:</strong> how strict you set <span class="math inline">\(\alpha\)</span> can flip a close call. Here B clears even the demanding 1% bar, but a result like <span class="math inline">\(p = 0.03\)</span> would reject at 5% and <em>fail</em> at 1%. <strong>Decide <span class="math inline">\(\alpha\)</span> before you test, and report it.</strong></li>
</ul>
</section>
<section id="do-it-in-excel-one-sample-t-mean" class="slide level2 center">
<h2>Do It in Excel: One-Sample <span class="math inline">\(t\)</span> (Mean)</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Select the 30 <code>erpm</code> B values; run <strong>Data -&gt; Data Analysis -&gt; Descriptive Statistics</strong> to read <span class="math inline">\(\bar{x} = 3.459\)</span>, <span class="math inline">\(s = 0.3444\)</span>, <span class="math inline">\(n = 30\)</span></li>
<li class="fragment"><code>=B/SQRT(n)</code> for <span class="math inline">\(SE\)</span> (the ToolPak’s <span class="math inline">\(t\)</span>-tools are all two-sample, so build the one-sample test in cells)</li>
<li class="fragment"><code>=(xbar-3.30)/SE</code> for <span class="math inline">\(t\)</span> (this returns <strong>2.529</strong>)</li>
<li class="fragment"><code>=T.DIST.RT(t, 29)</code> for the upper-tail <span class="math inline">\(p\)</span>, and <code>=T.INV(0.95, 29)</code> for the critical value</li>
<li class="fragment">Read the cells by name: <span class="math inline">\(t = 2.53\)</span>, <span class="math inline">\(p = 0.009\)</span></li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_one_sample_t_vungle.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="the-ci-and-the-test-agree" class="slide level2 center">
<h2>The CI and the Test Agree</h2>
<p><br></p>
<ul>
<li class="fragment">A two-sided 95% confidence interval for B’s true mean eRPM:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{x} \pm t_{0.025,\,29}\frac{s}{\sqrt{n}} = 3.459 \pm 2.045 \times 0.0629 \;=\; (\$3.330,\; \$3.588)
\]</span></p>
</div>
<ul>
<li class="fragment"><p>The benchmark <strong>$3.30 sits below the entire interval</strong>, consistent with rejecting <span class="math inline">\(H_0: \mu \leq 3.30\)</span>.</p></li>
<li class="fragment"><p>This is the <strong>duality</strong>: a value outside the CI is exactly a value the test would reject. Estimation and testing tell one story.</p></li>
<li class="fragment"><p>Even the lower bound, $3.33, is above the line: at Vungle’s scale of hundreds of millions of impressions, a few cents per 1,000 is real money.</p></li>
</ul>
</section>
<section id="step-5-managers-translation" class="slide level2 center">
<h2>Step 5: Manager’s Translation</h2>
<p><br></p>
<ul>
<li class="fragment"><p><em>“If algorithm B were truly no better than the $3.30 benchmark, we would see 30 days average this high only about <strong>9 times in 1,000</strong>. That is overwhelming evidence B clears the line; its true mean eRPM is plausibly between $3.33 and $3.59. <strong>Fund B.</strong>”</em></p></li>
<li class="fragment"><p><strong>One number, one caveat:</strong> the call rests on <span class="math inline">\(t = 2.53\)</span> (<span class="math inline">\(p = 0.009\)</span>), and on the assumption that June’s 30 days are <strong>representative</strong> of future traffic. A new month with different seasonality could shift the mean.</p></li>
<li class="fragment"><p>This answers <em>“is B above the line?”</em>, but the deeper question is <em>“is B better than <strong>A</strong>?”</em> That comparison of <strong>two</strong> populations is Topic 9.</p></li>
</ul>
</section>
<section id="todays-question-todays-answer" class="slide level2 center">
<h2>Today’s Question, Today’s Answer</h2>
<p><br></p>
<p><strong>The question (Lecture 1’s rung):</strong></p>
<blockquote>
<p><em>Is B’s mean eRPM really above the $3.30 benchmark, or could a noisy 30-day sample land there by luck?</em></p>
</blockquote>
<div class="fragment">
<p><br></p>
<p><strong>The answer we reached today:</strong></p>
<blockquote>
<p><strong>Yes.</strong> B’s 30-day mean is <strong>$3.459</strong> against the $3.30 line; the one-sample <span class="math inline">\(t\)</span>-test gives <span class="math inline">\(t = 2.53\)</span>, <span class="math inline">\(p = 0.009\)</span>. If B were truly only at $3.30, 30 days would average this high about <strong>9 times in 1,000</strong>. <strong>Reject “no better” and fund B.</strong></p>
</blockquote>
</div>
</section>
<section id="the-managers-takeaway-lecture-1" class="slide level2 center">
<h2>The Manager’s Takeaway: Lecture 1</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> algorithm B’s mean daily eRPM is above the $3.30 benchmark; the one-sample <span class="math inline">\(t\)</span>-test rejects “no better” with overwhelming evidence (<span class="math inline">\(p = 0.009\)</span>). <strong>Fund B.</strong></p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <span class="math inline">\(t = 2.53\)</span>, and where it came from: <span class="math inline">\((\bar{x} - \mu_0)/(s/\sqrt{n})\)</span>.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> the test says B beats the <strong>$3.30 line</strong>, not that B beats <strong>A</strong>, and it assumes June is representative. Comparing B to A directly is Topic 9.</p></li>
<li class="fragment"><p><strong>Homework (group):</strong> today’s one-sample <span class="math inline">\(t\)</span> is drilled on <strong>HW3</strong>, previous-edition problem sets on Brightspace. Run it yourself so you can check an analyst who uses it.</p></li>
</ul>
</section>
<section id="team-sprint-your-group-case-lecture-1" class="slide level2 center">
<h2>⏱️ Team Sprint: Your Group Case (Lecture 1)</h2>
<div class="sprint">
<p><strong>Now it’s your group’s turn.</strong> Today’s in-class group case is posted on <strong>Brightspace</strong> (<em>Topic 08 Group Case, Lecture 1</em>): a separate business decision you make with today’s tools.</p>
<p><strong>What you’ll use:</strong> a one-sample <span class="math inline">\(t\)</span>-test about a <strong>mean</strong>. <strong>Excel:</strong> Analysis ToolPak → Descriptive Statistics, then formula cells for <span class="math inline">\(SE\)</span>, <span class="math inline">\(t\)</span>, and the upper-tail <span class="math inline">\(p\)</span> (<code>=T.DIST.RT</code>).</p>
<p><strong>Submit one PDF per group before you leave:</strong> your decision plus the numbers behind it.</p>
</div>
</section></section>
<section>
<section id="lecture-2-one-sample-test-about-a-proportion" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 2: One-Sample Test About a Proportion</h1>

</section>
<section id="the-brief-is-the-proportion-really-above-the-target" class="slide level2 center">
<h2>The Brief: Is the Proportion Really Above the Target?</h2>
<p><br></p>
<ul>
<li class="fragment"><p>The big call is still <em>roll out B, or stay with A?</em> <strong>Lecture 2’s piece:</strong> <em>is B’s conversion rate really above the 0.35% viability target?</em></p></li>
<li class="fragment"><p>eRPM is revenue per impression. The ops team also watches the <strong>conversion rate</strong>: installs ÷ impressions. Any algorithm must clear a minimum <strong>0.35%</strong> conversion target to be viable.</p></li>
<li class="fragment"><p>Now the parameter is a <strong>proportion</strong> <span class="math inline">\(p\)</span>, not a mean, but the machinery is the same: state <span class="math inline">\(H_0\)</span>/<span class="math inline">\(H_a\)</span>, compute a test statistic, get a <span class="math inline">\(p\)</span>-value, decide at <span class="math inline">\(\alpha\)</span>.</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
H_0: p \leq 0.0035 \qquad \text{vs.} \qquad H_a: p &gt; 0.0035 \qquad \alpha = 0.05
\]</span></p>
</div>
<ul>
<li class="fragment"><span class="math inline">\(p\)</span> = B’s <strong>true</strong> install-per-impression rate; the sample is every June impression served under B.</li>
</ul>
</section>
<section id="how-every-class-runs-1" class="slide level2 center">
<h2>How Every Class Runs</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/lecture_dynamic.png" class="quarto-figure quarto-figure-center" style="width:90.0%"></p>
</figure>
</div>
<p>The class <strong>ends on the Team Sprint</strong>, your group’s graded submission: a decision plus your read of the analysis, one PDF before you leave.</p>
</section>
<section id="the-unit-of-observation-just-changed" class="slide level2 center">
<h2>The Unit of Observation Just Changed</h2>
<p><br></p>
<ul>
<li class="fragment"><p>For <strong>eRPM</strong> the unit was the <strong>day</strong> (<span class="math inline">\(n = 30\)</span>). For <strong>conversion</strong> the unit is the <strong>impression</strong>, each one a Bernoulli trial (install / no install).</p></li>
<li class="fragment"><p>So <span class="math inline">\(n\)</span> is now <strong>15.8 million</strong>, not 30. The “sample” exploded in size.</p></li>
<li class="fragment"><p>We aggregate June’s B rows: total installs ÷ total impressions.</p></li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Algorithm B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Impressions (<span class="math inline">\(n\)</span>)</td>
<td style="text-align: right;">15,825,376</td>
</tr>
<tr class="even">
<td>Installs (<span class="math inline">\(x\)</span>)</td>
<td style="text-align: right;">56,031</td>
</tr>
<tr class="odd">
<td>Sample proportion <span class="math inline">\(\bar{p} = x/n\)</span></td>
<td style="text-align: right;"><strong>0.3541%</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><em>Honest caveat:</em> impressions within a day are not perfectly independent (beyond today’s scope), but a fair question to ask any A/B platform.</li>
</ul>
</section>
<section id="the-proportion-test-statistic" class="slide level2 center">
<h2>The Proportion Test Statistic</h2>
<p><br></p>
<ul>
<li class="fragment">Standard error of the sample proportion, computed <strong>under <span class="math inline">\(H_0\)</span></strong> (so it uses the hypothesized <span class="math inline">\(p_0\)</span>, not <span class="math inline">\(\bar p\)</span>):</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\sigma_{\bar{p}} = \sqrt{\frac{p_0(1-p_0)}{n}}
\]</span></p>
</div>
<ul>
<li class="fragment">Test statistic, a <strong><span class="math inline">\(z\)</span></strong>, because for large <span class="math inline">\(n\)</span> the sampling distribution of <span class="math inline">\(\bar p\)</span> is approximately normal:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
z = \frac{\bar{p} - p_0}{\sigma_{\bar{p}}}
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>Large-sample condition:</strong> <span class="math inline">\(np_0 \geq 5\)</span> and <span class="math inline">\(n(1-p_0) \geq 5\)</span>. Here <span class="math inline">\(np_0 \approx 55{,}000 \gg 5\)</span>, easily satisfied.</li>
</ul>
</section>
<section id="a-question-that-often-comes-up-3" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">Why does the standard error use the target <span class="math inline">\(p_0 = 0.0035\)</span> and not B’s observed rate <span class="math inline">\(\bar p = 0.003541\)</span>?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> the test runs <em>as if</em> <span class="math inline">\(H_0\)</span> were true, so it measures how surprising B’s rate is <strong>under</strong> the 0.35% target. Building the standard error from <span class="math inline">\(p_0\)</span> keeps the whole calculation on that “what if the target is the truth?” footing. (In a confidence interval, where there is no hypothesized value, you would use <span class="math inline">\(\bar p\)</span> instead.)</p>
</div>
</div>
</section>
<section id="decision-rules-for-a-proportion" class="slide level2 center">
<h2>Decision Rules for a Proportion</h2>
<p><br></p>
<ul>
<li class="fragment">Same two roads, now with the <strong>standard normal</strong>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\begin{aligned}
\text{Lower-tail:} \;&amp; \text{reject } H_0 \text{ if } z \leq -z_{\alpha} \\
\text{Upper-tail:} \;&amp; \text{reject } H_0 \text{ if } z \geq z_{\alpha} \\
\text{Two-tailed:} \;&amp; \text{reject } H_0 \text{ if } |z| \geq z_{\alpha/2}
\end{aligned}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Excel: <code>=NORM.S.INV(1-α)</code> for the critical <span class="math inline">\(z\)</span> (e.g., <span class="math inline">\(z_{0.05} = 1.645\)</span>); <code>=1-NORM.S.DIST(z, TRUE)</code> for an upper-tail <span class="math inline">\(p\)</span>-value.</p></li>
<li class="fragment"><p>For a two-tailed test, <strong>double</strong> the single-tail area to get the <span class="math inline">\(p\)</span>-value, and split <span class="math inline">\(\alpha\)</span> into <span class="math inline">\(\alpha/2\)</span> per tail for the two critical values.</p></li>
</ul>
</section>
<section id="anchor-example-pine-creek-golf-course" class="slide level2 center">
<h2>Anchor Example: Pine Creek Golf Course</h2>
<p><br></p>
<p>Last year <strong>20%</strong> of Pine Creek’s players were women. After a promotion to attract women golfers, the manager wants evidence the proportion <strong>increased</strong>. A sample of <strong>400</strong> players includes <strong>100</strong> women (<span class="math inline">\(\bar{p} = 0.25\)</span>), <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="fragment">
<p><span class="math display">\[
H_0: p \leq 0.20 \qquad H_a: p &gt; 0.20 \qquad \text{(upper-tail)}
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
\sigma_{\bar{p}} = \sqrt{\frac{0.20(0.80)}{400}} = 0.02, \qquad
z = \frac{0.25 - 0.20}{0.02} = 2.50
\]</span></p>
</div>
</section>
<section id="pine-creek-decision" class="slide level2 center">
<h2>Pine Creek: Decision</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Critical value:</strong> <span class="math inline">\(z_{0.05} = 1.645\)</span>. Since <span class="math inline">\(z = 2.50 \geq 1.645\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>reject <span class="math inline">\(H_0\)</span></strong>.</p></li>
<li class="fragment"><p><strong><span class="math inline">\(p\)</span>-value:</strong> <span class="math inline">\(1 - \text{NORM.S.DIST}(2.50) = 1 - 0.9938 = 0.0062 \leq 0.05\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>reject <span class="math inline">\(H_0\)</span></strong>.</p></li>
</ul>
<div class="fragment">
<blockquote>
<p><em>Strong, in fact overwhelming, evidence that the promotion raised the proportion of women players above 20%.</em></p>
</blockquote>
</div>
<ul>
<li class="fragment">Notice the parallel to the airport case: same five steps, same two roads; only the standard error formula and the reference distribution (normal vs.&nbsp;<span class="math inline">\(t\)</span>) changed.</li>
</ul>
</section>
<section id="now-the-spine-case-bs-conversion-in-numbers" class="slide level2 center">
<h2>Now the Spine Case: B’s Conversion in Numbers</h2>
<p><br></p>
<ul>
<li class="fragment">Plugging B’s June totals into the proportion test, with <span class="math inline">\(p_0 = 0.0035\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\sigma_{\bar{p}} = \sqrt{\frac{0.0035(1-0.0035)}{15{,}825{,}376}} = 1.485 \times 10^{-5}
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
z = \frac{0.003541 - 0.003500}{1.485 \times 10^{-5}} = 2.733
\]</span></p>
</div>
<ul>
<li class="fragment"><span class="math inline">\(\bar p\)</span> sits just <strong>0.0041 percentage points</strong> above the target (a tiny gap), yet with 15.8M impressions even a tiny gap is many standard errors out.</li>
</ul>
</section>
<section id="step-4-decision" class="slide level2 center">
<h2>Step 4: Decision</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Critical value:</strong> <span class="math inline">\(z_{0.05} = 1.645\)</span>. Since <span class="math inline">\(z = 2.733 \geq 1.645\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>reject <span class="math inline">\(H_0\)</span></strong>.</p></li>
<li class="fragment"><p><strong><span class="math inline">\(p\)</span>-value:</strong> <span class="math inline">\(1 - \text{NORM.S.DIST}(2.733) = 0.0031 \leq 0.05\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>reject <span class="math inline">\(H_0\)</span></strong>.</p></li>
</ul>
<div class="fragment">
<blockquote>
<p><em>Statistically, B’s conversion rate clears the 0.35% target.</em></p>
</blockquote>
</div>
<ul>
<li class="fragment"><strong>But pause on the magnitude:</strong> the <em>effect size</em> is 0.0041 percentage points. With <span class="math inline">\(n\)</span> in the millions the test was almost <strong>guaranteed</strong> to be “significant,” which raises the question we tackle next.</li>
</ul>
</section>
<section id="do-it-in-excel-one-proportion-z" class="slide level2 center">
<h2>Do It in Excel: One-Proportion <span class="math inline">\(z\)</span></h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along</strong> (no ToolPak tool exists, so build it in cells):</p>
<ol type="1">
<li class="fragment"><code>=SUM</code> June’s B installs (<span class="math inline">\(x = 56{,}031\)</span>) and impressions (<span class="math inline">\(n = 15{,}825{,}376\)</span>)</li>
<li class="fragment"><code>=x/n</code> for <span class="math inline">\(\bar p\)</span> (this returns <strong>0.3541%</strong>)</li>
<li class="fragment"><code>=SQRT(0.0035*(1-0.0035)/n)</code> for <span class="math inline">\(SE\)</span>, computed under <span class="math inline">\(H_0\)</span> with <span class="math inline">\(p_0 = 0.0035\)</span></li>
<li class="fragment"><code>=(pbar-0.0035)/SE</code> for <span class="math inline">\(z\)</span>, and <code>=1-NORM.S.DIST(z, TRUE)</code> for the upper-tail <span class="math inline">\(p\)</span></li>
<li class="fragment">Read the cells: <span class="math inline">\(z = 2.73\)</span>, <span class="math inline">\(p = 0.003\)</span></li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_one_prop_z_vungle.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="statistical-vs.-practical-significance" class="slide level2 center">
<h2>Statistical vs.&nbsp;Practical Significance</h2>
<p><br></p>
<ul>
<li class="fragment"><p>With <span class="math inline">\(n\)</span> in the <strong>millions</strong>, the conversion test was nearly guaranteed to reject: at this scale even a microscopic gap produces a large <span class="math inline">\(z\)</span>.</p></li>
<li class="fragment"><p><span class="math inline">\(z = 2.73\)</span> tells you the gap is <strong>real</strong>; it does <strong>not</strong> tell you the gap <strong>matters</strong>. Always pair the test with the <strong>effect size</strong>: here +0.0041 percentage points above target.</p></li>
<li class="fragment"><p>Flip side, from small samples: a real effect can be <strong>invisible</strong> when <span class="math inline">\(n\)</span> is tiny (low power <span class="math inline">\(\rightarrow\)</span> Type II error). <strong>Large <span class="math inline">\(n\)</span>: almost everything is significant. Small <span class="math inline">\(n\)</span>: almost nothing is.</strong></p></li>
<li class="fragment"><p>Neither replaces judgment about <strong>magnitude</strong>. <em>“Is it real?”</em> and <em>“is it big enough to act on?”</em> are different questions.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-4" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If 15.8M impressions make almost any gap “significant,” does the conversion test still tell us anything useful?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> yes, it rules out luck. <span class="math inline">\(z = 2.73\)</span> confirms B’s +0.0041-point edge is real, not sampling noise. What the test cannot do is decide whether that edge is <strong>worth acting on</strong>: that is the manager’s call, made by pairing the <span class="math inline">\(z\)</span> with the effect size. Report both, and never let a big <span class="math inline">\(z\)</span> stand in for a big effect.</p>
</div>
</div>
</section>
<section id="reading-p-values-like-a-manager" class="slide level2 center">
<h2>Reading <span class="math inline">\(p\)</span>-Values Like a Manager</h2>
<div class="r-fit-text">
<p>The same statistic, re-anchored to the Vungle eRPM mean test under different benchmarks: what would the verdict be?</p>
<table class="caption-top">
<colgroup>
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>If the benchmark were…</th>
<th style="text-align: right;"><span class="math inline">\(t\)</span></th>
<th style="text-align: right;"><span class="math inline">\(p\)</span>-value</th>
<th>Rubric label</th>
<th>Manager’s read</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mu_0 = 3.30\)</span> (our case)</td>
<td style="text-align: right;">2.53</td>
<td style="text-align: right;"><strong>0.009</strong></td>
<td>Overwhelming</td>
<td>Clear the line decisively, fund B</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mu_0 = 3.35\)</span></td>
<td style="text-align: right;">1.73</td>
<td style="text-align: right;"><strong>0.047</strong></td>
<td>Strong</td>
<td>Significant at 5%, not at 1%; fund, but watch it</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mu_0 = 3.40\)</span></td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;"><strong>0.178</strong></td>
<td>Insufficient</td>
<td>Cannot distinguish B from 3.40, so hold</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment">The <strong>same data</strong> support different conclusions depending on <strong>where you draw the line</strong>, which is why the benchmark is a <em>business</em> decision, set before the test.</li>
</ul>
</section>
<section id="do-it-in-excel-read-the-p-against-the-rubric" class="slide level2 center">
<h2>Do It in Excel: Read the <span class="math inline">\(p\)</span> Against the Rubric</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">In one column, list the candidate benchmarks <span class="math inline">\(\mu_0 = 3.30, 3.35, 3.40\)</span></li>
<li class="fragment"><code>=(3.459-mu0)/0.0629</code> for <span class="math inline">\(t\)</span> at each line</li>
<li class="fragment"><code>=T.DIST.RT(t, 29)</code> for the upper-tail <span class="math inline">\(p\)</span> at each line</li>
<li class="fragment">Compare each <span class="math inline">\(p\)</span> to the rubric: <span class="math inline">\(\leq 0.01\)</span> overwhelming, <span class="math inline">\(\leq 0.05\)</span> strong, <span class="math inline">\(\leq 0.10\)</span> weak, else insufficient</li>
<li class="fragment">Read the verdict: 3.30 -&gt; 0.009 (fund), 3.40 -&gt; 0.178 (hold)</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_pvalue_rubric.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="todays-question-todays-answer-1" class="slide level2 center">
<h2>Today’s Question, Today’s Answer</h2>
<p><br></p>
<p><strong>The question (Lecture 2’s rung):</strong></p>
<blockquote>
<p><em>Is B’s conversion rate really above the 0.35% viability target?</em></p>
</blockquote>
<div class="fragment">
<p><br></p>
<p><strong>The answer we reached today:</strong></p>
<blockquote>
<p><strong>Yes, but read the size.</strong> B’s install rate is <strong>0.3541%</strong> against the 0.3500% target; with 15.8M impressions the one-proportion <span class="math inline">\(z\)</span>-test gives <span class="math inline">\(z = 2.73\)</span>, <span class="math inline">\(p = 0.003\)</span>, so <strong>reject “below target.”</strong> The gap is real, but only <strong>+0.0041 percentage points</strong>: significant, not large.</p>
</blockquote>
</div>
</section>
<section id="the-managers-takeaway-lecture-2" class="slide level2 center">
<h2>The Manager’s Takeaway: Lecture 2</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> B’s conversion rate clears the 0.35% target; the one-proportion <span class="math inline">\(z\)</span>-test rejects “below target” (<span class="math inline">\(z = 2.73\)</span>, <span class="math inline">\(p = 0.003\)</span>). Viable on conversion, too.</p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <span class="math inline">\(z = 2.73\)</span>, same machinery as the <span class="math inline">\(t\)</span>, with <span class="math inline">\(\sigma_{\bar p} = \sqrt{p_0(1-p_0)/n}\)</span> in the denominator.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> with 15.8M impressions, <em>significance was almost automatic</em>. The honest headline is the <strong>effect size</strong> (+0.0041 pts), not the <span class="math inline">\(z\)</span>. Statistical significance <span class="math inline">\(\neq\)</span> practical importance.</p></li>
<li class="fragment"><p><strong>Homework (group):</strong> today’s one-proportion <span class="math inline">\(z\)</span> is drilled on <strong>HW3</strong>, previous-edition problem sets on Brightspace. Run it yourself so you can check an analyst who uses it.</p></li>
</ul>
</section>
<section id="team-sprint-your-group-case-lecture-2" class="slide level2 center">
<h2>⏱️ Team Sprint: Your Group Case (Lecture 2)</h2>
<div class="sprint">
<p><strong>Now it’s your group’s turn.</strong> Today’s in-class group case is posted on <strong>Brightspace</strong> (<em>Topic 08 Group Case, Lecture 2</em>): a separate business decision you make with today’s tools.</p>
<p><strong>What you’ll use:</strong> a one-proportion <span class="math inline">\(z\)</span>-test. <strong>Excel:</strong> Analysis ToolPak for any summaries, then formula cells for <span class="math inline">\(SE\)</span>, <span class="math inline">\(z\)</span>, and the upper-tail <span class="math inline">\(p\)</span> (<code>=1-NORM.S.DIST</code>).</p>
<p><strong>Submit one PDF per group before you leave:</strong> your decision plus the numbers behind it.</p>
</div>
</section></section>
<section>
<section id="wrap-up" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Wrap-up</h1>

</section>
<section id="the-one-population-testing-recipe-one-page" class="slide level2 center">
<h2>The One-Population Testing Recipe: One Page</h2>
<div class="r-fit-text">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Mean (<span class="math inline">\(\sigma\)</span> unknown)</th>
<th>Proportion (large <span class="math inline">\(n\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1. Hypotheses</strong></td>
<td><span class="math inline">\(H_0\)</span> vs.&nbsp;<span class="math inline">\(H_a\)</span> about <span class="math inline">\(\mu\)</span>; tail from the decision</td>
<td><span class="math inline">\(H_0\)</span> vs.&nbsp;<span class="math inline">\(H_a\)</span> about <span class="math inline">\(p\)</span>; tail from the decision</td>
</tr>
<tr class="even">
<td><strong>2. Significance</strong></td>
<td>choose <span class="math inline">\(\alpha\)</span> (Type I risk) before testing</td>
<td>choose <span class="math inline">\(\alpha\)</span> before testing</td>
</tr>
<tr class="odd">
<td><strong>3. Statistic</strong></td>
<td><span class="math inline">\(t = \dfrac{\bar{x}-\mu_0}{s/\sqrt{n}}\)</span>, <span class="math inline">\(df = n-1\)</span></td>
<td><span class="math inline">\(z = \dfrac{\bar{p}-p_0}{\sqrt{p_0(1-p_0)/n}}\)</span></td>
</tr>
<tr class="even">
<td><strong>4. Decision</strong></td>
<td>reject if <span class="math inline">\(\lvert t\rvert \geq t_{crit}\)</span> or <span class="math inline">\(p \leq \alpha\)</span></td>
<td>reject if <span class="math inline">\(\lvert z\rvert \geq z_{crit}\)</span> or <span class="math inline">\(p \leq \alpha\)</span></td>
</tr>
<tr class="odd">
<td><strong>5. Translate</strong></td>
<td>back to the business call + effect size</td>
<td>back to the business call + effect size</td>
</tr>
<tr class="even">
<td><strong>Excel</strong></td>
<td><code>T.DIST.RT</code>, <code>T.INV</code> (+ Descriptive Stats)</td>
<td><code>NORM.S.DIST</code>, <code>NORM.S.INV</code> (formula cells)</td>
</tr>
<tr class="odd">
<td><strong>Vungle result</strong></td>
<td><span class="math inline">\(t = 2.53\)</span>, <span class="math inline">\(p = 0.009\)</span> (fund B)</td>
<td><span class="math inline">\(z = 2.73\)</span>, <span class="math inline">\(p = 0.003\)</span> (clears target)</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="the-managers-takeaway" class="slide level2 center">
<h2>The Manager’s Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> Algorithm B’s mean eRPM ($3.46) is above the $3.30 funding benchmark and its conversion clears the 0.35% target; both one-sample tests reject the skeptic, so <strong>fund B</strong>.</p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <span class="math inline">\(t = 2.53\)</span> for the eRPM test, and the recipe behind it: <span class="math inline">\((\bar{x} - \mu_0)/(s/\sqrt{n})\)</span>.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> these tests say B beats a <strong>line</strong>, not that B beats <strong>A</strong>, and a large <span class="math inline">\(n\)</span> can make a tiny gap “significant.” Always report the <strong>effect size</strong> and check whether the benchmark is the right line.</p></li>
<li class="fragment"><p><strong>Practice with the real data:</strong></p>
<ul>
<li class="fragment"><code>data/vungle_daily.csv</code> + formula cells <span class="math inline">\(\rightarrow\)</span> reproduce <span class="math inline">\(t = 2.53\)</span> (eRPM) and <span class="math inline">\(z = 2.73\)</span> (conversion).</li>
<li class="fragment">Worked solutions: <code>data/vungle_one_sample_tests.xlsx</code>.</li>
</ul></li>
</ul>
</section>
<section id="summary" class="slide level2 center">
<h2>Summary</h2>
<p>Some takeaways from this session:</p>
<ul>
<li><strong><span class="math inline">\(H_0\)</span> is the skeptic on trial:</strong> put the claim you want to prove in <span class="math inline">\(H_a\)</span>, keep the equality in <span class="math inline">\(H_0\)</span>, and let the data carry the burden of proof.</li>
<li><strong>Two errors, one knob:</strong> you set <span class="math inline">\(\alpha\)</span> (Type I risk) before the test; <span class="math inline">\(\beta\)</span> (Type II) follows. Say <em>“fail to reject,”</em> never <em>“accept.”</em></li>
<li><strong>One recipe, two parameters:</strong> the one-sample <span class="math inline">\(t\)</span> (mean, <span class="math inline">\(\sigma\)</span> unknown) and the one-proportion <span class="math inline">\(z\)</span> share the same five steps; only the standard error and reference distribution change.</li>
<li><strong>Two roads agree:</strong> the critical-value and <span class="math inline">\(p\)</span>-value approaches always reach the same decision, and both agree with the confidence interval.</li>
<li><strong>Significance <span class="math inline">\(\neq\)</span> importance:</strong> with millions of impressions almost everything is “significant,” so judge the <strong>effect size</strong>; with tiny samples real effects can hide, so mind the <strong>power</strong>.</li>
<li>A test answers <em>is the parameter past a line?</em> Comparing <strong>two</strong> populations (<em>is B better than A?</em>) is Topic 9.</li>
</ul>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Thank you!</h1>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Business Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>