<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Professor Davi Moreira ">
  <title>QM 6700: Business Analytics –  QM 6700: Business Analytics </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-8fc47a4fdcba9931a3aa90ef56f89358.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="font-size: 100%;"> QM 6700: Business Analytics </span></h1>
  <p class="subtitle"><span style="font-size: 150%;"> Sampling Distributions &amp; Interval Estimation </span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor<br>Davi Moreira<br> 
</div>
</div>
</div>

</section>
<section id="overview" class="slide level2 center">
<h2>Overview</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Case Spotlight: A/B Testing at Vungle</li>
<li><strong>Lecture 1:</strong> sampling, point estimation</li>
<li>The sampling distribution of <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\bar{p}\)</span></li>
<li>The Central Limit Theorem &amp; standard error</li>
<li>How sure can 30 days make us?</li>
</ul>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li><strong>Lecture 2:</strong> the interval estimate</li>
<li>Confidence intervals for a mean (<span class="math inline">\(t\)</span>) and a proportion</li>
<li>The margin of error and the three levers that set it</li>
<li>How many days for <span class="math inline">\(\pm\$0.05\)</span>? Sample size</li>
<li>The estimation memo for Vungle</li>
</ul>
</div></div>
</section>
<section>
<section id="case-spotlight-ab-testing-at-vungle" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Case Spotlight: A/B Testing at Vungle</h1>

</section>
<section id="the-brief-30-days-is-a-sample" class="slide level2 center">
<h2>The Brief: 30 Days Is a <em>Sample</em></h2>
<p><br></p>
<blockquote>
<p>“We ran algorithm B for <strong>30 days</strong> and saw a mean eRPM of about <strong>$3.46</strong>. But June is over. What is B’s <strong>true</strong> mean eRPM going forward, and how close can 30 days really get us?”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p><strong>The big call you own as the manager:</strong> <em>roll out B, or stay with A?</em> You cannot make it on a single 30-day number whose error you can’t name.</p></li>
<li class="fragment"><p><strong>Today’s question (Lecture 1):</strong> <em>how trustworthy is a 30-day sample mean?</em> Until now we <strong>described</strong> the 30 days we have; today we <strong>generalize</strong> to the days we <em>don’t</em> have, every future impression B will serve.</p></li>
<li class="fragment"><p>The 30-day mean $3.46 is a single <strong>point estimate</strong>. By itself it hides the question the manager must ask: <strong><em>how much could it be off?</em></strong> This lecture quantifies that wobble; the next turns it into a range.</p></li>
</ul>
</section>
<section id="how-todays-studio-runs" class="slide level2 center">
<h2>How Today’s Studio Runs</h2>
<p><br></p>
<ul>
<li class="fragment">This is a <strong>two-lecture</strong> topic. Each lecture runs the same loop: <strong>the Brief (your decision) → Method Studio (I demo on Vungle) → Debrief (we land the call) → Team Sprint (your group case, submitted before you leave).</strong></li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Lecture</th>
<th>The question</th>
<th>The tool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1</strong></td>
<td>How trustworthy is a 30-day sample mean?</td>
<td>Sampling distribution, standard error, the CLT</td>
</tr>
<tr class="even">
<td><strong>2</strong></td>
<td>What is B’s <em>true</em> mean eRPM, give or take? How many days do we need?</td>
<td>Confidence intervals, margin of error, sample size</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment">By the end, you can write Vungle’s <strong>estimation memo</strong>: the true mean eRPM and conversion rate, each with a 95% interval, plus the days needed for a tighter test.</li>
</ul>
</section></section>
<section>
<section id="lecture-1-samples-estimates-the-sampling-distribution" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 1: Samples, Estimates &amp; the Sampling Distribution</h1>

</section>
<section id="the-brief-why-a-sample-mean-wobbles" class="slide level2 center">
<h2>The Brief: Why a Sample Mean Wobbles</h2>
<p><br></p>
<ul>
<li class="fragment"><p>A different 30 days (say, <strong>July</strong>) would give a <strong>different</strong> mean eRPM. So would any other random sample.</p></li>
<li class="fragment"><p>That wobble is not a mistake; it is the price of working from a <strong>sample</strong> instead of the whole <strong>population</strong>.</p></li>
<li class="fragment"><p><strong>Lecture 1’s question:</strong> <em>if the sample mean changes every time we sample, how can the manager trust any one of them?</em> The answer is the <strong>sampling distribution</strong>, and it is surprisingly well-behaved.</p></li>
</ul>
</section>
<section id="how-every-class-runs" class="slide level2 center">
<h2>How Every Class Runs</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/lecture_dynamic.png" class="quarto-figure quarto-figure-center" style="width:90.0%"></p>
</figure>
</div>
<p>The class <strong>ends on the Team Sprint</strong>, your group’s graded submission: a decision plus your read of the analysis, one PDF before you leave.</p>
</section>
<section id="population-sample-inference" class="slide level2 center">
<h2>Population, Sample, Inference</h2>

<img data-src="figs/population_sample_inference.png" class="quarto-figure quarto-figure-center r-stretch" style="width:78.0%"><ul>
<li><strong>Population:</strong> every future impression B will serve; its true mean eRPM <span class="math inline">\(\mu\)</span> is <strong>unknown</strong>.</li>
<li><strong>Sample:</strong> the 30 June days. We use them to <strong>estimate</strong> <span class="math inline">\(\mu\)</span>, first with a point, later with an interval.</li>
</ul>
</section>
<section id="how-the-sample-is-drawn" class="slide level2 center">
<h2>How the Sample Is Drawn</h2>

<img data-src="figs/sampling_methods.png" class="quarto-figure quarto-figure-center r-stretch" style="width:84.0%"><ul>
<li><strong>Probability</strong> sampling gives every unit a <strong>known chance</strong> of selection, so the sampling distribution and every formula today hold. <strong>Non-probability</strong> samples (convenience, judgment) have no known selection chance, so the inference math does not apply.</li>
<li>Vungle’s 30 days are a probability sample of B’s running output, which is what licenses the standard error and interval we build today.</li>
</ul>
</section></section>
<section>
<section id="point-estimation" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Point Estimation</h1>

</section>
<section id="from-population-parameter-to-sample-statistic" class="slide level2 center">
<h2>From Population Parameter to Sample Statistic</h2>
<p><br></p>
<ul>
<li class="fragment">A <strong>parameter</strong> is a fixed (usually unknown) number describing the <strong>population</strong>; a <strong>statistic</strong> is computed from the <strong>sample</strong> to estimate it.</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Population parameter</th>
<th>Point estimator (statistic)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>mean <span class="math inline">\(\mu\)</span></td>
<td>sample mean <span class="math inline">\(\bar{x}\)</span></td>
</tr>
<tr class="even">
<td>standard deviation <span class="math inline">\(\sigma\)</span></td>
<td>sample SD <span class="math inline">\(s\)</span></td>
</tr>
<tr class="odd">
<td>proportion <span class="math inline">\(p\)</span></td>
<td>sample proportion <span class="math inline">\(\bar{p}\)</span></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p><strong>Point estimation</strong> uses one sample to compute a single number as our best guess of the parameter.</p></li>
<li class="fragment"><p>A different random sample gives a different estimate, so a point estimate alone never tells us <strong>how close</strong> we are.</p></li>
</ul>
</section>
<section id="anchor-example-st.-andrews-college" class="slide level2 center">
<h2>Anchor Example: St.&nbsp;Andrew’s College</h2>
<p><br></p>
<ul>
<li class="fragment"><p>St.&nbsp;Andrew’s received <strong>900 applications</strong>. The Director wants the <strong>mean SAT score</strong> and the <strong>proportion</strong> wanting on-campus housing, <em>before</em> the full data are entered.</p></li>
<li class="fragment"><p>She draws a <strong>simple random sample</strong> of <span class="math inline">\(n = 30\)</span> applicants:</p></li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Parameter</th>
<th style="text-align: right;">True value (later)</th>
<th style="text-align: right;">Sample estimate (<span class="math inline">\(n=30\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean SAT <span class="math inline">\(\mu\)</span></td>
<td style="text-align: right;">1697</td>
<td style="text-align: right;"><span class="math inline">\(\bar{x} = 1684\)</span></td>
</tr>
<tr class="even">
<td>SD <span class="math inline">\(\sigma\)</span></td>
<td style="text-align: right;">87.4</td>
<td style="text-align: right;"><span class="math inline">\(s = 85.2\)</span></td>
</tr>
<tr class="odd">
<td>Proportion housing <span class="math inline">\(p\)</span></td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;"><span class="math inline">\(\bar{p} = 0.67\)</span></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment">Each estimate is <strong>close but not exact</strong>, and a <em>different</em> 30 applicants would have landed elsewhere. That variability is exactly what the sampling distribution describes.</li>
</ul>
</section>
<section id="the-vungle-point-estimates" class="slide level2 center">
<h2>The Vungle Point Estimates</h2>
<p><br></p>
<ul>
<li class="fragment">Vungle’s 30-day sample gives the same kind of best guesses:</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Parameter (true, going forward)</th>
<th style="text-align: right;">Point estimate from 30 days</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean eRPM, Algorithm A</td>
<td style="text-align: right;"><span class="math inline">\(\bar{x}_A = \$3.347\)</span></td>
</tr>
<tr class="even">
<td>Mean eRPM, Algorithm B</td>
<td style="text-align: right;"><span class="math inline">\(\bar{x}_B = \$3.459\)</span></td>
</tr>
<tr class="odd">
<td>Mean daily conversion rate, B</td>
<td style="text-align: right;"><span class="math inline">\(\bar{x} = 0.354\%\)</span></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment">These three numbers are our best single guesses. The rest of the topic builds the <strong>interval</strong> that quantifies how far off each guess might be.</li>
</ul>
</section>
<section id="do-it-in-excel-descriptive-statistics-for-b" class="slide level2 center">
<h2>Do It in Excel: Descriptive Statistics for B</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Select B’s 30 daily eRPMs (<code>erpm_B</code>).</li>
<li class="fragment"><strong>Data -&gt; Data Analysis -&gt; Descriptive Statistics</strong>.</li>
<li class="fragment">Set Input Range; check <strong>Summary statistics</strong> and <strong>Confidence Level for Mean (95%)</strong>.</li>
<li class="fragment">Click OK; read <strong>Mean</strong> (<span class="math inline">\(\bar{x}_B = \$3.459\)</span>) and <strong>Standard Deviation</strong> (<span class="math inline">\(s = \$0.344\)</span>).</li>
<li class="fragment">The <code>Confidence Level(95.0%)</code> row is the margin <span class="math inline">\(E\)</span> we build the interval from next.</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_desc_erpm_B.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="a-question-that-often-comes-up" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If a point estimate like <span class="math inline">\(\bar{x}_B = \$3.459\)</span> is never exactly the true mean, why report a single number at all?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> <span class="math inline">\(\bar{x}_B = \$3.459\)</span> is still the best single guess we have, and every revenue projection has to start somewhere. The point is not to throw it away; it is to <strong>attach a measure of how far off it might be</strong>. That measure is the standard error, and the rest of the topic turns $3.459 into a defensible range around it.</p>
</div>
</div>
</section></section>
<section>
<section id="the-sampling-distribution-of-barx" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Sampling Distribution of <span class="math inline">\(\bar{x}\)</span></h1>

</section>
<section id="a-distribution-of-the-estimates-themselves" class="slide level2 center">
<h2>A Distribution <em>of the Estimates Themselves</em></h2>
<p><br></p>
<ul>
<li class="fragment"><p>Imagine drawing <strong>many</strong> random samples of size <span class="math inline">\(n\)</span>, computing <span class="math inline">\(\bar{x}\)</span> for each. Collect all those <span class="math inline">\(\bar{x}\)</span> values.</p></li>
<li class="fragment"><p>Their distribution is the <strong>sampling distribution of <span class="math inline">\(\bar{x}\)</span></strong>, the probability distribution of the sample mean.</p></li>
<li class="fragment"><p><strong>Do not confuse two distributions:</strong></p>
<ul>
<li class="fragment">the distribution of the <strong>raw data</strong> in one sample (30 daily eRPMs), versus</li>
<li class="fragment">the distribution of the <strong>sample mean</strong> across many samples.</li>
</ul></li>
<li class="fragment"><p>The sampling distribution is what lets us say how close <em>our</em> <span class="math inline">\(\bar{x}\)</span> is likely to be to <span class="math inline">\(\mu\)</span>.</p></li>
</ul>
</section>
<section id="center-and-spread-of-barx" class="slide level2 center">
<h2>Center and Spread of <span class="math inline">\(\bar{x}\)</span></h2>
<p><br></p>
<ul>
<li class="fragment"><strong>Center (unbiased):</strong> on average, the sample mean equals the population mean:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(\bar{x}) = \mu
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>Spread (the standard error):</strong> the standard deviation of <span class="math inline">\(\bar{x}\)</span> is the <strong>standard error of the mean</strong>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\sigma_{\bar{x}} = \frac{\sigma}{\sqrt{n}}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Two terms not to confuse: the <strong>sampling error</strong> is the gap <span class="math inline">\(\bar{x} - \mu\)</span> for <em>one</em> sample (we never see it, since <span class="math inline">\(\mu\)</span> is unknown); the <strong>standard error</strong> <span class="math inline">\(\sigma_{\bar{x}}\)</span> is the <em>typical size</em> of that gap across all samples (we can compute it).</p></li>
<li class="fragment"><p>The estimate is <strong>unbiased</strong> (centered on the truth) and gets <strong>more precise</strong> as <span class="math inline">\(n\)</span> grows.</p></li>
</ul>
</section>
<section id="standard-error-precision-depends-on-n-not-n" class="slide level2 center">
<h2>Standard Error: Precision Depends on <span class="math inline">\(n\)</span>, Not <span class="math inline">\(N\)</span></h2>
<p><br></p>
<ul>
<li class="fragment"><p>The standard error <span class="math inline">\(\sigma/\sqrt{n}\)</span> depends on the <strong>sample size <span class="math inline">\(n\)</span></strong>, <em>not</em> on how big the population is.</p></li>
<li class="fragment"><p><strong>This is the wonderful part:</strong> to halve the wobble of your estimate you need <strong>four times</strong> the data (<span class="math inline">\(\sqrt{n}\)</span>), and it does not matter whether the population is 900 applicants or billions of impressions.</p></li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>St.&nbsp;Andrew’s: <span class="math inline">\(\sigma = 87.4\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\sigma_{\bar{x}} = 87.4/\sqrt{n}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(n = 30\)</span></td>
<td style="text-align: right;"><span class="math inline">\(15.96\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(n = 100\)</span></td>
<td style="text-align: right;"><span class="math inline">\(8.74\)</span></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment">More than triple the sample → the standard error roughly <strong>halves</strong>. Precision is <em>bought</em> with sample size.</li>
</ul>
</section>
<section id="a-question-that-often-comes-up-1" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">Vungle serves billions of impressions. How can 30 days possibly say anything about a population that huge?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> the standard error is <span class="math inline">\(\sigma/\sqrt{n}\)</span>, and the population size <span class="math inline">\(N\)</span> is <strong>nowhere in it</strong>. A 30-day sample is exactly as precise whether the population is 900 St.&nbsp;Andrew’s applicants or Vungle’s billions of impressions. Precision rides on <strong>how many days you sampled</strong>, not on how big the world you sampled from is.</p>
</div>
</div>
</section>
<section id="seeing-the-sampling-distribution" class="slide level2 center">
<h2>Seeing the Sampling Distribution</h2>

<img data-src="figs/sampling_dist_xbar.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><ul>
<li>Repeatedly averaging 10 Vungle A-days: the <strong>individual days</strong> are scattered, but their <strong>averages</strong> pile up tightly in a bell around <span class="math inline">\(\mu\)</span>, narrower than the raw data and roughly Normal.</li>
</ul>
</section></section>
<section>
<section id="the-central-limit-theorem" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Central Limit Theorem</h1>

</section>
<section id="the-clt-why-the-bell-always-appears" class="slide level2 center">
<h2>The CLT: Why the Bell Always Appears</h2>
<p><br></p>
<ul>
<li class="fragment"><strong>Central Limit Theorem:</strong> for random samples of size <span class="math inline">\(n\)</span> from <em>any</em> population with mean <span class="math inline">\(\mu\)</span> and SD <span class="math inline">\(\sigma\)</span>, the sampling distribution of <span class="math inline">\(\bar{x}\)</span> is approximately</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{x} \;\sim\; \text{approximately } N\!\left(\mu,\; \frac{\sigma^2}{n}\right) \quad \text{as } n \text{ grows}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>It works <strong>regardless of the population’s shape</strong>: skewed, uniform, or lumpy, it does not matter.</p></li>
<li class="fragment"><p><strong>Rule of thumb:</strong> <span class="math inline">\(n \geq 30\)</span> is usually enough; <span class="math inline">\(n \geq 50\)</span> if the population is highly skewed or has outliers. Vungle’s <span class="math inline">\(n = 30\)</span> sits right on the line.</p></li>
</ul>
</section>
<section id="the-clt-in-one-picture" class="slide level2 center">
<h2>The CLT in One Picture</h2>

<img data-src="figs/clt_population_shapes.png" class="quarto-figure quarto-figure-center r-stretch" style="width:92.0%"><ul>
<li>Start with a sharply <strong>right-skewed</strong> population (<span class="math inline">\(n = 1\)</span>). Average just a handful of values (<span class="math inline">\(n = 5\)</span>) and it already symmetrizes; by <span class="math inline">\(n = 30\)</span> the distribution of <span class="math inline">\(\bar{x}\)</span> is essentially <strong>Normal</strong>.</li>
</ul>
</section>
<section id="see-the-clt-in-action" class="slide level2 center">
<h2>See the CLT in Action</h2>
<div style="font-size: 90%;">
<p>The CLT is the engine behind every interval we build today: it is <em>why</em> B’s sample mean <span class="math inline">\(\bar{x}_B\)</span> stacks up in a Normal curve around the true <span class="math inline">\(\mu\)</span>, even though B’s 30 daily eRPMs are not perfectly bell-shaped. Watch it happen, then move the sliders yourself.</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div style="text-align:center; font-weight:bold; margin-bottom:0.3em;">
<p>Bunnies, Dragons and the ‘Normal’ World (NYT)</p>
</div>
<iframe width="100%" height="400" src="https://www.youtube.com/embed/jvoxEYmQHNM" title="Central Limit Theorem | The New York Times" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="">
</iframe>
</div><div class="column" style="width:50%;">
<div style="text-align:center; font-weight:bold; margin-bottom:0.3em;">
<p>Seeing Theory (interactive)</p>
</div>
<iframe src="https://seeing-theory.brown.edu/" width="100%" height="400" style="border:1px solid #ccc; border-radius:4px;">
</iframe>
</div></div>
</section>
<section id="using-the-clt-a-probability-question" class="slide level2 center">
<h2>Using the CLT: A Probability Question</h2>
<div class="r-fit-text">
<p><strong>St.&nbsp;Andrew’s:</strong> with <span class="math inline">\(\sigma = 87.4\)</span> and <span class="math inline">\(n = 30\)</span>, what is the probability the sample mean SAT lands <strong>within 10 points</strong> of the true <span class="math inline">\(\mu = 1697\)</span> (i.e., between 1687 and 1707)?</p>
<div class="fragment">
<p><span class="math display">\[
\sigma_{\bar{x}} = \frac{87.4}{\sqrt{30}} = 15.96,
\qquad
z = \frac{10}{15.96} = 0.63
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
P(1687 \le \bar{x} \le 1707) = P(-0.63 \le Z \le 0.63) = 0.4714
\]</span></p>
</div>
<p><strong>Read it:</strong> a single sample of 30 has only about a <strong>47% chance</strong> of landing within 10 SAT points of the truth: precision you can now <em>quantify</em>, and improve by raising <span class="math inline">\(n\)</span>. In Excel: <code>=NORM.S.DIST(0.63,TRUE)-NORM.S.DIST(-0.63,TRUE)</code>.</p>
</div>
</section>
<section id="a-question-that-often-comes-up-2" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">Vungle’s 30 daily eRPMs are not perfectly bell-shaped. Does the CLT still apply to our case?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> yes. The CLT is about the distribution of the <strong>sample mean</strong>, not the raw daily values. It holds no matter the shape of the daily eRPMs: skewed, lumpy, whatever. At <span class="math inline">\(n = 30\)</span> the sampling distribution of <span class="math inline">\(\bar{x}_B\)</span> is already close to Normal, which is what lets us put a <span class="math inline">\(z\)</span> (or <span class="math inline">\(t\)</span>) interval around $3.459. The one caution: <span class="math inline">\(n = 30\)</span> sits on the rule-of-thumb line, so heavy skew or outliers would push us toward wanting more days.</p>
</div>
</div>
</section></section>
<section>
<section id="the-sampling-distribution-of-barp" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Sampling Distribution of <span class="math inline">\(\bar{p}\)</span></h1>

</section>
<section id="proportions-have-a-sampling-distribution-too" class="slide level2 center">
<h2>Proportions Have a Sampling Distribution Too</h2>
<p><br></p>
<ul>
<li class="fragment"><p>For a <strong>yes/no</strong> outcome (an impression converts or it doesn’t), the sample proportion is <span class="math inline">\(\bar{p} = x/n\)</span>.</p></li>
<li class="fragment"><p>It has its own sampling distribution, centered and spread by:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(\bar{p}) = p
\qquad\qquad
\sigma_{\bar{p}} = \sqrt{\frac{p(1-p)}{n}}
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>Normal approximation holds when</strong> the sample is large enough:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
np \geq 5 \qquad \text{and} \qquad n(1-p) \geq 5
\]</span></p>
</div>
<ul>
<li class="fragment">St.&nbsp;Andrew’s: <span class="math inline">\(n = 30\)</span>, <span class="math inline">\(p = 0.72\)</span> → <span class="math inline">\(np = 21.6 \geq 5\)</span> and <span class="math inline">\(n(1-p) = 8.4 \geq 5\)</span> ✓, so the normal approximation is acceptable.</li>
</ul>
</section>
<section id="debrief-lecture-1-takeaway" class="slide level2 center">
<h2>Debrief: Lecture 1 Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> a sample mean is an <strong>unbiased</strong> estimate of the truth, but it <strong>wobbles</strong> by a standard error of <span class="math inline">\(\sigma/\sqrt{n}\)</span>; thanks to the CLT, that wobble is <strong>Normal</strong> for <span class="math inline">\(n \geq 30\)</span>.</p></li>
<li class="fragment"><p><strong>One number:</strong> B’s standard error is <span class="math inline">\(s/\sqrt{30} = 0.344/\sqrt{30} \approx \$0.063\)</span>, the typical gap between a 30-day mean and the truth.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> precision is bought with <span class="math inline">\(n\)</span>, and only as <span class="math inline">\(\sqrt{n}\)</span>; quadrupling the days only halves the error.</p></li>
</ul>
</section>
<section id="todays-question-todays-answer" class="slide level2 center">
<h2>Today’s Question, Today’s Answer</h2>
<p><br></p>
<p><strong>The question (Lecture 1):</strong></p>
<blockquote>
<p><em>How trustworthy is a 30-day sample mean?</em></p>
</blockquote>
<div class="fragment">
<p><br></p>
<p><strong>The answer we reached today:</strong></p>
<blockquote>
<p>A 30-day mean is <strong>unbiased</strong> (it centers on the truth), but it <strong>wobbles</strong> by a standard error of <span class="math inline">\(s/\sqrt{n}\)</span>: for B that is <span class="math inline">\(0.344/\sqrt{30} \approx \mathbf{\$0.063}\)</span>. Thanks to the <strong>CLT</strong>, that wobble is <strong>Normal</strong> at <span class="math inline">\(n = 30\)</span>, so the gap to the truth is small and now <strong>quantifiable</strong>: that is what lets us build a range next.</p>
</blockquote>
</div>
</section>
<section id="team-sprint-your-group-case-lecture-1" class="slide level2 center">
<h2>⏱️ Team Sprint: Your Group Case (Lecture 1)</h2>
<div class="sprint">
<p><strong>Now it’s your group’s turn.</strong> Today’s in-class group case is posted on <strong>Brightspace</strong> (<em>Topic 07 Group Case, Lecture 1</em>): a separate business decision you make with today’s tools.</p>
<p><strong>What you’ll use:</strong> the <strong>standard error</strong> <span class="math inline">\(s/\sqrt{n}\)</span> and the <strong>sampling distribution</strong> of <span class="math inline">\(\bar{x}\)</span> (CLT, <span class="math inline">\(n \geq 30\)</span>). <strong>Excel:</strong> Analysis ToolPak → Descriptive Statistics.</p>
<p><strong>Submit one PDF per group before you leave:</strong> your decision plus the numbers behind it.</p>
</div>
</section></section>
<section>
<section id="lecture-2-the-interval-estimate" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 2: The Interval Estimate</h1>

</section>
<section id="the-brief-3.46-give-or-take-how-much" class="slide level2 center">
<h2>The Brief: $3.46, Give or Take How Much?</h2>
<p><br></p>
<blockquote>
<p>“Don’t just tell me B earns $3.46. Tell me the <strong>range</strong> I can bank on, and tell me how many test-days it would take to cut that range in half.”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p><strong>The big call you still own as the manager:</strong> <em>roll out B, or stay with A?</em> A single $3.46 with no range cannot support it.</p></li>
<li class="fragment"><p><strong>Today’s question (Lecture 2):</strong> <em>what is B’s true mean (and conversion rate), give or take, and how big a sample do we need?</em> We attach a <strong>margin of error</strong> and report an <strong>interval</strong> we are 95% confident contains the truth.</p></li>
<li class="fragment"><p>Then we <strong>invert</strong> the question: pick the precision first (<span class="math inline">\(\pm\$0.05\)</span>), and solve for the <strong>sample size</strong> that delivers it.</p></li>
</ul>
</section>
<section id="how-every-class-runs-1" class="slide level2 center">
<h2>How Every Class Runs</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/lecture_dynamic.png" class="quarto-figure quarto-figure-center" style="width:90.0%"></p>
</figure>
</div>
<p>The class <strong>ends on the Team Sprint</strong>, your group’s graded submission: a decision plus your read of the analysis, one PDF before you leave.</p>
</section>
<section id="a-point-estimate-is-a-spear-an-interval-is-a-net" class="slide level2 center">
<h2>A Point Estimate Is a Spear; an Interval Is a Net</h2>

<img data-src="figs/point_interval_estimate.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><div style="font-size: 92%;">
<ul>
<li>B’s 30 days give one <strong>point estimate</strong>, <span class="math inline">\(\bar{x}_B = \$3.459\)</span>: the manager’s single best guess at B’s true mean eRPM, but almost surely not the exact truth.</li>
<li>Quoting only that one number is <strong>spear-fishing</strong>, a single throw at a moving target. A <strong>confidence interval</strong> is <strong>casting a net</strong>: a plausible range, <span class="math inline">\(\bar{x}_B \pm\)</span> a <strong>margin of error</strong>, built to land on the true <span class="math inline">\(\mu\)</span> most of the time.</li>
<li>The net is what the manager can bank the rollout on. Sizing that margin of error is the rest of today’s work.</li>
</ul>
</div>
</section>
<section id="from-standard-error-to-a-margin-of-error" class="slide level2 center">
<h2>From Standard Error to a Margin of Error</h2>
<p><br></p>
<ul>
<li class="fragment">An <strong>interval estimate</strong> adds and subtracts a <strong>margin of error</strong> <span class="math inline">\(E\)</span> from the point estimate:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{x} \pm E
\qquad\text{where}\qquad
E = (\text{a multiplier}) \times (\text{standard error})
\]</span></p>
</div>
<ul>
<li class="fragment"><p>The multiplier comes from the sampling distribution: about <strong>1.96</strong> standard errors capture the middle <strong>95%</strong> of a Normal curve.</p></li>
<li class="fragment"><p>Two cases for the multiplier:</p>
<ul>
<li class="fragment"><span class="math inline">\(\sigma\)</span> <strong>known</strong> (rare) → use <span class="math inline">\(z\)</span>.</li>
<li class="fragment"><span class="math inline">\(\sigma\)</span> <strong>unknown</strong> (almost always) → estimate it with <span class="math inline">\(s\)</span> and use the <strong><span class="math inline">\(t\)</span> distribution</strong>.</li>
</ul></li>
</ul>
</section>
<section id="the-special-case-sigma-known-use-z" class="slide level2 center">
<h2>The Special Case: <span class="math inline">\(\sigma\)</span> Known → Use <span class="math inline">\(z\)</span></h2>
<p><br></p>
<ul>
<li class="fragment">When <span class="math inline">\(\sigma\)</span> is somehow known (a long production history, a fixed process spec), the interval for <span class="math inline">\(\mu\)</span> uses the <span class="math inline">\(z\)</span> multiplier directly:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{x} \pm z_{\alpha/2}\,\frac{\sigma}{\sqrt{n}}
\]</span></p>
</div>
<ul>
<li class="fragment">The multiplier is read straight from the Normal table, the same values for every sample size:</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Confidence</th>
<th style="text-align: right;"><span class="math inline">\(z_{\alpha/2}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90%</td>
<td style="text-align: right;">1.645</td>
</tr>
<tr class="even">
<td>95%</td>
<td style="text-align: right;">1.960</td>
</tr>
<tr class="odd">
<td>99%</td>
<td style="text-align: right;">2.576</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment">Vungle does <strong>not</strong> know <span class="math inline">\(\sigma\)</span> for B’s eRPM, so this case does not apply here. We estimate <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(s\)</span>, which is why the rest of the topic uses <span class="math inline">\(t\)</span>.</li>
</ul>
</section></section>
<section>
<section id="the-t-distribution" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The <span class="math inline">\(t\)</span> Distribution</h1>

</section>
<section id="why-t-not-z" class="slide level2 center">
<h2>Why <span class="math inline">\(t\)</span>, Not <span class="math inline">\(z\)</span></h2>
<p><br></p>
<ul>
<li class="fragment"><p>In real data we never know <span class="math inline">\(\sigma\)</span>; we estimate it with the sample SD <span class="math inline">\(s\)</span>. That extra uncertainty makes the bell <strong>fatter in the tails</strong>: the <strong><span class="math inline">\(t\)</span> distribution</strong>.</p></li>
<li class="fragment"><p>A <span class="math inline">\(t\)</span> distribution is indexed by its <strong>degrees of freedom</strong> <span class="math inline">\(df = n - 1\)</span> (the <span class="math inline">\(n\)</span> observations, minus one used up estimating <span class="math inline">\(s\)</span>).</p></li>
<li class="fragment"><p>As <span class="math inline">\(df\)</span> grows, <span class="math inline">\(t\)</span> converges to <span class="math inline">\(z\)</span>: by <span class="math inline">\(df = 29\)</span> they are nearly identical, and beyond <span class="math inline">\(df = 100\)</span> the difference is negligible.</p></li>
</ul>
</section>
<section id="t-has-fatter-tails-than-z" class="slide level2 center">
<h2><span class="math inline">\(t\)</span> Has Fatter Tails Than <span class="math inline">\(z\)</span></h2>

<img data-src="figs/t_vs_z.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><ul>
<li>Fatter tails → a <strong>larger</strong> multiplier → a <strong>wider</strong> interval. That is the honest “tax” for not knowing <span class="math inline">\(\sigma\)</span>. Excel: <code>=T.INV.2T(0.05, df)</code> gives the 95% multiplier.</li>
</ul>
</section>
<section id="a-question-that-often-comes-up-3" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">At <span class="math inline">\(df = 29\)</span> the <span class="math inline">\(t\)</span> multiplier 2.045 is barely above <span class="math inline">\(z\)</span>’s 1.96. For Vungle’s 30 days, is the difference even worth the trouble?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> here it is small but not zero: using 2.045 instead of 1.96 widens B’s eRPM margin from about $0.124 to $0.129, the honest cost of not knowing <span class="math inline">\(\sigma\)</span>. The habit matters more than this one case. With a small sample, say <span class="math inline">\(n = 10\)</span>, the gap is large, and “always use <span class="math inline">\(t\)</span> when <span class="math inline">\(\sigma\)</span> is unknown” keeps you correct without having to decide each time whether <span class="math inline">\(n\)</span> is “big enough.”</p>
</div>
</div>
</section></section>
<section>
<section id="confidence-interval-for-a-mean" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Confidence Interval for a Mean</h1>

</section>
<section id="the-t-interval-formula" class="slide level2 center">
<h2>The <span class="math inline">\(t\)</span>-Interval Formula</h2>
<p><br></p>
<ul>
<li class="fragment">With <span class="math inline">\(\sigma\)</span> unknown (the usual case), the confidence interval for <span class="math inline">\(\mu\)</span> is:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{x} \pm t_{\alpha/2,\,n-1}\,\frac{s}{\sqrt{n}}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>The pieces: <span class="math inline">\(\bar{x}\)</span> the point estimate, <span class="math inline">\(s/\sqrt{n}\)</span> the standard error, <span class="math inline">\(t_{\alpha/2,\,n-1}\)</span> the multiplier for confidence level <span class="math inline">\(1-\alpha\)</span>.</p></li>
<li class="fragment"><p>Excel multipliers: <code>=T.INV.2T(0.05, n-1)</code> (95%), <code>=T.INV.2T(0.10, n-1)</code> (90%), <code>=T.INV.2T(0.01, n-1)</code> (99%).</p></li>
</ul>
</section>
<section id="what-95-confident-really-means" class="slide level2 center">
<h2>What “95% Confident” Really Means</h2>

<img data-src="figs/ci_mechanics.png" class="quarto-figure quarto-figure-center r-stretch" style="width:74.0%"><ul>
<li><strong>Correct:</strong> <em>“in repeated sampling, about 95% of intervals built this way contain <span class="math inline">\(\mu\)</span>.”</em> The interval is random; <span class="math inline">\(\mu\)</span> is fixed.</li>
<li><strong>Wrong:</strong> <em>“there is a 95% chance <span class="math inline">\(\mu\)</span> is in this one interval.”</em> Once computed, an interval either contains <span class="math inline">\(\mu\)</span> or it doesn’t.</li>
</ul>
</section>
<section id="a-question-that-often-comes-up-4" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If I can’t say there’s a 95% chance B’s true eRPM is inside ($3.33, $3.59), then what do I actually tell my boss?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> you tell the boss, <em>“we built this range with a method that captures the true mean 95% of the time, and it puts B’s eRPM between $3.33 and $3.59.”</em> The 95% is your confidence in the <strong>procedure</strong>, not a betting line on this one interval. In practice the manager acts on the range exactly the same way; the wording just keeps you honest about where the uncertainty lives.</p>
</div>
</div>
</section>
<section id="anchor-example-apartment-rents" class="slide level2 center">
<h2>Anchor Example: Apartment Rents</h2>
<div class="r-fit-text">
<p>A reporter samples <span class="math inline">\(n = 16\)</span> one-bedroom apartments near campus: <span class="math inline">\(\bar{x} = \$750\)</span>/month, <span class="math inline">\(s = \$55\)</span>. Population assumed roughly Normal; <span class="math inline">\(\sigma\)</span> unknown → <strong><span class="math inline">\(t\)</span>-interval</strong>, <span class="math inline">\(df = 15\)</span>.</p>
<div class="fragment">
<p><span class="math display">\[
t_{0.025,\,15} = 2.131,
\qquad
\frac{s}{\sqrt{n}} = \frac{55}{\sqrt{16}} = 13.75,
\qquad
E = 2.131 \times 13.75 = 29.31
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
750 \pm 29.31 \;=\; (\$720.69,\; \$779.31)
\]</span></p>
</div>
<p><strong>Read it:</strong> <em>we are 95% confident the true mean rent for one-bedroom apartments near campus is between $721 and $779.</em> In Excel: <code>=CONFIDENCE.T(0.05, 55, 16)</code> returns the margin $29.31 directly.</p>
</div>
</section>
<section id="the-vungle-erpm-interval-the-five-steps" class="slide level2 center">
<h2>The Vungle eRPM Interval: the Five Steps</h2>
<div class="r-fit-text">
<p><strong>1. Business context.</strong> B’s true mean eRPM drives every revenue projection; the manager needs a defensible range, not a single number.</p>
<p><strong>2. Setup.</strong> <span class="math inline">\(n = 30\)</span> days, <span class="math inline">\(\sigma\)</span> unknown, <span class="math inline">\(\bar{x}_B = \$3.459\)</span>, <span class="math inline">\(s_B = \$0.344\)</span>, <span class="math inline">\(df = 29\)</span>, 95% confidence.</p>
<p><strong>3. Compute.</strong></p>
<p><span class="math display">\[
\frac{s}{\sqrt{n}} = \frac{0.344}{\sqrt{30}} = 0.0629,
\qquad
t_{0.025,\,29} = 2.045,
\qquad
E = 2.045 \times 0.0629 = 0.1286
\]</span></p>
<p><strong>4. Interval.</strong> <span class="math inline">\(3.459 \pm 0.129 = (\$3.330,\; \$3.588)\)</span>.</p>
<p><strong>5. Manager’s Translation.</strong> <em>We are 95% confident B’s true mean eRPM is between $3.33 and $3.59. The $0.13 margin is wide relative to the $0.11 gap over A, a first hint that 30 days may not yet settle the A-vs-B question.</em></p>
</div>
</section>
<section id="the-two-intervals-side-by-side" class="slide level2 center">
<h2>The Two Intervals, Side by Side</h2>

<img data-src="figs/vungle_erpm_ci.png" class="quarto-figure quarto-figure-center r-stretch" style="width:78.0%"><ul>
<li>A’s interval is <strong>($3.27, $3.43)</strong>, B’s is <strong>($3.33, $3.59)</strong>, and they <strong>overlap</strong>. Estimation alone cannot yet declare a winner; that is the job of <strong>hypothesis testing</strong>, next topic.</li>
</ul>
</section>
<section id="do-it-in-excel-the-erpm-t-interval" class="slide level2 center">
<h2>Do It in Excel: the eRPM <span class="math inline">\(t\)</span>-Interval</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Select B’s 30 daily eRPMs (<code>erpm_B</code>).</li>
<li class="fragment"><code>=AVERAGE(range)</code> → <span class="math inline">\(\bar{x}_B\)</span>; <code>=STDEV.S(range)</code> → <span class="math inline">\(s\)</span>.</li>
<li class="fragment"><code>=T.INV.2T(0.05, 29)</code> → the multiplier <span class="math inline">\(2.045\)</span>.</li>
<li class="fragment"><code>=CONFIDENCE.T(0.05, s, 30)</code> → the margin <span class="math inline">\(E = \$0.129\)</span> in one cell.</li>
<li class="fragment">Read <span class="math inline">\(\bar{x}_B \pm E\)</span>: the 95% interval <span class="math inline">\((\$3.330,\ \$3.588)\)</span>.</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_ci_mean.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="adequate-sample-size-for-a-t-interval" class="slide level2 center">
<h2>Adequate Sample Size for a <span class="math inline">\(t\)</span>-Interval</h2>
<p><br></p>
<ul>
<li>A general guide for the <span class="math inline">\(t\)</span>-interval to behave well:
<ul>
<li><span class="math inline">\(n \geq 30\)</span> is usually adequate.</li>
<li><span class="math inline">\(n \geq 50\)</span> if the population is highly skewed or has outliers.</li>
<li><span class="math inline">\(n \geq 15\)</span> suffices if the population is roughly symmetric.</li>
<li><span class="math inline">\(n &lt; 15\)</span> only if the population is approximately Normal.</li>
</ul></li>
</ul>
<ul>
<li class="fragment">Vungle’s eRPM is roughly symmetric (mean <span class="math inline">\(\approx\)</span> median in our descriptives), so <span class="math inline">\(n = 30\)</span> clears the bar; the interval is trustworthy, it is just <strong>wide</strong>.</li>
</ul>
</section></section>
<section>
<section id="confidence-interval-for-a-proportion" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Confidence Interval for a Proportion</h1>

</section>
<section id="the-proportion-interval" class="slide level2 center">
<h2>The Proportion Interval</h2>
<p><br></p>
<ul>
<li class="fragment">For a population proportion <span class="math inline">\(p\)</span>, the interval uses <span class="math inline">\(\bar{p}\)</span> and the <strong><span class="math inline">\(z\)</span></strong> multiplier (no <span class="math inline">\(t\)</span>, since there is no separate SD to estimate):</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{p} \pm z_{\alpha/2}\sqrt{\frac{\bar{p}(1-\bar{p})}{n}}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Check the large-sample condition first: <span class="math inline">\(n\bar{p} \geq 5\)</span> and <span class="math inline">\(n(1-\bar{p}) \geq 5\)</span>.</p></li>
<li class="fragment"><p>Excel: <code>=NORM.S.INV(0.975)</code> → 1.96 for the 95% multiplier.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-5" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">We just learned to use <span class="math inline">\(t\)</span> when <span class="math inline">\(\sigma\)</span> is unknown. For B’s conversion rate we don’t know the true <span class="math inline">\(p\)</span> either, so why does the proportion interval use <span class="math inline">\(z\)</span>, not <span class="math inline">\(t\)</span>?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> the <span class="math inline">\(t\)</span> exists to fix one specific problem: estimating a <strong>separate</strong> spread <span class="math inline">\(s\)</span> for a mean. A proportion has no separate spread; its variability is fixed by <span class="math inline">\(p\)</span> itself, so there is nothing extra to estimate and no fattened tails to correct. We plug <span class="math inline">\(\bar{p}\)</span> into the standard error and use <span class="math inline">\(z\)</span> straight away, after checking <span class="math inline">\(n\bar{p} \geq 5\)</span> and <span class="math inline">\(n(1-\bar{p}) \geq 5\)</span>.</p>
</div>
</div>
</section>
<section id="anchor-example-psi-election-poll" class="slide level2 center">
<h2>Anchor Example: PSI Election Poll</h2>
<div class="r-fit-text">
<p>Political Science Inc.&nbsp;contacts <span class="math inline">\(n = 500\)</span> registered voters; <strong>220</strong> favor the candidate, so <span class="math inline">\(\bar{p} = 220/500 = 0.44\)</span>. Build a 95% interval for the true share.</p>
<div class="fragment">
<p><span class="math display">\[
\sqrt{\frac{0.44(0.56)}{500}} = 0.0222,
\qquad
E = 1.96 \times 0.0222 = 0.0435
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
0.44 \pm 0.0435 \;=\; (0.3965,\; 0.4835)
\]</span></p>
</div>
<p><strong>Read it:</strong> <em>PSI is 95% confident that between 39.6% and 48.4% of all voters favor the candidate.</em> The interval straddles 50% from below: too close to call a lead.</p>
</div>
</section>
<section id="vungle-conversion-rate-a-proportion-in-practice" class="slide level2 center">
<h2>Vungle Conversion Rate: a Proportion in Practice</h2>
<p><br></p>
<ul>
<li class="fragment">Each impression either becomes an install or not, a proportion. We estimate B’s <strong>true mean daily conversion rate</strong> from the 30 daily rates (a <span class="math inline">\(t\)</span>-interval on the daily percentages keeps the unit the <strong>day</strong>, parallel to eRPM):</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Algorithm B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>mean daily rate</td>
<td style="text-align: right;"><span class="math inline">\(0.3538\%\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(s\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.0231\%\)</span></td>
</tr>
<tr class="odd">
<td>standard error</td>
<td style="text-align: right;"><span class="math inline">\(0.0042\%\)</span></td>
</tr>
<tr class="even">
<td>95% margin (<span class="math inline">\(t_{29}\)</span>)</td>
<td style="text-align: right;"><span class="math inline">\(0.0086\%\)</span></td>
</tr>
<tr class="odd">
<td><strong>95% CI</strong></td>
<td style="text-align: right;"><span class="math inline">\((0.345\%,\; 0.362\%)\)</span></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><strong>Read it:</strong> we are 95% confident B converts between <strong>0.345% and 0.362%</strong> of impressions to installs, a tight interval because day-to-day conversion is very stable.</li>
</ul>
</section>
<section id="do-it-in-excel-the-conversion-rate-interval" class="slide level2 center">
<h2>Do It in Excel: the Conversion-Rate Interval</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Select B’s daily conversion column (<code>conv_B_pct</code>).</li>
<li class="fragment"><code>=AVERAGE</code> → <span class="math inline">\(0.354\%\)</span>; <code>=STDEV.S</code> → <span class="math inline">\(s = 0.023\%\)</span>.</li>
<li class="fragment"><code>=CONFIDENCE.T(0.05, s, 30)</code> → margin <span class="math inline">\(E = 0.0086\%\)</span>.</li>
<li class="fragment">Read <span class="math inline">\(\bar{x} \pm E\)</span>: <span class="math inline">\((0.345\%,\ 0.362\%)\)</span>.</li>
<li class="fragment">Note how tiny <span class="math inline">\(s\)</span> is: stable days give a very tight interval.</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_ci_prop.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section></section>
<section>
<section id="margin-of-error-sample-size" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Margin of Error &amp; Sample Size</h1>

</section>
<section id="the-three-levers-that-set-interval-width" class="slide level2 center">
<h2>The Three Levers That Set Interval Width</h2>
<p><br></p>
<ul>
<li class="fragment">The margin of error <span class="math inline">\(E = t_{\alpha/2}\,s/\sqrt{n}\)</span> moves with exactly three things:</li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Lever</th>
<th>Increase it → interval gets</th>
<th>Manager’s control?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Confidence level</strong> (<span class="math inline">\(1-\alpha\)</span>)</td>
<td><strong>wider</strong> (bigger multiplier)</td>
<td>choose it</td>
</tr>
<tr class="even">
<td><strong>Variability</strong> (<span class="math inline">\(s\)</span>)</td>
<td><strong>wider</strong></td>
<td>not directly</td>
</tr>
<tr class="odd">
<td><strong>Sample size</strong> (<span class="math inline">\(n\)</span>)</td>
<td><strong>narrower</strong> (as <span class="math inline">\(\sqrt{n}\)</span>)</td>
<td><strong>yes: buy more data</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment">The only lever a manager freely controls is <strong><span class="math inline">\(n\)</span></strong>. Want a tighter interval at the same confidence? Collect more days.</li>
</ul>
</section>
<section id="higher-confidence-costs-width" class="slide level2 center">
<h2>Higher Confidence Costs Width</h2>
<p><br></p>
<ul>
<li class="fragment">For B’s eRPM, holding <span class="math inline">\(n = 30\)</span> fixed, raising confidence <strong>widens</strong> the interval:</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Confidence</th>
<th style="text-align: right;"><span class="math inline">\(t^*\)</span> multiplier</th>
<th style="text-align: right;">Margin <span class="math inline">\(E\)</span></th>
<th style="text-align: right;">Interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90%</td>
<td style="text-align: right;">1.699</td>
<td style="text-align: right;">$0.107</td>
<td style="text-align: right;">($3.352, $3.566)</td>
</tr>
<tr class="even">
<td>95%</td>
<td style="text-align: right;">2.045</td>
<td style="text-align: right;">$0.129</td>
<td style="text-align: right;">($3.330, $3.588)</td>
</tr>
<tr class="odd">
<td>99%</td>
<td style="text-align: right;">2.756</td>
<td style="text-align: right;">$0.173</td>
<td style="text-align: right;">($3.286, $3.632)</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment">More confidence = a <strong>wider net</strong>. There is no free lunch: to be <em>more</em> sure the interval contains <span class="math inline">\(\mu\)</span>, you must accept a <em>less</em> precise range.</li>
</ul>
</section>
<section id="sample-size-pick-precision-first-solve-for-n" class="slide level2 center">
<h2>Sample Size: Pick Precision First, Solve for <span class="math inline">\(n\)</span></h2>
<p><br></p>
<ul>
<li class="fragment">Invert the margin-of-error formula. Set the target <span class="math inline">\(E\)</span>, use a planning <span class="math inline">\(s\)</span> and <span class="math inline">\(z\)</span> (95% → 1.96):</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E = z_{\alpha/2}\frac{s}{\sqrt{n}}
\qquad\Longrightarrow\qquad
n = \left(\frac{z_{\alpha/2}\,s}{E}\right)^{2}
\]</span></p>
</div>
<ul>
<li class="fragment"><p><strong>Always round up:</strong> a fractional person or day cannot be sampled, and rounding down would miss the target precision.</p></li>
<li class="fragment"><p>Planning value for <span class="math inline">\(s\)</span>: a prior study, a pilot sample, or a best guess. Here we use B’s pilot <span class="math inline">\(s = \$0.3444\)</span>.</p></li>
</ul>
</section>
<section id="how-many-days-does-vungle-need" class="slide level2 center">
<h2>How Many Days Does Vungle Need?</h2>
<div class="r-fit-text">
<p><strong>Question:</strong> how many test-days for the mean eRPM margin to hit <span class="math inline">\(\pm\$0.10\)</span>? <span class="math inline">\(\pm\$0.05\)</span>? (planning <span class="math inline">\(s = 0.3444\)</span>, 95% confidence, <span class="math inline">\(z = 1.96\)</span>)</p>
<div class="fragment">
<p><span class="math display">\[
n_{0.10} = \left(\frac{1.96 \times 0.3444}{0.10}\right)^{2} = 45.6 \;\rightarrow\; \mathbf{46 \text{ days}}
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
n_{0.05} = \left(\frac{1.96 \times 0.3444}{0.05}\right)^{2} = 182.3 \;\rightarrow\; \mathbf{183 \text{ days}}
\]</span></p>
</div>
<p><strong>The lesson:</strong> halving the margin (<span class="math inline">\(\$0.10 \rightarrow \$0.05\)</span>) takes <strong>four times</strong> the days (<span class="math inline">\(46 \rightarrow 183\)</span>). Precision is expensive, and the manager must decide whether $0.05 of precision is worth six months of testing.</p>
</div>
</section>
<section id="a-question-that-often-comes-up-6" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">The sample-size formula needs <span class="math inline">\(s\)</span>, but <span class="math inline">\(s\)</span> is exactly what a longer test is supposed to pin down. Isn’t that circular?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> it would be, except we use a <strong>planning value</strong> for <span class="math inline">\(s\)</span>, not the final one. Here we borrow B’s pilot <span class="math inline">\(s = \$0.3444\)</span> from the 30 days we already have. It only needs to be roughly right to get the day count in the ballpark: <span class="math inline">\(183\)</span> days for <span class="math inline">\(\pm\$0.05\)</span>. When the real test finishes you recompute <span class="math inline">\(s\)</span> from the full data and report the actual interval; the planning value is just for sizing the test, not for the final answer.</p>
</div>
</div>
</section>
<section id="margin-of-error-vs.-sample-size" class="slide level2 center">
<h2>Margin of Error vs.&nbsp;Sample Size</h2>

<img data-src="figs/moe_vs_n.png" class="quarto-figure quarto-figure-center r-stretch" style="width:78.0%"><ul>
<li>The curve flattens fast: early days buy a lot of precision, later days buy very little. The <span class="math inline">\(\sqrt{n}\)</span> law is why <strong>doubling down</strong> on data has <strong>diminishing returns</strong>.</li>
</ul>
</section>
<section id="do-it-in-excel-the-required-sample-size" class="slide level2 center">
<h2>Do It in Excel: the Required Sample Size</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Enter the planning SD <code>s</code> (B’s pilot <span class="math inline">\(\$0.3444\)</span>) and the target margin <code>E</code> in cells.</li>
<li class="fragment"><code>=NORM.S.INV(0.975)</code> → the <span class="math inline">\(z\)</span> multiplier <span class="math inline">\(1.96\)</span>.</li>
<li class="fragment"><code>=CEILING((NORM.S.INV(0.975)*s/E)^2, 1)</code> in one cell.</li>
<li class="fragment">Set <span class="math inline">\(E = 0.10\)</span> → reads <strong>46 days</strong>; set <span class="math inline">\(E = 0.05\)</span> → reads <strong>183 days</strong>.</li>
<li class="fragment"><code>CEILING(...,1)</code> rounds <strong>up</strong>: never round a day count down.</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_sample_size.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="sample-size-for-a-proportion" class="slide level2 center">
<h2>Sample Size for a Proportion</h2>
<p><br></p>
<ul>
<li class="fragment">The proportion version, solving the same way:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
n = \frac{z_{\alpha/2}^{2}\,p^*(1-p^*)}{E^{2}}
\]</span></p>
</div>
<ul>
<li class="fragment"><p><span class="math inline">\(p^*\)</span> is a <strong>planning value</strong> for the proportion: a prior estimate, a pilot, or (if you know nothing) the <strong>conservative <span class="math inline">\(p^* = 0.5\)</span></strong>, which maximizes <span class="math inline">\(p^*(1-p^*)\)</span> and gives the largest (safest) <span class="math inline">\(n\)</span>.</p></li>
<li class="fragment"><p><strong>PSI example:</strong> for <span class="math inline">\(E = 0.03\)</span> at 99% (<span class="math inline">\(z = 2.576\)</span>): with <span class="math inline">\(p^* = 0.44\)</span>, <span class="math inline">\(n = 1817\)</span>; with the conservative <span class="math inline">\(p^* = 0.5\)</span>, <span class="math inline">\(n = 1844\)</span>. When unsure, plan for the larger.</p></li>
</ul>
</section></section>
<section>
<section id="debrief-the-estimation-memo" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Debrief: The Estimation Memo</h1>

</section>
<section id="what-the-intervals-tell-vungle" class="slide level2 center">
<h2>What the Intervals Tell Vungle</h2>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Point estimate</th>
<th style="text-align: right;">95% interval</th>
<th>Read</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean eRPM (B)</td>
<td style="text-align: right;">$3.459</td>
<td style="text-align: right;">($3.330, $3.588)</td>
<td>true earning power, <span class="math inline">\(\pm\$0.13\)</span></td>
</tr>
<tr class="even">
<td>Conversion rate (B)</td>
<td style="text-align: right;">0.354%</td>
<td style="text-align: right;">(0.345%, 0.362%)</td>
<td>very stable, <span class="math inline">\(\pm 0.009\)</span>pt</td>
</tr>
<tr class="odd">
<td>Days for <span class="math inline">\(\pm\$0.05\)</span> eRPM</td>
<td style="text-align: right;">(n/a)</td>
<td style="text-align: right;"><span class="math inline">\(n = 183\)</span></td>
<td>six months to halve the margin</td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment"><strong>The memo in one line:</strong> B’s true mean eRPM is <strong>$3.46 give or take $0.13</strong>, its conversion rate is <strong>0.354% give or take 0.009pt</strong>, and reaching <span class="math inline">\(\pm\$0.05\)</span> on eRPM would take about <strong>183 days</strong> of testing.</li>
</ul>
</section>
<section id="the-honest-limit-of-estimation" class="slide level2 center">
<h2>The Honest Limit of Estimation</h2>
<p><br></p>
<ul>
<li class="fragment"><p>B’s eRPM interval <strong>($3.33, $3.59)</strong> and A’s <strong>($3.27, $3.43)</strong> <strong>overlap</strong>. The $0.11 sample gap is real in <em>this</em> sample, but the intervals do not, by themselves, prove B’s <em>true</em> mean beats A’s.</p></li>
<li class="fragment"><p>Estimation answers <em>“how big, and how sure are we about that size?”</em>; it does <strong>not</strong> directly answer <em>“is B better than A?”</em></p></li>
<li class="fragment"><p>That comparison question (<strong>does B beat a benchmark, and does B beat A?</strong>) is <strong>hypothesis testing</strong>, the next two topics. Today’s standard error and <span class="math inline">\(t\)</span> machinery carry straight over.</p></li>
</ul>
</section>
<section id="the-managers-takeaway" class="slide level2 center">
<h2>The Manager’s Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> a confidence interval turns a point estimate into a defensible <strong>range</strong> (B’s true mean eRPM is $3.46 <span class="math inline">\(\pm\)</span> $0.13 at 95% confidence), and the <strong>margin of error</strong> is the number the manager should actually negotiate over.</p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <span class="math inline">\(E = t_{\alpha/2}\,s/\sqrt{n}\)</span>, with the <span class="math inline">\(\sqrt{n}\)</span> in the denominator that makes precision expensive.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> “95% confident” describes the <strong>procedure</strong> over many samples, not a probability for this one interval; overlapping intervals do <strong>not</strong> settle a comparison.</p></li>
</ul>
</section>
<section id="todays-question-todays-answer-1" class="slide level2 center">
<h2>Today’s Question, Today’s Answer</h2>
<p><br></p>
<p><strong>The question (Lecture 2, and Topic 7 of the ladder):</strong></p>
<blockquote>
<p><em>From 30 days, what is B’s true mean eRPM, give or take, and how big a sample do we need?</em></p>
</blockquote>
<div class="fragment">
<p><br></p>
<p><strong>The answer we reached today:</strong></p>
<blockquote>
<p>We are 95% confident B’s true mean eRPM is <strong>$3.46 give or take $0.13</strong>, i.e.&nbsp;<strong>($3.33, $3.59)</strong>, and its conversion rate is <strong>0.354% give or take 0.009pt</strong>, i.e.&nbsp;<strong>(0.345%, 0.362%)</strong>. To cut the eRPM margin to <span class="math inline">\(\pm\$0.05\)</span> takes about <strong>183 days</strong> of testing. The eRPM range still <strong>overlaps A’s</strong>, so estimation alone cannot yet name a winner: that is hypothesis testing, next.</p>
</blockquote>
</div>
</section>
<section id="team-sprint-your-group-case-lecture-2" class="slide level2 center">
<h2>⏱️ Team Sprint: Your Group Case (Lecture 2)</h2>
<div class="sprint">
<p><strong>Now it’s your group’s turn.</strong> Today’s in-class group case is posted on <strong>Brightspace</strong> (<em>Topic 07 Group Case, Lecture 2</em>): a separate business decision you make with today’s tools.</p>
<p><strong>What you’ll use:</strong> <strong>confidence intervals</strong> for a mean (<span class="math inline">\(t\)</span>) and a proportion (<span class="math inline">\(z\)</span>), the <strong>margin of error</strong>, and <strong>sample size</strong> planning. <strong>Excel:</strong> Analysis ToolPak, plus <code>=CONFIDENCE.T</code> and <code>=CEILING</code>.</p>
<p><strong>Submit one PDF per group before you leave:</strong> your decision plus the numbers behind it.</p>
</div>
</section></section>
<section>
<section id="wrap-up" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Wrap-up</h1>

</section>
<section id="summary" class="slide level2 center">
<h2>Summary</h2>
<p>Some key takeaways from this session:</p>
<ul>
<li>A <strong>point estimate</strong> (<span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(\bar{p}\)</span>) is a single best guess; it is <strong>unbiased</strong> but tells you nothing about how close it is.</li>
<li>The <strong>sampling distribution</strong> of <span class="math inline">\(\bar{x}\)</span> is centered at <span class="math inline">\(\mu\)</span> with standard error <span class="math inline">\(\sigma/\sqrt{n}\)</span>; the <strong>CLT</strong> makes it Normal for <span class="math inline">\(n \geq 30\)</span>, whatever the population’s shape.</li>
<li>A <strong>confidence interval</strong> = point estimate <span class="math inline">\(\pm\)</span> margin of error; use <strong><span class="math inline">\(t\)</span></strong> for a mean (<span class="math inline">\(\sigma\)</span> unknown), <strong><span class="math inline">\(z\)</span></strong> for a proportion.</li>
<li>The margin of error has <strong>three levers</strong>: confidence level (up → wider), variability <span class="math inline">\(s\)</span> (up → wider), sample size <span class="math inline">\(n\)</span> (up → narrower, as <span class="math inline">\(\sqrt{n}\)</span>).</li>
<li><strong>Sample size</strong> inverts the margin formula: pick the precision, solve for <span class="math inline">\(n\)</span>, round up; halving the margin costs ~4× the data.</li>
<li>“95% confident” is a statement about the <strong>method</strong>, not a probability for one interval, and overlapping intervals do not prove a difference.</li>
<li><strong>Next time:</strong> we stop <em>estimating ranges</em> and start <em>testing claims</em> (<strong>Hypothesis Testing</strong>: fund B only if its mean eRPM clears a benchmark); today’s standard error and <span class="math inline">\(t\)</span> become the test statistic.</li>
</ul>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Thank you!</h1>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Business Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>