<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Professor Davi Moreira ">
  <title>QM 6700: Business Analytics –  QM 6700: Business Analytics </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-113b5beb2a57b2deea58feb1108e76b2.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="font-size: 100%;"> QM 6700: Business Analytics </span></h1>
  <p class="subtitle"><span style="font-size: 150%;"> Continuous Probability Distributions </span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor<br>Davi Moreira<br> 
</div>
</div>
</div>

</section>
<section id="overview" class="slide level2 center">
<h2>Overview</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Case Spotlight: A/B Testing at Vungle</li>
<li>Continuous random variables: probability is <strong>area</strong></li>
<li>The uniform distribution (the simplest continuous model)</li>
<li>The <strong>Normal</strong> distribution: shape, the empirical rule</li>
<li>The standard Normal and <strong>z</strong>-scores</li>
<li>Modeling daily eRPM as Normal</li>
</ul>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Normal probabilities in Excel: <code>NORM.DIST</code>, <code>NORM.INV</code></li>
<li>Tail probabilities: <span class="math inline">\(P(\text{eRPM} &gt; \$3.50)\)</span></li>
<li>Percentiles: the <strong>90th-percentile day</strong></li>
<li><strong>Checking</strong> the Normal assumption (QQ plot)</li>
<li>The Normal <strong>approximation of the Binomial</strong></li>
<li>From a distribution to a planning number</li>
</ul>
</div></div>
</section>
<section>
<section id="case-spotlight-ab-testing-at-vungle" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Case Spotlight: A/B Testing at Vungle</h1>

</section>
<section id="back-to-vungle-now-we-model-the-distribution" class="slide level2 center">
<h2>Back to Vungle — Now We Model the <em>Distribution</em></h2>
<p><br></p>
<ul>
<li class="fragment"><p><a href="https://en.wikipedia.org/wiki/Liftoff_Mobile">Vungle</a> serves 15-second video ads inside other apps and earns revenue mainly when viewers <strong>install</strong> the advertised app.</p></li>
<li class="fragment"><p>The metric that pays the bills is <strong>eRPM</strong>: effective revenue per 1,000 impressions. Algorithm <strong>B</strong> is the new ad-serving engine the team is evaluating.</p></li>
<li class="fragment"><p>So far we have <strong>summarized</strong> eRPM (center, spread) and modeled <strong>counts</strong> (installs) with the Binomial and Poisson. Today we model a <strong>continuous</strong> quantity — the dollar value of eRPM itself.</p></li>
<li class="fragment"><p>Over 30 days of June 2014, B’s daily eRPM averaged <strong>$3.46</strong> with a standard deviation of <strong>$0.34</strong>. The histogram is a bell.</p></li>
<li class="fragment"><p><strong>Today’s move:</strong> treat daily eRPM as a draw from a <strong>Normal distribution</strong> — then we can answer <em>forward-looking</em> questions about days we have not yet seen.</p></li>
</ul>
</section>
<section id="the-brief-todays-managerial-question" class="slide level2 center">
<h2>The Brief — Today’s Managerial Question</h2>
<p><br></p>
<blockquote>
<p>“Model B’s daily eRPM as Normal($3.46, $0.34). What’s the chance tomorrow’s eRPM <strong>tops $3.50</strong>? What eRPM marks a <strong>90th-percentile day</strong> — and is the Normal model even <strong>trustworthy</strong> here?”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p>Counting distributions (Binomial, Poisson) answered “how many installs?” Today’s tool answers “<strong>how much revenue per impression</strong>, and how often above a threshold?”</p></li>
<li class="fragment"><p><strong>How today’s studio runs:</strong> I demo each idea on a textbook example → <strong>your team fits the Normal to Vungle eRPM</strong> (two sprints) → we debrief what the model can and cannot tell a manager.</p></li>
<li class="fragment"><p>By the end, <strong>your team</strong> turns a fitted distribution into a planning number (a probability and a percentile) and stress-tests the assumption behind it.</p></li>
</ul>
</section>
<section id="how-todays-tools-answer-it" class="slide level2 center">
<h2>How Today’s Tools Answer It</h2>
<p><br></p>
<p>Every tool today maps onto the Vungle eRPM data:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>The managerial question</th>
<th>The tool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“What does a <em>typical</em> day look like?”</td>
<td><strong>Normal model</strong> — mean $3.46, sd $0.34</td>
</tr>
<tr class="even">
<td>“How likely is eRPM above $3.50?”</td>
<td><strong>z-score + <code>NORM.DIST</code></strong> (a tail area)</td>
</tr>
<tr class="odd">
<td>“What’s a great day — the top 10%?”</td>
<td><strong><code>NORM.INV</code></strong> (a percentile)</td>
</tr>
<tr class="even">
<td>“Is ‘Normal’ even a fair assumption?”</td>
<td><strong>Normal-probability (QQ) plot</strong></td>
</tr>
<tr class="odd">
<td>“Plan for installs at huge scale”</td>
<td><strong>Normal approximation of the Binomial</strong></td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment">One dataset, one bell curve — and from it, every probability and percentile a manager needs.</li>
</ul>
</section></section>
<section>
<section id="lecture-1-continuous-variables-the-uniform-and-the-normal" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 1 — Continuous Variables, the Uniform, and the Normal</h1>

</section>
<section id="the-brief-lecture-1" class="slide level2 center">
<h2>The Brief — Lecture 1</h2>
<p><br></p>
<blockquote>
<p>“Before we can ask <em>‘how likely is eRPM above $3.50?’</em>, we need a <strong>model</strong> for a continuous quantity. Today: what a continuous distribution <em>is</em>, and the two we use most — the <strong>uniform</strong> and the <strong>Normal</strong>.”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p>The payoff question <span class="math inline">\(P(\text{eRPM} &gt; \$3.50)\)</span> waits for Lecture 2. First we build the machinery: <strong>probability as area</strong>, the <strong>Normal</strong> shape, and the <strong>z-score</strong> that handles any Normal.</p></li>
<li class="fragment"><p>Anchor examples today: <strong>Slater’s Buffet</strong> (uniform) and <strong>Pep Zone</strong> inventory (Normal). Then we fit the Normal to Vungle eRPM.</p></li>
</ul>
</section></section>
<section>
<section id="continuous-random-variables" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Continuous Random Variables</h1>

</section>
<section id="discrete-vs.-continuous-probability-becomes-area" class="slide level2 center">
<h2>Discrete vs.&nbsp;Continuous: Probability Becomes Area</h2>
<p><br></p>
<ul>
<li class="fragment"><p>A <strong>continuous</strong> random variable can assume <strong>any</strong> value in an interval on the real line (eRPM could be $3.4590, $3.45901, …).</p></li>
<li class="fragment"><p>Unlike a die roll, you <strong>cannot</strong> ask for the probability of one <em>exact</em> value:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
P(X = x) = 0 \quad \text{for any single point } x
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Instead we ask about an <strong>interval</strong>: <span class="math inline">\(P(x_1 \le X \le x_2)\)</span>. The eRPM is never <em>exactly</em> $3.50 — but it can be <em>between</em> $3.40 and $3.60.</p></li>
<li class="fragment"><p>For a continuous variable, probability is the <strong>area under a curve</strong> called the <strong>probability density function</strong> <span class="math inline">\(f(x)\)</span>.</p></li>
</ul>
</section>
<section id="the-probability-density-function-pdf" class="slide level2 center">
<h2>The Probability Density Function (PDF)</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Think of <span class="math inline">\(f(x)\)</span> as a <strong>smoothed histogram</strong>: the relative-frequency bars, refined until they form a continuous curve.</p></li>
<li class="fragment"><p>Two defining properties:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
f(x) \ge 0 \quad \text{for all } x \qquad\qquad \int_{-\infty}^{\infty} f(x)\, dx = 1 \;\; (\text{total area} = 1)
\]</span></p>
</div>
<ul>
<li class="fragment"><p><strong>Key subtlety:</strong> <span class="math inline">\(f(x)\)</span> is a <em>density</em>, <strong>not</strong> a probability — it can exceed 1. Only <strong>areas</strong> are probabilities.</p></li>
<li class="fragment"><p>The probability <span class="math inline">\(X\)</span> lands between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> is the area under <span class="math inline">\(f(x)\)</span> across that interval:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
P(x_1 \le X \le x_2) = \text{area under } f(x) \text{ from } x_1 \text{ to } x_2
\]</span></p>
</div>
</section></section>
<section>
<section id="the-uniform-distribution" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Uniform Distribution</h1>

</section>
<section id="the-simplest-continuous-model" class="slide level2 center">
<h2>The Simplest Continuous Model</h2>
<p><br></p>
<ul>
<li class="fragment">A variable is <strong>uniformly distributed</strong> when the probability is <strong>proportional to the length</strong> of the interval — every equal-width slice is equally likely.</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
f(x) = \begin{cases} \dfrac{1}{b - a} &amp; a \le x \le b \\[4pt] 0 &amp; \text{otherwise} \end{cases}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>The density is a <strong>flat rectangle</strong> of height <span class="math inline">\(1/(b-a)\)</span> — and the rectangle’s total area is exactly 1.</p></li>
<li class="fragment"><p>Mean and variance:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(X) = \frac{a + b}{2} \qquad\qquad \operatorname{Var}(X) = \frac{(b - a)^2}{12}
\]</span></p>
</div>
</section>
<section id="anchor-example-slaters-buffet" class="slide level2 center">
<h2>Anchor Example: Slater’s Buffet</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Slater’s charges customers by the <strong>weight of salad</strong> they take. Sampling shows the amount is <strong>uniform between 5 and 15 ounces</strong>: <span class="math inline">\(X \sim \text{Uniform}(5, 15)\)</span>, so <span class="math inline">\(f(x) = 1/10\)</span>.</p></li>
<li class="fragment"><p><strong>Expected value and variance:</strong></p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(X) = \frac{5 + 15}{2} = 10 \text{ oz} \qquad \operatorname{Var}(X) = \frac{(15 - 5)^2}{12} = 8.33
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>What is <span class="math inline">\(P(12 \le X \le 15)\)</span> — a heaping plate?</strong> Area = base <span class="math inline">\(\times\)</span> height:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
P(12 \le X \le 15) = (15 - 12) \times \frac{1}{10} = 0.30
\]</span></p>
</div>
</section>
<section id="slaters-buffet-probability-is-the-shaded-area" class="slide level2 center">
<h2>Slater’s Buffet — Probability Is the Shaded Area</h2>

<img data-src="figs/uniform_slater.png" class="quarto-figure quarto-figure-center r-stretch" style="width:72.0%"><ul>
<li>30% of customers take between 12 and 15 ounces — directly the <strong>area</strong> of the shaded rectangle, no calculus needed.</li>
<li>The same idea, <strong>probability = area</strong>, now carries over to the bell-shaped Normal, where the area is harder to compute by hand (so we lean on z-scores and Excel).</li>
</ul>
</section></section>
<section>
<section id="the-normal-probability-distribution" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Normal Probability Distribution</h1>

</section>
<section id="why-the-normal-matters" class="slide level2 center">
<h2>Why the Normal Matters</h2>
<p><br></p>
<ul>
<li class="fragment"><p>The <strong>Normal</strong> is the most important distribution for a continuous variable — it describes heights, test scores, measurement errors, rainfall, <strong>and</strong> daily revenue metrics like eRPM.</p></li>
<li class="fragment"><p>It is the backbone of statistical inference (the next several topics), and it <strong>approximates</strong> the Binomial and Poisson at large <span class="math inline">\(n\)</span>.</p></li>
<li class="fragment"><p>Its density:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
f(x) = \frac{1}{\sigma\sqrt{2\pi}}\; e^{-\frac{1}{2}\left(\frac{x - \mu}{\sigma}\right)^2}, \qquad \pi \approx 3.14159, \;\; e \approx 2.71828
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>Don’t tattoo this on your arm.</strong> You will never plug numbers into it by hand — z-scores and Excel do the work. It is here so you see <em>where the bell comes from</em>: two parameters, <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>.</li>
</ul>
</section>
<section id="what-the-two-parameters-do" class="slide level2 center">
<h2>What the Two Parameters Do</h2>

<img data-src="figs/normal_shapes.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><ul>
<li>The <strong>mean <span class="math inline">\(\mu\)</span></strong> sets the <strong>location</strong> (the peak); it can be any value — negative, zero, or positive.</li>
<li>The <strong>standard deviation <span class="math inline">\(\sigma\)</span></strong> sets the <strong>spread</strong>: larger <span class="math inline">\(\sigma\)</span> → wider, flatter curve.</li>
<li>Every Normal is <strong>symmetric</strong> and <strong>bell-shaped</strong>, with <strong>mean = median = mode</strong>, and an (in principle) infinite range.</li>
</ul>
</section>
<section id="the-empirical-rule" class="slide level2 center">
<h2>The Empirical Rule</h2>

<img data-src="figs/empirical_rule.png" class="quarto-figure quarto-figure-center r-stretch" style="width:68.0%"><ul>
<li><strong>68.26%</strong> of values fall within <strong><span class="math inline">\(\pm 1\sigma\)</span></strong> of the mean.</li>
<li><strong>95.44%</strong> fall within <strong><span class="math inline">\(\pm 2\sigma\)</span></strong>; <strong>99.72%</strong> fall within <strong><span class="math inline">\(\pm 3\sigma\)</span></strong>.</li>
<li>Half the area (0.5) sits on each side of <span class="math inline">\(\mu\)</span>. For Vungle: ~95% of B-days should fall in <span class="math inline">\(3.46 \pm 2(0.34) = (\$2.77, \$4.15)\)</span>.</li>
</ul>
</section></section>
<section>
<section id="the-standard-normal-z-scores" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Standard Normal &amp; z-Scores</h1>

</section>
<section id="one-curve-to-rule-them-all-z-n0-1" class="slide level2 center">
<h2>One Curve to Rule Them All: Z ~ N(0, 1)</h2>
<p><br></p>
<ul>
<li class="fragment"><p>There are infinitely many Normal curves (one per <span class="math inline">\(\mu, \sigma\)</span>). We standardize them all to a <strong>single reference</strong>: the <strong>standard Normal</strong>, <span class="math inline">\(Z \sim N(0, 1)\)</span> — mean 0, standard deviation 1.</p></li>
<li class="fragment"><p><strong>Standardization</strong> converts any <span class="math inline">\(x\)</span> to a <span class="math inline">\(z\)</span>:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
z = \frac{x - \mu}{\sigma}
\]</span></p>
</div>
<ul>
<li class="fragment"><p><span class="math inline">\(z\)</span> is <strong>the number of standard deviations</strong> <span class="math inline">\(x\)</span> lies from the mean. <span class="math inline">\(z = +1.5\)</span> means “1.5 SDs above average”; <span class="math inline">\(z = -2\)</span> means “2 SDs below.”</p></li>
<li class="fragment"><p>Once standardized, <strong>one</strong> table (or one Excel function) gives the area for <em>any</em> Normal problem.</p></li>
</ul>
</section>
<section id="standardizing-in-pictures" class="slide level2 center">
<h2>Standardizing in Pictures</h2>

<img data-src="figs/standardization.png" class="quarto-figure quarto-figure-center r-stretch" style="width:78.0%"><ul>
<li>The <strong>shape and the shaded area are identical</strong> before and after standardizing — only the axis labels change.</li>
<li>Compute <span class="math inline">\(z\)</span>, then read the area off <span class="math inline">\(N(0,1)\)</span>. This is the move behind every Normal probability you will ever calculate.</li>
</ul>
</section>
<section id="anchor-example-pep-zone-stockout" class="slide level2 center">
<h2>Anchor Example: Pep Zone Stockout</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Pep Zone reorders motor oil when stock hits <strong>20 gallons</strong>. Demand during the replenishment lead time is <strong>Normal with mean 15, sd 6</strong>: <span class="math inline">\(X \sim N(15, 6)\)</span>.</p></li>
<li class="fragment"><p><strong>What is the probability of a stockout</strong> — that demand <em>exceeds</em> 20 before the new stock arrives?</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
z = \frac{20 - 15}{6} = 0.83 \quad\Rightarrow\quad P(X &gt; 20) = P(Z &gt; 0.83) = 0.2023
\]</span></p>
</div>
<ul>
<li class="fragment">About a <strong>20% chance</strong> of running out on each cycle — the store manager wants that lower.</li>
</ul>
</section>
<section id="pep-zone-the-stockout-area" class="slide level2 center">
<h2>Pep Zone — the Stockout Area</h2>

<img data-src="figs/pepzone_stockout.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><ul>
<li>The stockout probability is the <strong>right-tail area</strong> beyond 20 gallons: <strong>0.2023</strong>.</li>
<li><em>Inverse question (Lecture 2 tool):</em> what reorder point cuts stockout risk to 5%? Answer: <span class="math inline">\(x = 15 + 1.645(6) \approx 25\)</span> gallons. Raising the trigger from 20 to 25 drops stockout risk from ~20% to ~5%.</li>
</ul>
</section></section>
<section>
<section id="modeling-vungle-erpm-as-normal" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Modeling Vungle eRPM as Normal</h1>

</section>
<section id="fitting-the-normal-to-daily-erpm-algorithm-b" class="slide level2 center">
<h2>Fitting the Normal to Daily eRPM (Algorithm B)</h2>
<div style="font-size: 86%;">
<ul>
<li class="fragment">Treat each day’s eRPM for algorithm B as a draw from a Normal. From the 30 June days (<code>data/vungle_daily.csv</code>, <code>algorithm == "B"</code>):</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(n\)</span> (days)</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\bar{x}\)</span> (mean eRPM)</td>
<td style="text-align: right;"><strong>$3.459</strong></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(s\)</span> (standard deviation)</td>
<td style="text-align: right;"><strong>$0.344</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p>So our working model is <span class="math inline">\(\text{eRPM}_B \sim N(\mu = 3.459, \; \sigma = 0.344)\)</span>.</p></li>
<li class="fragment"><p><strong>A first z-score.</strong> A $3.50 day standardizes to:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
z = \frac{3.50 - 3.459}{0.344} = 0.12
\]</span></p>
</div>
<ul>
<li class="fragment">A $3.50 day is barely above average — only <strong>0.12 SD</strong> up. That hints (we’ll confirm next time) that beating $3.50 is close to a coin flip.</li>
</ul>
</div>
</section>
<section id="normal-probabilities-in-excel-two-functions" class="slide level2 center">
<h2>Normal Probabilities in Excel — Two Functions</h2>
<p><br></p>
<ul>
<li class="fragment"><p>The ToolPak is not needed for Normal probabilities — two worksheet functions do everything:</p>
<ul>
<li class="fragment"><code>=NORM.DIST(x, mean, sd, TRUE)</code> → the <strong>cumulative</strong> probability <span class="math inline">\(P(X \le x)\)</span>.</li>
<li class="fragment"><code>=NORM.INV(p, mean, sd)</code> → the <strong>inverse</strong>: the <span class="math inline">\(x\)</span> with <span class="math inline">\(P(X \le x) = p\)</span> (a percentile).</li>
</ul></li>
<li class="fragment"><p>The standardized cousins act on <span class="math inline">\(z\)</span> directly:</p>
<ul>
<li class="fragment"><code>=NORM.S.DIST(z, TRUE)</code> → <span class="math inline">\(P(Z \le z)\)</span>; <code>=NORM.S.INV(p)</code> → the <span class="math inline">\(z\)</span> for probability <span class="math inline">\(p\)</span>.</li>
</ul></li>
<li class="fragment"><p><strong>Workhorses:</strong> <code>NORM.DIST</code> and <code>NORM.INV</code> (real units). The <code>.S.</code> versions are for when you have already standardized to a <span class="math inline">\(z\)</span>.</p></li>
<li class="fragment"><p>We put them to work in Lecture 2 — for now, your team just <strong>fits the model and reads its shape</strong>.</p></li>
</ul>
</section>
<section id="team-sprint-1-fit-the-normal-to-erpm" class="slide level2 center">
<h2>⏱️ Team Sprint 1 — Fit the Normal to eRPM</h2>
<div class="sprint">
<p><strong>Decide:</strong> is the Normal a sensible model for B’s daily eRPM — and what does a “typical” day look like?</p>
<p><strong>Data:</strong> <code>data/vungle_daily.csv</code> (filter <code>algorithm = "B"</code>) · <strong>Time:</strong> ~8 min</p>
<ol type="1">
<li>In Excel, compute <span class="math inline">\(\bar{x}\)</span> = <code>AVERAGE</code> and <span class="math inline">\(s\)</span> = <code>STDEV.S</code> of the 30 B-day <code>erpm</code> values (target: ~3.459, ~0.344).</li>
<li>Apply the <strong>empirical rule</strong>: give the interval that should hold ~95% of days (<span class="math inline">\(\bar{x} \pm 2s\)</span>).</li>
<li>Standardize a $3.50 day: compute <span class="math inline">\(z = (3.50 - \bar{x})/s\)</span>. Is $3.50 a good day, an average day, or a bad day?</li>
</ol>
<p><strong>Submit before you leave (graded, one slide per group):</strong> your call on whether Normal is a sensible model for B’s eRPM + the key numbers (<span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(s\)</span>, the 95% empirical interval, the <span class="math inline">\(z\)</span> for $3.50) + the <strong>two things you would challenge</strong> in the fit.</p>
</div>
</section>
<section id="debrief-lecture-1-takeaway" class="slide level2 center">
<h2>Debrief — Lecture 1 Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> B’s daily eRPM is well described by a Normal centered at <strong>$3.46</strong> with spread <strong>$0.34</strong> — and standardizing (<span class="math inline">\(z = (x-\mu)/\sigma\)</span>) turns any eRPM question into a single standard-Normal area.</p></li>
<li class="fragment"><p><strong>One number:</strong> <span class="math inline">\(z = 0.12\)</span> for a $3.50 day — barely above average, so “beating $3.50” is roughly a coin flip (we’ll nail the exact probability next time).</p></li>
<li class="fragment"><p><strong>One caveat:</strong> the empirical rule and z-scores are only as good as the <strong>Normal assumption</strong>. We have <em>assumed</em> the bell; Lecture 2 we <strong>check</strong> it with a QQ plot before betting a decision on it.</p></li>
</ul>
</section>
<section id="carry-forward-lecture-1" class="slide level2 center">
<h2>Carry-forward — Lecture 1</h2>
<ul>
<li><p><strong>Homework (individual):</strong> today’s tools (the Normal model, z-scores, and percentiles) are drilled on <strong>HW2</strong> — individual problem sets in the previous-edition format, posted on Brightspace. Run them yourself so you can check an analyst who uses them.</p></li>
<li><p><strong>Next time:</strong> we cash in the model — exact tail probabilities (<span class="math inline">\(P(\text{eRPM} &gt; \$3.50)\)</span>), the <strong>90th-percentile day</strong>, a formal <strong>normality check</strong>, and the Normal approximation of the Binomial.</p></li>
</ul>
</section></section>
<section>
<section id="lecture-2-normal-applications-the-normal-approximation" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 2 — Normal Applications &amp; the Normal Approximation</h1>

</section>
<section id="the-brief-lecture-2" class="slide level2 center">
<h2>The Brief — Lecture 2</h2>
<p><br></p>
<blockquote>
<p>“Cash in the model. Tomorrow’s eRPM is <span class="math inline">\(\sim N(3.459, 0.344)\)</span>. <strong>What’s <span class="math inline">\(P(\text{eRPM} &gt; \$3.50)\)</span>? What eRPM defines a top-10% day?</strong> And before we trust any of it, <strong>is the Normal assumption fair?</strong>”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p>Lecture 1 built the model; today we <strong>use</strong> it: a tail probability, a percentile, an assumption check, and the bridge from counts (Binomial) to the Normal at scale.</p></li>
<li class="fragment"><p>Tools: <code>NORM.DIST</code> (tail areas), <code>NORM.INV</code> (percentiles), the <strong>QQ plot</strong> (assumption), and the <strong>Normal approximation of the Binomial</strong> (planning installs).</p></li>
</ul>
</section></section>
<section>
<section id="normal-probabilities-tails" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Normal Probabilities: Tails</h1>

</section>
<section id="perpm-3.50-a-right-tail-area" class="slide level2 center">
<h2>P(eRPM &gt; $3.50) — a Right-Tail Area</h2>
<p><br></p>
<ul>
<li class="fragment">The managerial question: how often does B clear the <strong>$3.50</strong> bar? Standardize, then take the tail area.</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
z = \frac{3.50 - 3.459}{0.344} = 0.12 \qquad P(\text{eRPM} &gt; 3.50) = P(Z &gt; 0.12) = 1 - 0.547 = 0.453
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>In Excel</strong> (no standardizing needed):</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\texttt{=1 - NORM.DIST(3.50, 3.459, 0.344, TRUE)} \;=\; 0.4526
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>Read it for the manager:</strong> on roughly <strong>45 of every 100 days</strong>, B’s eRPM tops $3.50. A $3.50 day is <em>not</em> exceptional — it is just shy of a coin flip.</li>
</ul>
</section>
<section id="the-tail-area-visualized" class="slide level2 center">
<h2>The Tail Area, Visualized</h2>

<img data-src="figs/vungle_pgt350.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><ul>
<li>The shaded right tail beyond $3.50 is <strong>0.4526</strong> of the total area.</li>
<li>Same machine for a <strong>bad day</strong>: <span class="math inline">\(P(\text{eRPM} &lt; \$3.00) =\)</span> <code>NORM.DIST(3.00, 3.459, 0.344, TRUE)</code> <span class="math inline">\(= 0.091\)</span> — about a <strong>1-in-11</strong> chance B dips below $3.00.</li>
</ul>
</section>
<section id="excel-norm.dist-on-the-vungle-model" class="slide level2 center">
<h2>Excel: NORM.DIST on the Vungle Model</h2>

<img data-src="figs/excel_normdist_vungle.png" class="quarto-figure quarto-figure-center r-stretch" style="width:82.0%"><ul>
<li><code>NORM.DIST(..., TRUE)</code> returns the area to the <strong>left</strong>; subtract from 1 for a right tail.</li>
<li>The standard-Normal route (standardize to <span class="math inline">\(z = 0.12\)</span>, then <code>1 - NORM.S.DIST(0.12, TRUE)</code>) gives the <strong>same</strong> 0.4526. Two roads, one answer.</li>
</ul>
</section></section>
<section>
<section id="normal-percentiles-norm.inv" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Normal Percentiles: NORM.INV</h1>

</section>
<section id="the-90th-percentile-day" class="slide level2 center">
<h2>The 90th-Percentile Day</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Flip the question. Instead of “what area is above $3.50?”, ask “<strong>what eRPM marks the top 10% of days?</strong>” — the 90th percentile.</p></li>
<li class="fragment"><p><strong>Inverse Normal:</strong> find <span class="math inline">\(x\)</span> with <span class="math inline">\(P(X \le x) = 0.90\)</span>. By hand, <span class="math inline">\(z_{0.90} = 1.282\)</span>, then back-convert:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
x = \mu + z\,\sigma = 3.459 + 1.282 \times 0.344 = \$3.90
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>In Excel</strong> (direct, no z needed):</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\texttt{=NORM.INV(0.90, 3.459, 0.344)} \;=\; \$3.90
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>For the manager:</strong> a <strong>$3.90</strong> day is a genuine top-10% performance — a useful internal benchmark for “a great day.”</li>
</ul>
</section>
<section id="the-percentile-visualized" class="slide level2 center">
<h2>The Percentile, Visualized</h2>

<img data-src="figs/vungle_pct90.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><ul>
<li>90% of the area sits <strong>at or below $3.90</strong>; the top 10% of days lie beyond it.</li>
<li><code>NORM.DIST</code> and <code>NORM.INV</code> are <strong>inverses</strong>: <code>NORM.DIST(3.90, …)</code> <span class="math inline">\(\approx 0.90\)</span>, and <code>NORM.INV(0.90, …)</code> <span class="math inline">\(\approx 3.90\)</span>. One asks “what area?”, the other “what value?”.</li>
</ul>
</section>
<section id="excel-norm.inv-percentiles-tails" class="slide level2 center">
<h2>Excel: NORM.INV — Percentiles &amp; Tails</h2>

<img data-src="figs/excel_norminv_vungle.png" class="quarto-figure quarto-figure-center r-stretch" style="width:82.0%"><ul>
<li>The median equals the mean (<span class="math inline">\(\$3.46\)</span>) for a symmetric Normal — <code>NORM.INV(0.50, …)</code> confirms it.</li>
<li>Percentiles turn an abstract distribution into <strong>decision thresholds</strong>: a 75th-percentile day ($3.69) is “good,” a 90th ($3.90) is “great.” Same model, business-ready language.</li>
</ul>
</section></section>
<section>
<section id="is-the-normal-assumption-fair" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Is the Normal Assumption Fair?</h1>

</section>
<section id="check-before-you-trust-the-qq-plot" class="slide level2 center">
<h2>Check Before You Trust: the QQ Plot</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Every probability and percentile we just computed <strong>assumes</strong> eRPM is Normal. If the assumption fails, the numbers are fiction. So we <strong>check</strong>.</p></li>
<li class="fragment"><p>A <strong>Normal-probability plot</strong> (QQ plot) sorts the data and plots each value against the value a perfect Normal would predict at that rank.</p></li>
<li class="fragment"><p><strong>The read:</strong></p>
<ul>
<li class="fragment">Points hug a <strong>straight line</strong> → Normal is a reasonable model.</li>
<li class="fragment">Systematic curves, S-shapes, or fat tails → Normal is suspect.</li>
</ul></li>
<li class="fragment"><p>A formal companion is the <strong>Shapiro-Wilk test</strong> (<span class="math inline">\(H_0\)</span>: the data are Normal). A <em>large</em> p-value means “<strong>no evidence against</strong> Normal” — exactly what we want here.</p></li>
</ul>
</section>
<section id="the-qq-plot-for-erpm-algorithm-b" class="slide level2 center">
<h2>The QQ Plot for eRPM (Algorithm B)</h2>

<img data-src="figs/vungle_qq.png" class="quarto-figure quarto-figure-center r-stretch" style="width:68.0%"><ul>
<li>The 30 B-day points <strong>track the line</strong> closely — no fat tails, no S-curve.</li>
<li>Shapiro-Wilk: <strong>W = 0.961, p = 0.33</strong> → we <strong>do not reject</strong> Normality. The model is fair to use.</li>
<li><em>Honest caveat:</em> <span class="math inline">\(n = 30\)</span> is modest; the QQ plot can’t <em>prove</em> Normal, only fail to flag a problem. For business decisions, “Normal is a reasonable working model” is the right standard.</li>
</ul>
</section>
<section id="team-sprint-2-probabilities-percentiles-a-normality-check" class="slide level2 center">
<h2>⏱️ Team Sprint 2 — Probabilities, Percentiles &amp; a Normality Check</h2>
<div class="sprint">
<p><strong>Decide:</strong> how often does B top $3.50, what’s a top-10% day, and is the Normal model trustworthy?</p>
<p><strong>Data:</strong> <code>data/vungle_daily.csv</code> (filter <code>algorithm = "B"</code>) · <strong>Time:</strong> ~12 min</p>
<ol type="1">
<li><strong>Tail probability:</strong> <code>=1 - NORM.DIST(3.50, mean, sd, TRUE)</code>. State <span class="math inline">\(P(\text{eRPM} &gt; \$3.50)\)</span> in plain English.</li>
<li><strong>Percentile:</strong> <code>=NORM.INV(0.90, mean, sd)</code>. Report the <strong>90th-percentile day</strong> as a “great day” benchmark.</li>
<li><strong>Check the assumption:</strong> sort the 30 values; eyeball them against the Normal QQ plot (provided). Do they hug the line?</li>
</ol>
<p><strong>Submit before you leave (graded, one slide per group):</strong> your verdict on whether to trust the Normal model + the key numbers (<span class="math inline">\(P(\text{eRPM} &gt; \$3.50)\)</span>, the 90th-percentile eRPM, the QQ-plot read) + the <strong>two things you would challenge</strong> in the analysis.</p>
</div>
</section></section>
<section>
<section id="the-normal-approximation-of-the-binomial" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Normal Approximation of the Binomial</h1>

</section>
<section id="why-approximate-counts-at-huge-scale" class="slide level2 center">
<h2>Why Approximate? Counts at Huge Scale</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Recall installs are <strong>counts</strong>: each impression either installs (success) or not — a Binomial with huge <span class="math inline">\(n\)</span>. On a typical B-traffic day, <span class="math inline">\(n \approx 527{,}000\)</span> impressions, <span class="math inline">\(p \approx 0.0035\)</span>.</p></li>
<li class="fragment"><p>The exact Binomial is <strong>unwieldy</strong> at that scale — but a smooth <strong>Normal</strong> matches it beautifully.</p></li>
<li class="fragment"><p><strong>Conditions to approximate</strong> <span class="math inline">\(\text{Binomial}(n, p)\)</span> with a Normal:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
n &gt; 20, \qquad np \ge 5, \qquad n(1 - p) \ge 5
\]</span></p>
</div>
<ul>
<li class="fragment">Then set:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\mu = np \qquad\qquad \sigma = \sqrt{np(1 - p)}
\]</span></p>
</div>
</section>
<section id="the-picture-binomial-bars-normal-curve" class="slide level2 center">
<h2>The Picture: Binomial Bars, Normal Curve</h2>

<img data-src="figs/normal_approx_binomial.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><ul>
<li>Textbook anchor: <span class="math inline">\(\text{Binomial}(100, 0.4)\)</span> → <span class="math inline">\(\mu = 40\)</span>, <span class="math inline">\(\sigma = 4.90\)</span>. The Normal curve traces the tops of the bars.</li>
<li>The bigger <span class="math inline">\(n\)</span> gets, the better the fit — which is why a 527,000-impression install count is essentially Normal.</li>
</ul>
</section>
<section id="continuity-correction-bars-have-width" class="slide level2 center">
<h2>Continuity Correction: Bars Have Width</h2>

<img data-src="figs/continuity_correction.png" class="quarto-figure quarto-figure-center r-stretch" style="width:62.0%"><ul>
<li>A discrete count of exactly 10 occupies the <strong>continuous interval [9.5, 10.5]</strong> — so <span class="math inline">\(P(X = 10) \approx P(9.5 \le X \le 10.5)\)</span>.</li>
<li>Add/subtract <strong>0.5</strong> at the edges. For <span class="math inline">\(P(30 \le X \le 50)\)</span> use <span class="math inline">\(P(29.5 \le X \le 50.5)\)</span> — this <span class="math inline">\(\pm 0.5\)</span> “continuity correction” sharpens the approximation (most relevant when <span class="math inline">\(n\)</span> is moderate).</li>
</ul>
</section>
<section id="vungle-installs-as-a-planning-number" class="slide level2 center">
<h2>Vungle Installs as a Planning Number</h2>
<div class="r-fit-text">
<p><strong>Setup.</strong> On a typical B-traffic day: <span class="math inline">\(n = 527{,}513\)</span> impressions, install rate <span class="math inline">\(p = 0.00354\)</span>. Model daily installs <span class="math inline">\(\approx \text{Binomial}(n, p)\)</span>.</p>
<p><strong>Conditions.</strong> <span class="math inline">\(np = 1{,}867 \ge 5\)</span> and <span class="math inline">\(n(1-p) = 525{,}646 \ge 5\)</span> → Normal approximation is safe.</p>
<p><span class="math display">\[
\mu = np = 1{,}867 \text{ installs} \qquad \sigma = \sqrt{np(1-p)} = 43.1 \text{ installs}
\]</span></p>
<p><strong>Planning question.</strong> What is the chance the day delivers <strong>more than 2,000 installs</strong> (e.g., a capacity / fulfillment trigger)?</p>
<p><span class="math display">\[
z = \frac{2000.5 - 1867}{43.1} = 3.10 \qquad P(\text{installs} &gt; 2000) = \texttt{1 - NORM.DIST(2000.5, 1867, 43.1, TRUE)} = 0.0010
\]</span></p>
<p><strong>Manager’s translation.</strong> <em>A 2,000-install B-day is rare — about a 1-in-1,000 event under current traffic. Capacity planned to 2,000 installs is comfortable; the constraint is impressions, not the install spike.</em></p>
</div>
</section>
<section id="excel-normal-approximation-formula-sheet" class="slide level2 center">
<h2>Excel: Normal Approximation Formula Sheet</h2>

<img data-src="figs/excel_normapprox_vungle.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><ul>
<li>Five cells: compute <span class="math inline">\(np\)</span> and <span class="math inline">\(n(1-p)\)</span> (the condition check), then <span class="math inline">\(\mu = np\)</span>, <span class="math inline">\(\sigma = \sqrt{np(1-p)}\)</span>, and the tail with <code>NORM.DIST</code>.</li>
<li>This is the bridge from Topic 5’s <strong>counting</strong> distributions to today’s <strong>continuous</strong> Normal — at scale, the Binomial <em>becomes</em> a Normal.</li>
</ul>
</section></section>
<section>
<section id="debrief-from-distribution-to-decision" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Debrief — From Distribution to Decision</h1>

</section>
<section id="three-answers-one-model" class="slide level2 center">
<h2>Three Answers, One Model</h2>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Tool</th>
<th>Vungle answer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>How often does eRPM top $3.50?</td>
<td><span class="math inline">\(z\)</span> + <code>NORM.DIST</code></td>
<td><span class="math inline">\(P = 0.453\)</span> — almost a coin flip</td>
</tr>
<tr class="even">
<td>What’s a top-10% day?</td>
<td><code>NORM.INV(0.90)</code></td>
<td><strong>$3.90</strong> — the “great day” benchmark</td>
</tr>
<tr class="odd">
<td>Is the Normal model fair?</td>
<td>QQ plot + Shapiro</td>
<td>Yes — <span class="math inline">\(W = 0.96\)</span>, <span class="math inline">\(p = 0.33\)</span></td>
</tr>
<tr class="even">
<td>Plan installs at scale</td>
<td>Normal approx. Binomial</td>
<td><span class="math inline">\(P(&gt;2000) = 0.001\)</span> — rare</td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment">Every row came from <strong>one</strong> fitted distribution, <span class="math inline">\(N(3.459, 0.344)\)</span> — the model turns 30 observed days into statements about days we have not yet seen.</li>
</ul>
</section>
<section id="managers-takeaway" class="slide level2 center">
<h2>Manager’s Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> Model B’s daily eRPM as <span class="math inline">\(N(\$3.46, \$0.34)\)</span> and the whole business vocabulary follows — “beats $3.50” happens <strong>45%</strong> of days, a “great day” is <strong>$3.90</strong>, and a sub-$3.00 day is a <strong>1-in-11</strong> disappointment.</p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <span class="math inline">\(z = (x - \mu)/\sigma\)</span> — the single move that turns <em>any</em> Normal question into a standard-Normal area.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> the model is only as good as its assumption. <strong>Check it</strong> (QQ plot, Shapiro) before you bet a decision on a Normal probability — and remember that at huge <span class="math inline">\(n\)</span>, even the Binomial <em>becomes</em> Normal.</p></li>
<li class="fragment"><p><strong>Practice with the real data:</strong></p>
<ul>
<li class="fragment"><code>data/vungle_daily.csv</code> (filter B) + <code>NORM.DIST</code> / <code>NORM.INV</code> → reproduce <span class="math inline">\(P(&gt;3.50) = 0.453\)</span> and the $3.90 percentile.</li>
<li class="fragment">Worked solutions: <code>data/vungle_normal_analysis.xlsx</code>.</li>
</ul></li>
</ul>
</section>
<section id="summary" class="slide level2 center">
<h2>Summary</h2>
<p>Some key takeaways from this session:</p>
<ul>
<li>For a <strong>continuous</strong> variable, <span class="math inline">\(P(X = x) = 0\)</span>; probability is the <strong>area</strong> under the density <span class="math inline">\(f(x)\)</span>.</li>
<li>The <strong>uniform</strong> is the simplest model (probability ∝ interval length); the <strong>Normal</strong>, set by <span class="math inline">\(\mu\)</span> (location) and <span class="math inline">\(\sigma\)</span> (spread), is the workhorse, with the <strong>empirical rule</strong> (68/95/99.7).</li>
<li><strong>Standardize</strong> with <span class="math inline">\(z = (x - \mu)/\sigma\)</span>, then read areas off the single standard Normal <span class="math inline">\(N(0,1)\)</span>.</li>
<li>In Excel: <code>NORM.DIST</code> for <strong>probabilities</strong> (tail areas), <code>NORM.INV</code> for <strong>percentiles</strong> — they are inverses.</li>
<li><strong>Check the assumption</strong> with a QQ plot / Shapiro-Wilk before trusting a Normal probability.</li>
<li>At large <span class="math inline">\(n\)</span> with <span class="math inline">\(np \ge 5\)</span> and <span class="math inline">\(n(1-p) \ge 5\)</span>, the <strong>Binomial is well approximated by a Normal</strong> (<span class="math inline">\(\mu = np\)</span>, <span class="math inline">\(\sigma = \sqrt{np(1-p)}\)</span>, with a <span class="math inline">\(\pm 0.5\)</span> continuity correction).</li>
</ul>
</section>
<section id="carry-forward" class="slide level2 center">
<h2>Carry-forward</h2>
<ul>
<li><p><strong>Homework (individual):</strong> today’s tools (the Normal model, z-scores, and percentiles) are drilled on <strong>HW2</strong> — individual problem sets in the previous-edition format, posted on Brightspace. Run them yourself so you can check an analyst who uses them.</p></li>
<li><p><strong>Next time:</strong> we stop treating these 30 days as the whole story and recognize them as a <strong>sample</strong> — <strong>Sampling &amp; Estimation</strong>: how to estimate the <em>true</em> eRPM, with a margin of error.</p></li>
</ul>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Thank you!</h1>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Business Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>