<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Professor Davi Moreira ">
  <title>QM 6700: Business Analytics –  QM 6700: Business Analytics </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-8fc47a4fdcba9931a3aa90ef56f89358.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="font-size: 100%;"> QM 6700: Business Analytics </span></h1>
  <p class="subtitle"><span style="font-size: 150%;"> Decision Analysis </span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor<br>Davi Moreira<br> 
</div>
</div>
</div>

</section>
<section id="overview" class="slide level2 center">
<h2>Overview</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Case Spotlight: the Vungle rollout decision</li>
<li>Structuring a decision: alternatives, states of nature, payoffs</li>
<li>Payoff tables and decision trees</li>
<li>Expected value (EV): deciding under risk</li>
</ul>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Expected value of perfect information (EVPI)</li>
<li>Sample information, Bayes revision, and EVSI</li>
<li>Sensitivity: does the call hold if the prior shifts?</li>
<li>From inference to action: making the rollout recommendation</li>
</ul>
</div></div>
</section>
<section>
<section id="case-spotlight-the-vungle-rollout-decision" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Case Spotlight: The Vungle Rollout Decision</h1>

</section>
<section id="rewind-before-the-ab-test" class="slide level2 center">
<h2>Rewind: Before the A/B Test</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Earlier in our work with <a href="https://techcrunch.com/2019/07/15/blackstone-is-acquiring-mobile-ad-company-vungle/">Vungle</a> (the mobile ad-tech startup that earns revenue when viewers <strong>install</strong> an advertised app) we tested whether their new ad-serving algorithm <strong>B</strong> beat the incumbent <strong>A</strong>.</p></li>
<li class="fragment"><p>The verdict: B’s daily eRPM (revenue per 1,000 impressions) ran about <strong>$0.11 higher</strong> than A’s, and a paired test said that lift was <strong>real</strong> (<span class="math inline">\(t = 3.33\)</span>), worth roughly <strong>$26.5K/month</strong> at June’s traffic.</p></li>
<li class="fragment"><p>But statistics told us <em>what is true and how sure we are</em>. They did <strong>not</strong> tell management <strong>what to do</strong>.</p></li>
<li class="fragment"><p>Today you put on the <strong>manager’s hat</strong>: given that uncertainty, what is the right <strong>action</strong>?</p></li>
</ul>
</section>
<section id="the-brief-todays-manager-question" class="slide level2 center">
<h2>The Brief: Today’s Manager Question</h2>
<p><br></p>
<ul>
<li class="fragment"><strong>The big call</strong> running through Vungle is one decision: <em>roll out algorithm B to all traffic, or stay with A?</em> <strong>Today’s piece of it:</strong> roll out, keep A, or test more, which has the best <strong>expected value</strong>?</li>
</ul>
<div class="fragment">
<blockquote>
<p>“Algorithm B looks better, but we’re not certain. Do we <strong>roll out B</strong> to all traffic now, <strong>keep A</strong> and play it safe, or <strong>run a bigger test</strong> before committing? Quantify it and make the call.”</p>
</blockquote>
</div>
<p><br></p>
<ul>
<li class="fragment"><p>Rolling out B and being <strong>wrong</strong> degrades <em>all</em> of Vungle’s revenue, not a 1/16 slice. Keeping A forgoes a real upside. Testing more costs time and money.</p></li>
<li class="fragment"><p><strong>How today’s studio runs:</strong> I demo each tool on a textbook anchor; you reproduce the Vungle rollout tree and interrogate it; we debrief the recommendation together.</p></li>
<li class="fragment"><p>By the end of class, <strong>you</strong> make the call, with the decision math to back it up.</p></li>
</ul>
</section>
<section id="how-every-class-runs" class="slide level2 center">
<h2>How Every Class Runs</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/lecture_dynamic.png" class="quarto-figure quarto-figure-center" style="width:90.0%"></p>
</figure>
</div>
<p>The class <strong>ends on the Team Sprint</strong>, your group’s graded submission: a decision plus your read of the analysis, one PDF before you leave.</p>
</section>
<section id="how-todays-tools-answer-it" class="slide level2 center">
<h2>How Today’s Tools Answer It</h2>
<p><br></p>
<p>Every tool today maps onto the Vungle rollout:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>The manager’s question</th>
<th>The tool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>What are my options, and what could happen?</td>
<td><strong>Payoff table</strong> (alternatives × states)</td>
</tr>
<tr class="even">
<td>What’s the sequence of choice and chance?</td>
<td><strong>Decision tree</strong></td>
</tr>
<tr class="odd">
<td>Which option is best <em>on average</em>?</td>
<td><strong>Expected value (EV)</strong></td>
</tr>
<tr class="even">
<td>What is it worth to remove the uncertainty?</td>
<td><strong>EVPI</strong> / <strong>EVSI</strong></td>
</tr>
<tr class="odd">
<td>Would the call change if I’m a bit off?</td>
<td><strong>Sensitivity analysis</strong></td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment">One decision, five tools, and they all build on the <strong>probability</strong> logic from earlier in the course.</li>
</ul>
</section></section>
<section>
<section id="structuring-the-decision" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Structuring the Decision</h1>

</section>
<section id="step-zero-problem-formulation" class="slide level2 center">
<h2>Step Zero: Problem Formulation</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Before any number, <strong>decision analysis</strong> forces three clean lists:</p>
<ul>
<li class="fragment"><strong>Decision alternatives:</strong> the strategies <em>you</em> control.</li>
<li class="fragment"><strong>States of nature:</strong> the uncertain future events <em>you do not</em> control. They must be <strong>mutually exclusive</strong> and <strong>collectively exhaustive</strong>.</li>
<li class="fragment"><strong>Payoffs:</strong> the consequence (profit, cost, time…) of each <em>alternative × state</em> combination.</li>
</ul></li>
<li class="fragment"><p>The discipline is in the structuring: most bad business decisions come from a <strong>missing alternative</strong> or an <strong>unstated state of nature</strong>, not from arithmetic.</p></li>
<li class="fragment"><p>The whole apparatus (payoff tables, trees, EV) is just bookkeeping on top of these three lists.</p></li>
</ul>
</section>
<section id="the-vungle-decision-in-three-lists" class="slide level2 center">
<h2>The Vungle Decision, in Three Lists</h2>
<p><br></p>
<p><strong>Decision alternatives</strong> (what Vungle controls):</p>
<ul>
<li><span class="math inline">\(d_1\)</span>: <strong>Roll out B now</strong> to all traffic</li>
<li><span class="math inline">\(d_2\)</span>: <strong>Keep A</strong> (the safe baseline)</li>
<li><span class="math inline">\(d_3\)</span>: <strong>Run a bigger test</strong> first, then decide</li>
</ul>
<p><strong>States of nature</strong> (the uncertainty management faces):</p>
<ul>
<li><span class="math inline">\(s_1\)</span>: <strong>B is truly better</strong> than A</li>
<li><span class="math inline">\(s_2\)</span>: <strong>B is not better</strong> (no real lift, or worse)</li>
</ul>
<ul>
<li class="fragment"><p>These two states are mutually exclusive and exhaustive: exactly one is true, we just don’t know which.</p></li>
<li class="fragment"><p><strong>Payoffs</strong> come next, and we’ll build them from the data we already have.</p></li>
</ul>
</section>
<section id="where-do-the-payoffs-come-from-the-data" class="slide level2 center">
<h2>Where Do the Payoffs Come From? The Data</h2>
<p><br></p>
<ul>
<li class="fragment"><p>We don’t invent payoffs; we <strong>anchor them in the eRPM evidence</strong>:</p>
<ul>
<li class="fragment">The mean lift was <strong>+$0.112</strong> per 1,000 impressions; A served <strong>≈ 236.5M</strong> impressions/month.</li>
<li class="fragment">At that scale: <span class="math inline">\(\dfrac{236{,}459{,}402}{1{,}000} \times \$0.112 \approx \$26.5\text{K/month} \approx \$318\text{K/year}\)</span>.</li>
</ul></li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>If we <strong>roll out B</strong> and…</th>
<th style="text-align: right;">Annual payoff ($K)</th>
<th>Reasoning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(s_1\)</span>: B <em>is</em> truly better</td>
<td style="text-align: right;"><strong>+318</strong></td>
<td>full lift across all traffic</td>
</tr>
<tr class="even">
<td><span class="math inline">\(s_2\)</span>: B is <em>not</em> better</td>
<td style="text-align: right;"><strong>−160</strong></td>
<td>degraded revenue vs.&nbsp;a working algorithm</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p><strong>Keep A</strong> is the baseline: <strong>$0</strong> in both states (no gain, no loss).</p></li>
<li class="fragment"><p><em>(The −160 is management’s estimate of the downside of replacing a working algorithm with a worse one, about half the upside. We’ll stress-test it later.)</em></p></li>
</ul>
</section>
<section id="the-payoff-table" class="slide level2 center">
<h2>The Payoff Table</h2>
<p><br></p>
<p>The payoff table is the whole problem on one page; rows are <strong>alternatives</strong>, columns are <strong>states of nature</strong>:</p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Decision alternative</th>
<th style="text-align: right;"><span class="math inline">\(s_1\)</span>: B truly better</th>
<th style="text-align: right;"><span class="math inline">\(s_2\)</span>: B not better</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(d_1\)</span>: Roll out B now</td>
<td style="text-align: right;"><strong>+$318K</strong></td>
<td style="text-align: right;"><strong>−$160K</strong></td>
</tr>
<tr class="even">
<td><span class="math inline">\(d_2\)</span>: Keep A</td>
<td style="text-align: right;">$0</td>
<td style="text-align: right;">$0</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
<ul>
<li class="fragment"><p>Read a cell as: “<em>if I choose this row and that state occurs, this is what I get</em>.”</p></li>
<li class="fragment"><p>A payoff table with no probabilities supports only crude rules (best-case, worst-case). To do better, we need the <strong>odds</strong> on the states; that is the next ingredient.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">The +318 comes straight from the eRPM data, but the −160 downside is just management’s estimate. Doesn’t that make the whole table arbitrary?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> the downside is a judgment, not data, and that is fine as long as you say so and test it. We pin +318 to the measured $0.112 lift at 236.5M impressions, and we flag −160 as an estimate (about half the upside). The discipline is putting the number on the table so it can be <strong>stress-tested</strong>; later the sensitivity step shows exactly how wrong −160 would have to be to change the call.</p>
</div>
</div>
</section>
<section id="decision-trees-sequencing-choice-and-chance" class="slide level2 center">
<h2>Decision Trees: Sequencing Choice and Chance</h2>

<img data-src="figs/decision_tree_anatomy.png" class="quarto-figure quarto-figure-center r-stretch" style="width:78.0%"><ul>
<li><strong>Square node = a decision</strong> (you choose the branch). <strong>Round node = a chance event</strong> (nature chooses, with probabilities).</li>
<li>Branches from a square = alternatives; branches from a circle = states of nature. <strong>Payoffs sit at the tips.</strong></li>
</ul>
</section></section>
<section>
<section id="decision-making-with-probabilities" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Decision Making with Probabilities</h1>

</section>
<section id="putting-odds-on-the-states-of-nature" class="slide level2 center">
<h2>Putting Odds on the States of Nature</h2>
<p><br></p>
<ul>
<li class="fragment">To choose, we need <span class="math inline">\(P(s_1)\)</span> and <span class="math inline">\(P(s_2)\)</span>. Because exactly one state occurs, they must satisfy</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
P(s_j) \geq 0 \quad\text{for all } j, \qquad \sum_{j=1}^{N} P(s_j) = 1
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Vungle’s data-science team, having seen the encouraging A/B signal, assigns a <strong>prior</strong>:</p>
<ul>
<li class="fragment"><span class="math inline">\(P(s_1) = 0.60\)</span> (B truly better) and <span class="math inline">\(P(s_2) = 0.40\)</span> (not better).</li>
</ul></li>
<li class="fragment"><p>These can come from the <strong>classical</strong>, <strong>relative-frequency</strong>, or <strong>subjective</strong> method. Here they are an informed subjective judgment, and we will <strong>test how much they matter</strong> at the end.</p></li>
</ul>
</section>
<section id="the-expected-value-approach" class="slide level2 center">
<h2>The Expected Value Approach</h2>
<p><br></p>
<ul>
<li class="fragment">The <strong>expected value</strong> of a decision alternative is its probability-weighted average payoff:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
EV(d_i) = \sum_{j=1}^{N} P(s_j)\, V_{ij}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>where <span class="math inline">\(V_{ij}\)</span> is the payoff for alternative <span class="math inline">\(d_i\)</span> under state <span class="math inline">\(s_j\)</span>, and <span class="math inline">\(N\)</span> is the number of states.</p></li>
<li class="fragment"><p>The <strong>decision rule:</strong> choose the alternative with the <strong>best EV</strong> (highest for profit, lowest for cost).</p></li>
<li class="fragment"><p>In Excel, one formula does it: <code>=SUMPRODUCT(probabilities, payoff_row)</code>.</p></li>
</ul>
</section>
<section id="do-it-in-excel-expected-value" class="slide level2 center">
<h2>Do It in Excel: Expected Value</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Put the <strong>priors</strong> in one row (0.60, 0.40) and each alternative’s <strong>payoff row</strong> beneath (<span class="math inline">\(d_1\)</span>: 318, −160; <span class="math inline">\(d_2\)</span>: 0, 0)</li>
<li class="fragment">In an <strong>EV</strong> cell for <span class="math inline">\(d_1\)</span>: <code>=SUMPRODUCT($B$3:$C$3, B4:C4)</code> (lock the priors with <code>$</code>)</li>
<li class="fragment">Fill the formula <strong>down</strong> to get EV for every alternative</li>
<li class="fragment">Read the <strong>best EV</strong> (roll out B = $126.8K vs.&nbsp;keep A = $0); that row is the call</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_payoff_ev.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="anchor-example-burger-prince" class="slide level2 center">
<h2>Anchor Example: Burger Prince</h2>
<div class="r-fit-text">
<p><strong>Burger Prince</strong> is choosing a restaurant layout. Demand could be <strong>80, 100, or 120</strong> customers/hour, with probabilities <strong>0.4, 0.2, 0.4</strong>. Profit ($):</p>
<table class="caption-top">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;"><span class="math inline">\(s_1{=}80\)</span> (0.4)</th>
<th style="text-align: right;"><span class="math inline">\(s_2{=}100\)</span> (0.2)</th>
<th style="text-align: right;"><span class="math inline">\(s_3{=}120\)</span> (0.4)</th>
<th style="text-align: right;"><strong>EV</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;">10,000</td>
<td style="text-align: right;">15,000</td>
<td style="text-align: right;">14,000</td>
<td style="text-align: right;"><strong>$12,600</strong></td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;">8,000</td>
<td style="text-align: right;">18,000</td>
<td style="text-align: right;">12,000</td>
<td style="text-align: right;">$11,600</td>
</tr>
<tr class="odd">
<td><strong>C</strong></td>
<td style="text-align: right;">6,000</td>
<td style="text-align: right;">16,000</td>
<td style="text-align: right;">21,000</td>
<td style="text-align: right;"><strong>$14,000</strong> ✅</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
EV(\text{C}) = 0.4(6{,}000) + 0.2(16{,}000) + 0.4(21{,}000) = \$14{,}000
\]</span></p>
<p><strong>Decision:</strong> Model C has the highest EV → choose <strong>Model C</strong>. (We’ll reuse this example for EVPI and Bayes.)</p>
</div>
</section>
<section id="the-vungle-decision-tree" class="slide level2 center">
<h2>The Vungle Decision Tree</h2>

<img data-src="figs/vungle_decision_tree.png" class="quarto-figure quarto-figure-center r-stretch" style="width:82.0%"><ul>
<li>The square is Vungle’s choice; the circle is nature deciding whether B is truly better. To pick a branch, we <strong>fold the tree back</strong>: replace each chance node by its EV.</li>
</ul>
</section>
<section id="folding-back-ev-of-each-vungle-alternative" class="slide level2 center">
<h2>Folding Back: EV of Each Vungle Alternative</h2>
<p><br></p>
<p>Using priors <span class="math inline">\(P(s_1)=0.60\)</span>, <span class="math inline">\(P(s_2)=0.40\)</span>:</p>
<div class="fragment">
<p><span class="math display">\[
EV(\text{Roll out B}) = 0.60(318) + 0.40(-160) = 190.8 - 64.0 = \mathbf{\$126.8K}
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
EV(\text{Keep A}) = 0.60(0) + 0.40(0) = \mathbf{\$0}
\]</span></p>
</div>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Decision rule:</strong> $126.8K &gt; $0 → <strong>roll out B</strong>.</p></li>
<li class="fragment"><p>The expected payoff is positive <em>because</em> the upside (+318) is large and fairly likely (0.60), even though the downside (−160) is real.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-1" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">Why do we work the tree from the tips backward to the root, instead of forward from Vungle’s choice?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> you cannot score the “roll out B” branch until you know what the chance node beyond it is worth, and that needs the payoffs at the tips. So you start at the right (the +318 / −160 tips), collapse each chance circle into its EV, and only then can the square at the left compare branches. Forward, you would be choosing before you knew what each choice leads to.</p>
</div>
</div>
</section>
<section id="visualizing-the-expected-values" class="slide level2 center">
<h2>Visualizing the Expected Values</h2>

<img data-src="figs/vungle_ev_bars.png" class="quarto-figure quarto-figure-center r-stretch" style="width:68.0%"><ul>
<li>EV ranks the alternatives, but it <strong>hides the risk</strong>: “roll out B” averages +$126.8K while still risking a <strong>−$160K</strong> year. EV is the right tool when this decision repeats; a one-shot, bet-the-company call would also weigh that downside.</li>
</ul>
</section>
<section id="a-quick-check-on-the-logic" class="slide level2 center">
<h2>A Quick Check on the Logic</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>EV is a long-run average, not a guaranteed outcome.</strong> If Vungle faced this exact decision many times, “roll out B” would net +$126.8K <em>per decision on average</em>.</p></li>
<li class="fragment"><p>The actual result will be <strong>either</strong> +$318K <strong>or</strong> −$160K, never $126.8K. The expected value is a <strong>ranking device</strong>, not a forecast of what happens this once.</p></li>
<li class="fragment"><p>This is exactly why a manager also asks: <em>what would it be worth to know the true state before deciding?</em> That question has a precise answer: <strong>EVPI</strong>.</p></li>
</ul>
</section></section>
<section>
<section id="the-value-of-information" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Value of Information</h1>

</section>
<section id="expected-value-of-perfect-information-evpi" class="slide level2 center">
<h2>Expected Value of Perfect Information (EVPI)</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Imagine a perfect oracle who tells you the true state <strong>before</strong> you decide. How much is that worth?</p></li>
<li class="fragment"><p><strong>EVwPI</strong> (expected value <em>with</em> perfect information): for each state, take the <strong>best</strong> payoff you’d choose if you knew that state, then weight by the priors.</p></li>
<li class="fragment"><p><strong>EVPI</strong> is the <em>gain</em> over deciding blind:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\text{EVPI} = \lvert\, \text{EVwPI} - \text{EVwoPI} \,\rvert
\]</span></p>
</div>
<ul>
<li class="fragment"><p>where <strong>EVwoPI</strong> is the best EV <strong>without</strong> information, what we just computed ($126.8K).</p></li>
<li class="fragment"><p>EVPI is an <strong>upper bound</strong> on the value of <em>any</em> study, survey, or test: no information can beat perfect information.</p></li>
</ul>
</section>
<section id="evpi-the-three-steps-vungle" class="slide level2 center">
<h2>EVPI: the Three Steps (Vungle)</h2>
<div class="r-fit-text">
<p><strong>Step 1, best payoff in each state</strong> (look down each column of the payoff table):</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>State</th>
<th>Best choice if you knew</th>
<th style="text-align: right;">Best payoff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(s_1\)</span>: B truly better (0.60)</td>
<td>Roll out B</td>
<td style="text-align: right;">+$318K</td>
</tr>
<tr class="even">
<td><span class="math inline">\(s_2\)</span>: B not better (0.40)</td>
<td>Keep A</td>
<td style="text-align: right;">$0</td>
</tr>
</tbody>
</table>
<p><strong>Step 2, expected value of those best returns:</strong></p>
<p><span class="math display">\[
\text{EVwPI} = 0.60(318) + 0.40(0) = \$190.8\text{K}
\]</span></p>
<p><strong>Step 3, subtract the best EV without information:</strong></p>
<p><span class="math display">\[
\text{EVPI} = 190.8 - 126.8 = \mathbf{\$64K}
\]</span></p>
</div>
</section>
<section id="what-evpi-tells-the-manager" class="slide level2 center">
<h2>What EVPI Tells the Manager</h2>

<img data-src="figs/vungle_evpi.png" class="quarto-figure quarto-figure-center r-stretch" style="width:60.0%"><ul>
<li><strong>$64K</strong> is the <em>most</em> Vungle should ever pay to remove all doubt about B before deciding. Any real test (always imperfect) is worth <strong>less</strong> than this ceiling.</li>
</ul>
</section>
<section id="a-question-that-often-comes-up-2" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">A perfect oracle doesn’t exist. Why compute the value of information Vungle can never actually buy?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> because it gives you a hard ceiling before you shop. Any real study (an A/B test, a survey) is imperfect, so it is worth strictly less than the $64K EVPI. The instant a vendor quotes more than $64K for any study, you decline without doing further math. EVPI is the budget cap that no real information can ever justify exceeding.</p>
</div>
</div>
</section>
<section id="do-it-in-excel-evpi" class="slide level2 center">
<h2>Do It in Excel: EVPI</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Below the payoff table, add a <strong>Best per state</strong> cell under each column: <code>=MAX(B4:B5)</code>, <code>=MAX(C4:C5)</code></li>
<li class="fragment"><strong>EVwPI</strong> in one cell: <code>=SUMPRODUCT($B$3:$C$3, best-per-state)</code> (the priors times the best returns)</li>
<li class="fragment"><strong>EVPI</strong> in the next cell: <code>=EVwPI - EVwoPI</code> (subtract the best blind EV, $126.8K)</li>
<li class="fragment">Read <strong>EVPI = $64K</strong>; it is always <strong>≥ 0</strong> (you can ignore information, so it can’t hurt)</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_evpi.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section></section>
<section>
<section id="sample-information-bayes" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Sample Information &amp; Bayes</h1>

</section>
<section id="the-third-alternative-run-a-bigger-test" class="slide level2 center">
<h2>The Third Alternative: Run a Bigger Test</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Vungle’s real third option, <span class="math inline">\(d_3\)</span>, is to <strong>buy information</strong>: run a larger, longer A/B test before committing.</p></li>
<li class="fragment"><p>A test is <strong>imperfect</strong> (sample) information: it returns a <strong>signal</strong>, not the truth.</p>
<ul>
<li class="fragment"><strong>Favorable (F):</strong> the bigger test shows a significant lift.</li>
<li class="fragment"><strong>Unfavorable (U):</strong> the test shows no significant lift.</li>
</ul></li>
<li class="fragment"><p>The signal is <strong>reliable but not perfect</strong>. Suppose the test’s track record gives the conditional probabilities:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
P(F \mid s_1) = 0.80, \qquad P(F \mid s_2) = 0.25
\]</span></p>
</div>
<ul>
<li class="fragment">“When B really is better, the test flags it 80% of the time; when B is not better, it gives a false ‘favorable’ 25% of the time.”</li>
</ul>
</section>
<section id="prior-conditional-posterior" class="slide level2 center">
<h2>Prior, Conditional, Posterior</h2>
<p><br></p>
<ul>
<li class="fragment">We have <strong>priors</strong> <span class="math inline">\(P(s_j)\)</span> and <strong>conditionals</strong> <span class="math inline">\(P(\text{signal} \mid s_j)\)</span>. We want the <strong>posterior</strong>, the revised odds <em>after</em> seeing the signal:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
P(s_j \mid \text{signal}) = \frac{P(s_j)\,P(\text{signal}\mid s_j)}{\sum_k P(s_k)\,P(\text{signal}\mid s_k)}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>This is <strong>Bayes’ theorem</strong>, the same updating logic from earlier in the course, now feeding a decision tree.</p></li>
<li class="fragment"><p>A simple <strong>tabular</strong> layout does the arithmetic: <strong>prior → joint → marginal → posterior</strong>. The posteriors become the <strong>branch probabilities</strong> on the tree after the test.</p></li>
</ul>
</section>
<section id="do-it-in-excel-bayes-revision-favorable-report" class="slide level2 center">
<h2>Do It in Excel: Bayes Revision (Favorable Report)</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">List the <strong>priors</strong> column (0.60, 0.40) and the <strong>conditionals</strong> <span class="math inline">\(P(F \mid s_j)\)</span> (0.80, 0.25)</li>
<li class="fragment"><strong>Joint</strong> column: <code>=prior*conditional</code> → 0.48, 0.10</li>
<li class="fragment"><strong>Marginal</strong> <span class="math inline">\(P(F)\)</span>: <code>=SUM(joint)</code> = 0.48 + 0.10 = 0.58</li>
<li class="fragment"><strong>Posterior</strong> column: <code>=joint/marginal</code>; read the odds B is better rise <strong>0.60 → 0.828</strong></li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_bayes_favorable.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="do-it-in-excel-bayes-revision-unfavorable-report" class="slide level2 center">
<h2>Do It in Excel: Bayes Revision (Unfavorable Report)</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Repeat the table with the <strong>other</strong> conditionals <span class="math inline">\(P(U \mid s_j)\)</span> (0.20, 0.75)</li>
<li class="fragment"><strong>Joint</strong>: <code>=prior*conditional</code> → 0.12, 0.30</li>
<li class="fragment"><strong>Marginal</strong> <span class="math inline">\(P(U)\)</span>: <code>=SUM(joint)</code> = 0.42 (check: 0.58 + 0.42 = 1)</li>
<li class="fragment"><strong>Posterior</strong> = <code>=joint/marginal</code>; the odds B is better <strong>drop 0.60 → 0.286</strong> (same data, opposite signal)</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_bayes_unfavorable.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="the-signal-moves-the-decision" class="slide level2 center">
<h2>The Signal Moves the Decision</h2>

<img data-src="figs/vungle_bayes_posterior.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><ul>
<li>After <strong>favorable</strong>: <span class="math inline">\(EV(\text{roll}) = 0.828(318) + 0.172(-160) = \$235.6K &gt; 0\)</span> → <strong>roll out B</strong>.</li>
<li>After <strong>unfavorable</strong>: <span class="math inline">\(EV(\text{roll}) = 0.286(318) + 0.714(-160) = -\$23.4K &lt; 0\)</span> → <strong>keep A</strong>.</li>
</ul>
</section>
<section id="a-question-that-often-comes-up-3" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">A favorable report only lifts the odds from 0.60 to 0.828, not to certainty. Why doesn’t a positive test just prove B is better?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> because the test is imperfect: it cries “favorable” 25% of the time even when B is <em>not</em> better (<span class="math inline">\(P(F \mid s_2) = 0.25\)</span>). So some favorable reports are false alarms, and the posterior holds back from 1.0 to absorb that. The stronger the signal (a lower false-alarm rate), the closer to certainty it would push you; a perfect test would take you to 1.0, which is exactly the oracle EVPI priced.</p>
</div>
</div>
</section>
<section id="expected-value-of-sample-information-evsi" class="slide level2 center">
<h2>Expected Value of Sample Information (EVSI)</h2>
<p><br></p>
<ul>
<li class="fragment">The test is worth the <em>extra</em> expected profit it buys, <strong>before</strong> its cost:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\text{EVSI} = \lvert\, \text{EVwSI} - \text{EVwoSI} \,\rvert
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>EVwSI</strong> weights each signal’s best decision by how often that signal occurs:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\text{EVwSI} = P(F)\,(235.6) + P(U)\,(0) = 0.58(235.6) + 0.42(0) = \$136.6\text{K}
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>EVwoSI</strong> is the best EV with no test = <strong>$126.8K</strong>. So</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\text{EVSI} = 136.6 - 126.8 = \mathbf{\$9.84K}
\]</span></p>
</div>
</section>
<section id="is-the-test-worth-buying" class="slide level2 center">
<h2>Is the Test Worth Buying?</h2>

<img data-src="figs/vungle_evsi.png" class="quarto-figure quarto-figure-center r-stretch" style="width:58.0%"><ul>
<li><strong>Efficiency</strong> <span class="math inline">\(= \text{EVSI}/\text{EVPI} = 9.84/64 \approx 15\%\)</span>: this imperfect test captures only 15% of perfect information’s value.</li>
<li>The test costs <strong>≈ $20K</strong> to run, but is worth only <strong>$9.84K</strong> → <strong>net −$10K</strong>. <strong>Do not run the bigger test.</strong> (Compare: the textbook’s Burger Prince survey also failed this test, EVSI &lt; its price.)</li>
</ul>
</section>
<section id="a-question-that-often-comes-up-4" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">We already ran an A/B test, and that was clearly worth it. So why is running a <em>bigger</em> test now not worth it?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> EVSI is the value of information <em>from where you stand now</em>. Before the first test, Vungle knew almost nothing, so a test bought a lot. After it, the 0.60 prior already points toward rolling out, so a second test would mostly confirm what you would do anyway: it only changes the call in the unfavorable case, which is unlikely. Less left to learn means a smaller EVSI ($9.84K), and that is now below the $20K price.</p>
</div>
</div>
</section>
<section id="do-it-in-excel-evsi" class="slide level2 center">
<h2>Do It in Excel: EVSI</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">From each Bayes table, compute the <strong>best EV after that signal</strong> with the posteriors: favorable $235.6K, unfavorable $0</li>
<li class="fragment"><strong>EVwSI</strong>: <code>=SUMPRODUCT(P(signal), best-EV)</code> = <code>0.58*235.6 + 0.42*0</code> = $136.6K</li>
<li class="fragment"><strong>EVSI</strong>: <code>=EVwSI - EVwoSI</code> = <code>136.6 - 126.8</code> = <strong>$9.84K</strong></li>
<li class="fragment">Compare to the <strong>test cost</strong> ($20K): EVSI &lt; cost, so <strong>skip the study</strong> and decide now</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_evsi.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section></section>
<section>
<section id="how-robust-is-the-call" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>How Robust Is the Call?</h1>

</section>
<section id="sensitivity-analysis" class="slide level2 center">
<h2>Sensitivity Analysis</h2>

<img data-src="figs/vungle_sensitivity.png" class="quarto-figure quarto-figure-center r-stretch" style="width:68.0%"><ul>
<li>“Roll out B” wins as long as <span class="math inline">\(P(s_1)\)</span> exceeds the <strong>indifference prior</strong> <span class="math inline">\(p^{*} \approx 0.33\)</span>. Our prior (0.60) clears it comfortably, so the call is <strong>stable</strong>.</li>
<li>Below one-third, keep A. The call only flips if we’re <em>very</em> pessimistic about B.</li>
</ul>
</section>
<section id="finding-the-tipping-point" class="slide level2 center">
<h2>Finding the Tipping Point</h2>
<p><br></p>
<ul>
<li class="fragment">The decision flips where the two EV lines cross: set <span class="math inline">\(EV(\text{roll}) = EV(\text{keep})\)</span> and solve for the prior <span class="math inline">\(p = P(s_1)\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
p(318) + (1-p)(-160) = 0 \;\Longrightarrow\; p^{*} = \frac{160}{318 + 160} \approx 0.335
\]</span></p>
</div>
<ul>
<li class="fragment"><p>A <strong>stable</strong> decision is one that holds under small changes in the inputs. Here, B would have to be <strong>more likely wrong than right</strong> before we’d keep A.</p></li>
<li class="fragment"><p><strong>This is the real payoff of structuring the decision:</strong> we now know not just <em>what</em> to do, but <em>how sure we’d have to be to change our minds</em>. In Excel: a <strong>What-If Data Table</strong> varying <span class="math inline">\(p\)</span> traces the whole line.</p></li>
</ul>
</section></section>
<section>
<section id="debrief-the-rollout-recommendation" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Debrief: The Rollout Recommendation</h1>

</section>
<section id="the-decision-on-one-page" class="slide level2 center">
<h2>The Decision on One Page</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Question</th>
<th>Tool</th>
<th style="text-align: right;">Answer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Best option on average?</td>
<td>EV</td>
<td style="text-align: right;"><strong>Roll out B</strong> ($126.8K vs.&nbsp;$0)</td>
</tr>
<tr class="even">
<td>Worth knowing the truth for sure?</td>
<td>EVPI</td>
<td style="text-align: right;">$64K ceiling</td>
</tr>
<tr class="odd">
<td>Worth running a bigger test?</td>
<td>EVSI</td>
<td style="text-align: right;">$9.84K &lt; $20K cost → <strong>no</strong></td>
</tr>
<tr class="even">
<td>Stable to our prior?</td>
<td>Sensitivity</td>
<td style="text-align: right;">flips only below <span class="math inline">\(p^{*} = 0.33\)</span></td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment"><strong>Recommendation:</strong> <strong>roll out B now.</strong> Expected value is clearly positive (+$126.8K/yr), the decision holds unless we think B is more likely wrong than right, and a further test isn’t worth its price. <strong>Caveat:</strong> there is a real <strong>−$160K</strong> downside if B disappoints, so monitor eRPM closely post-rollout and be ready to revert.</li>
</ul>
</section>
<section id="how-inference-and-decision-analysis-fit-together" class="slide level2 center">
<h2>How Inference and Decision Analysis Fit Together</h2>
<p><br></p>
<ul>
<li class="fragment"><p>This is the division of labor that runs through the whole course:</p>
<ul>
<li class="fragment"><strong>Inference</strong> (estimation, hypothesis tests): <em>what is true, and how sure are we?</em> → gave us the <strong>$0.11 lift</strong>, the CI, the <span class="math inline">\(p\)</span>-value.</li>
<li class="fragment"><strong>Decision analysis</strong> (today): <em>given that uncertainty, what should we do?</em> → turned those into <strong>alternatives, payoffs, and an EV-maximizing call</strong>.</li>
</ul></li>
<li class="fragment"><p>The test result was an <strong>input</strong> to the decision, not the decision itself. The paired <span class="math inline">\(t\)</span> said “the lift is real”; the EV said “and acting on it is worth +$126.8K.”</p></li>
<li class="fragment"><p>A good analyst can do both, and knows which question they’re answering.</p></li>
</ul>
</section>
<section id="todays-question-todays-answer" class="slide level2 center">
<h2>Today’s Question, Today’s Answer</h2>
<p><br></p>
<p><strong>The question (Topic 4 of the ladder):</strong></p>
<blockquote>
<p><em>Roll out B, keep A, or run a bigger test, which has the best expected value?</em></p>
</blockquote>
<div class="fragment">
<p><br></p>
<p><strong>The answer we reached today:</strong></p>
<blockquote>
<p><strong>Roll out B.</strong> Its expected value (<strong>$126.8K/yr</strong>) beats keeping A (<strong>$0</strong>); the call stays the same unless B is more likely wrong than right (<span class="math inline">\(p^{*} \approx 0.33\)</span>, and our prior is <strong>0.60</strong>); and a bigger test is worth only <strong>$9.84K</strong>, under its <strong>$20K</strong> price, so we skip it.</p>
</blockquote>
</div>
</section>
<section id="the-managers-takeaway" class="slide level2 center">
<h2>The Manager’s Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> Structuring the rollout as a decision (alternatives, states, payoffs) says <strong>roll out B</strong>, because its expected value (<strong>$126.8K/yr</strong>) beats keeping A, and a further test isn’t worth its cost.</p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <strong>EVPI = $64K</strong>, the ceiling on what <em>any</em> information is worth here; the actual test cleared only $9.84K of it.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> EV is a long-run average. “Roll out B” still risks a <strong>−$160K</strong> year; sensitivity shows the call is stable (flips only below <span class="math inline">\(p^{*} = 0.33\)</span>), but the downside is real, so monitor and stay ready to revert.</p></li>
</ul>
</section>
<section id="team-sprint-your-group-case" class="slide level2 center">
<h2>⏱️ Team Sprint: Your Group Case</h2>
<div class="sprint">
<p><strong>Now it’s your group’s turn.</strong> Today’s in-class group case is posted on <strong>Brightspace</strong> (<em>Topic 04 Group Case</em>): a separate business decision you make with today’s tools.</p>
<p><strong>What you’ll use:</strong> payoff tables, decision trees, <strong>EV</strong>, and <strong>EVPI / EVSI</strong>. <strong>Excel:</strong> Analysis ToolPak → <code>=SUMPRODUCT</code> for EV, <code>=MAX</code> per state for EVPI.</p>
<p><strong>Submit one PDF per group before you leave:</strong> your decision plus the numbers behind it.</p>
</div>
</section></section>
<section>
<section id="wrap-up" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Wrap-up</h1>

</section>
<section id="summary" class="slide level2 center">
<h2>Summary</h2>
<ul>
<li><strong>Structure first:</strong> every decision under uncertainty reduces to <strong>alternatives × states of nature → payoffs</strong>; the payoff table and tree are that on a page.</li>
<li><strong>Decide by expected value:</strong> <span class="math inline">\(EV(d_i) = \sum_j P(s_j) V_{ij}\)</span>; pick the best EV, a long-run average that hides the downside.</li>
<li><strong>Value information before buying it:</strong> <strong>EVPI</strong> is the ceiling (perfect info); <strong>EVSI</strong> is what a real, imperfect test is worth; buy a study only if its value beats its cost.</li>
<li><strong>Bayes turns a signal into revised odds:</strong> prior → joint → marginal → posterior; the posteriors become the post-test branch probabilities.</li>
<li><strong>Sensitivity tells you how stable the call is:</strong> find the prior <span class="math inline">\(p^{*}\)</span> where the decision flips; ours holds comfortably.</li>
<li><strong>Inference and decision analysis are partners:</strong> one says <em>what’s true and how sure</em>; the other says <em>what to do about it</em>.</li>
<li><strong>Next time:</strong> modeling <strong>uncertain counts</strong> (how many installs tomorrow?) with discrete probability distributions.</li>
</ul>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Thank you!</h1>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Business Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>