<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Professor Davi Moreira ">
  <title>QM 6700: Business Analytics –  QM 6700: Business Analytics </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-113b5beb2a57b2deea58feb1108e76b2.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="font-size: 100%;"> QM 6700: Business Analytics </span></h1>
  <p class="subtitle"><span style="font-size: 150%;"> Simple Linear Regression </span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor<br>Davi Moreira<br> 
</div>
</div>
</div>

</section>
<section id="overview" class="slide level2 center">
<h2>Overview</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>New Case Spotlight: an auto-parts retailer picking store sites</li>
<li>From <em>comparing</em> groups to <em>predicting</em> an outcome</li>
<li>The simple linear regression model</li>
<li>Least squares: the best-fit line</li>
<li>Interpreting the slope and intercept</li>
<li><span class="math inline">\(R^2\)</span>: how much does the line explain?</li>
</ul>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Is the relationship real? The <span class="math inline">\(t\)</span>-test on the slope</li>
<li>Confidence interval for the slope</li>
<li>Residual analysis: checking the assumptions</li>
<li>Predicting sales for a brand-new store</li>
<li>Confidence vs.&nbsp;prediction intervals</li>
<li>From a fitted line to a site recommendation</li>
</ul>
</div></div>
</section>
<section>
<section id="case-spotlight-auto-parts-retail" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Case Spotlight: Auto-Parts Retail</h1>

</section>
<section id="a-new-client-where-should-the-next-store-go" class="slide level2 center">
<h2>A New Client — Where Should the Next Store Go?</h2>
<p><br></p>
<ul>
<li class="fragment"><p>We close the Vungle engagement and open a new one. Our client is a regional <strong>auto-parts retailer</strong> with <strong>45 stores</strong> and capital to open more.</p></li>
<li class="fragment"><p>The real-estate team scores prospective sites on demographics — population, income — and on the store’s <strong>Yelp rating</strong> (a proxy for service quality once a store is open).</p></li>
<li class="fragment"><p>The question on the table: <strong>which sites will sell?</strong> The CFO wants every new lease backed by a sales forecast, not a hunch.</p></li>
<li class="fragment"><p>We have one dataset, <code>data/autoparts.csv</code>: for each of the 45 existing stores, its <strong>2012 annual sales</strong> ($K), trade-area <strong>population</strong> and <strong>income</strong>, an <strong>end-cap</strong> placement flag, and its <strong>Yelp rating</strong>.</p></li>
<li class="fragment"><p>Until now we <em>compared</em> two groups. Now we <em>predict</em> a number — and that is what <strong>regression</strong> does.</p></li>
</ul>
</section>
<section id="the-brief-todays-managerial-question" class="slide level2 center">
<h2>The Brief — Today’s Managerial Question</h2>
<p><br></p>
<blockquote>
<p>“Does a store’s <strong>Yelp rating</strong> predict its <strong>annual sales</strong>? If so, by how much — and how confident are we when we forecast a brand-new store?”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Lecture 1</strong> builds and reads the model: fit <code>sales ~ yelp_rating</code>, interpret the slope (dollars per star), and measure fit with <span class="math inline">\(R^2\)</span>.</p></li>
<li class="fragment"><p><strong>Lecture 2</strong> asks whether the relationship is <em>real</em> (a <span class="math inline">\(t\)</span>-test on the slope), checks the model’s <strong>assumptions</strong>, and turns the line into a <strong>site-selection forecast</strong>.</p></li>
<li class="fragment"><p><strong>How the studio runs:</strong> I demo each step on a textbook anchor (<strong>Armand’s Pizza</strong>) and on the auto-parts data → <strong>your team</strong> fits the model and makes the site call.</p></li>
</ul>
</section>
<section id="from-comparing-to-predicting" class="slide level2 center">
<h2>From Comparing to Predicting</h2>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>What we did (Topics 7–9)</th>
<th>What we do now</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimate / test <strong>one</strong> number (a mean, a proportion)</td>
<td>Model <strong>how one variable moves with another</strong></td>
</tr>
<tr class="even">
<td>“Is B’s eRPM above $3.30?”</td>
<td>“How many $ of sales per Yelp star?”</td>
</tr>
<tr class="odd">
<td>Output: a decision (reject / fail to reject)</td>
<td>Output: an <strong>equation you can forecast with</strong></td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment"><p>Regression develops an <strong>equation</strong> showing how a <strong>dependent variable</strong> <span class="math inline">\(y\)</span> (what we predict — sales) relates to an <strong>independent variable</strong> <span class="math inline">\(x\)</span> (the predictor — Yelp rating).</p></li>
<li class="fragment"><p><strong>Simple</strong> linear regression uses <strong>one</strong> predictor; the relationship is approximated by a <strong>straight line</strong>. (More predictors → multiple regression, next topic.)</p></li>
</ul>
</section></section>
<section>
<section id="lecture-1-the-model-least-squares-and-r2" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 1 — The Model, Least Squares, and <span class="math inline">\(R^2\)</span></h1>

</section>
<section id="the-brief-lecture-1" class="slide level2 center">
<h2>The Brief — Lecture 1</h2>
<p><br></p>
<blockquote>
<p>“Fit a straight line to <code>sales ~ yelp_rating</code>. What does the slope mean in dollars, and how much of the store-to-store sales gap does Yelp rating explain?”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p>By the end of Lecture 1 <strong>your team</strong> will have a fitted equation, a dollars-per-star interpretation, and an <span class="math inline">\(R^2\)</span> — the raw material for a site score.</p></li>
<li class="fragment"><p>The decision it feeds: <strong>rank prospective sites</strong> by predicted sales.</p></li>
</ul>
</section>
<section id="the-simple-linear-regression-model" class="slide level2 center">
<h2>The Simple Linear Regression Model</h2>
<p><br></p>
<ul>
<li class="fragment">The <strong>model</strong> describes how <span class="math inline">\(y\)</span> relates to <span class="math inline">\(x\)</span> and a random <strong>error term</strong> <span class="math inline">\(\varepsilon\)</span> in the whole population of stores:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
y = \beta_0 + \beta_1 x + \varepsilon
\]</span></p>
</div>
<ul>
<li class="fragment"><p><span class="math inline">\(\beta_0\)</span> (intercept) and <span class="math inline">\(\beta_1\)</span> (slope) are unknown <strong>population parameters</strong>; <span class="math inline">\(\varepsilon\)</span> captures everything about sales that Yelp rating does <strong>not</strong> explain.</p></li>
<li class="fragment"><p>We never see <span class="math inline">\(\beta_0, \beta_1\)</span> — we <strong>estimate</strong> them from our 45-store sample. The estimated equation is</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\hat{y} = b_0 + b_1 x
\]</span></p>
</div>
<ul>
<li class="fragment"><span class="math inline">\(\hat{y}\)</span> is the <strong>predicted</strong> mean sales at a given rating; <span class="math inline">\(b_0, b_1\)</span> are the sample estimates of <span class="math inline">\(\beta_0, \beta_1\)</span>.</li>
</ul>
</section>
<section id="what-a-line-can-look-like" class="slide level2 center">
<h2>What a Line Can Look Like</h2>
<p><br></p>
<ul>
<li class="fragment"><p>The sign of <span class="math inline">\(\beta_1\)</span> sets the story:</p>
<ul>
<li class="fragment"><span class="math inline">\(\beta_1 &gt; 0\)</span> — <strong>positive</strong> relationship: higher <span class="math inline">\(x\)</span> goes with higher <span class="math inline">\(y\)</span> (we expect this for Yelp → sales).</li>
<li class="fragment"><span class="math inline">\(\beta_1 &lt; 0\)</span> — <strong>negative</strong> relationship: higher <span class="math inline">\(x\)</span> goes with lower <span class="math inline">\(y\)</span>.</li>
<li class="fragment"><span class="math inline">\(\beta_1 = 0\)</span> — <strong>no</strong> linear relationship: <span class="math inline">\(x\)</span> tells you nothing about <span class="math inline">\(y\)</span>.</li>
</ul></li>
<li class="fragment"><p><strong>Honest caveat — regression is not causation.</strong> A line that fits well says rating and sales <em>move together</em>; it does <strong>not</strong> prove better service <em>causes</em> sales. We will return to this when we test significance.</p></li>
</ul>
</section>
<section id="the-data-just-look-first" class="slide level2 center">
<h2>The Data: Just Look First</h2>

<img data-src="figs/autoparts_scatter.png" class="quarto-figure quarto-figure-center r-stretch" style="width:78.0%"><ul>
<li>45 stores. Higher-rated stores clearly tend to sell more — but the cloud has spread. We need a <strong>line</strong> to summarize the trend and a <strong>number</strong> to summarize how tight it is.</li>
</ul>
</section>
<section id="least-squares-define-best-fit" class="slide level2 center">
<h2>Least Squares: Define “Best Fit”</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Infinitely many lines pass through a cloud of points. Which one is <strong>best</strong>? The one that makes the <strong>residuals</strong> smallest.</p></li>
<li class="fragment"><p>A <strong>residual</strong> is the vertical gap between an actual store and the line:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
e_i = y_i - \hat{y}_i
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>Least squares criterion:</strong> choose <span class="math inline">\(b_0, b_1\)</span> to <strong>minimize the sum of squared residuals</strong>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\min \;\; \text{SSE} = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2
\]</span></p>
</div>
<ul>
<li class="fragment">Squaring penalizes big misses and keeps positives and negatives from cancelling.</li>
</ul>
</section>
<section id="the-least-squares-formulas" class="slide level2 center">
<h2>The Least-Squares Formulas</h2>
<p><br></p>
<div style="font-size: 90%;">
<ul>
<li class="fragment"><strong>Slope</strong> — the workhorse:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
b_1 = \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n} (x_i - \bar{x})^2}
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>Intercept</strong> — forces the line through the point of averages <span class="math inline">\((\bar{x}, \bar{y})\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
b_0 = \bar{y} - b_1 \bar{x}
\]</span></p>
</div>
<ul>
<li class="fragment">In Excel you rarely type these: <code>=SLOPE(y, x)</code>, <code>=INTERCEPT(y, x)</code>, or the full <strong>Regression</strong> tool do the arithmetic.</li>
</ul>
</div>
</section>
<section id="what-the-criterion-is-minimizing" class="slide level2 center">
<h2>What the Criterion Is Minimizing</h2>

<img data-src="figs/autoparts_residual_concept.png" class="quarto-figure quarto-figure-center r-stretch" style="width:72.0%"><ul>
<li>Each grey segment is one residual <span class="math inline">\(e_i\)</span>. Least squares is the unique line that makes the <strong>sum of those squared lengths</strong> as small as possible.</li>
</ul>
</section>
<section id="anchor-example-armands-pizza-parlors" class="slide level2 center">
<h2>Anchor Example: Armand’s Pizza Parlors</h2>
<div class="r-fit-text">
<p>A classic: <strong>Armand’s Pizza</strong> has 10 restaurants near college campuses. Sales clearly depend on how many students live nearby. <span class="math inline">\(x\)</span> = student population in the trade area (1,000s); <span class="math inline">\(y\)</span> = quarterly sales ($1,000s).</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Student population <span class="math inline">\(x\)</span> (000s)</th>
<th style="text-align: right;">Quarterly sales <span class="math inline">\(y\)</span> ($000s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Restaurant 1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">58</td>
</tr>
<tr class="even">
<td>Restaurant 2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">105</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td>Restaurant 10</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">202</td>
</tr>
</tbody>
</table>
<p><strong>Least-squares fit:</strong> <span class="math inline">\(\bar{x} = 14\)</span>, <span class="math inline">\(\bar{y} = 130\)</span>, and the slope/intercept formulas give</p>
<p><span class="math display">\[
b_1 = 5, \qquad b_0 = 60 \qquad\Rightarrow\qquad \hat{y} = 60 + 5x
\]</span></p>
</div>
</section>
<section id="armands-reading-the-line" class="slide level2 center">
<h2>Armand’s — Reading the Line</h2>

<img data-src="figs/armands_fit.png" class="quarto-figure quarto-figure-center r-stretch" style="width:58.0%"><ul>
<li><strong>Slope <span class="math inline">\(b_1 = 5\)</span>:</strong> each additional <strong>1,000 students</strong> in the trade area is associated with <strong>$5,000</strong> more quarterly sales.</li>
<li><strong>Intercept <span class="math inline">\(b_0 = 60\)</span>:</strong> the line’s height at <span class="math inline">\(x = 0\)</span> — outside the data range, so read it as a fitting constant, not “sales with zero students.”</li>
</ul>
</section>
<section id="the-auto-parts-fit" class="slide level2 center">
<h2>The Auto-Parts Fit</h2>

<img data-src="figs/autoparts_fit.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><div class="fragment">
<p><span class="math display">\[
\widehat{\text{sales}} = 332.8 + 757.5 \times (\text{Yelp rating})
\]</span></p>
</div>
</section>
<section id="interpreting-the-auto-parts-slope-and-intercept" class="slide level2 center">
<h2>Interpreting the Auto-Parts Slope and Intercept</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Slope <span class="math inline">\(b_1 = +757.5\)</span>:</strong> each additional <strong>Yelp star</strong> is associated with about <strong>$757.5K</strong> more in annual sales. <em>This is the number the real-estate team can use to score sites.</em></p></li>
<li class="fragment"><p><strong>Intercept <span class="math inline">\(b_0 = +332.8\)</span>:</strong> the line’s height at a rating of zero. No store has a zero rating, so do <strong>not</strong> interpret it as “sales of a zero-star store” — it just anchors the line.</p></li>
<li class="fragment"><p><strong>Manager’s translation:</strong> <em>Moving a store from a 3.0 to a 4.0 Yelp rating is worth roughly three-quarters of a million dollars in predicted annual sales.</em></p></li>
<li class="fragment"><p><strong>Sanity check:</strong> the slope is positive and large — consistent with the upward cloud. Good.</p></li>
</ul>
</section>
<section id="r2-how-much-does-the-line-explain" class="slide level2 center">
<h2><span class="math inline">\(R^2\)</span>: How Much Does the Line Explain?</h2>
<p><br></p>
<ul>
<li class="fragment">Total variation in sales splits into what the line <strong>explains</strong> and what it <strong>leaves</strong> as error:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\underbrace{\text{SST}}_{\sum (y_i - \bar{y})^2} \;=\; \underbrace{\text{SSR}}_{\sum (\hat{y}_i - \bar{y})^2} \;+\; \underbrace{\text{SSE}}_{\sum (y_i - \hat{y}_i)^2}
\]</span></p>
</div>
<ul>
<li class="fragment">The <strong>coefficient of determination</strong> is the explained share:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
R^2 = \frac{\text{SSR}}{\text{SST}} = 1 - \frac{\text{SSE}}{\text{SST}}, \qquad 0 \le R^2 \le 1
\]</span></p>
</div>
<ul>
<li class="fragment"><span class="math inline">\(R^2 = 0\)</span>: the line explains nothing. <span class="math inline">\(R^2 = 1\)</span>: every point sits exactly on the line.</li>
</ul>
</section>
<section id="r2-for-the-auto-parts-model" class="slide level2 center">
<h2><span class="math inline">\(R^2\)</span> for the Auto-Parts Model</h2>
<p><br></p>
<ul>
<li class="fragment">From the auto-parts fit:</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SST (total variation)</td>
<td style="text-align: right;">55,840,034</td>
</tr>
<tr class="even">
<td>SSR (explained by line)</td>
<td style="text-align: right;">46,594,785</td>
</tr>
<tr class="odd">
<td>SSE (left as error)</td>
<td style="text-align: right;">9,245,249</td>
</tr>
<tr class="even">
<td><span class="math inline">\(R^2 = \text{SSR}/\text{SST}\)</span></td>
<td style="text-align: right;"><strong>0.834</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p><strong>Interpretation:</strong> Yelp rating alone explains <strong>83.4%</strong> of the store-to-store variation in annual sales — strong for a single predictor.</p></li>
<li class="fragment"><p>The remaining <strong>16.6%</strong> is everything else (location, merchandising, competition). <em>That gap is exactly what motivates adding more predictors next topic.</em></p></li>
<li class="fragment"><p>In Excel: <code>=RSQ(sales, yelp)</code> or read <strong>R Square</strong> off the Regression output.</p></li>
</ul>
</section>
<section id="r2-and-correlation-are-the-same-story" class="slide level2 center">
<h2><span class="math inline">\(R^2\)</span> and Correlation Are the Same Story</h2>
<p><br></p>
<ul>
<li class="fragment">The sample <strong>correlation</strong> <span class="math inline">\(r\)</span> and <span class="math inline">\(R^2\)</span> are tightly linked in simple regression:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
r = (\text{sign of } b_1)\sqrt{R^2}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Here <span class="math inline">\(b_1 &gt; 0\)</span> and <span class="math inline">\(R^2 = 0.834\)</span>, so <span class="math inline">\(r = +\sqrt{0.834} = +0.913\)</span> — a strong positive correlation, the same fact <span class="math inline">\(R^2\)</span> reports.</p></li>
<li class="fragment"><p><strong>Correlation</strong> measures the <em>tightness and direction</em> of the linear association; <strong><span class="math inline">\(R^2\)</span></strong> measures the <em>share of variation explained</em>. Same coin, two faces.</p></li>
</ul>
</section>
<section id="excel-one-click-gives-you-everything" class="slide level2 center">
<h2>Excel: One Click Gives You Everything</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p><br></p>
<p><strong>Data → Data Analysis → Regression</strong></p>
<ul>
<li>Input Y Range: <code>sales2012_k</code></li>
<li>Input X Range: <code>yelp_rating</code></li>
<li>Check <strong>Labels</strong>, <strong>Residuals</strong>, <strong>Residual Plots</strong></li>
</ul>
<p><br></p>
<p>The top block is <strong>Regression Statistics</strong> — <code>Multiple R</code>, <code>R Square</code>, <code>Standard Error</code>, <code>Observations</code>.</p>
</div><div class="column" style="width:60%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/autoparts_reg_stats.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/autoparts_reg_coef.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="team-sprint-1-fit-the-line-read-the-slope" class="slide level2 center">
<h2>⏱️ Team Sprint 1 — Fit the line, read the slope</h2>
<div class="sprint">
<p><strong>Decide:</strong> does Yelp rating predict store sales — and what is one star worth?</p>
<p><strong>Data:</strong> <code>data/autoparts.csv</code> · <strong>Time:</strong> ~12 min</p>
<ol type="1">
<li>In Excel: <strong>Data → Data Analysis → Regression</strong> (Y = <code>sales2012_k</code>, X = <code>yelp_rating</code>, check <strong>Labels</strong>).</li>
<li>Write the estimated equation <span class="math inline">\(\hat{y} = b_0 + b_1 x\)</span> and interpret the <strong>slope</strong> in plain dollars-per-star.</li>
<li>Read <strong>R Square</strong>: what fraction of the sales gap does Yelp rating explain? State the unexplained share.</li>
</ol>
<p><strong>Hand in (1 slide):</strong> the equation, the dollars-per-star sentence, and your <span class="math inline">\(R^2\)</span> read — would you use Yelp rating to score sites?</p>
</div>
</section>
<section id="debrief-managers-takeaway-lecture-1" class="slide level2 center">
<h2>Debrief — Manager’s Takeaway (Lecture 1)</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> Yelp rating is a strong predictor of store sales — each star is worth about <strong>$757K</strong> in predicted annual sales.</p></li>
<li class="fragment"><p><strong>One number:</strong> <span class="math inline">\(R^2 = 0.834\)</span> — Yelp rating alone explains <strong>83%</strong> of the sales differences across stores.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> “explains” is <strong>association, not cause</strong>, and 17% is still unexplained — one variable is rarely the whole story. We have a <em>fitted</em> line, but we have not yet asked whether it is <strong>statistically real</strong> or whether the model’s <strong>assumptions</strong> hold. That is Lecture 2.</p></li>
</ul>
</section>
<section id="carry-forward-lecture-1" class="slide level2 center">
<h2>Carry-forward (Lecture 1)</h2>
<ul>
<li><p><strong>Your client (homework):</strong> in your team’s case, pick a plausible numeric predictor of your key outcome. Fit the simple regression, write the slope interpretation in business units, and report <span class="math inline">\(R^2\)</span>.</p></li>
<li><p><strong>Next time:</strong> is the slope <strong>real</strong> or could it be noise? We test it, check the assumptions behind the line, and forecast a brand-new store.</p></li>
</ul>
</section></section>
<section>
<section id="lecture-2-inference-assumptions-and-prediction" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 2 — Inference, Assumptions, and Prediction</h1>

</section>
<section id="the-brief-lecture-2" class="slide level2 center">
<h2>The Brief — Lecture 2</h2>
<p><br></p>
<blockquote>
<p>“The fitted slope is +757.5 $K per star. But our 45 stores are a <strong>sample</strong>. Is the Yelp–sales relationship <strong>real</strong>, do the model’s assumptions hold, and what sales should we <strong>forecast</strong> for a specific new site?”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p>Lecture 1 <em>described</em> the sample. Lecture 2 does <strong>inference</strong>: from these 45 stores to the population of all possible stores.</p></li>
<li class="fragment"><p>Three jobs: (1) <strong>test</strong> the slope, (2) <strong>validate</strong> the assumptions with residuals, (3) <strong>predict</strong> a new store with an honest margin of error.</p></li>
</ul>
</section>
<section id="the-assumptions-behind-the-line" class="slide level2 center">
<h2>The Assumptions Behind the Line</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Everything we are about to do (tests, intervals) rests on four assumptions about the error term <span class="math inline">\(\varepsilon\)</span>:</p>
<ol type="1">
<li class="fragment"><strong>Mean zero:</strong> <span class="math inline">\(E(\varepsilon) = 0\)</span> — the line is right on average.</li>
<li class="fragment"><strong>Constant variance:</strong> <span class="math inline">\(\text{Var}(\varepsilon) = \sigma^2\)</span> is the same for all <span class="math inline">\(x\)</span> (<strong>homoscedasticity</strong>).</li>
<li class="fragment"><strong>Independence:</strong> the errors for different stores are independent.</li>
<li class="fragment"><strong>Normality:</strong> <span class="math inline">\(\varepsilon\)</span> is normally distributed.</li>
</ol></li>
<li class="fragment"><p>If these are badly violated, the <span class="math inline">\(p\)</span>-values and intervals can mislead. We will <strong>check</strong> them with residual plots after we test — but they are the foundation, so flag them first.</p></li>
</ul>
</section>
<section id="estimating-sigma-the-standard-error-of-the-estimate" class="slide level2 center">
<h2>Estimating <span class="math inline">\(\sigma\)</span>: the Standard Error of the Estimate</h2>
<p><br></p>
<ul>
<li class="fragment">The tests need an estimate of the error spread <span class="math inline">\(\sigma\)</span>. The <strong>mean square error</strong> estimates <span class="math inline">\(\sigma^2\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
s^2 = \text{MSE} = \frac{\text{SSE}}{n - 2}
\]</span></p>
</div>
<ul>
<li class="fragment">Its square root, <span class="math inline">\(s = \sqrt{\text{MSE}}\)</span>, is the <strong>standard error of the estimate</strong> — the typical vertical miss of the line, in the units of <span class="math inline">\(y\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
s = \sqrt{\frac{\text{SSE}}{n-2}} = \sqrt{\frac{9{,}245{,}249}{43}} \approx \$464\text{K}
\]</span></p>
</div>
<ul>
<li class="fragment">We divide by <span class="math inline">\(n - 2\)</span> because we spent two degrees of freedom estimating <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>. In Excel: <code>=STEYX(sales, yelp)</code> or read <strong>Standard Error</strong> off the output.</li>
</ul>
</section>
<section id="testing-the-slope-is-the-relationship-real" class="slide level2 center">
<h2>Testing the Slope: Is the Relationship Real?</h2>
<p><br></p>
<ul>
<li class="fragment">If <span class="math inline">\(\beta_1 = 0\)</span>, <span class="math inline">\(x\)</span> has <strong>no</strong> linear effect on <span class="math inline">\(y\)</span> — there is no relationship to forecast with. So we test:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
H_0: \beta_1 = 0 \qquad \text{vs.} \qquad H_a: \beta_1 \neq 0 \qquad (\alpha = 0.05)
\]</span></p>
</div>
<ul>
<li class="fragment">The test statistic divides the estimated slope by its standard error, with <span class="math inline">\(df = n - 2\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
t = \frac{b_1 - 0}{s_{b_1}}, \qquad s_{b_1} = \frac{s}{\sqrt{\sum (x_i - \bar{x})^2}}
\]</span></p>
</div>
<ul>
<li class="fragment">Same logic as every test since Topic 8: a statistic, a <span class="math inline">\(t\)</span> distribution, a <span class="math inline">\(p\)</span>-value, a decision.</li>
</ul>
</section>
<section id="anchor-armands-slope-is-significant" class="slide level2 center">
<h2>Anchor: Armand’s Slope Is Significant</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p><br></p>
<p>For Armand’s Pizza:</p>
<p><span class="math display">\[
t = \frac{5}{0.580} = 8.62, \quad df = 8
\]</span></p>
<p><span class="math inline">\(p\text{-value} \approx 0.000 \le 0.05\)</span> → <strong>reject <span class="math inline">\(H_0\)</span></strong>.</p>
<p><br></p>
<p>Student population is a <strong>significant</strong> predictor of restaurant sales — the slope is not zero.</p>
</div><div class="column" style="width:60%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/armands_reg_coef.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-auto-parts-slope-test" class="slide level2 center">
<h2>The Auto-Parts Slope Test</h2>
<p><br></p>
<ul>
<li class="fragment">From the Regression output (<code>yelp_rating</code> row):</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(b_1\)</span> (slope)</td>
<td style="text-align: right;">757.5</td>
</tr>
<tr class="even">
<td><span class="math inline">\(s_{b_1}\)</span> (std. error of slope)</td>
<td style="text-align: right;">51.46</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(t = b_1 / s_{b_1}\)</span></td>
<td style="text-align: right;"><strong>14.7</strong></td>
</tr>
<tr class="even">
<td><span class="math inline">\(df = n - 2\)</span></td>
<td style="text-align: right;">43</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(p\)</span>-value</td>
<td style="text-align: right;"><span class="math inline">\(&lt; 0.0001\)</span></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p><span class="math inline">\(|t| = 14.7\)</span> is enormous against <span class="math inline">\(t_{0.025, 43} = 2.02\)</span> → <strong>reject <span class="math inline">\(H_0\)</span></strong> decisively.</p></li>
<li class="fragment"><p><strong>Translation:</strong> the Yelp–sales relationship is <em>not</em> a fluke of these 45 stores. There is overwhelming evidence the true slope is positive.</p></li>
</ul>
</section>
<section id="confidence-interval-for-the-slope" class="slide level2 center">
<h2>Confidence Interval for the Slope</h2>
<p><br></p>
<ul>
<li class="fragment">The test says the slope is nonzero; the <strong>confidence interval</strong> says how big it plausibly is:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
b_1 \pm t_{\alpha/2,\,n-2}\; s_{b_1} = 757.5 \pm 2.02 \times 51.46 = (\$653.7\text{K},\; \$861.3\text{K})
\]</span></p>
</div>
<ul>
<li class="fragment"><p>We are 95% confident each Yelp star is worth between <strong>$654K and $861K</strong> in annual sales.</p></li>
<li class="fragment"><p>The interval is <strong>entirely above zero</strong> — the same conclusion as the test (reject <span class="math inline">\(H_0\)</span>), now with a magnitude a manager can plan around.</p></li>
<li class="fragment"><p><strong>Equivalence:</strong> reject <span class="math inline">\(H_0: \beta_1 = 0\)</span> at <span class="math inline">\(\alpha = 0.05\)</span> <span class="math inline">\(\iff\)</span> zero is <strong>not</strong> in the 95% CI. Read directly off the <strong>Lower 95% / Upper 95%</strong> columns of the output.</p></li>
</ul>
</section>
<section id="a-note-on-the-f-test" class="slide level2 center">
<h2>A Note on the F Test</h2>
<p><br></p>
<ul>
<li class="fragment"><p>The Regression output also reports an <strong>F test</strong> (the ANOVA block): <span class="math inline">\(F = \text{MSR}/\text{MSE}\)</span>, testing the same <span class="math inline">\(H_0: \beta_1 = 0\)</span>.</p></li>
<li class="fragment"><p>In <strong>simple</strong> regression (one predictor) the <span class="math inline">\(F\)</span> and <span class="math inline">\(t\)</span> tests are <strong>equivalent</strong> — in fact <span class="math inline">\(F = t^2\)</span>:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
F = 216.7 = (14.7)^2 = t^2
\]</span></p>
</div>
<ul>
<li class="fragment">Same conclusion, same <span class="math inline">\(p\)</span>-value. (When we add predictors next topic, <span class="math inline">\(F\)</span> tests the model <em>as a whole</em> while each <span class="math inline">\(t\)</span> tests one variable — then they differ.)</li>
</ul>
</section>
<section id="significance-is-not-causation" class="slide level2 center">
<h2>Significance Is Not Causation</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Rejecting <span class="math inline">\(H_0: \beta_1 = 0\)</span> tells us the <strong>relationship is statistically significant</strong> — Yelp and sales move together more than chance would explain.</p></li>
<li class="fragment"><p>It does <strong>not</strong> establish that <strong>better service causes</strong> higher sales. Reverse causation (busy, well-stocked stores earn better reviews) and lurking variables (a great location drives <em>both</em>) are live alternatives.</p></li>
<li class="fragment"><p>It also does <strong>not</strong> prove the relationship is truly <strong>linear</strong> outside the range we observed — extrapolating a 6-star store is meaningless.</p></li>
<li class="fragment"><p><em>Use regression to forecast and to quantify; use judgment and design to claim causation.</em></p></li>
</ul>
</section>
<section id="residual-analysis-validating-the-assumptions" class="slide level2 center">
<h2>Residual Analysis: Validating the Assumptions</h2>
<p><br></p>
<ul>
<li class="fragment"><p>A significant slope is worthless if the model is the <strong>wrong shape</strong>. <strong>Residuals</strong> are our window onto the error term — they should look like random noise.</p></li>
<li class="fragment"><p>The core diagnostic: <strong>plot residuals against <span class="math inline">\(x\)</span></strong> (or against <span class="math inline">\(\hat{y}\)</span>). We want a <strong>horizontal band of points centered at zero</strong> with no pattern.</p></li>
<li class="fragment"><p>Two warning signs to learn:</p>
<ul>
<li class="fragment">A <strong>curved</strong> (U-shaped) band → the relationship is <strong>nonlinear</strong>; a straight line is the wrong functional form (consider adding <span class="math inline">\(x^2\)</span>).</li>
<li class="fragment">A <strong>fan</strong> that widens → <strong>non-constant variance</strong> (heteroscedasticity); the constant-variance assumption fails (consider transforming <span class="math inline">\(y\)</span>).</li>
</ul></li>
</ul>
</section>
<section id="the-auto-parts-residual-plot" class="slide level2 center">
<h2>The Auto-Parts Residual Plot</h2>

<img data-src="figs/autoparts_residual_plot.png" class="quarto-figure quarto-figure-center r-stretch" style="width:72.0%"><ul>
<li>Roughly horizontal, centered at zero, no fan and no curve → the <strong>linearity</strong> and <strong>constant-variance</strong> assumptions look reasonable. The straight-line model is defensible.</li>
</ul>
</section>
<section id="standardized-residuals-and-outliers" class="slide level2 center">
<h2>Standardized Residuals and Outliers</h2>
<ul>
<li class="fragment"><p>Dividing each residual by its standard deviation gives a <strong>standardized residual</strong> — on a <span class="math inline">\(z\)</span>-like scale.</p></li>
<li class="fragment"><p><strong>Rule of thumb:</strong> a standardized residual with <span class="math inline">\(|z| &gt; 2\)</span> flags an <strong>outlier</strong> — a store that performs far off-trend for its rating. Investigate; don’t auto-delete.</p></li>
</ul>
<div class="fragment">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/autoparts_std_residual_plot.png" class="quarto-figure quarto-figure-center" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="two-stores-worth-a-conversation" class="slide level2 center">
<h2>Two Stores Worth a Conversation</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Two stores sit just past <span class="math inline">\(\pm 2\)</span> — both rated <strong>5.0 stars</strong>:</p>
<ul>
<li class="fragment">One <strong>under-performs</strong> badly (sales far below the $4.1M its rating predicts).</li>
<li class="fragment">One <strong>over-performs</strong> (sales well above the line).</li>
</ul></li>
<li class="fragment"><p>These are <strong>not data errors</strong> — they are real stores the model can’t fully explain with rating alone.</p></li>
<li class="fragment"><p><em>What might separate two 5-star stores?</em> End-cap placement, local income, population. <strong>That is the teaser for multiple regression</strong> — adding the variables that explain the residuals.</p></li>
</ul>
</section>
<section id="forecasting-a-new-store-point-prediction" class="slide level2 center">
<h2>Forecasting a New Store: Point Prediction</h2>
<p><br></p>
<ul>
<li class="fragment">The real payoff: a prospective site rates <strong>4.5 stars</strong> on comparable stores. Predicted sales:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\hat{y} = 332.8 + 757.5 \times 4.5 = \$3{,}742\text{K} \;\approx\; \$3.74\text{M}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>That single number is the <strong>point prediction</strong> — but a point with no margin of error is a trap. Two different questions need two different intervals:</p>
<ul>
<li class="fragment"><strong>Confidence interval</strong> — the <strong>mean</strong> sales of <em>all</em> stores rated 4.5.</li>
<li class="fragment"><strong>Prediction interval</strong> — the sales of <strong>this one</strong> new store.</li>
</ul></li>
</ul>
</section>
<section id="confidence-interval-vs.-prediction-interval" class="slide level2 center">
<h2>Confidence Interval vs.&nbsp;Prediction Interval</h2>
<p><br></p>
<div style="font-size: 86%;">
<ul>
<li class="fragment"><strong>Confidence interval</strong> for the mean response at <span class="math inline">\(x^*\)</span> — narrower:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\hat{y} \pm t_{\alpha/2,\,n-2}\; s\sqrt{\frac{1}{n} + \frac{(x^* - \bar{x})^2}{\sum (x_i - \bar{x})^2}}
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>Prediction interval</strong> for one new store at <span class="math inline">\(x^*\)</span> — wider (note the extra <strong>1</strong>):</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\hat{y} \pm t_{\alpha/2,\,n-2}\; s\sqrt{1 + \frac{1}{n} + \frac{(x^* - \bar{x})^2}{\sum (x_i - \bar{x})^2}}
\]</span></p>
</div>
<ul>
<li class="fragment">The PI carries the <strong>individual store’s</strong> own scatter (<span class="math inline">\(s\)</span>) <em>on top of</em> the uncertainty in the line — that is the extra “1.”</li>
</ul>
</div>
</section>
<section id="the-two-intervals-in-a-picture" class="slide level2 center">
<h2>The Two Intervals, in a Picture</h2>

<img data-src="figs/autoparts_pred_band.png" class="quarto-figure quarto-figure-center r-stretch" style="width:66.0%"><ul>
<li>At Yelp = 4.5: point $3.74M; <strong>CI</strong> <span class="math inline">\((\$3{,}543\text{K},\; \$3{,}940\text{K})\)</span> for the average such store; <strong>PI</strong> <span class="math inline">\((\$2{,}786\text{K},\; \$4{,}698\text{K})\)</span> for one specific new store.</li>
<li>Both bands are <strong>narrowest near <span class="math inline">\(\bar{x}\)</span></strong> and flare out at the edges — forecasts far from the data are less certain.</li>
</ul>
</section>
<section id="what-makes-a-forecast-tighter-or-looser" class="slide level2 center">
<h2>What Makes a Forecast Tighter or Looser</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Four levers set the width of these intervals:</p>
<ol type="1">
<li class="fragment"><strong>Confidence level</strong> <span class="math inline">\((1-\alpha)\)</span> — more confidence → wider.</li>
<li class="fragment"><strong>Data spread</strong> <span class="math inline">\(s\)</span> — noisier data → wider.</li>
<li class="fragment"><strong>Sample size</strong> <span class="math inline">\(n\)</span> — more stores → narrower.</li>
<li class="fragment"><strong>Distance of <span class="math inline">\(x^*\)</span> from <span class="math inline">\(\bar{x}\)</span></strong> — forecasting far from the average rating → wider.</li>
</ol></li>
<li class="fragment"><p><strong>Manager’s lesson:</strong> a confident forecast comes from a tight model (<span class="math inline">\(s\)</span> small), lots of data (<span class="math inline">\(n\)</span> large), and a site that looks like the stores we already have (<span class="math inline">\(x^*\)</span> near <span class="math inline">\(\bar{x}\)</span>). Forecasting an exotic site is a guess dressed as a number.</p></li>
</ul>
</section>
<section id="team-sprint-2-test-the-slope-forecast-a-site" class="slide level2 center">
<h2>⏱️ Team Sprint 2 — Test the slope, forecast a site</h2>
<div class="sprint">
<p><strong>Decide:</strong> is the Yelp–sales relationship real, and what should we forecast for a candidate 4.5-star site?</p>
<p><strong>Data:</strong> <code>data/autoparts.csv</code> · <strong>Time:</strong> ~15 min</p>
<ol type="1">
<li>From the Regression output, state <span class="math inline">\(t\)</span>, the <span class="math inline">\(p\)</span>-value, and the <strong>95% CI for the slope</strong> — is <span class="math inline">\(\beta_1\)</span> significantly nonzero?</li>
<li>Glance at the <strong>residual plot</strong> (check Residual Plots in the dialog): any fan or curve that breaks the assumptions?</li>
<li>Forecast a site at <strong>Yelp = 4.5</strong>: give the point prediction, and say whether the CFO should quote the <strong>CI</strong> or the <strong>PI</strong> for one new lease — and why.</li>
</ol>
<p><strong>Hand in (1 slide):</strong> the slope verdict (with CI), an assumptions one-liner, and your forecast + the interval you’d put in the lease memo.</p>
</div>
</section>
<section id="debrief-managers-takeaway-lecture-2" class="slide level2 center">
<h2>Debrief — Manager’s Takeaway (Lecture 2)</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> the Yelp–sales slope is overwhelmingly significant (<span class="math inline">\(t = 14.7\)</span>, <span class="math inline">\(p &lt; 0.0001\)</span>); a 4.5-star site is forecast at <strong>$3.74M</strong>, and for <em>one</em> lease we quote the <strong>prediction interval</strong> <span class="math inline">\((\$2.79\text{M}, \$4.70\text{M})\)</span>.</p></li>
<li class="fragment"><p><strong>One number:</strong> 95% CI for the slope = <strong>($654K, $861K)</strong> per star — the magnitude the real-estate team plans around.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> the model assumes the new site behaves like our 45 stores; the two off-trend 5-star outliers warn that rating alone misses something — which is exactly why we add predictors next.</p></li>
</ul>
</section>
<section id="carry-forward-lecture-2" class="slide level2 center">
<h2>Carry-forward (Lecture 2)</h2>
<ul>
<li><p><strong>Your client (homework):</strong> on your team’s simple regression — test the slope (report <span class="math inline">\(t\)</span>, <span class="math inline">\(p\)</span>, and the 95% CI), check the residual plot for assumption violations, and produce a point prediction <em>with the right interval</em> for one new case. State whether you’d trust the forecast.</p></li>
<li><p><strong>Next time:</strong> sales depend on more than one thing. We add <strong>population, income, and end-cap placement</strong> to the model — <strong>Multiple Regression</strong> — and learn why a variable that looks important alone can vanish once others are in the room.</p></li>
</ul>
</section></section>
<section>
<section id="debrief-from-a-line-to-a-site-decision" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Debrief — From a Line to a Site Decision</h1>

</section>
<section id="the-whole-engagement-on-one-page" class="slide level2 center">
<h2>The Whole Engagement on One Page</h2>
<div class="r-fit-text">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Question</th>
<th>Tool</th>
<th>Auto-parts result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fit</td>
<td>What’s the line?</td>
<td>Least squares</td>
<td><span class="math inline">\(\hat{y} = 332.8 + 757.5\,x\)</span></td>
</tr>
<tr class="even">
<td>Interpret</td>
<td>What’s a star worth?</td>
<td>Slope <span class="math inline">\(b_1\)</span></td>
<td><strong>+$757.5K</strong> per Yelp star</td>
</tr>
<tr class="odd">
<td>Explain</td>
<td>How good is the fit?</td>
<td><span class="math inline">\(R^2\)</span></td>
<td><strong>0.834</strong> — 83% of sales variation</td>
</tr>
<tr class="even">
<td>Test</td>
<td>Is it real?</td>
<td><span class="math inline">\(t\)</span> test on slope</td>
<td><span class="math inline">\(t = 14.7\)</span>, <span class="math inline">\(p &lt; .0001\)</span> → reject <span class="math inline">\(H_0\)</span></td>
</tr>
<tr class="odd">
<td>Quantify</td>
<td>How big, plausibly?</td>
<td>95% CI for slope</td>
<td>($654K, $861K) per star</td>
</tr>
<tr class="even">
<td>Validate</td>
<td>Do assumptions hold?</td>
<td>Residual plot</td>
<td>Horizontal band → OK (2 outliers)</td>
</tr>
<tr class="odd">
<td>Forecast</td>
<td>What will a new site sell?</td>
<td>Point + PI</td>
<td>$3.74M; PI ($2.79M, $4.70M) at 4.5 stars</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="managers-takeaway" class="slide level2 center">
<h2>Manager’s Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> Yelp rating predicts auto-parts store sales strongly and significantly — about <strong>$758K per star</strong>, explaining <strong>83%</strong> of the sales gap — so the real-estate team can use it to score and forecast sites.</p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <span class="math inline">\(b_1 = 757.5\)</span> — and where it came from: <span class="math inline">\(\sum(x-\bar{x})(y-\bar{y}) / \sum(x-\bar{x})^2\)</span>.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> regression forecasts and quantifies; it does <strong>not</strong> prove causation, and 17% of sales is still unexplained — a single predictor is a start, not the answer.</p></li>
<li class="fragment"><p><strong>Practice with the real data:</strong></p>
<ul>
<li class="fragment"><code>data/autoparts.csv</code> + Regression tool → reproduce <span class="math inline">\(b_1 = 757.5\)</span>, <span class="math inline">\(R^2 = 0.834\)</span>, <span class="math inline">\(t = 14.7\)</span>.</li>
<li class="fragment">Worked solutions: <code>data/autoparts_regression.xlsx</code>.</li>
</ul></li>
</ul>
</section>
<section id="summary" class="slide level2 center">
<h2>Summary</h2>
<p>Some key takeaways from this session:</p>
<ul>
<li><strong>Regression predicts</strong>, where comparison only contrasts: the estimated line <span class="math inline">\(\hat{y} = b_0 + b_1 x\)</span> turns a relationship into a forecast.</li>
<li><strong>Least squares</strong> picks the unique line that minimizes <span class="math inline">\(\sum (y_i - \hat{y}_i)^2\)</span>; the <strong>slope</strong> is the business number ($757.5K per Yelp star), the <strong>intercept</strong> just anchors the line.</li>
<li><strong><span class="math inline">\(R^2 = \text{SSR}/\text{SST}\)</span></strong> is the share of variation the line explains (0.834 here); <span class="math inline">\(r = (\text{sign } b_1)\sqrt{R^2}\)</span> ties it to correlation.</li>
<li><strong>Inference</strong> asks if the slope is real: <span class="math inline">\(t = b_1/s_{b_1}\)</span> with <span class="math inline">\(df = n-2\)</span> (and <span class="math inline">\(F = t^2\)</span>); the 95% CI gives the plausible magnitude.</li>
<li><strong>Residual plots</strong> validate the assumptions — look for a horizontal band; a curve means nonlinearity, a fan means non-constant variance.</li>
<li><strong>Prediction</strong> needs the right interval: a <strong>CI</strong> for the mean response, a <strong>wider PI</strong> for one new store; both widen as <span class="math inline">\(x^*\)</span> leaves <span class="math inline">\(\bar{x}\)</span>.</li>
<li>Significance <span class="math inline">\(\neq\)</span> causation, and one predictor is rarely enough — the bridge to multiple regression.</li>
</ul>
</section>
<section id="carry-forward" class="slide level2 center">
<h2>Carry-forward</h2>
<ul>
<li><p><strong>Your client (homework):</strong> fit, interpret, test, validate, and forecast a simple regression on your team’s case — the full arc on one slide, ending with a forecast you’d defend.</p></li>
<li><p><strong>Next time:</strong> we add more predictors and learn what “holding everything else constant” really means — <strong>Multiple Regression</strong> on the same auto-parts client.</p></li>
</ul>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Thank you!</h1>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Business Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>