<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Professor Davi Moreira ">
  <title>QM 6700: Business Analytics –  QM 6700: Business Analytics </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-8fc47a4fdcba9931a3aa90ef56f89358.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="font-size: 100%;"> QM 6700: Business Analytics </span></h1>
  <p class="subtitle"><span style="font-size: 150%;"> Discrete Probability Distributions </span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor<br>Davi Moreira<br> 
</div>
</div>
</div>

</section>
<section id="overview" class="slide level2 center">
<h2>Overview</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Case Spotlight: planning capacity at Vungle</li>
<li>Random variables: discrete vs.&nbsp;continuous</li>
<li>Discrete probability distributions: table, conditions, graph</li>
<li>Expected value and variance of a random variable</li>
<li>Covariance, correlation, and the diversification math</li>
<li>The <strong>Binomial</strong> distribution: counting installs over impressions</li>
</ul>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>The <strong>Poisson</strong> distribution: rare events over an interval</li>
<li>When Binomial ≈ Poisson (large <span class="math inline">\(n\)</span>, small <span class="math inline">\(p\)</span>)</li>
<li>Excel: <code>BINOM.DIST</code> and <code>POISSON.DIST</code></li>
<li>Tail probabilities: <span class="math inline">\(P(X \geq N)\)</span> for capacity planning</li>
<li>The decision: how big a postback pipeline does Vungle need?</li>
</ul>
</div></div>
</section>
<section>
<section id="case-spotlight-ab-testing-at-vungle" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Case Spotlight: A/B Testing at Vungle</h1>

</section>
<section id="june-2014-from-is-b-better-to-can-we-handle-it" class="slide level2 center">
<h2>June 2014: From “Is B Better?” to “Can We Handle It?”</h2>
<p><br></p>
<ul>
<li class="fragment"><p><a href="https://techcrunch.com/2019/07/15/blackstone-is-acquiring-mobile-ad-company-vungle/">Vungle</a> (today part of Liftoff) is a mobile ad-tech startup: it serves 15-second video ads inside other apps and earns revenue mainly when a viewer <strong>installs</strong> the advertised app.</p></li>
<li class="fragment"><p>Across June 2014, algorithm <strong>A</strong> served ~236M impressions and <strong>B</strong> served ~16M, side by side. The metric that pays the bills is <strong>eRPM</strong> (revenue per 1,000 impressions).</p></li>
<li class="fragment"><p>Every install fires a <strong>postback</strong>: a real-time callback the ad server must record, bill, and confirm to the advertiser. Installs are the events the <strong>infrastructure</strong> has to absorb.</p></li>
<li class="fragment"><p>Engineering’s worry is not “is B better?”; it is <strong>“how many installs hit us at once, and how often?”</strong> Provision too little capacity and postbacks drop (lost revenue); too much and you burn cash on idle servers.</p></li>
</ul>
</section>
<section id="the-brief-todays-managerial-question" class="slide level2 center">
<h2>The Brief: Today’s Managerial Question</h2>
<p><br></p>
<ul>
<li class="fragment"><strong>The big call (Topics 1–9):</strong> <em>roll out B to all advertisers, or stay with A?</em> Before you can ship B, engineering has to know the install load it creates. Today’s slice of that call:</li>
</ul>
<div class="fragment">
<blockquote>
<p>“For a typical burst, <strong>what’s the chance of at least <span class="math inline">\(N\)</span> installs</strong>, so we can size the postback pipeline without over- or under-building?”</p>
</blockquote>
</div>
<p><br></p>
<ul>
<li class="fragment"><p>So far we have <em>described</em> and <em>compared</em> data. Today we <strong>model</strong> it: as the manager you put a <strong>probability distribution</strong> on a random count, then read off the chance of any outcome you care about.</p></li>
<li class="fragment"><p><strong>How today’s studio runs:</strong> I demo each distribution on a textbook example, then your group cracks a separate posted case (one sprint per class), then we debrief the capacity call.</p></li>
<li class="fragment"><p>By the end you turn a conversion rate into a defensible <strong>capacity plan</strong>, with the probabilities to back it up.</p></li>
</ul>
</section>
<section id="how-todays-tools-answer-it" class="slide level2 center">
<h2>How Today’s Tools Answer It</h2>
<p><br></p>
<p>Every tool today maps onto the Vungle install count:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Feature of the Vungle problem</th>
<th>The tool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Each impression installs (yes) or not (no)</td>
<td><strong>Bernoulli trial</strong></td>
</tr>
<tr class="even">
<td>Count installs over <span class="math inline">\(n\)</span> fixed impressions</td>
<td><strong>Binomial</strong> distribution (Lecture 1)</td>
</tr>
<tr class="odd">
<td>Installs as rare arrivals over an interval</td>
<td><strong>Poisson</strong> distribution (Lecture 2)</td>
</tr>
<tr class="even">
<td>“How big must capacity be?”</td>
<td>a <strong>tail probability</strong> <span class="math inline">\(P(X \geq N)\)</span></td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment">One conversion rate, two models; for Vungle’s tiny <span class="math inline">\(p\)</span> they will give <strong>almost the same answer</strong>. That is today’s punchline.</li>
</ul>
</section></section>
<section>
<section id="lecture-1-random-variables-expected-value-the-binomial" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 1: Random Variables, Expected Value &amp; the Binomial</h1>

</section>
<section id="the-brief-lecture-1" class="slide level2 center">
<h2>The Brief: Lecture 1</h2>
<p><br></p>
<ul>
<li class="fragment"><strong>The big call:</strong> <em>roll out B, or stay with A?</em> <strong>Today’s rung:</strong> <em>how many installs should we expect, and how do we model them as a Binomial?</em></li>
</ul>
<div class="fragment">
<blockquote>
<p>“Model the number of <strong>installs in a burst of 1,000 impressions</strong> as a random count. What is its expected value, its spread, and the probability it hits <strong>at least 8</strong>, the level that stresses a single postback worker?”</p>
</blockquote>
</div>
<p><br></p>
<ul>
<li class="fragment"><p>As the manager you build the machinery in three steps: (1) name the <strong>random variable</strong>, (2) get its <strong>expected value and variance</strong>, (3) recognize it as a <strong>Binomial</strong> and compute exact probabilities in Excel.</p></li>
<li class="fragment"><p>The number that drives everything is Vungle’s conversion rate: <span class="math inline">\(p \approx 0.0035\)</span> for B, <span class="math inline">\(p \approx 0.0040\)</span> for A.</p></li>
</ul>
</section>
<section id="how-every-class-runs" class="slide level2 center">
<h2>How Every Class Runs</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/lecture_dynamic.png" class="quarto-figure quarto-figure-center" style="width:90.0%"></p>
</figure>
</div>
<p>The class <strong>ends on the Team Sprint</strong>, your group’s graded submission: a decision plus your read of the analysis, one PDF before you leave.</p>
</section></section>
<section>
<section id="random-variables" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Random Variables</h1>

</section>
<section id="what-is-a-random-variable" class="slide level2 center">
<h2>What Is a Random Variable?</h2>
<p><br></p>
<ul>
<li class="fragment"><p>A <strong>random variable</strong> is a numerical description of the outcome of an experiment: it assigns a <strong>number</strong> to each possible result.</p></li>
<li class="fragment"><p>Two flavors:</p>
<ul>
<li class="fragment"><strong>Discrete</strong>: assumes a finite or countable list of values (you can list them: <span class="math inline">\(0, 1, 2, \dots\)</span>).</li>
<li class="fragment"><strong>Continuous</strong>: assumes any value in an interval (we handle these next topic).</li>
</ul></li>
<li class="fragment"><p>For Vungle, the count we care about is discrete:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
X = \text{number of installs in a fixed batch of impressions} \in \{0, 1, 2, \dots\}
\]</span></p>
</div>
<ul>
<li class="fragment">Installs are <strong>counted</strong>, not measured, so <span class="math inline">\(X\)</span> is a <strong>discrete</strong> random variable. (eRPM, by contrast, is continuous; next topic.)</li>
</ul>
</section>
<section id="discrete-finite-vs.-countably-infinite" class="slide level2 center">
<h2>Discrete: Finite vs.&nbsp;Countably Infinite</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Finite</strong> number of values, a hard upper limit exists:</p>
<ul>
<li class="fragment"><em>JSL Appliances:</em> <span class="math inline">\(x\)</span> = TVs sold in a day <span class="math inline">\(\in \{0,1,2,3,4\}\)</span> (you cannot sell more than you stock).</li>
<li class="fragment"><em>Vungle burst:</em> installs in 1,000 impressions <span class="math inline">\(\in \{0, 1, \dots, 1000\}\)</span>.</li>
</ul></li>
<li class="fragment"><p><strong>Countably infinite</strong>: no upper limit, but still countable:</p>
<ul>
<li class="fragment"><em>JSL:</em> <span class="math inline">\(x\)</span> = customers arriving in a day <span class="math inline">\(\in \{0, 1, 2, \dots\}\)</span>.</li>
<li class="fragment"><em>Vungle:</em> installs across a whole day (millions of impressions), no fixed ceiling.</li>
</ul></li>
<li class="fragment"><p><strong>Why it matters:</strong> the distribution we choose mirrors the structure. A fixed-<span class="math inline">\(n\)</span> count → <strong>Binomial</strong>; an open-ended count of rare events → <strong>Poisson</strong>.</p></li>
</ul>
</section>
<section id="quick-check-classify-the-variable" class="slide level2 center">
<h2>Quick Check: Classify the Variable</h2>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Random variable</th>
<th>Discrete or continuous?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Installs in a 1,000-impression burst</td>
<td><strong>Discrete</strong> (finite)</td>
</tr>
<tr class="even">
<td>Customers arriving at Vungle’s API per minute</td>
<td><strong>Discrete</strong> (countably infinite)</td>
</tr>
<tr class="odd">
<td>eRPM on a given day ($ per 1,000 impr.)</td>
<td><strong>Continuous</strong></td>
</tr>
<tr class="even">
<td>Number of postbacks dropped in an hour</td>
<td><strong>Discrete</strong></td>
</tr>
<tr class="odd">
<td>Time until the next install fires</td>
<td><strong>Continuous</strong></td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment"><strong>Rule of thumb:</strong> if you would naturally <em>count</em> it, it is discrete; if you would <em>measure</em> it on a scale, it is continuous.</li>
</ul>
</section></section>
<section>
<section id="discrete-probability-distributions" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Discrete Probability Distributions</h1>

</section>
<section id="the-probability-distribution" class="slide level2 center">
<h2>The Probability Distribution</h2>
<p><br></p>
<ul>
<li class="fragment"><p>The <strong>probability distribution</strong> of a discrete random variable lists every value <span class="math inline">\(x\)</span> together with its probability, through a <strong>probability function</strong> <span class="math inline">\(f(x) = P(X = x)\)</span>.</p></li>
<li class="fragment"><p>It can be given as a <strong>table</strong>, a <strong>graph</strong>, or a <strong>formula</strong>.</p></li>
<li class="fragment"><p>Two conditions make a probability function <strong>valid</strong>:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
f(x) \geq 0 \qquad \text{for every } x \qquad\qquad \sum_{x} f(x) = 1
\]</span></p>
</div>
<ul>
<li class="fragment">The first says probabilities cannot be negative; the second says <em>something</em> must happen.</li>
</ul>
</section>
<section id="where-the-probabilities-come-from" class="slide level2 center">
<h2>Where the Probabilities Come From</h2>
<p><br></p>
<ul>
<li class="fragment">Three standard ways to assign the probabilities <span class="math inline">\(f(x)\)</span>:</li>
</ul>
<div class="fragment">
<ul>
<li><strong>Classical:</strong> equally likely outcomes (a fair die: each face <span class="math inline">\(1/6\)</span>).</li>
<li><strong>Subjective:</strong> informed judgment when there is no track record.</li>
<li><strong>Relative frequency:</strong> the share of past observations, the route we take for JSL next. It gives an <strong>empirical</strong> distribution.</li>
</ul>
</div>
<ul>
<li class="fragment"><p>A <strong>formula</strong> can also supply <span class="math inline">\(f(x)\)</span> directly. The simplest is the <strong>discrete uniform</strong>, <span class="math inline">\(f(x) = 1/n\)</span> over <span class="math inline">\(n\)</span> equally likely values.</p></li>
<li class="fragment"><p>Our two workhorses, the <strong>Binomial</strong> and <strong>Poisson</strong>, are the formula distributions that fit the Vungle install count.</p></li>
</ul>
</section>
<section id="anchor-example-jsl-appliances" class="slide level2 center">
<h2>Anchor Example: JSL Appliances</h2>
<p><br></p>
<ul>
<li class="fragment">Using 200 days of past TV-sales data, JSL builds an <strong>empirical</strong> distribution (relative frequencies):</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(x\)</span> (TVs sold)</th>
<th style="text-align: right;">Days</th>
<th style="text-align: right;"><span class="math inline">\(f(x) = P(X=x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">0.40</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0.10</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>Total</strong></td>
<td style="text-align: right;"><strong>200</strong></td>
<td style="text-align: right;"><strong>1.00</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><strong>Check the conditions:</strong> every <span class="math inline">\(f(x) \geq 0\)</span> ✓, and they sum to <span class="math inline">\(1.00\)</span> ✓, a valid distribution.</li>
</ul>
</section>
<section id="reading-the-distribution" class="slide level2 center">
<h2>Reading the Distribution</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Once you have <span class="math inline">\(f(x)\)</span>, <strong>any</strong> question about <span class="math inline">\(X\)</span> is just addition:</p>
<ul>
<li class="fragment"><span class="math inline">\(P(X = 0) = 0.40\)</span>: no sale on 40% of days.</li>
<li class="fragment"><span class="math inline">\(P(X \geq 2) = 0.20 + 0.05 + 0.10 = 0.35\)</span>.</li>
<li class="fragment"><span class="math inline">\(P(X \leq 1) = 0.40 + 0.25 = 0.65\)</span>.</li>
</ul></li>
<li class="fragment"><p>This is exactly the move we will make for Vungle: build <span class="math inline">\(f(x)\)</span> for installs, then read off <span class="math inline">\(P(X \geq N)\)</span> for the capacity plan.</p></li>
<li class="fragment"><p>The only change is <strong>how</strong> we get <span class="math inline">\(f(x)\)</span>: JSL used past data; for Vungle we will use a <strong>formula</strong> (the Binomial) driven by the conversion rate <span class="math inline">\(p\)</span>.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">JSL got its <span class="math inline">\(f(x)\)</span> by counting 200 days of sales. Why would I ever trust a formula’s <span class="math inline">\(f(x)\)</span> for Vungle instead of just counting past installs the same way?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> counting works only for outcomes you have already seen at the right scale. JSL sold at most 4 TVs a day, so 200 days cover every value. A 1,000-impression burst can produce <strong>0 to 1,000</strong> installs; you will never observe enough bursts to fill that table by hand. The Binomial formula gives the probability of <strong>every</strong> <span class="math inline">\(x\)</span>, including the rare 8-plus bursts that size the pipeline, from just <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span>.</p>
</div>
</div>
</section></section>
<section>
<section id="expected-value-and-variance" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Expected Value and Variance</h1>

</section>
<section id="expected-value-the-center" class="slide level2 center">
<h2>Expected Value: the Center</h2>
<p><br></p>
<ul>
<li class="fragment">The <strong>expected value</strong> <span class="math inline">\(E(X)\)</span> (or mean <span class="math inline">\(\mu\)</span>) is the <strong>probability-weighted average</strong> of the values <span class="math inline">\(X\)</span> can take:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(X) = \mu = \sum_{x} x \, f(x)
\]</span></p>
</div>
<ul>
<li class="fragment"><p>It is the <strong>long-run average</strong> outcome over many repetitions of the experiment.</p></li>
<li class="fragment"><p>It need <strong>not</strong> be a value <span class="math inline">\(X\)</span> can actually assume: JSL’s <span class="math inline">\(E(X) = 1.2\)</span> TVs, though you never sell 1.2 TVs.</p></li>
</ul>
</section>
<section id="variance-and-standard-deviation-the-spread" class="slide level2 center">
<h2>Variance and Standard Deviation: the Spread</h2>
<p><br></p>
<ul>
<li class="fragment">The <strong>variance</strong> is the probability-weighted average of squared deviations from the mean; it measures <strong>risk / variability</strong>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\text{Var}(X) = \sigma^2 = \sum_{x} (x - \mu)^2 \, f(x)
\]</span></p>
</div>
<ul>
<li class="fragment">The <strong>standard deviation</strong> is its positive square root, in the same units as <span class="math inline">\(X\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\sigma = \sqrt{\text{Var}(X)}
\]</span></p>
</div>
<ul>
<li class="fragment">Same mean, larger <span class="math inline">\(\sigma\)</span> → <strong>more spread, more risk</strong>, exactly what a capacity planner fears (a big burst).</li>
</ul>
</section>
<section id="jsl-appliances-the-worksheet" class="slide level2 center">
<h2>JSL Appliances: the Worksheet</h2>
<div class="r-fit-text">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(x\)</span></th>
<th style="text-align: right;"><span class="math inline">\(f(x)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x\,f(x)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x - \mu\)</span></th>
<th style="text-align: right;"><span class="math inline">\((x-\mu)^2\)</span></th>
<th style="text-align: right;"><span class="math inline">\((x-\mu)^2 f(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;"><span class="math inline">\(-1.2\)</span></td>
<td style="text-align: right;">1.44</td>
<td style="text-align: right;">0.576</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;"><span class="math inline">\(-0.2\)</span></td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;"><span class="math inline">\(0.8\)</span></td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">0.128</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;"><span class="math inline">\(1.8\)</span></td>
<td style="text-align: right;">3.24</td>
<td style="text-align: right;">0.162</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;"><span class="math inline">\(2.8\)</span></td>
<td style="text-align: right;">7.84</td>
<td style="text-align: right;">0.784</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>Sum</strong></td>
<td style="text-align: right;"><strong>1.00</strong></td>
<td style="text-align: right;"><span class="math inline">\(\boldsymbol{\mu = 1.20}\)</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><span class="math inline">\(\boldsymbol{\sigma^2 = 1.660}\)</span></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
E(X) = 1.20 \text{ TVs} \qquad \sigma^2 = 1.660 \qquad \sigma = \sqrt{1.660} = 1.288 \text{ TVs}
\]</span></p>
</div>
</section>
<section id="do-it-in-excel-expected-value-variance" class="slide level2 center">
<h2>Do It in Excel: Expected Value &amp; Variance</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Lay out the <span class="math inline">\(x\)</span> values in column A and <span class="math inline">\(f(x)\)</span> in column B (the JSL table).</li>
<li class="fragment">Column C: <code>=A2*B2</code> (the <span class="math inline">\(x\,f(x)\)</span> terms); <span class="math inline">\(E(X) =\)</span> <code>=SUM(C2:C6)</code> <span class="math inline">\(= 1.20\)</span>.</li>
<li class="fragment">Column D: <code>=(A2-$E$1)^2*B2</code>, with <span class="math inline">\(\mu\)</span> parked in <code>E1</code>; <span class="math inline">\(\sigma^2 =\)</span> <code>=SUM(D2:D6)</code> <span class="math inline">\(= 1.66\)</span>.</li>
<li class="fragment"><span class="math inline">\(\sigma =\)</span> <code>=SQRT(...)</code> <span class="math inline">\(= 1.29\)</span>, back in plain TV units.</li>
</ol>
<p>No ToolPak tool needed: this is the engine behind <strong>every</strong> discrete distribution; Binomial and Poisson just supply <span class="math inline">\(f(x)\)</span>.</p>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_ev_var.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="why-managers-care-mean-and-risk-together" class="slide level2 center">
<h2>Why Managers Care: Mean and Risk Together</h2>
<p><br></p>
<ul>
<li class="fragment"><p><span class="math inline">\(E(X)\)</span> alone is not enough. Two ad algorithms could deliver the <strong>same average</strong> installs but a different <strong>spread</strong>, and spread is what overflows a server or empties a sales pipeline.</p></li>
<li class="fragment"><p>A capacity planner reads <span class="math inline">\(E(X)\)</span> to <strong>size for the typical load</strong> and <span class="math inline">\(\sigma\)</span> (and the tail) to <strong>size for the bad days</strong>.</p></li>
<li class="fragment"><p><strong>Forward pointer:</strong> the Vungle install count has a special structure, a fixed number of impressions, each an independent yes/no at the <strong>same</strong> rate <span class="math inline">\(p\)</span>. That structure has a name: the <strong>Binomial</strong>, and it hands us <span class="math inline">\(E(X)\)</span>, <span class="math inline">\(\sigma\)</span>, and the full <span class="math inline">\(f(x)\)</span> from just two numbers, <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span>.</p></li>
</ul>
</section></section>
<section>
<section id="two-random-variables-together" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Two Random Variables Together</h1>

</section>
<section id="when-two-counts-move-together" class="slide level2 center">
<h2>When Two Counts Move Together</h2>
<p><br></p>
<ul>
<li class="fragment"><p>So far one random variable at a time. Most business risk involves <strong>two</strong> moving together: A’s installs and B’s installs each day, two stores’ sales, two stocks in a portfolio.</p></li>
<li class="fragment"><p>A <strong>bivariate distribution</strong> gives the probability of each <em>pair</em> of outcomes, <span class="math inline">\(f(x, y) = P(X = x, Y = y)\)</span>.</p></li>
<li class="fragment"><p>The new question is <strong>association</strong>: when one is high, is the other high too? That is what <strong>covariance</strong> and <strong>correlation</strong> measure, and it is the hinge of every diversification decision.</p></li>
<li class="fragment"><p><strong>Textbook anchor:</strong> DiCarlo Motors runs two dealerships (Geneva = <span class="math inline">\(x\)</span>, Saratoga = <span class="math inline">\(y\)</span>) and tracks 300 days of joint sales. <strong>Vungle parallel:</strong> A and B run side by side, so their daily install counts are a bivariate pair too.</p></li>
</ul>
</section>
<section id="rules-for-combining-random-variables" class="slide level2 center">
<h2>Rules for Combining Random Variables</h2>
<p><br></p>
<ul>
<li class="fragment">Before covariance, the algebra of <strong>shifting and adding</strong> random variables. For constants <span class="math inline">\(a, b\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(aX + b) = a\,E(X) + b \qquad\qquad \text{Var}(aX + b) = a^2\,\text{Var}(X)
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Adding a constant shifts the mean but <strong>not</strong> the spread; scaling by <span class="math inline">\(a\)</span> multiplies the variance by <span class="math inline">\(a^2\)</span>.</p></li>
<li class="fragment"><p>For a <strong>sum</strong> of two random variables, the means just add, but the variance carries a cross term:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(aX + bY) = a\,E(X) + b\,E(Y)
\]</span></p>
<p><span class="math display">\[
\text{Var}(aX + bY) = a^2\,\text{Var}(X) + b^2\,\text{Var}(Y) + 2ab\,\text{Cov}(X, Y)
\]</span></p>
</div>
<ul>
<li class="fragment">That last term, <span class="math inline">\(\text{Cov}(X, Y)\)</span>, is the whole story: it is <strong>why combining two things can lower (or raise) total risk</strong>.</li>
</ul>
</section>
<section id="covariance-and-correlation" class="slide level2 center">
<h2>Covariance and Correlation</h2>
<p><br></p>
<div style="font-size: 92%;">
<ul>
<li class="fragment"><strong>Covariance</strong> is the probability-weighted average of the joint deviations from each mean:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\text{Cov}(X, Y) = \sigma_{xy} = \sum \big[x - E(X)\big]\big[y - E(Y)\big]\,f(x, y)
\]</span></p>
</div>
<ul>
<li class="fragment">Sign reads the direction: <strong>positive</strong> = they tend to move together, <strong>negative</strong> = one up while the other down, <strong>zero</strong> = no linear link. Its size is hard to read (it carries mixed units), so we standardize it into the <strong>correlation coefficient</strong>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\rho_{xy} = \frac{\text{Cov}(X, Y)}{\sigma_x\,\sigma_y}, \qquad -1 \leq \rho_{xy} \leq 1
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>DiCarlo:</strong> <span class="math inline">\(\sigma_{xy} = 0.1350\)</span> and <span class="math inline">\(\rho_{xy} = 0.1295\)</span>, a <strong>weak positive</strong> link: the two dealerships rise and fall together a little, not in lockstep.</li>
</ul>
</div>
</section>
<section id="diversification-why-combine-at-all" class="slide level2 center">
<h2>Diversification: Why Combine at All?</h2>
<p><br></p>
<ul>
<li class="fragment">Put a fraction <span class="math inline">\(w\)</span> of a portfolio in asset <span class="math inline">\(X\)</span> and the rest in <span class="math inline">\(Y\)</span>. The portfolio return is <span class="math inline">\(Z = wX + (1-w)Y\)</span>, so by the rules above:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(Z) = w\,E(X) + (1-w)\,E(Y)
\]</span></p>
<p><span class="math display">\[
\text{Var}(Z) = w^2 \sigma_x^2 + (1-w)^2 \sigma_y^2 + 2\,w(1-w)\,\rho_{xy}\,\sigma_x\,\sigma_y
\]</span></p>
</div>
<ul>
<li class="fragment"><p>The mean is a plain blend, but the <strong>risk is not</strong>: when <span class="math inline">\(\rho_{xy} &lt; 1\)</span>, the cross term shrinks <span class="math inline">\(\text{Var}(Z)\)</span> below the blend of the two variances. <strong>Low or negative correlation is what makes diversification work.</strong></p></li>
<li class="fragment"><p>The same math sizes a <strong>supply chain</strong>: two independent suppliers (<span class="math inline">\(\rho \approx 0\)</span>) cut shortage risk far more than two whose outages correlate.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-1" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If covariance and correlation measure the same direction, why bother computing both? Why not just report the covariance?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> covariance gives the <strong>sign</strong> but not a readable <strong>size</strong>: its units are “<span class="math inline">\(x\)</span>-units times <span class="math inline">\(y\)</span>-units” (cars-times-cars for DiCarlo), so <span class="math inline">\(0.135\)</span> could be strong or trivial, you cannot tell. Dividing by the two standard deviations strips the units and pins it to <span class="math inline">\([-1, 1]\)</span>, so <span class="math inline">\(\rho = 0.1295\)</span> instantly reads as “weak positive.” You need the covariance to <strong>build</strong> the portfolio variance, and the correlation to <strong>judge</strong> how much diversification will actually help.</p>
</div>
</div>
</section></section>
<section>
<section id="the-binomial-distribution" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Binomial Distribution</h1>

</section>
<section id="from-one-impression-to-many-the-bernoulli-trial" class="slide level2 center">
<h2>From One Impression to Many: the Bernoulli Trial</h2>

<img data-src="figs/bernoulli_to_binomial.png" class="quarto-figure quarto-figure-center r-stretch" style="width:92.0%"><ul>
<li>Each impression is a <strong>Bernoulli trial</strong>: it installs (<strong>success</strong>, prob. <span class="math inline">\(p\)</span>) or not (<strong>failure</strong>, prob. <span class="math inline">\(1-p\)</span>).</li>
<li>Count the successes over <span class="math inline">\(n\)</span> impressions and you have a <strong>Binomial</strong> random variable.</li>
</ul>
</section>
<section id="the-four-binomial-assumptions" class="slide level2 center">
<h2>The Four Binomial Assumptions</h2>
<p><br></p>
<p>A <strong>Binomial experiment</strong> requires all four:</p>
<div class="fragment">
<ol type="1">
<li>A sequence of <span class="math inline">\(n\)</span> <strong>identical</strong> trials.</li>
<li>Exactly <strong>two</strong> outcomes per trial: <em>success</em> and <em>failure</em>.</li>
<li>The success probability <span class="math inline">\(p\)</span> is <strong>constant</strong> across trials (the <em>stationarity</em> assumption).</li>
<li>The trials are <strong>independent</strong>.</li>
</ol>
</div>
<p><br></p>
<ul>
<li class="fragment"><strong>Vungle check:</strong> <span class="math inline">\(n\)</span> impressions in a burst (1); each one installs or not (2); the conversion rate <span class="math inline">\(p\)</span> is the same within a stable burst (3); one user installing does not change another’s odds (4). All four hold (approximately). So installs are <strong>Binomial</strong>.</li>
</ul>
</section>
<section id="a-question-that-often-comes-up-2" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">Real ad traffic is never perfectly identical or independent, so isn’t calling Vungle’s installs “Binomial” just wishful thinking?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> the assumptions are an approximation, and the manager’s job is to know when it is good enough. Within one <strong>stable</strong> burst, impressions are similar users seeing the same ad at the same rate, so the four conditions nearly hold and the Binomial is trustworthy. They break during a <strong>viral spike</strong> (the rate jumps and installs cluster); that is the one caveat we flag in the Takeaway, and the cue to re-estimate <span class="math inline">\(p\)</span> rather than trust the model blindly.</p>
</div>
</div>
</section>
<section id="the-binomial-probability-function" class="slide level2 center">
<h2>The Binomial Probability Function</h2>
<p><br></p>
<div style="font-size: 88%;">
<ul>
<li class="fragment">The probability of exactly <span class="math inline">\(x\)</span> successes in <span class="math inline">\(n\)</span> trials:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
f(x) = \binom{n}{x} p^x (1-p)^{n-x}, \qquad x = 0, 1, 2, \dots, n
\]</span></p>
</div>
<ul>
<li class="fragment">The <strong>binomial coefficient</strong> counts the ways to arrange <span class="math inline">\(x\)</span> successes among <span class="math inline">\(n\)</span> trials:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\binom{n}{x} = \frac{n!}{x!\,(n-x)!}
\]</span></p>
</div>
<ul>
<li class="fragment">Read it in two pieces: <span class="math inline">\(p^x (1-p)^{n-x}\)</span> is the probability of <strong>one specific</strong> arrangement; <span class="math inline">\(\binom{n}{x}\)</span> is <strong>how many</strong> arrangements give <span class="math inline">\(x\)</span> successes.</li>
</ul>
</div>
</section>
<section id="anchor-example-evans-electronics" class="slide level2 center">
<h2>Anchor Example: Evans Electronics</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Evans Electronics loses about <strong>10%</strong> of hourly employees per year (<span class="math inline">\(p = 0.10\)</span>). Choosing <strong>3</strong> employees at random (<span class="math inline">\(n = 3\)</span>), what is <span class="math inline">\(P(\text{exactly 1 leaves})\)</span>?</p></li>
<li class="fragment"><p>One specific way (leaver, stayer, stayer) has probability:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
(0.10)(0.90)(0.90) = (0.10)(0.90)^2 = 0.081
\]</span></p>
</div>
<ul>
<li class="fragment">There are <span class="math inline">\(\binom{3}{1} = 3\)</span> such arrangements (the leaver could be 1st, 2nd, or 3rd):</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
f(1) = \binom{3}{1}(0.10)^1 (0.90)^2 = 3 \times 0.081 = 0.243
\]</span></p>
</div>
</section>
<section id="evans-electronics-the-full-distribution" class="slide level2 center">
<h2>Evans Electronics: the Full Distribution</h2>

<img data-src="figs/binom_pmf_evans.png" class="quarto-figure quarto-figure-center r-stretch" style="width:72.0%"><ul>
<li><span class="math inline">\(f(0)=0.729,\; f(1)=0.243,\; f(2)=0.027,\; f(3)=0.001\)</span>, and they sum to 1.</li>
<li><span class="math inline">\(P(\text{at least 1 leaves}) = 1 - f(0) = 1 - 0.729 = 0.271\)</span>.</li>
</ul>
</section>
<section id="binomial-mean-variance-and-sd" class="slide level2 center">
<h2>Binomial Mean, Variance, and SD</h2>
<p><br></p>
<ul>
<li class="fragment">Because the trials are identical and independent, the mean and variance collapse to clean formulas, no worksheet needed:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(X) = \mu = np \qquad\quad \text{Var}(X) = \sigma^2 = np(1-p) \qquad\quad \sigma = \sqrt{np(1-p)}
\]</span></p>
</div>
<ul>
<li class="fragment"><p><strong>Evans:</strong> <span class="math inline">\(\mu = 3(0.10) = 0.30\)</span> leavers, <span class="math inline">\(\sigma^2 = 3(0.10)(0.90) = 0.27\)</span>, <span class="math inline">\(\sigma = 0.520\)</span>.</p></li>
<li class="fragment"><p>These are the same <span class="math inline">\(E(X)\)</span> and <span class="math inline">\(\sigma\)</span> from the worksheet; the Binomial just hands them to you from <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span>.</p></li>
</ul>
</section>
<section id="cumulative-probabilities-and-the-tail" class="slide level2 center">
<h2>Cumulative Probabilities and the Tail</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Most business questions are about a <strong>range</strong>, not a single value. Two cumulative moves cover them all:</p>
<ul>
<li class="fragment">“<strong>at most</strong> <span class="math inline">\(k\)</span>”: <span class="math inline">\(P(X \leq k) = f(0) + f(1) + \dots + f(k)\)</span>.</li>
<li class="fragment">“<strong>at least</strong> <span class="math inline">\(N\)</span>”: <span class="math inline">\(P(X \geq N) = 1 - P(X \leq N-1)\)</span>, the <strong>complement</strong> trick.</li>
</ul></li>
<li class="fragment"><p>The capacity question is a <strong>tail</strong>: <span class="math inline">\(P(X \geq N)\)</span>, <em>how often does the load exceed level <span class="math inline">\(N\)</span>?</em></p></li>
<li class="fragment"><p>Computing these by hand is tedious; Excel does the summation for us with one function.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-3" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">For “at least 8 installs,” why is it <span class="math inline">\(1 - P(X \leq 7)\)</span> and not <span class="math inline">\(1 - P(X \leq 8)\)</span>? The off-by-one keeps tripping me up.</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> “at least 8” means <span class="math inline">\(8, 9, 10, \dots\)</span>, so the <strong>opposite</strong> event is <span class="math inline">\(7\)</span> or fewer, not 8 or fewer. Subtracting <span class="math inline">\(P(X \leq 8)\)</span> would wrongly throw out the 8 itself. The rule: <span class="math inline">\(P(X \geq N) = 1 - P(X \leq N - 1)\)</span>, so for <span class="math inline">\(N = 8\)</span> you use <span class="math inline">\(P(X \leq 7)\)</span>. Get that boundary wrong and Vungle’s capacity probability is off by exactly the <span class="math inline">\(f(8)\)</span> term.</p>
</div>
</div>
</section>
<section id="excel-binom.dist" class="slide level2 center">
<h2>Excel: <code>BINOM.DIST</code></h2>
<p><br></p>
<ul>
<li class="fragment">Two arguments and a TRUE/FALSE switch give you everything:</li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>You want</th>
<th>Excel</th>
<th>Returns</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(P(X = x)\)</span> (PMF)</td>
<td><code>=BINOM.DIST(x, n, p, FALSE)</code></td>
<td>exact probability</td>
</tr>
<tr class="even">
<td><span class="math inline">\(P(X \leq x)\)</span> (CDF)</td>
<td><code>=BINOM.DIST(x, n, p, TRUE)</code></td>
<td>cumulative probability</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(P(X \geq N)\)</span> (tail)</td>
<td><code>=1 - BINOM.DIST(N-1, n, p, TRUE)</code></td>
<td>complement</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p><code>BINOMDIST</code> (no dot) is the legacy alias, same result.</p></li>
<li class="fragment"><p><strong>Capacity example:</strong> <span class="math inline">\(P(\geq 5 \text{ installs in 1{,}000 impressions at } p=0.004) =\)</span> <code>=1-BINOM.DIST(4, 1000, 0.004, TRUE)</code>.</p></li>
</ul>
</section></section>
<section>
<section id="the-vungle-burst-installs-as-a-binomial" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Vungle Burst: Installs as a Binomial</h1>

</section>
<section id="set-up-the-model" class="slide level2 center">
<h2>Set Up the Model</h2>
<p><br></p>
<ul>
<li class="fragment">The data give us the daily install <strong>counts</strong>; a count over a fixed batch of impressions is exactly a Binomial.</li>
</ul>

<img data-src="figs/vungle_installs_timeseries.png" class="quarto-figure quarto-figure-center r-stretch" style="width:78.0%"><ul>
<li>A averages ~31,700 installs/day, B ~1,870; but for capacity we work at the <strong>burst</strong> scale (1,000 impressions), where the model is tractable and the tail is the story.</li>
</ul>
</section>
<section id="estimate-p-then-build-the-distribution" class="slide level2 center">
<h2>Estimate <span class="math inline">\(p\)</span>, then Build the Distribution</h2>
<p><br></p>
<ul>
<li class="fragment">From <code>vungle_daily.csv</code>, the conversion rate is <code>installs / impressions</code>, averaged over the 30 days:</li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Algorithm</th>
<th style="text-align: right;">Conversion rate <span class="math inline">\(p\)</span></th>
<th style="text-align: right;">Per-burst mean <span class="math inline">\(\mu = np\)</span> (<span class="math inline">\(n=1000\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;">0.4027% <span class="math inline">\(\approx\)</span> <strong>0.0040</strong></td>
<td style="text-align: right;">$1000 = $ <strong>4.0</strong> installs</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;">0.3538% <span class="math inline">\(\approx\)</span> <strong>0.0035</strong></td>
<td style="text-align: right;">$1000 = $ <strong>3.5</strong> installs</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment">So installs per 1,000-impression burst are:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
X_A \sim \text{Binomial}(1000,\, 0.0040) \qquad\qquad X_B \sim \text{Binomial}(1000,\, 0.0035)
\]</span></p>
</div>
<ul>
<li class="fragment"><span class="math inline">\(\sigma_B = \sqrt{1000(0.0035)(0.9965)} = 1.868\)</span> installs: a tight, right-skewed count.</li>
</ul>
</section>
<section id="the-burst-distribution-a-vs.-b" class="slide level2 center">
<h2>The Burst Distribution: A vs.&nbsp;B</h2>

<img data-src="figs/binom_pmf_vungle_burst.png" class="quarto-figure quarto-figure-center r-stretch" style="width:82.0%"><ul>
<li>Both peak near 3–4 installs; A’s higher rate shifts mass right and <strong>fattens the tail</strong>, so A’s bursts overflow capacity more often.</li>
</ul>
</section>
<section id="the-tail-that-sizes-the-pipeline" class="slide level2 center">
<h2>The Tail That Sizes the Pipeline</h2>

<img data-src="figs/binom_tail_vungle_B.png" class="quarto-figure quarto-figure-center r-stretch" style="width:72.0%"><ul>
<li>For B, $P(X ) = 1 - P(X ) = 1 - 0.9735 = $ <strong>0.0265</strong>: about <strong>1 burst in 38</strong> delivers 8+ installs.</li>
<li>If one postback worker handles up to 7 installs/burst, ~2.7% of B’s bursts need a second worker; <em>that</em> is the capacity number.</li>
</ul>
</section>
<section id="do-it-in-excel-the-vungle-burst-binom.dist" class="slide level2 center">
<h2>Do It in Excel: The Vungle Burst (<code>BINOM.DIST</code>)</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">List the install counts <span class="math inline">\(x = 0, 1, 2, \dots\)</span> down column A.</li>
<li class="fragment">Column B (PMF): <code>=BINOM.DIST(A2, 1000, 0.0035, FALSE)</code>.</li>
<li class="fragment">Column C (CDF): <code>=BINOM.DIST(A2, 1000, 0.0035, TRUE)</code>.</li>
<li class="fragment">Read the capacity tail off the cumulative column: <span class="math inline">\(P(X \leq 7) = 0.9735\)</span>, so <span class="math inline">\(P(X \geq 8) =\)</span> <code>=1-C9</code> <span class="math inline">\(= 0.0265\)</span>.</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_binom_vungle.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="the-managers-takeaway-lecture-1" class="slide level2 center">
<h2>The Manager’s Takeaway (Lecture 1)</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> model installs over a fixed batch of impressions as <strong>Binomial(<span class="math inline">\(n\)</span>, <span class="math inline">\(p\)</span>)</strong>, and every capacity question becomes a tail probability you read off <code>BINOM.DIST</code>.</p></li>
<li class="fragment"><p><strong>One number:</strong> for Algorithm A, <span class="math inline">\(P(\geq 8 \text{ installs / 1,000-impr. burst}) \approx\)</span> <strong>0.051</strong>, twice B’s 0.027, because A converts at a higher rate.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> the Binomial assumes a <strong>constant, independent</strong> <span class="math inline">\(p\)</span>. Within a stable burst that holds; across a viral campaign spike it does not, so re-estimate <span class="math inline">\(p\)</span> when traffic shifts.</p></li>
</ul>
</section>
<section id="todays-question-todays-answer" class="slide level2 center">
<h2>Today’s Question, Today’s Answer</h2>
<p><br></p>
<p><strong>The question (Lecture 1):</strong></p>
<blockquote>
<p><em>How many installs should we expect in a 1,000-impression burst, and how do we model them as a Binomial?</em></p>
</blockquote>
<div class="fragment">
<p><br></p>
<p><strong>The answer we reached today:</strong></p>
<blockquote>
<p>Installs are <strong>Binomial(<span class="math inline">\(1000\)</span>, <span class="math inline">\(p\)</span>)</strong>. For B (<span class="math inline">\(p = 0.0035\)</span>): expect $= np = $ <strong>3.5</strong> installs with spread $= $ <strong>1.87</strong>, and the stress level $P(X ) = 1 - P(X ) = $ <strong>0.0265</strong> (about <strong>1 burst in 38</strong>). A converts higher, so its tail <span class="math inline">\(P(X \geq 8) \approx\)</span> <strong>0.051</strong> is roughly twice B’s.</p>
</blockquote>
</div>
</section>
<section id="team-sprint-your-group-case-lecture-1" class="slide level2 center">
<h2>⏱️ Team Sprint: Your Group Case (Lecture 1)</h2>
<div class="sprint">
<p><strong>Now it’s your group’s turn.</strong> Today’s in-class group case is posted on <strong>Brightspace</strong> (<em>Topic 05 Group Case, Lecture 1</em>): a separate business decision you make with today’s tools.</p>
<p><strong>What you’ll use:</strong> the <strong>Binomial</strong> model, <span class="math inline">\(E(X)=np\)</span>, <span class="math inline">\(\sigma=\sqrt{np(1-p)}\)</span>, and the tail <span class="math inline">\(P(X \geq N)\)</span>. <strong>Excel:</strong> Analysis ToolPak with <code>BINOM.DIST(x, n, p, FALSE/TRUE)</code>.</p>
<p><strong>Submit one PDF per group before you leave:</strong> your decision plus the numbers behind it.</p>
</div>
</section></section>
<section>
<section id="lecture-2-the-poisson-distribution" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 2: The Poisson Distribution</h1>

</section>
<section id="the-brief-lecture-2" class="slide level2 center">
<h2>The Brief: Lecture 2</h2>
<p><br></p>
<ul>
<li class="fragment"><strong>The big call:</strong> <em>roll out B, or stay with A?</em> <strong>Today’s rung:</strong> <em>how many rare-event installs hit us over an interval, and how do we model them as a Poisson?</em></li>
</ul>
<div class="fragment">
<blockquote>
<p>“Installs are <strong>rare</strong> (a few per thousand impressions). Is there a model that needs only the <strong>average rate</strong>, not the full <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span>? And does it give the same capacity answer?”</p>
</blockquote>
</div>
<p><br></p>
<ul>
<li class="fragment"><p>Yesterday we needed two numbers, <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span>. The <strong>Poisson</strong> distribution needs only <strong>one</strong>: the mean rate <span class="math inline">\(\mu\)</span> over an interval.</p></li>
<li class="fragment"><p>We will introduce Poisson on its own terms, then show it is the <strong>large-<span class="math inline">\(n\)</span>, small-<span class="math inline">\(p\)</span> limit</strong> of the Binomial, and that for Vungle the two are nearly identical.</p></li>
</ul>
</section>
<section id="how-every-class-runs-1" class="slide level2 center">
<h2>How Every Class Runs</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/lecture_dynamic.png" class="quarto-figure quarto-figure-center" style="width:90.0%"></p>
</figure>
</div>
<p>The class <strong>ends on the Team Sprint</strong>, your group’s graded submission: a decision plus your read of the analysis, one PDF before you leave.</p>
</section></section>
<section>
<section id="poisson-rare-events-over-an-interval" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Poisson: Rare Events Over an Interval</h1>

</section>
<section id="when-the-count-has-no-fixed-n" class="slide level2 center">
<h2>When the Count Has No Fixed <span class="math inline">\(n\)</span></h2>
<p><br></p>
<ul>
<li class="fragment"><p>The <strong>Poisson</strong> distribution models the number of times an event occurs over a fixed <strong>interval of time or space</strong>, when occurrences are rare and independent:</p>
<ul>
<li class="fragment">calls arriving at a switchboard in an hour;</li>
<li class="fragment">flaws in 14 feet of pine board;</li>
<li class="fragment">patients reaching an ER in 30 minutes;</li>
<li class="fragment"><strong>installs (postbacks) hitting Vungle’s API in a one-second window</strong>.</li>
</ul></li>
<li class="fragment"><p>There is <strong>no natural <span class="math inline">\(n\)</span></strong>: you are not counting successes out of a fixed number of trials; you are counting <strong>arrivals</strong> over an interval.</p></li>
</ul>
</section>
<section id="the-two-poisson-assumptions" class="slide level2 center">
<h2>The Two Poisson Assumptions</h2>
<p><br></p>
<ol type="1">
<li class="fragment">The probability of an occurrence is the <strong>same</strong> for any two intervals of equal length (a constant rate).</li>
<li class="fragment">Occurrences in <strong>non-overlapping</strong> intervals are <strong>independent</strong>.</li>
</ol>
<p><br></p>
<ul>
<li class="fragment"><p>One parameter governs everything: the <strong>mean number of occurrences per interval</strong>, <span class="math inline">\(\mu\)</span> (many texts write it <span class="math inline">\(\lambda\)</span>; we keep <span class="math inline">\(\mu\)</span>, the same mean symbol as everywhere else in the course).</p></li>
<li class="fragment"><p><strong>Vungle:</strong> at <span class="math inline">\(p \approx 0.0035\)</span> over 1,000 impressions, installs arrive at a mean rate <span class="math inline">\(\mu = np = 3.5\)</span> per burst. The rate is steady within a stable burst, and one install does not trigger another, so both assumptions hold.</p></li>
</ul>
</section>
<section id="the-poisson-probability-function" class="slide level2 center">
<h2>The Poisson Probability Function</h2>
<p><br></p>
<ul>
<li class="fragment">The probability of exactly <span class="math inline">\(x\)</span> occurrences in an interval with mean <span class="math inline">\(\mu\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
f(x) = \frac{\mu^x e^{-\mu}}{x!}, \qquad x = 0, 1, 2, \dots \qquad (e \approx 2.71828)
\]</span></p>
</div>
<ul>
<li class="fragment">A defining property: the mean <strong>and</strong> variance are <strong>both</strong> <span class="math inline">\(\mu\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(X) = \mu \qquad\qquad \text{Var}(X) = \mu \qquad\qquad \sigma = \sqrt{\mu}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>There is <strong>no upper limit</strong> on <span class="math inline">\(x\)</span>, but <span class="math inline">\(f(x)\)</span> shrinks fast; for large <span class="math inline">\(x\)</span> it rounds to zero.</p></li>
<li class="fragment"><p>(Excel calls the parameter <span class="math inline">\(\mu\)</span> its <em>mean</em> argument; some calculators and texts label the same number <span class="math inline">\(\lambda\)</span>.)</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-4" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">Mean equals variance, both just <span class="math inline">\(\mu\)</span>? With the Binomial I had two separate knobs. How can one number fix the spread too?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> it falls right out of the large-<span class="math inline">\(n\)</span>, small-<span class="math inline">\(p\)</span> setup. The Binomial variance is <span class="math inline">\(np(1-p)\)</span>; when <span class="math inline">\(p\)</span> is tiny, <span class="math inline">\((1-p) \approx 1\)</span>, so the variance collapses to <span class="math inline">\(np = \mu\)</span>, the same as the mean. For Vungle’s <span class="math inline">\(p = 0.0035\)</span> that approximation is excellent, which is why <span class="math inline">\(\mu = 3.5\)</span> alone pins down both the center and the spread of the install count.</p>
</div>
</div>
</section>
<section id="anchor-example-mercy-hospital" class="slide level2 center">
<h2>Anchor Example: Mercy Hospital</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Patients arrive at Mercy Hospital’s ER at <strong>6 per hour</strong> on weekend evenings. What is <span class="math inline">\(P(\text{exactly 4 arrivals in 30 minutes})\)</span>?</p></li>
<li class="fragment"><p>First <strong>rescale the rate</strong> to the interval: 6 per hour <span class="math inline">\(= 3\)</span> per half-hour, so <span class="math inline">\(\mu = 3\)</span>.</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
f(4) = \frac{3^4 e^{-3}}{4!} = \frac{81 \times 0.0498}{24} = 0.1680
\]</span></p>
</div>
<ul>
<li class="fragment">And the spread of arrivals: <span class="math inline">\(\text{Var}(X) = \mu = 3\)</span>, so <span class="math inline">\(\sigma = \sqrt{3} = 1.73\)</span> patients per half-hour.</li>
</ul>
</section>
<section id="mercy-hospital-the-full-distribution" class="slide level2 center">
<h2>Mercy Hospital: the Full Distribution</h2>

<img data-src="figs/poisson_pmf_mercy.png" class="quarto-figure quarto-figure-center r-stretch" style="width:72.0%"><ul>
<li>The whole distribution comes from the <strong>single</strong> number <span class="math inline">\(\mu = 3\)</span>: no <span class="math inline">\(n\)</span>, no <span class="math inline">\(p\)</span>.</li>
<li><strong>Watch the units:</strong> <span class="math inline">\(\mu\)</span> must match the interval. Six per hour and three per half-hour describe the <em>same</em> process at different scales.</li>
</ul>
</section>
<section id="a-question-that-often-comes-up-5" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If 6-per-hour and 3-per-half-hour are the “same process,” why did we have to switch to <span class="math inline">\(\mu = 3\)</span>? Couldn’t we just plug in <span class="math inline">\(\mu = 6\)</span>?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> no, because <span class="math inline">\(\mu\)</span> is the mean for the <strong>interval the question asks about</strong>, and the question was about <strong>30 minutes</strong>. Plug in <span class="math inline">\(\mu = 6\)</span> and Excel answers “4 arrivals in an <em>hour</em>,” a different event. The rule is one line: match <span class="math inline">\(\mu\)</span> to the window. For Vungle the same step turns a per-burst <span class="math inline">\(\mu = 3.5\)</span> into a per-second or per-day rate before you read off any tail.</p>
</div>
</div>
</section>
<section id="excel-poisson.dist" class="slide level2 center">
<h2>Excel: <code>POISSON.DIST</code></h2>
<p><br></p>
<ul>
<li class="fragment">Same TRUE/FALSE switch as the Binomial, but only <strong>one</strong> parameter (<span class="math inline">\(\mu\)</span>, the <em>mean</em> argument in Excel):</li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>You want</th>
<th>Excel</th>
<th>Returns</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(P(X = x)\)</span> (PMF)</td>
<td><code>=POISSON.DIST(x, mean, FALSE)</code></td>
<td>exact probability</td>
</tr>
<tr class="even">
<td><span class="math inline">\(P(X \leq x)\)</span> (CDF)</td>
<td><code>=POISSON.DIST(x, mean, TRUE)</code></td>
<td>cumulative probability</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(P(X \geq N)\)</span> (tail)</td>
<td><code>=1 - POISSON.DIST(N-1, mean, TRUE)</code></td>
<td>complement</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p><code>POISSON</code> (no dot) is the legacy alias.</p></li>
<li class="fragment"><p><strong>Mercy check:</strong> <code>=POISSON.DIST(4, 3, FALSE)</code> returns <code>0.1680</code>: the formula and Excel agree.</p></li>
</ul>
</section></section>
<section>
<section id="binomial-vs.-poisson" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Binomial vs.&nbsp;Poisson</h1>

</section>
<section id="the-poisson-approximation-to-the-binomial" class="slide level2 center">
<h2>The Poisson Approximation to the Binomial</h2>
<p><br></p>
<ul>
<li class="fragment">When <span class="math inline">\(n\)</span> is <strong>large</strong> and <span class="math inline">\(p\)</span> is <strong>small</strong>, the Binomial and the Poisson with <span class="math inline">\(\mu = np\)</span> are nearly identical:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\text{Binomial}(n, p) \;\approx\; \text{Poisson}(\mu = np) \qquad \text{for large } n,\; \text{small } p
\]</span></p>
</div>
<ul>
<li class="fragment"><p><strong>Rule of thumb:</strong> the approximation is excellent when <span class="math inline">\(n \geq 20\)</span> and <span class="math inline">\(p \leq 0.05\)</span> (some texts use <span class="math inline">\(np \leq 7\)</span>).</p></li>
<li class="fragment"><p>Vungle is the textbook case: <span class="math inline">\(n = 1000 \geq 20\)</span> and <span class="math inline">\(p = 0.0035 \leq 0.05\)</span>. So <span class="math inline">\(X_B \approx \text{Poisson}(3.5)\)</span>, and we can drop <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> and work with <strong>rate alone</strong>.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-6" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If the Poisson just approximates the Binomial here, isn’t it strictly worse? Why not always use the exact Binomial and skip the approximation?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> because in real ops you often <strong>do not have</strong> <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span>, only the rate. Vungle’s pipeline tracks “installs per second,” not “successes out of how many impressions,” so the Binomial’s two inputs are not even available; the Poisson’s single <span class="math inline">\(\mu\)</span> is. When you <em>do</em> have <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> and they are small, the two agree to three decimals (next slide), so you lose nothing by taking the simpler model.</p>
</div>
</div>
</section>
<section id="see-it-the-two-models-overlap" class="slide level2 center">
<h2>See It: The Two Models Overlap</h2>

<img data-src="figs/binom_vs_poisson.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><ul>
<li>Binomial(<span class="math inline">\(1000\)</span>, <span class="math inline">\(0.0035\)</span>) and Poisson(<span class="math inline">\(3.5\)</span>) agree to <strong>three decimals</strong> at every <span class="math inline">\(x\)</span>: the bars sit right on top of each other.</li>
</ul>
</section>
<section id="do-it-in-excel-binomial-vs.-poisson-side-by-side" class="slide level2 center">
<h2>Do It in Excel: Binomial vs.&nbsp;Poisson Side by Side</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">List the counts <span class="math inline">\(x = 0, 1, 2, \dots\)</span> in column A.</li>
<li class="fragment">Column B (Binomial): <code>=BINOM.DIST(A2, 1000, 0.0035, FALSE)</code>.</li>
<li class="fragment">Column C (Poisson): <code>=POISSON.DIST(A2, 3.5, FALSE)</code>.</li>
<li class="fragment">Column D: <code>=B2-C2</code> to see the gap; it stays under 0.001 at every <span class="math inline">\(x\)</span>.</li>
</ol>
<p>Poisson needs <strong>one</strong> input (<span class="math inline">\(\mu = 3.5\)</span>); Binomial needs <strong>two</strong> (<span class="math inline">\(n, p\)</span>); for rare events you often only know the rate.</p>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_binom_vs_poisson.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="which-model-should-you-reach-for" class="slide level2 center">
<h2>Which Model Should You Reach For?</h2>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Situation</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fixed number of trials <span class="math inline">\(n\)</span>, each success/failure at known <span class="math inline">\(p\)</span></td>
<td><strong>Binomial</strong></td>
</tr>
<tr class="even">
<td>Count of rare arrivals over an interval; no fixed <span class="math inline">\(n\)</span>; you know the <strong>rate</strong></td>
<td><strong>Poisson</strong></td>
</tr>
<tr class="odd">
<td>Large <span class="math inline">\(n\)</span>, small <span class="math inline">\(p\)</span> (e.g., installs over impressions)</td>
<td><strong>Either</strong> (Poisson is the simpler shortcut)</td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment">For Vungle’s capacity work, <strong>Poisson is the natural choice</strong>: postbacks arrive over a <em>time</em> window, and all engineering tracks is the <strong>mean rate</strong> <span class="math inline">\(\mu\)</span>, not a count of impressions.</li>
</ul>
</section></section>
<section>
<section id="the-vungle-pipeline-a-poisson-capacity-plan" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Vungle Pipeline: A Poisson Capacity Plan</h1>

</section>
<section id="installs-per-burst-as-a-poisson-process" class="slide level2 center">
<h2>Installs per Burst as a Poisson Process</h2>

<img data-src="figs/poisson_pmf_vungle.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><ul>
<li><span class="math inline">\(X_A \sim \text{Poisson}(4.0)\)</span> and <span class="math inline">\(X_B \sim \text{Poisson}(3.5)\)</span>.</li>
<li>A’s higher rate means <strong>heavier tails</strong>, so A overflows a fixed capacity more often than B.</li>
</ul>
</section>
<section id="the-capacity-tail-both-ways-agree" class="slide level2 center">
<h2>The Capacity Tail: Both Ways Agree</h2>
<p><br></p>
<ul>
<li class="fragment">The question that sizes the pipeline: <span class="math inline">\(P(X \geq 8)\)</span>, how often does a burst exceed a single worker’s capacity of 7?</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Algorithm</th>
<th style="text-align: right;">Binomial <span class="math inline">\(P(X \geq 8)\)</span></th>
<th style="text-align: right;">Poisson <span class="math inline">\(P(X \geq 8)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>B (<span class="math inline">\(\mu = 3.5\)</span>)</td>
<td style="text-align: right;">0.0265</td>
<td style="text-align: right;"><strong>0.0267</strong></td>
</tr>
<tr class="even">
<td>A (<span class="math inline">\(\mu = 4.0\)</span>)</td>
<td style="text-align: right;">0.0508</td>
<td style="text-align: right;"><strong>0.0511</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p>Both models give the <strong>same managerial answer</strong>: ~<strong>5%</strong> of A’s bursts and ~<strong>2.7%</strong> of B’s bursts need overflow capacity.</p></li>
<li class="fragment"><p>In Excel: <code>=1 - POISSON.DIST(7, 4, TRUE)</code> <span class="math inline">\(= 0.0511\)</span> for A.</p></li>
</ul>
</section>
<section id="scaling-up-from-burst-to-pipeline" class="slide level2 center">
<h2>Scaling Up: From Burst to Pipeline</h2>
<p><br></p>
<ul>
<li class="fragment">The <strong>rate scales with the interval</strong>, the Poisson workhorse property. If a burst is 1,000 impressions and A serves ~7.9M impressions/day:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\mu_{\text{day}} = \underbrace{\frac{7{,}900{,}000}{1{,}000}}_{7{,}900 \text{ bursts}} \times \underbrace{4.0}_{\mu \text{ per burst}} \approx 31{,}600 \text{ installs/day} \quad (\text{matches the data's} \approx 31{,}700)
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Want installs <strong>per second</strong>? Divide <span class="math inline">\(\mu\)</span> by 86,400. Want <strong>per hour</strong>? Multiply by 3,600. <strong>One parameter, any interval</strong>, no need to recount impressions.</p></li>
<li class="fragment"><p>That is why ops teams model arrivals as Poisson: provision for <span class="math inline">\(\mu\)</span> plus a tail buffer, and re-scale instantly as traffic grows.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-7" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If I double the interval, <span class="math inline">\(\mu\)</span> doubles. Does the tail probability <span class="math inline">\(P(X \geq N)\)</span> just double too?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> no, only <span class="math inline">\(\mu\)</span> scales linearly with the interval; the tail does <strong>not</strong>. Double the window and you must recompute <span class="math inline">\(P(X \geq N)\)</span> with the <strong>new</strong> <span class="math inline">\(\mu\)</span> from scratch, because both the center and the whole shape shift. For Vungle: a per-second <span class="math inline">\(\mu\)</span> and a per-hour <span class="math inline">\(\mu\)</span> are a clean multiply apart, but their capacity tails are two separate <code>POISSON.DIST</code> calls. Scaling the rate is free; the probability still needs the function.</p>
</div>
</div>
</section>
<section id="the-managers-takeaway-lecture-2" class="slide level2 center">
<h2>The Manager’s Takeaway (Lecture 2)</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> for rare events over an interval, the <strong>Poisson(<span class="math inline">\(\mu\)</span>)</strong> models the count from a single rate, and for Vungle’s tiny <span class="math inline">\(p\)</span> it gives the <strong>same capacity answer</strong> as the Binomial.</p></li>
<li class="fragment"><p><strong>One number:</strong> <span class="math inline">\(P(\geq 8 \text{ installs/burst}) \approx\)</span> <strong>0.051</strong> for A (Poisson <span class="math inline">\(\mu = 4\)</span>): provision a second worker for ~1 burst in 20.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> Poisson assumes a <strong>constant, independent</strong> rate. A viral spike breaks both assumptions: arrivals cluster, the true tail is <em>heavier</em> than Poisson predicts, and you under-provision. Monitor for over-dispersion (variance <span class="math inline">\(&gt;\)</span> mean).</p></li>
</ul>
</section>
<section id="todays-question-todays-answer-1" class="slide level2 center">
<h2>Today’s Question, Today’s Answer</h2>
<p><br></p>
<p><strong>The question (Lecture 2):</strong></p>
<blockquote>
<p><em>Is there a model that needs only the average rate, not the full <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span>, and does it give the same capacity answer?</em></p>
</blockquote>
<div class="fragment">
<p><br></p>
<p><strong>The answer we reached today:</strong></p>
<blockquote>
<p>Yes: the <strong>Poisson(<span class="math inline">\(\mu\)</span>)</strong> needs only <span class="math inline">\(\mu = np\)</span>. For B, $= $ <strong>3.5</strong>; the capacity tail $P(X ) = $ <strong>0.0267</strong> matches the Binomial’s <strong>0.0265</strong>, and for A both give <span class="math inline">\(\approx\)</span> <strong>0.051</strong>. For Vungle’s tiny <span class="math inline">\(p\)</span> the two models agree to three decimals, so you can plan from the <strong>rate alone</strong>.</p>
</blockquote>
</div>
</section></section>
<section>
<section id="wrap-up" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Wrap-up</h1>

</section>
<section id="discrete-distributions-on-one-page-the-vungle-bridge" class="slide level2 center">
<h2>Discrete Distributions on One Page: the Vungle Bridge</h2>
<div class="r-fit-text">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>Formula</th>
<th>Applied to Vungle</th>
<th>Excel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Expected value</td>
<td><span class="math inline">\(E(X) = \sum x\,f(x)\)</span></td>
<td>mean installs per burst</td>
<td><code>=SUMPRODUCT(x, f)</code></td>
</tr>
<tr class="even">
<td>Variance</td>
<td><span class="math inline">\(\sigma^2 = \sum (x-\mu)^2 f(x)\)</span></td>
<td>spread / risk of the count</td>
<td>formula cells</td>
</tr>
<tr class="odd">
<td>Covariance / corr.</td>
<td><span class="math inline">\(\sigma_{xy};\;\rho_{xy} = \sigma_{xy}/(\sigma_x \sigma_y)\)</span></td>
<td>do A and B move together?</td>
<td>formula cells</td>
</tr>
<tr class="even">
<td><strong>Binomial</strong></td>
<td><span class="math inline">\(f(x) = \binom{n}{x}p^x(1-p)^{n-x}\)</span></td>
<td>installs in <span class="math inline">\(n=1000\)</span> impressions, <span class="math inline">\(p=0.0035\)</span></td>
<td><code>=BINOM.DIST(x,n,p,0/1)</code></td>
</tr>
<tr class="odd">
<td>Binomial mean/var</td>
<td><span class="math inline">\(np,\; np(1-p)\)</span></td>
<td><span class="math inline">\(\mu_B = 3.5,\; \sigma_B = 1.87\)</span></td>
<td>(formula)</td>
</tr>
<tr class="even">
<td><strong>Poisson</strong></td>
<td><span class="math inline">\(f(x) = \mu^x e^{-\mu}/x!\)</span></td>
<td>installs as rare arrivals, <span class="math inline">\(\mu = 3.5\)</span></td>
<td><code>=POISSON.DIST(x,mean,0/1)</code></td>
</tr>
<tr class="odd">
<td>Poisson mean/var</td>
<td><span class="math inline">\(\mu,\; \mu\)</span></td>
<td><span class="math inline">\(\mu_B = \sigma^2_B = 3.5\)</span></td>
<td>(formula)</td>
</tr>
<tr class="even">
<td>Tail (capacity)</td>
<td><span class="math inline">\(P(X \geq N) = 1 - P(X \leq N{-}1)\)</span></td>
<td><span class="math inline">\(P(X_A \geq 8) \approx 0.051\)</span></td>
<td><code>=1-...DIST(N-1,...,1)</code></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="the-managers-takeaway" class="slide level2 center">
<h2>The Manager’s Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> a conversion rate plus a count structure (fixed <span class="math inline">\(n\)</span> → <strong>Binomial</strong>; rare arrivals → <strong>Poisson</strong>) gives the <strong>full probability distribution</strong> of installs, and every capacity question is a <strong>tail probability</strong>.</p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <span class="math inline">\(P(X \geq 8) \approx\)</span> <strong>0.051</strong> for Algorithm A bursts (about 1 in 20): the number that sizes the overflow buffer.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> both models assume a <strong>constant, independent</strong> rate; real traffic spikes (viral campaigns) cluster arrivals and fatten the tail, so re-estimate the rate and watch for over-dispersion.</p></li>
<li class="fragment"><p><strong>Practice with the real data:</strong> <code>data/vungle_daily.csv</code> → estimate <span class="math inline">\(p\)</span>; <code>data/vungle_discrete.xlsx</code> → reproduce the PMF/CDF tables with <code>BINOM.DIST</code> and <code>POISSON.DIST</code>.</p></li>
</ul>
</section>
<section id="team-sprint-your-group-case-lecture-2" class="slide level2 center">
<h2>⏱️ Team Sprint: Your Group Case (Lecture 2)</h2>
<div class="sprint">
<p><strong>Now it’s your group’s turn.</strong> Today’s in-class group case is posted on <strong>Brightspace</strong> (<em>Topic 05 Group Case, Lecture 2</em>): a separate business decision you make with today’s tools.</p>
<p><strong>What you’ll use:</strong> the <strong>Poisson</strong> model, <span class="math inline">\(E(X)=\text{Var}(X)=\mu\)</span>, and the capacity tail <span class="math inline">\(P(X \geq N)\)</span>. <strong>Excel:</strong> Analysis ToolPak with <code>POISSON.DIST(x, mean, FALSE/TRUE)</code>.</p>
<p><strong>Submit one PDF per group before you leave:</strong> your decision plus the numbers behind it.</p>
</div>
</section>
<section id="summary" class="slide level2 center">
<h2>Summary</h2>
<p>The points to carry out of this session:</p>
<ul>
<li>A <strong>random variable</strong> assigns a number to each outcome (discrete = counted, continuous = measured); a valid <strong>distribution</strong> has <span class="math inline">\(f(x) \geq 0\)</span>, <span class="math inline">\(\sum f(x) = 1\)</span>, with <span class="math inline">\(E(X) = \sum x f(x)\)</span> and <span class="math inline">\(\sigma^2 = \sum (x-\mu)^2 f(x)\)</span>.</li>
<li><strong>Covariance / correlation</strong> measure how two counts move together; with <span class="math inline">\(\rho_{xy} &lt; 1\)</span> the cross term in <span class="math inline">\(\text{Var}(wX + (1-w)Y)\)</span> shrinks total risk: that is <strong>diversification</strong>.</li>
<li>The <strong>Binomial</strong> counts successes in <span class="math inline">\(n\)</span> fixed Bernoulli trials: <span class="math inline">\(f(x) = \binom{n}{x}p^x(1-p)^{n-x}\)</span>, with <span class="math inline">\(\mu = np\)</span>, <span class="math inline">\(\sigma^2 = np(1-p)\)</span>.</li>
<li>The <strong>Poisson</strong> counts rare arrivals from one rate <span class="math inline">\(\mu\)</span>: <span class="math inline">\(f(x) = \mu^x e^{-\mu}/x!\)</span>, with <span class="math inline">\(\mu = \sigma^2\)</span>; for large <span class="math inline">\(n\)</span>, small <span class="math inline">\(p\)</span> it equals Binomial(<span class="math inline">\(np\)</span>), the Vungle case.</li>
<li><strong>Capacity = a tail probability:</strong> <span class="math inline">\(P(X \geq N) = 1 - P(X \leq N-1)\)</span>, computed in one Excel cell.</li>
<li><strong>Next time:</strong> we move from <strong>discrete counts</strong> to <strong>continuous measurements</strong>, the <strong>Normal</strong> distribution, and the question <em>“what is the probability eRPM exceeds $3.50?”</em></li>
<li><strong>Homework (individual):</strong> the Binomial and Poisson models are drilled on <strong>HW2</strong>, posted on Brightspace; run them yourself so you can check an analyst who uses them.</li>
</ul>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Thank you!</h1>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Business Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>