<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Professor: Davi Moreira">
  <title>QM 6700: Business Analytics –  QM 6700: Business Analytics </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-113b5beb2a57b2deea58feb1108e76b2.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="font-size: 100%;"> QM 6700: Business Analytics </span></h1>
  <p class="subtitle"><span style="font-size: 150%;"> Course Introduction &amp; Descriptive Statistics I </span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor: Davi Moreira 
</div>
</div>
</div>

</section>
<section>
<section id="welcome" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Welcome!</h1>

</section>
<section id="overview" class="slide level2 center">
<h2>Overview</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Introductions, logistics &amp; your group</li>
<li><strong>The semester roadmap: two cases, one job</strong></li>
<li><strong>Case Spotlight: A/B Testing at Vungle</strong></li>
<li>What is statistics? Where is it used?</li>
<li>The map: descriptive vs.&nbsp;inferential</li>
</ul>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Data, variables &amp; observations — the Vungle dataset</li>
<li>Data types &amp; scales of measurement</li>
<li>Study design: why Vungle ran an <em>experiment</em></li>
<li>A first look at the data in Excel (<code>Excel4stats</code>)</li>
</ul>
</div></div>
</section></section>
<section>
<section id="introductions" class="title-slide slide level1 center">
<h1>Introductions</h1>

</section>
<section id="instructor" class="slide level2 center">
<h2>Instructor</h2>
<div class="columns">
<div class="column" style="width: 40%; text-align: center; justify-content: center; align-items: center;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/davi_moreira_photo.JPG" class="quarto-figure quarto-figure-center" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="dcordeir@purdue.edu">dcordeir@purdue.edu</a></p>
<p><a href="https://davi-moreira.github.io/" class="uri">https://davi-moreira.github.io/</a></p>
</div><div class="column" style="width: 60%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li class="fragment">Clinical Assistant Professor in the Management Department at Purdue University;</li>
</ul>
<p><br></p>
<ul>
<li class="fragment">My academic work addresses Political Communication, Data Science, Text as Data, Artificial Intelligence, and Comparative Politics.</li>
</ul>
<p><br></p>
<ul>
<li class="fragment"><a href="https://blogs.worldbank.org/opendata/improving-how-we-measure-progress-community-biodiversity-conservation-projects-mozambique">M&amp;E Specialist consultant - World Bank (Brazil, Mozambique, Angola, and DRC)</a></li>
</ul>
</div></div>
</section>
<section id="instructors-passions" class="slide level2 center">
<h2>Instructor’s Passions</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/palmeiras_logo.png" class="quarto-figure quarto-figure-center" style="width:15.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/palmeiras_stadium.jpg" class="quarto-figure quarto-figure-center" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
<center>
<div style="font-size: 80%;">
<p><a href="https://www.youtube.com/watch?v=FCebgeX_3hI&amp;t=89s">The Most Exciting Game in History - Video</a></p>
</div>
</center>
<p><br></p>
<p><br></p>
</section>
<section id="instructors-passions-1" class="slide level2 center">
<h2>Instructor’s Passions</h2>

<img data-src="figs/carnaval_olinda.jpg" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"><center>
<a href="https://www.nytimes.com/2024/02/13/world/americas/brazil-carnival-john-travolta.html">NYT - How John Travolta Became the Star of Carnival</a><a href="https://www.nytimes.com/video/world/americas/100000009311331/the-star-of-this-carnival-is-a-giant-john-travolta-puppet.html?auth=login-google1tap&amp;login=google1tap">-Video.</a>
</center>
<p><br></p>
</section>
<section id="students" class="slide level2 center">
<h2>Students</h2>
<p><br></p>
<ul>
<li class="fragment">It is your turn! - 5 minutes</li>
</ul>
<p><br></p>
<ul>
<li class="fragment">Introduce yourself to the colleague on your left or right. Then ask them to rate, on a scale from 1 (not at all) to 5 (a lot), how much they like statistics.</li>
</ul>
</section></section>
<section>
<section id="course-overview-and-logistics" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Course Overview and Logistics</h1>

</section>
<section id="course-overview-and-logistics-1" class="slide level2 center">
<h2>Course Overview and Logistics</h2>
<ul>
<li class="fragment"><p><strong>Materials</strong>:</p>
<ul>
<li class="fragment"><p>Brightspace</p></li>
<li class="fragment"><p><a href="https://davi-moreira.github.io/2026F_business_analytics_qm670" target="_blank">Course Webpage</a></p></li>
</ul></li>
<li class="fragment"><p><strong>Syllabus</strong></p></li>
<li class="fragment"><p><strong>Slides</strong></p></li>
<li class="fragment"><p><strong>Podcast</strong></p></li>
<li class="fragment"><p><strong>Videos</strong></p></li>
<li class="fragment"><p><strong>Supplementary Material</strong></p></li>
<li class="fragment"><p><strong>Schedule</strong></p></li>
</ul>
</section>
<section id="how-to-succeed-in-this-course" class="slide level2 center">
<h2>How to Succeed in This Course</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Start from zero, by design.</strong> No prior statistics is assumed — this is your first analytics course, and we build every method up from a real business decision.</p></li>
<li class="fragment"><p><strong>Keep up every week.</strong> Statistics builds on itself — today’s vocabulary becomes next week’s formulas. Falling behind compounds.</p></li>
<li class="fragment"><p><strong>Work with your group.</strong> In-class cases are solved and submitted together; homework you do on your own. Explaining a method to a groupmate is the fastest way to learn it.</p></li>
<li class="fragment"><p><strong>You’re the decision-maker.</strong> Every method we learn answers a call <em>you</em> have to make. Learn each one well enough to check an analyst’s work, and always ask: <em>what decision does this number support, and would I stake money on it?</em></p></li>
<li class="fragment"><p><strong>Use Excel from day one.</strong> Install the Analysis ToolPak this week and open the course dataset — you will use it all semester.</p></li>
</ul>
</section>
<section id="how-the-class-works" class="slide level2 center">
<h2>How the Class Works</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Your group:</strong> you’ll be randomly assigned to a <strong>fixed group</strong> this week and work every in-class case with it.</p></li>
<li class="fragment"><p><strong>Submit before you leave:</strong> each class your group turns in one deliverable on <strong>Brightspace</strong> — your decision plus the evidence. A grader scores it.</p></li>
<li class="fragment"><p><strong>Bring a laptop</strong> with <strong>Excel + the Analysis ToolPak</strong> to every session.</p></li>
<li class="fragment"><p><strong>Homework is individual:</strong> three problem sets that drill the mechanics, posted on Brightspace.</p></li>
</ul>
</section>
<section id="how-every-class-runs" class="slide level2 center">
<h2>How Every Class Runs</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/lecture_dynamic.png" class="quarto-figure quarto-figure-center" style="width:92.0%"></p>
</figure>
</div>
<ul>
<li>Same five beats every meeting. The one that counts for your grade is the <strong>Team Sprint</strong> — your group’s decision, submitted before you leave.</li>
</ul>
</section></section>
<section>
<section id="textbook-software" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Textbook &amp; Software</h1>

</section>
<section id="textbook-materials" class="slide level2 center">
<h2>Textbook &amp; Materials</h2>
<div class="columns">
<div class="column" style="width: 35%; text-align: center; justify-content: center; align-items: center;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/sbe_book.jpg" class="quarto-figure quarto-figure-center" style="width:72.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width: 65%; justify-content: center; align-items: center;">
<p><strong><em>Statistics for Business and Economics</em> (SBE), 14th edition</strong></p>
<p>Anderson · Sweeney · Williams · Camm · Cochran — Cengage, 2020 · ISBN-13 978-1337901062</p>
<p><a href="https://www.cengage.com/c/statistics-for-business-economics-14e-anderson/9781337901062/" target="_blank">View on Cengage</a></p>
<p><br></p>
<ul>
<li>The course <strong>schedule</strong> lists the readings for each topic.</li>
<li><strong>Software:</strong> Excel with the <strong>Analysis ToolPak</strong> — every worked example is Excel-first.</li>
</ul>
</div></div>
</section></section>
<section>
<section id="survey" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Survey</h1>

</section>
<section id="survey-1" class="slide level2 center" data-background-color="#cfb991">
<h2>Survey</h2>

<img data-src="figs/qrcode_review_survey.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"><center>
<a href="https://forms.office.com/r/3R2VwPJAzA" target="_blank">Attendance and Participation</a><br>10 min
</center>
</section></section>
<section>
<section id="your-semester-two-cases-one-job" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Your Semester: Two Cases, One Job</h1>

</section>
<section id="youre-the-decision-maker-two-cases-to-crack" class="slide level2 center">
<h2>You’re the Decision-Maker — Two Cases to Crack</h2>
<p><br></p>
<ul>
<li class="fragment">This course puts <strong>you in the decision-maker’s seat</strong>: the manager, CEO, or owner who has to act. You’ll work in a <strong>fixed group</strong> (assigned this week), cracking real cases in class and judging the analysis behind every call.</li>
</ul>
<div class="fragment">
<ul>
<li class="fragment"><strong>① Vungle A/B — Topics 1–9 (up first).</strong> A mobile ad-tech startup asking <em>roll out algorithm B, or keep A?</em> You’ll learn to <strong>describe, quantify uncertainty, and test</strong> so you can judge that claim before betting the company on it.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li class="fragment"><strong>② Auto-parts retail — Topics 10–11.</strong> A 45-store chain asking <em>where should the next dollar go?</em> You’ll <strong>evaluate the analyst’s model</strong> that predicts store sales, then decide where to invest.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li class="fragment"><strong>Every class:</strong> your group works the case live and <strong>submits its call before you leave</strong> (graded). <strong>Homework</strong> is separate and <strong>individual</strong> — problem sets that drill the mechanics.</li>
</ul>
</div>
</section>
<section id="the-roadmap-which-case-which-week" class="slide level2 center">
<h2>The Roadmap: Which Case, Which Week</h2>
<p>Every case runs the same path: <strong>describe → quantify the uncertainty → test → predict.</strong> You crack it in your group and submit before you leave; three <strong>individual</strong> homeworks build the mechanics:</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/course_roadmap.png" class="quarto-figure quarto-figure-center" style="width:72.0%"></p>
</figure>
</div>
</section></section>
<section>
<section id="case-spotlight-ab-testing-at-vungle" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Case Spotlight: A/B Testing at Vungle</h1>

</section>
<section id="meet-vungle-one-decision-30-days-of-data" class="slide level2 center">
<h2>Meet Vungle: One Decision, 30 Days of Data</h2>
<p><br></p>
<ul>
<li class="fragment"><p><a href="https://en.wikipedia.org/wiki/Liftoff_Mobile">Vungle</a> is a mobile ad-tech startup: it serves 15-second video ads inside other apps and earns revenue mainly when a viewer <strong>installs</strong> the advertised app.</p></li>
<li class="fragment"><p>The metric that pays the bills is <strong>eRPM</strong> — effective revenue per 1,000 impressions.</p></li>
<li class="fragment"><p>In June 2014, two analysts built a new ad-serving algorithm (<strong>B</strong>) and ran it head-to-head against the current one (<strong>A</strong>) for the whole month.</p></li>
<li class="fragment"><p><strong>Your call as Vungle’s CEO:</strong> <em>roll out B to all advertisers, or stay with A?</em></p></li>
<li class="fragment"><p>We will use this one decision (<em>is B better than A?</em>) to motivate <strong>every</strong> tool in this course.</p></li>
</ul>
</section>
<section id="the-data-behind-the-decision" class="slide level2 center">
<h2>The Data Behind the Decision</h2>

<img data-src="figs/vungle_funnel.png" class="quarto-figure quarto-figure-center r-stretch" style="width:78.0%"><ul>
<li>Each ad <strong>impression</strong> can become a completed view, then a click, then an <strong>install</strong>. That chain is the <em>conversion funnel</em>.</li>
<li>30 days, both algorithms, the full funnel — that is the dataset <code>vungle_daily.csv</code> we will analyze all term.</li>
</ul>
</section>
<section id="the-tempting-answer-and-why-it-is-not-enough" class="slide level2 center">
<h2>The Tempting Answer — and Why It Is Not Enough</h2>
<p><br></p>
<ul>
<li class="fragment"><p>A manager glances at the data: <em>“B’s average daily eRPM was <strong>$3.46</strong> vs.&nbsp;A’s <strong>$3.35</strong> — so roll out B!”</em></p></li>
<li class="fragment"><p>Not so fast. Before you can bet the company on that $0.11 gap, you have to ask:</p>
<ul>
<li class="fragment">Is $0.11 a <strong>real</strong> difference, or just day-to-day <strong>noise</strong>?</li>
<li class="fragment">Is <strong>30 days</strong> enough to generalize to all future traffic?</li>
<li class="fragment">What <strong>kind</strong> of data is this, and which statistics are even <strong>valid</strong> to compute?</li>
</ul></li>
<li class="fragment"><p>Answering those is the job of this course. <strong>Today we start at the foundation: what is this data?</strong></p></li>
</ul>
</section></section>
<section>
<section id="what-is-statistics" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>What is Statistics?</h1>

</section>
<section id="what-is-statistics-1" class="slide level2 center">
<h2>What is Statistics?</h2>
<div class="columns">
<div class="column" style="width: 60%; text-align: center; justify-content: center; align-items: center;">
<p><br></p>
<p><br></p>
<p><br></p>
<blockquote>
<p>“Without data, you’re just another person with an opinion.” – W. Edwards Deming</p>
</blockquote>
</div><div class="column" style="width: 40%; text-align: center; justify-content: center; align-items: center;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/w_edwards_deming.jpg" class="quarto-figure quarto-figure-center" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>W. Edwards Deming</p>
<p><a href="https://en.wikipedia.org/wiki/W._Edwards_Deming">Wiki</a></p>
</div></div>
</section>
<section id="what-is-statistics-2" class="slide level2 center">
<h2>What is Statistics?</h2>
<p><br></p>
<p>Statistics is the <strong>science of collecting, organizing, analyzing, interpreting, and presenting data to make informed business decisions</strong>.</p>
<p><br></p>
<ul>
<li class="fragment"><p>It turns raw numbers, like Vungle’s 30 days of eRPM, into a defensible answer to a manager’s question.</p></li>
<li class="fragment"><p>The goal is always the same: <strong>reduce uncertainty enough to act.</strong></p></li>
</ul>
</section>
<section id="where-is-statistics-applied-in-business" class="slide level2 center">
<h2>Where Is Statistics Applied in Business?</h2>
<ul>
<li><p><strong>Accounting</strong> — audit sampling to test whether reported figures are accurate.</p></li>
<li><p><strong>Finance</strong> — estimating the return and risk of portfolios; pricing default risk.</p></li>
<li><p><strong>Marketing</strong> — consumer surveys, A/B testing ad creative, demand forecasting.</p></li>
<li><p><strong>Production / Operations</strong> — quality control, process design, capacity planning.</p></li>
<li><p><strong>Human Resources</strong> — recruiting analytics, salary benchmarking, retention modeling.</p></li>
</ul>
</section>
<section id="the-map-how-statistical-analysis-works" class="slide level2 center">
<h2>The Map: How Statistical Analysis Works</h2>

<img data-src="figs/stat_analysis_scheme.png" class="quarto-figure quarto-figure-center r-stretch" style="width:82.0%"></section>
<section id="descriptive-vs.-inferential-statistics" class="slide level2 center">
<h2>Descriptive vs.&nbsp;Inferential Statistics</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Descriptive statistics</strong> — tabular, graphical, and numerical methods that <strong>summarize</strong> the data you have (means, charts, tables).</p></li>
<li class="fragment"><p><strong>Inferential statistics</strong> — using <strong>sample</strong> data to draw conclusions or make decisions about a larger <strong>population</strong>.</p></li>
<li class="fragment"><p>Classify each Vungle statement:</p></li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Statement</th>
<th>Descriptive or Inferential?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“Over the 30 test days, B’s mean eRPM was $3.46.”</td>
<td><strong>Descriptive</strong> (summarizes the sample)</td>
</tr>
<tr class="even">
<td>“If rolled out to all traffic, B will earn more than A.”</td>
<td><strong>Inferential</strong> (a claim about the population)</td>
</tr>
<tr class="odd">
<td>“26 of 30 days favored B.”</td>
<td><strong>Descriptive</strong></td>
</tr>
<tr class="even">
<td>“B’s true conversion rate differs from A’s.”</td>
<td><strong>Inferential</strong></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="roadmap-what-descriptive-covers" class="slide level2 center">
<h2>Roadmap: What “Descriptive” Covers</h2>
<p><br></p>
<p>The next topic builds five summary lenses — each with an Excel tool:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Lens</th>
<th>Question it answers</th>
<th>Tool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Location</strong></td>
<td>Where is the center?</td>
<td>mean, median — summary statistics</td>
</tr>
<tr class="even">
<td><strong>Variability</strong></td>
<td>How spread out?</td>
<td>standard deviation, range</td>
</tr>
<tr class="odd">
<td><strong>Shape</strong></td>
<td>Symmetric or skewed?</td>
<td>histogram, box plot</td>
</tr>
<tr class="even">
<td><strong>Empirical rule</strong></td>
<td>How much falls near the mean?</td>
<td>68–95–99.7%</td>
</tr>
<tr class="odd">
<td><strong>Association</strong></td>
<td>Do two variables move together?</td>
<td>scatter plot, correlation</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="data-and-statistics" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Data and Statistics</h1>

</section>
<section id="elements-variables-and-observations" class="slide level2 center">
<h2>Elements, Variables, and Observations</h2>

<img data-src="figs/variables_observations.png" class="quarto-figure quarto-figure-center r-stretch" style="width:28.0%"><ul>
<li>An <strong>element</strong> is the entity on which data are collected.</li>
<li>A <strong>variable</strong> is a characteristic of interest for the elements.</li>
<li>An <strong>observation</strong> is the set of measurements for one element.</li>
<li>A data set with <span class="math inline">\(n\)</span> elements has <span class="math inline">\(n\)</span> observations; total values = elements × variables.</li>
</ul>
</section>
<section id="read-the-data-before-you-trust-the-analysis" class="slide level2 center">
<h2>Read the Data Before You Trust the Analysis</h2>
<p><br></p>
<ul>
<li class="fragment">A recommendation is only as good as the data under it, so a sharp manager looks first. Here is a slice of <code>vungle_daily.csv</code>, algorithms interleaved by day:</li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>algorithm</th>
<th>date</th>
<th style="text-align: right;">impressions</th>
<th style="text-align: right;">completes</th>
<th style="text-align: right;">clicks</th>
<th style="text-align: right;">installs</th>
<th style="text-align: right;">erpm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>2014-06-01</td>
<td style="text-align: right;">6,777,407</td>
<td style="text-align: right;">5,978,434</td>
<td style="text-align: right;">345,309</td>
<td style="text-align: right;">31,119</td>
<td style="text-align: right;">3.327</td>
</tr>
<tr class="even">
<td>B</td>
<td>2014-06-01</td>
<td style="text-align: right;">569,044</td>
<td style="text-align: right;">499,235</td>
<td style="text-align: right;">28,035</td>
<td style="text-align: right;">2,111</td>
<td style="text-align: right;">2.953</td>
</tr>
<tr class="odd">
<td>A</td>
<td>2014-06-02</td>
<td style="text-align: right;">6,004,310</td>
<td style="text-align: right;">5,331,727</td>
<td style="text-align: right;">299,732</td>
<td style="text-align: right;">24,601</td>
<td style="text-align: right;">2.943</td>
</tr>
<tr class="even">
<td>B</td>
<td>2014-06-02</td>
<td style="text-align: right;">505,963</td>
<td style="text-align: right;">447,695</td>
<td style="text-align: right;">24,621</td>
<td style="text-align: right;">1,713</td>
<td style="text-align: right;">2.587</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<ul>
<li class="fragment"><strong>Element</strong> = one algorithm-day (60 of them). <strong>Variables</strong> = the 7 columns. <strong>One observation</strong> = one row. Total values = <strong>60 × 7 = 420</strong>.</li>
</ul>
</div>
</section>
<section id="data-types" class="slide level2 center">
<h2>Data Types</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<p><strong>Categorical (Qualitative) Data</strong></p>
<ul>
<li>Labels or names that identify an attribute of each element</li>
<li>Use the <strong>nominal</strong> or <strong>ordinal</strong> scale</li>
<li>Can be numeric or non-numeric</li>
<li>Only limited arithmetic is meaningful (counts, proportions)</li>
</ul>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<p><strong>Quantitative Data</strong></p>
<ul>
<li>Indicate <strong>how many</strong> or <strong>how much</strong> — always numeric</li>
<li><strong>Discrete</strong>: counts (how many) — e.g., installs</li>
<li><strong>Continuous</strong>: measurements (how much) — e.g., eRPM</li>
<li>Ordinary arithmetic (+, −, ×, ÷) is meaningful</li>
</ul>
</div></div>
</section>
<section id="data-types-examples" class="slide level2 center">
<h2>Data Types: Examples</h2>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 29%">
<col style="width: 26%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Categorical: Nominal</th>
<th>Categorical: Ordinal</th>
<th>Quantitative: Continuous or Discrete</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ad algorithm (A/B)</td>
<td>Satisfaction Level</td>
<td>eRPM (revenue / 1,000 impr.)</td>
</tr>
<tr class="even">
<td>Vehicle Type</td>
<td>Education Level</td>
<td>Number of Installs</td>
</tr>
<tr class="odd">
<td>Music Genre</td>
<td>Customer Feedback</td>
<td>Revenue</td>
</tr>
<tr class="even">
<td>Nationality</td>
<td>Job Position</td>
<td>Product Weight</td>
</tr>
<tr class="odd">
<td>Operating System</td>
<td>Priority Level</td>
<td>Market Share</td>
</tr>
</tbody>
</table>
<p><br></p>
<div class="r-fit-text">
<ul>
<li class="fragment"><strong>Nominal</strong> categorizes with no inherent order (Vungle’s <code>algorithm</code>: A vs.&nbsp;B).</li>
<li class="fragment"><strong>Ordinal</strong> categorizes with a meaningful order but no consistent gap between levels.</li>
<li class="fragment"><strong>Quantitative</strong> is numeric — <em>discrete</em> values are countable (<code>installs</code>); <em>continuous</em> values can take any value in a range (<code>erpm</code>).</li>
</ul>
</div>
</section>
<section id="scales-of-measurement" class="slide level2 center">
<h2>Scales of Measurement</h2>

<img data-src="figs/scale_measurement.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"></section>
<section id="scales-of-measurement-1" class="slide level2 center">
<h2>Scales of Measurement</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<div class="r-fit-text">
<ol type="1">
<li><strong>Categorical Data</strong> — sortable into groups.
<ul>
<li><strong>Nominal</strong>: no inherent order (gender, car type, nationality, <strong>ad algorithm</strong>).</li>
<li><strong>Ordinal</strong>: a meaningful order, but no consistent difference between levels (satisfaction level; education level; job rank).</li>
</ul></li>
</ol>
</div>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ol start="2" type="1">
<li><strong>Quantitative Data</strong> — measured numerically.
<ul>
<li><strong>Interval</strong>: meaningful differences, <strong>no true zero</strong> (temperature in °C/°F).</li>
<li><strong>Ratio</strong>: meaningful differences <strong>and a true zero</strong> (height, weight, revenue, <strong>eRPM</strong>, <strong>installs</strong>).</li>
</ul></li>
</ol>
</div></div>
</section>
<section id="classify-vungles-variables" class="slide level2 center">
<h2>Classify Vungle’s Variables</h2>
<p><br></p>
<ul>
<li class="fragment">Before any analysis, audit every column — because <strong>the scale determines which statistics are valid</strong>:</li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Type</th>
<th>Scale</th>
<th>What you may compute</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>algorithm</code></td>
<td>Categorical</td>
<td>Nominal</td>
<td>counts, proportions — <strong>not</strong> a mean</td>
</tr>
<tr class="even">
<td><code>date</code></td>
<td>Categorical (ordered)</td>
<td>Ordinal / Interval</td>
<td>ordering, time gaps</td>
</tr>
<tr class="odd">
<td><code>impressions</code>, <code>completes</code>, <code>clicks</code>, <code>installs</code></td>
<td>Quantitative — discrete</td>
<td>Ratio</td>
<td>counts, sums, means, rates</td>
</tr>
<tr class="even">
<td><code>erpm</code></td>
<td>Quantitative — continuous</td>
<td>Ratio</td>
<td>mean, SD, t-tests — the primary KPI</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<ul>
<li class="fragment">Asking for the “average <code>algorithm</code>” is meaningless; asking for the “average <code>erpm</code>” is the whole point. <strong>Scale sets your toolbox.</strong></li>
</ul>
</div>
</section>
<section id="where-data-comes-from" class="slide level2 center">
<h2>Where Data Comes From</h2>
<p><br></p>
<ul>
<li><p><strong>Existing sources</strong> — internal records (Vungle’s ad server logs), public/government databases, industry reports.</p></li>
<li><p><strong>Collection by study:</strong></p>
<ul>
<li><strong>Observational</strong> — record what happens without intervening (a customer survey).</li>
<li><strong>Experimental</strong> — set the conditions on purpose, then measure (Vungle <em>assigns</em> traffic to A or B).</li>
</ul></li>
<li><p><strong>Cross-sectional</strong> — many elements at <strong>one</strong> point in time.</p></li>
<li><p><strong>Time series</strong> — <strong>one</strong> element across <strong>many</strong> time periods.</p></li>
</ul>
</section>
<section id="cross-sectional-vs.-time-series-the-vungle-data" class="slide level2 center">
<h2>Cross-Sectional vs.&nbsp;Time Series — the Vungle Data</h2>
<p><br></p>
<ul>
<li><p>On any single day, comparing <strong>A vs.&nbsp;B</strong> is a <strong>cross-sectional</strong> snapshot (two entities, one moment).</p></li>
<li><p>Tracking <strong>one algorithm across the 30 days</strong> is a <strong>time series</strong>.</p></li>
<li><p>The full dataset is a <strong>panel</strong> — repeated cross-sections over time.</p></li>
</ul>

<img data-src="figs/time_series.png" class="quarto-figure quarto-figure-center r-stretch" style="width:42.0%"></section></section>
<section>
<section id="study-design" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Study Design</h1>

</section>
<section id="observational-vs.-experimental-studies" class="slide level2 center">
<h2>Observational vs.&nbsp;Experimental Studies</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<p><strong>Observational</strong></p>
<p>In an observational study, no attempt is made to control the variables of interest. A survey is the classic example.</p>
<p><br></p>
<blockquote>
<p>Researchers watch a random sample of Walmart shoppers and record time in store, gender, and amount spent, <em>without ever intervening</em>.</p>
</blockquote>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<p><strong>Experimental</strong></p>
<p>In an experiment, the variable of interest is identified, then its levels are <strong>set and controlled</strong>, so we can see how they influence an outcome.</p>
<p><br></p>
<blockquote>
<p>The 1954 Salk polio-vaccine trial randomly assigned nearly two million children to vaccine or placebo. It is the largest experiment ever run.</p>
</blockquote>
</div></div>
</section>
<section id="vungle-ran-an-experiment-so-we-can-say-caused" class="slide level2 center">
<h2>Vungle Ran an Experiment — So We Can Say “Caused”</h2>
<p><br></p>
<ul>
<li class="fragment"><p>The <code>algorithm</code> column is the <strong>treatment</strong>: each impression was randomly assigned to A or B (by an MD5 hash) <strong>on the same days</strong>.</p></li>
<li class="fragment"><p>Random assignment balances everything else (same market, same advertisers, same weekends), so the only systematic difference is the algorithm.</p></li>
<li class="fragment"><p>That is what licenses <strong>causal</strong> language: <em>“B <strong>caused</strong> higher eRPM,”</em> not merely <em>“B was associated with higher eRPM.”</em></p></li>
<li class="fragment"><p><strong>Payoff:</strong> only an <strong>experiment</strong> supports a causal claim. An observational “B-days looked better” could be confounded; Vungle’s design rules that out.</p></li>
</ul>
</section>
<section id="random-assignment-vs.-random-sampling" class="slide level2 center">
<h2>Random Assignment vs.&nbsp;Random Sampling</h2>
<p><br></p>

<img data-src="figs/random_assignment_sampling.png" class="quarto-figure quarto-figure-center r-stretch" style="width:50.0%"><ul>
<li><strong>Random sampling</strong> (<em>who gets into the study</em>) supports generalizing to the population.</li>
<li><strong>Random assignment</strong> (<em>who gets which treatment</em>) supports causal comparison.</li>
</ul>
</section></section>
<section>
<section id="descriptive-statistics" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Descriptive Statistics</h1>

</section>
<section id="summarizing-and-presenting-data" class="slide level2 smaller center">
<h2>Summarizing and Presenting Data</h2>
<p><br></p>

<img data-src="figs/steve-jobs-pie.jpg" class="quarto-figure quarto-figure-center r-stretch" style="width:50.0%"><p><br></p>
<center>
<a href="https://paragraft.wordpress.com/2008/06/03/the-chart-junk-of-steve-jobs/">June 9th Apple CEO Steve Jobs - Post</a>
</center>
</section>
<section id="summarizing-and-presenting-data-1" class="slide level2 smaller center">
<h2>Summarizing and Presenting Data</h2>

<img data-src="figs/pie-vs-bar.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><p><br></p>
<center>
<a href="https://stats.stackexchange.com/questions/8974/problems-with-pie-charts">Problems with pie charts - Post</a>
</center>
</section>
<section id="a-first-look-at-erpm" class="slide level2 center">
<h2>A First Look at eRPM</h2>

<img data-src="figs/vungle_erpm_box.png" class="quarto-figure quarto-figure-center r-stretch" style="width:55.0%"><ul>
<li>A picture already tells a story: <strong>B’s mean is higher</strong> (white diamonds), but B is <strong>more spread out</strong> — a hint that “B is better” may not be the whole truth.</li>
<li>Describing is step one; <em>deciding</em> whether that gap is real comes later (Topics 7–9).</li>
</ul>
</section>
<section id="measures-of-location-the-mean" class="slide level2 center">
<h2>Measures of Location: the Mean</h2>
<p><br></p>
<ul>
<li class="fragment">The first job of <em>describing</em> is finding the <strong>center</strong>. The workhorse is the <strong>mean</strong> — add the values, divide by the count:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{x} = \frac{\sum_{i=1}^{n} x_i}{n}
\]</span></p>
</div>
<div class="fragment">
<ul>
<li class="fragment">Vungle’s 30-day mean eRPM: <strong>A = $3.347</strong>, <strong>B = $3.459</strong> — B’s center sits <strong>$0.11 higher</strong>.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li class="fragment">That $3.459 is a <strong>point estimate</strong> of B’s <em>true</em> mean eRPM — the number we will later put to the test.</li>
</ul>
</div>
</section>
<section id="median-mode-and-when-to-use-which" class="slide level2 center">
<h2>Median &amp; Mode — and When to Use Which</h2>
<p><br></p>
<ul>
<li><strong>Median</strong> — the middle value (50th percentile); unmoved by outliers. Vungle: A median <strong>$3.327</strong>, B <strong>$3.434</strong>. Mean ≈ median ⟹ the eRPM distribution is roughly <strong>symmetric</strong>.</li>
<li><strong>Mode</strong> — the most frequent value; the only center valid for <strong>categorical</strong> data (e.g., the most-served <code>algorithm</code>). For continuous eRPM every value is distinct, so the mode says nothing.</li>
<li><strong>Rule of thumb:</strong> report the <strong>mean</strong> for symmetric data, the <strong>median</strong> when it is skewed or has outliers.</li>
</ul>
</section>
<section id="your-excel-toolkit-the-analysis-toolpak" class="slide level2 center">
<h2>Your Excel Toolkit: the Analysis ToolPak</h2>
<p><br></p>

<img data-src="figs/excel.png" class="quarto-figure quarto-figure-center r-stretch" style="width:12.0%"><center>
<code>data/vungle_daily.xlsx</code>
</center>
<p><br></p>
<ul>
<li class="fragment"><p>Install it once: <strong>File → Options → Add-ins → Analysis ToolPak</strong> (and Analysis ToolPak-VBA) <strong>→ Go</strong>.</p></li>
<li class="fragment"><p>Then every analysis lives under <strong>Data → Data Analysis</strong>.</p></li>
<li class="fragment"><p>Do this <strong>this week</strong> with <code>vungle_daily.xlsx</code> open — it is the dataset for the whole term.</p></li>
</ul>
</section>
<section id="teaser-descriptive-statistics-on-erpm" class="slide level2 center">
<h2>Teaser: Descriptive Statistics on eRPM</h2>
<div class="columns">
<div class="column" style="width:42%;">
<p><br></p>
<p><strong>Data → Data Analysis →<br> Descriptive Statistics</strong></p>
<ul>
<li>Input Range: the <code>erpm</code> values for Algorithm A</li>
<li>check <strong>Summary statistics</strong></li>
</ul>
<p><br></p>
<p>The mean eRPM for A is <strong>$3.347</strong>. Every row of this panel (median, SD, skewness) is a <em>descriptive</em> measure we unpack in <strong>Topic 2</strong>.</p>
</div><div class="column" style="width:58%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_desc_erpm.png" class="quarto-figure quarto-figure-center" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="team-sprint-pressure-test-the-analysts-claim" class="slide level2 center">
<h2>⏱️ Team Sprint — Pressure-Test the Analyst’s Claim</h2>
<div class="sprint">
<p><strong>You’re the management team.</strong> An analyst’s memo lands: <em>“B’s average eRPM beat A’s, so roll it out.”</em> Before you act on it, check it.</p>
<p><strong>Data:</strong> <code>data/vungle_daily.xlsx</code> · <strong>Time:</strong> ~12 min</p>
<ol type="1">
<li><strong>Reproduce it:</strong> with the ToolPak’s <em>Descriptive Statistics</em>, compute the <strong>mean and median eRPM for A and for B</strong> yourself. Does the analyst’s headline hold?</li>
<li><strong>Audit the inputs:</strong> name the elements, variables, and the <strong>type &amp; scale</strong> of <code>algorithm</code> and <code>erpm</code>, so you know which numbers are even valid to compare.</li>
<li><strong>Interrogate it:</strong> how big is B’s edge? Name <strong>two reasons</strong> it might not survive scrutiny (sample size, spread, traffic, the metric itself).</li>
</ol>
<p><strong>Submit before you leave (group, 1 slide):</strong> your <strong>call</strong> (roll out, wait, or send it back) plus the <strong>two weaknesses</strong> you would put to the analyst.</p>
</div>
</section>
<section id="debrief-back-to-the-decision" class="slide level2 center">
<h2>Debrief — Back to the Decision</h2>
<p><br></p>
<ul>
<li class="fragment"><p>We can now <strong>describe</strong> the data cleanly: A’s mean eRPM is <strong>$3.35</strong>, B’s is <strong>$3.46</strong>, over 30 carefully-designed experimental days.</p></li>
<li class="fragment"><p>We <strong>cannot yet</strong> say whether B is <em>really</em> better for all future traffic — that is <strong>inference</strong>, and it needs the tools in Topics 7–9.</p></li>
<li class="fragment"><p><strong>Your call today:</strong> <em>not yet.</em> You can describe B’s edge, but approving a company-wide roll-out needs an inference test, and that is exactly what you will demand from your analyst in Topics 7–9.</p></li>
</ul>
</section></section>
<section>
<section id="statistical-inference" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Statistical Inference</h1>

</section>
<section id="statistical-inference-1" class="slide level2 center">
<h2>Statistical Inference</h2>
<p><br></p>
<div class="columns">
<div class="column" style="width: 40%; text-align: center; justify-content: center; align-items: center;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/inference.svg" class="quarto-figure quarto-figure-center" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width: 50%; text-align: left; justify-content: center; align-items: center;">
<div class="fragment">
<div class="r-fit-text">
<ul>
<li class="fragment"><p><strong>Population</strong>: all elements of interest (every future impression).</p></li>
<li class="fragment"><p><strong>Sample</strong>: a subset (Vungle’s 30 test days).</p></li>
<li class="fragment"><p><strong>Descriptive Statistics</strong>: tabular, graphical, numerical summaries.</p></li>
<li class="fragment"><p><strong>Inferential Statistics</strong>: using the sample to estimate or test claims about the population.</p></li>
<li class="fragment"><p><strong>Estimation</strong>: approximate a population parameter (true mean eRPM).</p></li>
<li class="fragment"><p><strong>Hypothesis Testing</strong>: weigh evidence for a claim (is B &gt; A?).</p></li>
<li class="fragment"><p><strong>Prediction</strong>: forecast future outcomes from data.</p></li>
</ul>
</div>
</div>
</div></div>
</section></section>
<section>
<section id="data-science-big-data-and-data-mining" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Data Science, Big Data, and Data Mining</h1>

</section>
<section id="data-science-big-data-and-data-mining-definitions" class="slide level2 center">
<h2>Data Science, Big Data, and Data Mining — Definitions</h2>
<ul>
<li><strong>Data Science</strong>:
<ul>
<li>The interdisciplinary field that uses scientific methods, algorithms, and systems to extract knowledge and insights from structured and unstructured data.</li>
</ul></li>
<li><strong>Big Data</strong>:
<ul>
<li>Extremely large datasets analyzed computationally to reveal patterns, trends, and associations — especially about human behavior.</li>
</ul></li>
<li><strong>Data Mining</strong>:
<ul>
<li>Examining large databases to generate new information; at the intersection of machine learning, statistics, and database systems.</li>
</ul></li>
</ul>
</section>
<section id="how-data-science-big-data-and-data-mining-are-used" class="slide level2 center">
<h2>How Data Science, Big Data, and Data Mining Are Used</h2>
<div class="r-fit-text">
<ul>
<li><strong>Data Science</strong>:
<ul>
<li>Personalizing marketing by predicting preferences and buying behavior.</li>
<li>Optimizing supply chains through predictive analytics.</li>
</ul></li>
<li><strong>Big Data</strong>:
<ul>
<li>Mining customer feedback and social media to improve service and products.</li>
<li>Detecting fraud by monitoring transaction patterns in real time.</li>
</ul></li>
<li><strong>Data Mining</strong>:
<ul>
<li>Surfacing sales leads from past purchases and demographics.</li>
<li>Reducing churn by learning who is about to leave and why.</li>
</ul></li>
</ul>
</div>
</section></section>
<section>
<section id="the-takeaway" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Takeaway</h1>

</section>
<section id="managers-takeaway" class="slide level2 center">
<h2>Manager’s Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> today we turned a CEO’s question — <em>roll out B or keep A?</em> — into a precise data problem, and built the vocabulary to describe it.</p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <strong>60 rows × 7 variables = 420 values</strong> — that is Vungle’s dataset, and you can name every element, variable, and observation in it.</p></li>
<li class="fragment"><p><strong>One principle:</strong> the <strong>scale of a variable</strong> determines which statistics are valid — count <code>algorithm</code>, average <code>erpm</code>.</p></li>
<li class="fragment"><p><strong>Practice:</strong> open <code>data/vungle_daily.xlsx</code>, install the Analysis ToolPak, and run <strong>Descriptive Statistics</strong> on <code>erpm</code>. Bring one question to next class.</p></li>
</ul>
</section>
<section id="carry-forward" class="slide level2 center">
<h2>Carry-forward</h2>
<ul>
<li><p><strong>Today’s submission:</strong> your group’s roll-out call is your first graded deliverable — a real decision taken on day one.</p></li>
<li><p><strong>Next time:</strong> we go deeper into <em>describing</em> — spread, shape, the boxplot, and how two variables move together. (Individual homework starts in a couple of weeks; watch Brightspace.)</p></li>
</ul>
</section>
<section id="summary" class="slide level2 center">
<h2>Summary</h2>
<p>The main points from this session:</p>
<ul>
<li><strong>Your seat all term:</strong> you are the <strong>decision-maker</strong> — you run every method yourself, but to <em>judge</em> the analysis and make the call, not to be the analyst.</li>
<li><strong>Two cases, worked in your group:</strong> Vungle A/B (describe → test, Topics 1–9) and auto-parts retail (predict, Topics 10–11); you submit a graded group call each class, and individual homework drills the mechanics.</li>
<li><strong>Statistics</strong> turns data into defensible business decisions; it splits into <strong>descriptive</strong> (summarize) and <strong>inferential</strong> (generalize).</li>
<li><strong>Data vocabulary:</strong> elements, variables, observations; categorical vs.&nbsp;quantitative; the four scales of measurement — and the rule that <strong>scale determines method</strong>.</li>
<li><strong>Study design:</strong> Vungle ran a randomized <strong>experiment</strong>, which is what licenses <em>causal</em> claims.</li>
<li><strong>Excel is your toolkit:</strong> install the Analysis ToolPak and meet the dataset on day one.</li>
</ul>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Thank you!</h1>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Business Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>