<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Professor Davi Moreira ">
  <title>QM 6700: Business Analytics –  QM 6700: Business Analytics </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-8fc47a4fdcba9931a3aa90ef56f89358.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="font-size: 100%;"> QM 6700: Business Analytics </span></h1>
  <p class="subtitle"><span style="font-size: 150%;"> Hypothesis Testing II: Inference About Two Populations </span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor<br>Davi Moreira<br> 
</div>
</div>
</div>

</section>
<section id="overview" class="slide level2 center">
<h2>Overview</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Case Spotlight: A/B Testing at Vungle</li>
<li>Two designs: matched (paired) vs.&nbsp;independent samples</li>
<li>Matched samples: the paired <span class="math inline">\(t\)</span>-test</li>
<li>Inferences About the Difference Between Two Population Means
<ul>
<li><span class="math inline">\(\sigma_1, \sigma_2\)</span> Known</li>
<li><span class="math inline">\(\sigma_1, \sigma_2\)</span> Unknown: pooled <span class="math inline">\(t\)</span> and Welch <span class="math inline">\(t\)</span></li>
</ul></li>
</ul>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Same data, different design: why pairing matters</li>
<li>Inferences About the Difference Between Two Population Proportions</li>
<li>Statistical vs.&nbsp;practical significance</li>
<li>The rollout decision: from test results to a recommendation</li>
</ul>
</div></div>
</section>
<section>
<section id="case-spotlight-ab-testing-at-vungle" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Case Spotlight: A/B Testing at Vungle</h1>

</section>
<section id="june-30-2014-two-analysts-and-one-month-of-data" class="slide level2 center">
<h2>June 30, 2014: Two Analysts and One Month of Data</h2>
<p><br></p>
<ul>
<li class="fragment"><p><a href="https://techcrunch.com/2017/02/15/vungle-300-million/">Vungle</a> is a mobile ad-tech startup: it serves 15-second video ads inside other companies’ apps and earns revenue mainly when viewers <strong>install</strong> the advertised app (cost-per-install).</p></li>
<li class="fragment"><p>Two Darden MBAs, <strong>Andrew Kritzer</strong> and <strong>Hammond Guerin</strong>, built a new ad-serving algorithm (<strong>B</strong>) and ran it head-to-head against the existing one (<strong>A</strong>) for the entire month of June 2014.</p></li>
<li class="fragment"><p>The split was random: an MD5 hash of each user ID sent <strong>1/16 of traffic to B</strong>, the rest to A. Same market, same days, same apps; only the algorithm differs.</p></li>
<li class="fragment"><p>The metric that pays the bills is <strong>eRPM</strong>: effective revenue per 1,000 impressions.</p></li>
<li class="fragment"><p>Guerin is about to become Vungle’s <strong>head of data science</strong>. His credibility (and his stock options) ride on this call.</p></li>
</ul>
</section>
<section id="the-brief-todays-managerial-question" class="slide level2 center">
<h2>The Brief: Today’s Managerial Question</h2>
<p><br></p>
<ul>
<li class="fragment"><strong>The big call you own as Vungle’s manager:</strong> <em>roll out algorithm B, or stay with A?</em> We have built toward it all term; today we settle it.</li>
</ul>
<div class="fragment">
<blockquote>
<p>“B’s daily eRPM averaged about <strong>$0.11 higher</strong> than A’s. Is that a <strong>real improvement</strong>, or just month-to-month <strong>noise</strong>? Should Vungle <strong>roll out B</strong> to all traffic?”</p>
</blockquote>
</div>
<p><br></p>
<ul>
<li class="fragment"><p>In Topic 8 we tested <strong>one</strong> population against a benchmark (“is B’s mean eRPM above $3.30?”). Today’s question is the one that decides the rollout: <strong>is B really better than A?</strong>, comparing <strong>two</strong> populations.</p></li>
<li class="fragment"><p><strong>How today’s studio runs:</strong> I demo each test on a textbook example, then on the Vungle data; you debrief the rollout call; then your group runs a fresh case and submits its own call.</p></li>
<li class="fragment"><p>By the end of class you, the manager, will have the recommendation, with the statistics to back it up.</p></li>
</ul>
</section>
<section id="how-every-class-runs" class="slide level2 center">
<h2>How Every Class Runs</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/lecture_dynamic.png" class="quarto-figure quarto-figure-center" style="width:90.0%"></p>
</figure>
</div>
<p>The class <strong>ends on the Team Sprint</strong>, your group’s graded submission: a decision plus your read of the analysis, one PDF before you leave.</p>
</section>
<section id="how-todays-tools-answer-it" class="slide level2 center">
<h2>How Today’s Tools Answer It</h2>
<p><br></p>
<p>Every tool today maps onto the Vungle dataset:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Feature of the Vungle test</th>
<th>The tool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Same 30 days observed under both A and B</td>
<td><strong>Matched samples → paired <span class="math inline">\(t\)</span>-test</strong></td>
</tr>
<tr class="even">
<td>What if we (wrongly) ignored the day pairing?</td>
<td><strong>Independent samples <span class="math inline">\(t\)</span>-test</strong> (a cautionary contrast)</td>
</tr>
<tr class="odd">
<td>Millions of impressions → installs (yes/no)</td>
<td><strong>Two-proportion <span class="math inline">\(z\)</span>-test</strong></td>
</tr>
<tr class="even">
<td>“Roll out or not?”</td>
<td>Test results become <strong>decision signals</strong> (Decision Analysis, Topic 4)</td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment">One dataset, three tests, and they will <strong>not</strong> all point the same way. That tension is today’s managerial lesson.</li>
</ul>
</section></section>
<section>
<section id="comparing-two-groups-design-first" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Comparing Two Groups: Design First</h1>

</section>
<section id="the-canonical-business-question" class="slide level2 center">
<h2>The Canonical Business Question</h2>
<p><br></p>
<ul>
<li class="fragment"><p>“Is treatment B systematically different from A?” appears everywhere in business:</p>
<ul>
<li class="fragment">New ad algorithm vs.&nbsp;current one (Vungle)</li>
<li class="fragment">New web page layout vs.&nbsp;old (conversion A/B tests)</li>
<li class="fragment">Delivery carrier 1 vs.&nbsp;carrier 2 (cost, speed)</li>
<li class="fragment">Trained employees vs.&nbsp;untrained (productivity)</li>
</ul></li>
<li class="fragment"><p>The null hypothesis is the <strong>skeptic’s position</strong>: any observed gap is just sampling noise.</p></li>
<li class="fragment"><p>Before any formula, you must answer a <strong>design</strong> question: <em>how were the two samples collected?</em></p></li>
</ul>
</section>
<section id="two-ways-to-collect-the-comparison" class="slide level2 center">
<h2>Two Ways to Collect the Comparison</h2>
<p><br></p>
<p><strong>Suppose you run a taste test of two flavors:</strong></p>
<ul>
<li class="fragment"><p><strong>Paired test (matched samples):</strong> select <strong>one</strong> random sample and let <strong>every person rate both flavors</strong> (in random order).</p>
<ul>
<li class="fragment">Each sampled unit produces <strong>one pair</strong> of data values.</li>
</ul></li>
<li class="fragment"><p><strong>Unpaired test (independent samples):</strong> select <strong>two</strong> random samples and let <strong>each group rate only one flavor</strong>.</p>
<ul>
<li class="fragment">No natural link between an observation in group 1 and any observation in group 2.</li>
</ul></li>
<li class="fragment"><p>Which is better? The <strong>paired test tends to remove much of the extraneous variation</strong> (differences in people, days, and experimental conditions) so the flavor effect stands out.</p></li>
</ul>
</section>
<section id="two-designs-in-pictures" class="slide level2 center">
<h2>Two Designs, in Pictures</h2>

<img data-src="figs/ab_test_design_schematic.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><ul>
<li><strong>Paired is preferred when feasible</strong>, but it requires that every unit <em>can</em> be measured under both conditions.</li>
<li>When the units come from genuinely separate populations (bankrupt vs.&nbsp;non-bankrupt firms), only the <strong>independent</strong> design exists.</li>
</ul>
</section>
<section id="the-hypotheses-are-about-a-difference" class="slide level2 center">
<h2>The Hypotheses Are About a Difference</h2>
<p><br></p>
<ul>
<li class="fragment">All of today’s tests reuse the Topic 8 logic; the only change is the <strong>parameter</strong>: it is now a <strong>difference</strong>.</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\begin{aligned}
\text{Two means:} \quad &amp; H_0: \mu_1 - \mu_2 = 0 \quad \text{vs.} \quad H_a: \mu_1 - \mu_2 \neq 0 \; (\text{or } &gt;, &lt;) \\
\text{Two proportions:} \quad &amp; H_0: p_1 - p_2 = 0 \quad \text{vs.} \quad H_a: p_1 - p_2 \neq 0 \; (\text{or } &gt;, &lt;)
\end{aligned}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Same machinery as before: a test statistic, a rejection region, a <span class="math inline">\(p\)</span>-value, and a decision at significance level <span class="math inline">\(\alpha\)</span>.</p></li>
<li class="fragment"><p>The equality always lives in <span class="math inline">\(H_0\)</span>; the claim we seek evidence <strong>for</strong> lives in <span class="math inline">\(H_a\)</span>.</p></li>
</ul>
</section>
<section id="choosing-the-right-test" class="slide level2 center">
<h2>Choosing the Right Test</h2>

<img data-src="figs/decision_tree_test_selection.png" class="quarto-figure quarto-figure-center r-stretch" style="width:75.0%"></section>
<section id="test-selection-cheat-sheet" class="slide level2 center">
<h2>Test Selection Cheat Sheet</h2>
<div class="r-fit-text">
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Situation</th>
<th>Test</th>
<th>Test statistic</th>
<th>Distribution</th>
<th>Excel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Same units, two conditions</td>
<td><strong>Paired <span class="math inline">\(t\)</span></strong></td>
<td><span class="math inline">\(t = \dfrac{\bar{d} - 0}{s_d/\sqrt{n}}\)</span></td>
<td><span class="math inline">\(t\)</span>, <span class="math inline">\(df = n-1\)</span></td>
<td>ToolPak: <em>t-Test: Paired Two Sample for Means</em></td>
</tr>
<tr class="even">
<td>Independent, <span class="math inline">\(\sigma_1,\sigma_2\)</span> known</td>
<td><strong>Two-sample <span class="math inline">\(z\)</span></strong></td>
<td><span class="math inline">\(z = \dfrac{(\bar{x}_1-\bar{x}_2) - D_0}{\sqrt{\sigma_1^2/n_1 + \sigma_2^2/n_2}}\)</span></td>
<td><span class="math inline">\(N(0,1)\)</span></td>
<td>ToolPak: <em>z-Test: Two Sample for Means</em></td>
</tr>
<tr class="odd">
<td>Independent, <span class="math inline">\(\sigma\)</span> unknown, assumed equal</td>
<td><strong>Pooled <span class="math inline">\(t\)</span></strong></td>
<td><span class="math inline">\(t = \dfrac{(\bar{x}_1-\bar{x}_2) - D_0}{s_p\sqrt{1/n_1 + 1/n_2}}\)</span></td>
<td><span class="math inline">\(t\)</span>, <span class="math inline">\(df = n_1+n_2-2\)</span></td>
<td>ToolPak: <em>t-Test: Two-Sample Assuming Equal Variances</em></td>
</tr>
<tr class="even">
<td>Independent, <span class="math inline">\(\sigma\)</span> unknown, not assumed equal</td>
<td><strong>Welch <span class="math inline">\(t\)</span></strong> <em>(default)</em></td>
<td><span class="math inline">\(t = \dfrac{(\bar{x}_1-\bar{x}_2) - D_0}{\sqrt{s_1^2/n_1 + s_2^2/n_2}}\)</span></td>
<td><span class="math inline">\(t\)</span>, Satterthwaite <span class="math inline">\(df\)</span></td>
<td>ToolPak: <em>t-Test: Two-Sample Assuming Unequal Variances</em></td>
</tr>
<tr class="odd">
<td>Two proportions (large samples)</td>
<td><strong>Two-proportion <span class="math inline">\(z\)</span></strong></td>
<td><span class="math inline">\(z = \dfrac{\bar{p}_1-\bar{p}_2}{\sqrt{\bar{p}(1-\bar{p})(1/n_1+1/n_2)}}\)</span></td>
<td><span class="math inline">\(N(0,1)\)</span></td>
<td>No built-in tool; formula cells</td>
</tr>
</tbody>
</table>
</div>
</section></section>
<section>
<section id="matched-samples-the-paired-t-test" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Matched Samples: the Paired <span class="math inline">\(t\)</span>-Test</h1>

</section>
<section id="one-idea-reduce-two-samples-to-one" class="slide level2 center">
<h2>One Idea: Reduce Two Samples to One</h2>
<p><br></p>
<ul>
<li class="fragment"><p>With a matched-sample design, <strong>each sampled unit provides a pair of data values</strong>: <span class="math inline">\((x_{1i}, x_{2i})\)</span>.</p></li>
<li class="fragment"><p><strong>Key insight:</strong> work with the <strong>difference</strong> for each pair,</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
d_i = x_{1i} - x_{2i}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>The two-sample problem becomes a <strong>one-sample</strong> problem about the mean difference <span class="math inline">\(\mu_d\)</span>, and we can apply <em>exactly</em> the single-population procedures from Topic 8.</p></li>
<li class="fragment"><p>Point estimate of <span class="math inline">\(\mu_d\)</span>:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{d} = \frac{1}{n}\sum_{i=1}^{n} d_i
\]</span></p>
</div>
</section>
<section id="a-question-that-often-comes-up" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">Why does subtracting within each pair get rid of the day-to-day swings?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> because both numbers in a pair share that day’s conditions. If June 14 was a slow Saturday, <em>both</em> A and B earn less that day, so when you compute <span class="math inline">\(d = \text{eRPM}_B - \text{eRPM}_A\)</span> the Saturday effect cancels out of the difference. What survives is the part that is <em>not</em> shared: the algorithm. That is why the differences (<span class="math inline">\(s_d = 0.18\)</span>) are far less noisy than the raw daily series (<span class="math inline">\(s \approx 0.22\)</span> to <span class="math inline">\(0.34\)</span>).</p>
</div>
</div>
</section>
<section id="paired-t-mechanics" class="slide level2 center">
<h2>Paired <span class="math inline">\(t\)</span> Mechanics</h2>
<p><br></p>
<div style="font-size: 84%;">
<ul>
<li class="fragment">Sample standard deviation of the differences:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
s_d = \sqrt{\frac{\sum_{i=1}^n (d_i - \bar{d})^2}{n - 1}}
\]</span></p>
</div>
<ul>
<li class="fragment">Standard error of <span class="math inline">\(\bar{d}\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
SE(\bar{d}) = \frac{s_d}{\sqrt{n}}
\]</span></p>
</div>
<ul>
<li class="fragment">Test statistic (under <span class="math inline">\(H_0: \mu_d = 0\)</span>), with <span class="math inline">\(df = n - 1\)</span>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
t = \frac{\bar{d} - 0}{s_d / \sqrt{n}}
\]</span></p>
</div>
</div>
</section>
<section id="tests-intervals-and-decision-rules" class="slide level2 center">
<h2>Tests, Intervals, and Decision Rules</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Hypothesis forms:</strong> <span class="math inline">\(H_0: \mu_d = 0\)</span> vs.&nbsp;<span class="math inline">\(H_a: \mu_d \neq 0\)</span> (two-tailed), or the one-sided versions <span class="math inline">\(H_a: \mu_d &gt; 0\)</span> / <span class="math inline">\(H_a: \mu_d &lt; 0\)</span>.</p></li>
<li class="fragment"><p><strong>Decision rule (critical value):</strong> reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|t| \geq t_{\alpha/2,\,n-1}\)</span> (two-tailed) or <span class="math inline">\(t \geq t_{\alpha,\,n-1}\)</span> (upper-tail).</p></li>
<li class="fragment"><p><strong>Confidence interval for <span class="math inline">\(\mu_d\)</span>:</strong></p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{d} \pm t_{\alpha/2,\,n-1} \cdot \frac{s_d}{\sqrt{n}}
\]</span></p>
</div>
<ul>
<li class="fragment"><p><strong><span class="math inline">\(p\)</span>-values in Excel:</strong></p>
<ul>
<li class="fragment">Two-tailed: <code>=T.DIST.2T(ABS(t), df)</code></li>
<li class="fragment">Upper-tail: <code>=T.DIST.RT(t, df)</code></li>
</ul></li>
</ul>
</section>
<section id="anchor-example-express-deliveries" class="slide level2 center">
<h2>Anchor Example: Express Deliveries</h2>
<div class="r-fit-text">
<p>To compare delivery times of two express services, <strong>UPX</strong> and <strong>INTEX</strong>, two reports were sent to each of <strong>ten district offices</strong>: one carried by UPX, the other by INTEX. <em>Same origin, same destination, same day: a natural pair.</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>District Office</th>
<th style="text-align: right;">UPX</th>
<th style="text-align: right;">INTEX</th>
<th style="text-align: right;">Difference <span class="math inline">\(d_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Seattle</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td>Los Angeles</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td>Boston</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td>Cleveland</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td>New York</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td>Houston</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td>Atlanta</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="even">
<td>St.&nbsp;Louis</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td>Milwaukee</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">-2</td>
</tr>
<tr class="even">
<td>Denver</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
<p><strong>Question:</strong> do the data indicate a difference in mean delivery times?</p>
</div>
</section>
<section id="express-deliveries-the-five-steps" class="slide level2 center">
<h2>Express Deliveries: the Five Steps</h2>
<div class="r-fit-text">
<p><strong>1. Business context.</strong> Choosing a carrier; the metric is delivery time (hours); slower deliveries cost client goodwill.</p>
<p><strong>2. Hypotheses</strong> (is there <em>any</em> difference? → two-tailed):</p>
<p><span class="math display">\[
H_0: \mu_d = 0 \qquad H_a: \mu_d \neq 0 \qquad \alpha = 0.05
\]</span></p>
<p><strong>3. Test statistic.</strong> From the ten differences:</p>
<p><span class="math display">\[
\bar{d} = 2.70, \quad s_d = 2.908, \quad SE = \frac{2.908}{\sqrt{10}} = 0.920, \quad t = \frac{2.70}{0.920} = 2.94, \quad df = 9
\]</span></p>
<p><strong>4. Decision.</strong> <span class="math inline">\(p\text{-value} = 0.017 \leq \alpha = 0.05\)</span> → <strong>reject <span class="math inline">\(H_0\)</span></strong>. Also: 95% CI for <span class="math inline">\(\mu_d\)</span> = <span class="math inline">\((0.620,\; 4.780)\)</span> hours; zero is not a plausible mean difference.</p>
<p><strong>5. The Manager’s Translation.</strong> <em>UPX averages about 2.7 hours slower than INTEX on identical routes: a real difference, not noise. If speed matters, route the volume to INTEX (then negotiate with UPX).</em></p>
</div>
</section>
<section id="do-it-in-excel-paired-t-test-express-deliveries" class="slide level2 center">
<h2>Do It in Excel: Paired <span class="math inline">\(t\)</span>-Test (Express Deliveries)</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Lay UPX and INTEX in two columns, one row per district office.</li>
<li class="fragment"><strong>Data → Data Analysis → t-Test: Paired Two Sample for Means</strong></li>
<li class="fragment">Variable 1 = UPX, Variable 2 = INTEX; Hypothesized Mean Difference <code>0</code>; Alpha <code>0.05</code>.</li>
<li class="fragment">Click OK; read <code>t Stat = 2.936</code> and <code>P(T&lt;=t) two-tail = 0.017</code> <span class="math inline">\(\leq\)</span> 0.05 → reject <span class="math inline">\(H_0\)</span>.</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_paired_express.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section></section>
<section>
<section id="the-vungle-test-is-b-really-better" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Vungle Test: Is B Really Better?</h1>

</section>
<section id="step-1-business-context-why-a-paired-design" class="slide level2 center">
<h2>Step 1, Business Context: Why a Paired Design?</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Each of the <strong>30 days of June 2014</strong> is a natural experimental unit: on any given day, <strong>the same advertising market</strong> operates (same advertisers, same user pool, same day-of-week effects).</p></li>
<li class="fragment"><p>Users were randomly split <strong>within each day</strong>: A and B ran <strong>side by side</strong>.</p></li>
<li class="fragment"><p>So each day yields <strong>one pair</strong>, <span class="math inline">\((\text{eRPM}_A, \text{eRPM}_B)\)</span>, and one difference</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
d_i = \text{eRPM}_{B,i} - \text{eRPM}_{A,i}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Pairing <strong>subtracts out day-specific noise</strong> (weekend dips, late-June seasonality) and isolates the pure algorithm effect.</p></li>
<li class="fragment"><p>Data: <code>data/vungle_erpm_paired.csv</code>, 30 rows, columns <code>erpm_A</code>, <code>erpm_B</code>, <code>diff_B_minus_A</code>.</p></li>
</ul>
</section>
<section id="the-data-30-days-of-erpm" class="slide level2 center">
<h2>The Data: 30 Days of eRPM</h2>

<img data-src="figs/erpm_time_series.png" class="quarto-figure quarto-figure-center r-stretch" style="width:85.0%"><ul>
<li>B starts <em>below</em> A, then pulls ahead for most of the month. Eyeballing is suggestive, but Guerin needs more than an eyeball to bet his job on.</li>
</ul>
</section>
<section id="the-differences-d-b---a" class="slide level2 center">
<h2>The Differences: <span class="math inline">\(d = B - A\)</span></h2>

<img data-src="figs/erpm_diff_daily.png" class="quarto-figure quarto-figure-center r-stretch" style="width:85.0%"><ul>
<li>26 of 30 days favor B; the mean difference is <strong>+$0.112</strong> per 1,000 impressions.</li>
<li>The paired <span class="math inline">\(t\)</span>-test asks: <em>could a mean difference this large arise by chance if the true difference were zero?</em></li>
</ul>
</section>
<section id="step-2-hypotheses" class="slide level2 center">
<h2>Step 2: Hypotheses</h2>
<p><br></p>
<div class="fragment">
<p><span class="math display">\[
H_0: \mu_d \leq 0 \qquad \text{vs.} \qquad H_a: \mu_d &gt; 0 \qquad \text{(upper-tail)} \qquad \alpha = 0.05
\]</span></p>
</div>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Why one-tailed?</strong> The business decision is asymmetric: Vungle rolls out B <strong>only if it is better</strong>. “B is worse” and “B is the same” lead to the identical action: keep A.</p></li>
<li class="fragment"><p><span class="math inline">\(\mu_d\)</span> = the true mean daily eRPM advantage of B over A.</p></li>
<li class="fragment"><p>We will also report the two-tailed <span class="math inline">\(p\)</span>-value (the more conservative convention) and the conclusion will not change.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-1" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">Isn’t a one-tailed test just a trick to make the <span class="math inline">\(p\)</span>-value smaller and get the answer we want?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> it would be, if we picked the direction <em>after</em> seeing the data. We did not: the rollout rule, “ship B only if it beats A,” fixes the direction <span class="math inline">\(H_a: \mu_d &gt; 0\)</span> <strong>before</strong> the test, because “B is worse” and “B is the same” lead to the same action (keep A). The honest guard is that we also report the two-tailed <span class="math inline">\(p\)</span>-value (<span class="math inline">\(\approx 0.0024\)</span>), and B still wins. If the call had hinged on which tail you chose, that would be a red flag.</p>
</div>
</div>
</section>
<section id="step-3-test-statistic" class="slide level2 center">
<h2>Step 3: Test Statistic</h2>
<p><br></p>
<p>From the 30 daily differences in <code>vungle_erpm_paired.csv</code>:</p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(n\)</span> (days)</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\bar{d}\)</span> (mean difference)</td>
<td style="text-align: right;"><strong>$0.1119</strong></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(s_d\)</span></td>
<td style="text-align: right;">0.1843</td>
</tr>
<tr class="even">
<td><span class="math inline">\(SE = s_d/\sqrt{30}\)</span></td>
<td style="text-align: right;">0.0337</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(t = \bar{d}/SE\)</span></td>
<td style="text-align: right;"><strong>3.325</strong></td>
</tr>
<tr class="even">
<td><span class="math inline">\(df\)</span></td>
<td style="text-align: right;">29</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
<div class="fragment">
<p><span class="math display">\[
t = \frac{0.1119}{0.1843/\sqrt{30}} = \frac{0.1119}{0.0337} = 3.325
\]</span></p>
</div>
</section>
<section id="do-it-in-excel-paired-t-test-vungle-erpm" class="slide level2 center">
<h2>Do It in Excel: Paired <span class="math inline">\(t\)</span>-Test (Vungle eRPM)</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Open <code>vungle_erpm_paired.csv</code>; select the <code>erpm_B</code> and <code>erpm_A</code> columns.</li>
<li class="fragment"><strong>Data → Data Analysis → t-Test: Paired Two Sample for Means</strong></li>
<li class="fragment">Variable 1 = <code>erpm_B</code>, Variable 2 = <code>erpm_A</code>; Hypothesized Mean Difference <code>0</code>; Alpha <code>0.05</code>.</li>
<li class="fragment">Click OK; read <code>t Stat = 3.325</code>, <code>P(T&lt;=t) one-tail = 0.0012</code>, <code>t Critical one-tail = 1.699</code>.</li>
</ol>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_paired_vungle.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="step-4-decision" class="slide level2 center">
<h2>Step 4: Decision</h2>

<img data-src="figs/t_dist_paired_vungle.png" class="quarto-figure quarto-figure-center r-stretch" style="width:75.0%"><ul>
<li><strong>Critical value:</strong> <span class="math inline">\(t = 3.325 \geq t_{0.05,29} = 1.699\)</span> → <strong>reject <span class="math inline">\(H_0\)</span></strong>.</li>
<li><strong><span class="math inline">\(p\)</span>-value:</strong> one-tail <span class="math inline">\(p \approx 0.0012\)</span> (two-tail <span class="math inline">\(\approx 0.0024\)</span>) <span class="math inline">\(\leq \alpha = 0.05\)</span> → <strong>reject <span class="math inline">\(H_0\)</span></strong>.</li>
<li>Strong evidence that algorithm B’s mean daily eRPM is higher than A’s.</li>
</ul>
</section>
<section id="the-confidence-interval-tells-you-the-size" class="slide level2 center">
<h2>The Confidence Interval Tells You the Size</h2>
<p><br></p>
<ul>
<li class="fragment">The test says the lift is <strong>real</strong>; the confidence interval says <strong>how big</strong> it plausibly is:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{d} \pm t_{0.025,29}\frac{s_d}{\sqrt{n}} = 0.1119 \pm 2.045 \times 0.0337 \;=\; (\$0.043,\; \$0.181)
\]</span></p>
</div>
<ul>
<li class="fragment"><p>The entire interval is <strong>above zero</strong>, consistent with rejecting <span class="math inline">\(H_0\)</span>.</p></li>
<li class="fragment"><p>Even the <strong>lower bound</strong> ($0.043 per 1,000 impressions) is a meaningful lift at Vungle’s scale.</p></li>
<li class="fragment"><p>In Excel: <code>=T.INV(0.975, 29)</code> → 2.045; bounds with formula cells from <span class="math inline">\(\bar d\)</span> and <span class="math inline">\(SE\)</span>.</p></li>
</ul>
</section>
<section id="step-5-the-managers-translation-back-to-the-decision" class="slide level2 center">
<h2>Step 5, the Manager’s Translation: Back to the Decision</h2>
<p><br></p>
<ul>
<li class="fragment"><p><em>“A difference this large would arise by chance only about 1 in 1,000 times if B were no better than A, so we reject the ‘no difference’ story. On a typical day, B earns between $0.04 and $0.18 more per 1,000 impressions than A.”</em></p></li>
<li class="fragment"><p><strong>Scale it:</strong> A served ≈ 236.5M impressions in June. Had B served that traffic:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\frac{236{,}459{,}402}{1{,}000} \times \$0.112 \approx \$26{,}500 \text{ per month} \;\approx\; \$318\text{K per year}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Even at the CI lower bound ($0.043), the lift is ≈ $10K/month, material for a startup with $25.5M raised.</p></li>
<li class="fragment"><p><strong>Discussion hook:</strong> the daily gap is noisy. The first week even favored A, and after two weeks B’s lead was only ≈ $0.04, still well below the full-month $0.11. Stopping the test early could have hidden the effect. (Sequential testing is beyond today’s scope, but exactly what real A/B platforms wrestle with.)</p></li>
</ul>
</section>
<section id="studio-check-reproduce-the-paired-test" class="slide level2 center">
<h2>Studio Check: Reproduce the Paired Test</h2>
<p><strong>Reproduce what the analyst did</strong>, so you can verify the lift is real before you stake the rollout on it.</p>
<p><strong>Data:</strong> <code>data/vungle_erpm_paired.csv</code></p>
<ol type="1">
<li>In Excel: <strong>Data → Data Analysis → t-Test: Paired Two Sample for Means</strong> (Variable 1 = <code>erpm_B</code>, Variable 2 = <code>erpm_A</code>, α = 0.05).</li>
<li>Read off <code>t Stat</code> and <code>P(T&lt;=t) one-tail</code>; build the 95% CI for the mean difference.</li>
<li>Decide at α = 0.05: is the lift real?</li>
</ol>
<p>You should land on <span class="math inline">\(t = 3.325\)</span>, one-tail <span class="math inline">\(p \approx 0.0012\)</span>, 95% CI ≈ ($0.043, $0.181). The two things worth challenging: the one-tailed framing and whether 30 days generalizes.</p>
</section></section>
<section>
<section id="independent-samples-comparing-two-means" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Independent Samples: Comparing Two Means</h1>

</section>
<section id="setup-and-point-estimate" class="slide level2 center">
<h2>Setup and Point Estimate</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Two <strong>independent</strong> random samples: sizes <span class="math inline">\(n_1, n_2\)</span> from populations with means <span class="math inline">\(\mu_1, \mu_2\)</span>.</p></li>
<li class="fragment"><p>Point estimate of <span class="math inline">\(\mu_1 - \mu_2\)</span>: <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span>.</p></li>
<li class="fragment"><p>Sampling distribution of <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span>: centered at <span class="math inline">\(\mu_1 - \mu_2\)</span>, with standard error built from <strong>both</strong> sampling variances:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
SE(\bar{x}_1 - \bar{x}_2) = \sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}
\]</span></p>
</div>
<ul>
<li class="fragment">Which test statistic you use depends on what you know about <span class="math inline">\(\sigma_1, \sigma_2\)</span>: the three cases that follow.</li>
</ul>
</section>
<section id="case-1-sigma_1-sigma_2-known-the-two-sample-z" class="slide level2 center">
<h2>Case 1, <span class="math inline">\(\sigma_1, \sigma_2\)</span> Known: the Two-Sample <span class="math inline">\(z\)</span></h2>
<p><br></p>
<ul>
<li class="fragment">Rare in practice (you seldom <em>know</em> population standard deviations), but conceptually clean:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
z = \frac{(\bar{x}_1 - \bar{x}_2) - D_0}{\sqrt{\sigma_1^2/n_1 + \sigma_2^2/n_2}}
\qquad\qquad
\text{CI:}\;\; (\bar{x}_1 - \bar{x}_2) \pm z_{\alpha/2}\sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}
\]</span></p>
</div>
<ul>
<li class="fragment"><p><span class="math inline">\(D_0\)</span> = hypothesized difference, usually 0.</p></li>
<li class="fragment"><p><strong>Excel:</strong> Data Analysis → <em>z-Test: Two Sample for Means</em> (requires the two known variances as inputs); <span class="math inline">\(p\)</span>-values via <code>=NORM.S.DIST</code>.</p></li>
<li class="fragment"><p>Note: the worksheet function <code>=Z.TEST</code> is for <strong>one</strong> sample only; the two-sample version needs the ToolPak tool or formula cells.</p></li>
</ul>
</section>
<section id="case-2-sigma-unknown-assumed-equal-the-pooled-t" class="slide level2 center">
<h2>Case 2, <span class="math inline">\(\sigma\)</span> Unknown, Assumed Equal: the Pooled <span class="math inline">\(t\)</span></h2>
<p><br></p>
<ul>
<li class="fragment">If it is reasonable to assume <span class="math inline">\(\sigma_1 = \sigma_2 = \sigma\)</span>, combine both samples into one <strong>pooled variance</strong>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
s_p^2 = \frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
t = \frac{(\bar{x}_1 - \bar{x}_2) - D_0}{s_p\sqrt{\dfrac{1}{n_1} + \dfrac{1}{n_2}}},
\qquad df = n_1 + n_2 - 2
\]</span></p>
</div>
<ul>
<li class="fragment"><p>CI: <span class="math inline">\((\bar{x}_1 - \bar{x}_2) \pm t_{\alpha/2,\,n_1+n_2-2}\; s_p\sqrt{1/n_1 + 1/n_2}\)</span></p></li>
<li class="fragment"><p><strong>Excel:</strong> Data Analysis → <em>t-Test: Two-Sample Assuming Equal Variances</em>.</p></li>
</ul>
</section>
<section id="case-3-sigma-unknown-not-assumed-equal-the-welch-t" class="slide level2 center">
<h2>Case 3, <span class="math inline">\(\sigma\)</span> Unknown, Not Assumed Equal: the Welch <span class="math inline">\(t\)</span></h2>
<p><br></p>
<div style="font-size: 80%;">
<ul>
<li class="fragment">Drop the equal-variance assumption; each sample keeps its own variance:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
t = \frac{(\bar{x}_1 - \bar{x}_2) - D_0}{\sqrt{\dfrac{s_1^2}{n_1} + \dfrac{s_2^2}{n_2}}}
\]</span></p>
</div>
<ul>
<li class="fragment">Degrees of freedom (Satterthwaite approximation; typically non-integer, so round <strong>down</strong>):</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
df = \frac{\left(\dfrac{s_1^2}{n_1} + \dfrac{s_2^2}{n_2}\right)^2}{\dfrac{(s_1^2/n_1)^2}{n_1 - 1} + \dfrac{(s_2^2/n_2)^2}{n_2 - 1}}
\]</span></p>
</div>
<ul>
<li class="fragment">CI: <span class="math inline">\((\bar{x}_1 - \bar{x}_2) \pm t_{\alpha/2,\,df}\sqrt{s_1^2/n_1 + s_2^2/n_2}\)</span></li>
</ul>
</div>
</section>
<section id="practical-guidance-default-to-welch" class="slide level2 center">
<h2>Practical Guidance: Default to Welch</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Unless you have a strong theoretical reason to assume equal variances, use Welch.</strong> It is the safe default: when variances <em>are</em> equal it loses almost nothing; when they differ it protects you.</p></li>
<li class="fragment"><p><strong>Excel:</strong> Data Analysis → <em>t-Test: Two-Sample Assuming Unequal Variances</em>.</p></li>
<li class="fragment"><p>Reading any ToolPak <span class="math inline">\(t\)</span>-test output, the same rows every time:</p>
<ul>
<li class="fragment"><code>Mean</code>, <code>Variance</code>, <code>Observations</code>: the summary statistics per group</li>
<li class="fragment"><code>df</code>: degrees of freedom used</li>
<li class="fragment"><code>t Stat</code>: the test statistic</li>
<li class="fragment"><code>P(T&lt;=t) one-tail</code> / <code>two-tail</code>: your <span class="math inline">\(p\)</span>-values</li>
<li class="fragment"><code>t Critical one-tail</code> / <code>two-tail</code>: the cutoffs for <span class="math inline">\(\alpha\)</span></li>
</ul></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-2" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If the pooled <span class="math inline">\(t\)</span> usually gives a similar answer, why is Welch the safer default?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> Welch never assumes the two groups have the same spread; pooled does. When the variances really are equal, Welch costs you almost nothing (the owner’s-equity example gives nearly the same <span class="math inline">\(t\)</span> either way). When they differ, say a steady algorithm A versus a more volatile B, pooling understates the true uncertainty and can hand you a false “significant.” You only know the variances are equal <em>after</em> checking, so start with the test that does not need the assumption.</p>
</div>
</div>
</section>
<section id="anchor-example-start-up-owners-equity" class="slide level2 center">
<h2>Anchor Example: Start-up Owner’s Equity</h2>
<p><br></p>
<p><strong>Two populations</strong> (no pairing is possible, since a firm is either bankrupt or it isn’t):</p>
<ol type="1">
<li>Small business firms that went <strong>bankrupt</strong> within the first year</li>
<li>Firms that are <strong>not bankrupt</strong></li>
</ol>
<p><strong>Variable of interest:</strong> owner’s equity ($K) at founding.</p>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: right;"><span class="math inline">\(n\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\bar{x}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bankrupt</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">5.73</td>
<td style="text-align: right;">3.33</td>
</tr>
<tr class="even">
<td>Non-bankrupt</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">7.87</td>
<td style="text-align: right;">2.61</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Question:</strong> is there a difference in average owner’s equity between bankrupt and non-bankrupt firms?</p>
</section>
<section id="owners-equity-the-five-steps" class="slide level2 center">
<h2>Owner’s Equity: the Five Steps</h2>
<div class="r-fit-text">
<p><strong>1. Business context.</strong> Does thin capitalization at founding predict first-year failure? (Lender screening, founder advice.)</p>
<p><strong>2. Hypotheses</strong> (two-tailed): <span class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span> vs.&nbsp;<span class="math inline">\(H_a: \mu_1 - \mu_2 \neq 0\)</span>, <span class="math inline">\(\alpha = 0.05\)</span>. Independent samples, <span class="math inline">\(\sigma\)</span> unknown, no reason to assume equal variances → <strong>Welch <span class="math inline">\(t\)</span></strong>.</p>
<p><strong>3. Test statistic.</strong></p>
<p><span class="math display">\[
t = \frac{(5.73 - 7.87) - 0}{\sqrt{\dfrac{3.33^2}{15} + \dfrac{2.61^2}{15}}} = \frac{-2.14}{1.093} = -1.96, \qquad df \approx 26
\]</span></p>
<p><strong>4. Decision.</strong> <span class="math inline">\(p\)</span>-value (two-tail) <span class="math inline">\(\approx 0.061 &gt; \alpha = 0.05\)</span> → <strong>fail to reject <span class="math inline">\(H_0\)</span></strong>. 95% CI for <span class="math inline">\(\mu_1 - \mu_2\)</span>: <span class="math inline">\((-4.4,\; 0.1)\)</span>, which barely includes zero.</p>
<p><strong>5. The Manager’s Translation.</strong> <em>Bankrupt firms started with about $2.1K less equity on average, but with only 15 firms per group we cannot rule out chance at the 5% level. A borderline result, worth a bigger sample before building lending policy on it.</em></p>
</div>
</section>
<section id="do-it-in-excel-welch-t-test-owners-equity" class="slide level2 center">
<h2>Do It in Excel: Welch <span class="math inline">\(t\)</span>-Test (Owner’s Equity)</h2>
<div class="columns">
<div class="column r-fit-text" style="width:46%;">
<p><strong>Follow along:</strong></p>
<ol type="1">
<li class="fragment">Put Bankrupt and Non-bankrupt owner’s equity in two columns.</li>
<li class="fragment"><strong>Data → Data Analysis → t-Test: Two-Sample Assuming Unequal Variances</strong></li>
<li class="fragment">Variable 1 = Bankrupt, Variable 2 = Non-bankrupt; Hypothesized Mean Difference <code>0</code>; Alpha <code>0.05</code>.</li>
<li class="fragment">Click OK; read <code>t Stat = -1.96</code>, <code>df = 26</code>, <code>P(T&lt;=t) two-tail = 0.061</code> <span class="math inline">\(&gt; 0.05\)</span> → fail to reject <span class="math inline">\(H_0\)</span>.</li>
</ol>
<p><strong>“Fail to reject” ≠ “the means are equal.”</strong> With <span class="math inline">\(n = 15\)</span> per group the test has <strong>low power</strong>; a $2K average gap may be economically real yet statistically undetectable here. (Equal <span class="math inline">\(n\)</span>: pooled <span class="math inline">\(t\)</span> gives the same statistic with <span class="math inline">\(df = 28\)</span>, same conclusion.)</p>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_equity_welch.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section></section>
<section>
<section id="same-data-different-design" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Same Data, Different Design</h1>

</section>
<section id="do-it-in-excel-welch-on-the-same-data-wrong-design" class="slide level2 center">
<h2>Do It in Excel: Welch on the Same Data (Wrong Design)</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Follow along (the wrong design, on purpose):</strong></p>
<ol type="1">
<li class="fragment">Same <code>erpm_B</code> and <code>erpm_A</code> columns, now treated as two <strong>independent</strong> samples.</li>
<li class="fragment"><strong>Data → Data Analysis → t-Test: Two-Sample Assuming Unequal Variances</strong></li>
<li class="fragment">Variable 1 = <code>erpm_B</code>, Variable 2 = <code>erpm_A</code> (same order, so <span class="math inline">\(t\)</span> is positive); Alpha <code>0.05</code>.</li>
<li class="fragment">Click OK; read <code>t Stat = 1.51</code>, <code>P(T&lt;=t) two-tail = 0.138</code> <span class="math inline">\(&gt; 0.05\)</span> → fail to reject.</li>
</ol>
<p><strong>The $0.11 lift “disappears.”</strong> Same numbers (<span class="math inline">\(\bar{x}_A = 3.347\)</span>, <span class="math inline">\(\bar{x}_B = 3.459\)</span>), wrong design, opposite call.</p>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_welch_vungle.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="the-lesson-design-drives-conclusions" class="slide level2 center">
<h2>The Lesson: Design Drives Conclusions</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Paired <span class="math inline">\(t\)</span> (correct)</th>
<th style="text-align: right;">Independent <span class="math inline">\(t\)</span> (wrong)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Test statistic</td>
<td style="text-align: right;"><strong>3.33</strong></td>
<td style="text-align: right;">1.51</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p\)</span>-value (two-tail)</td>
<td style="text-align: right;"><strong>0.0024</strong></td>
<td style="text-align: right;">0.138</td>
</tr>
<tr class="odd">
<td>Decision at <span class="math inline">\(\alpha = .05\)</span></td>
<td style="text-align: right;">Reject <span class="math inline">\(H_0\)</span> (B wins)</td>
<td style="text-align: right;">Fail to reject</td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Same data. Same question. Different design assumption → opposite conclusion.</strong></p></li>
<li class="fragment"><p>Why: day-to-day market swings (weekends, seasonality) inflate the independent-samples noise (<span class="math inline">\(s \approx 0.22\)</span>–<span class="math inline">\(0.34\)</span>), while pairing cancels them (<span class="math inline">\(s_d = 0.18\)</span> on the <em>differences</em>, and the A/B series are correlated at <span class="math inline">\(r = 0.88\)</span>).</p></li>
<li class="fragment"><p>The design decision was made <strong>before any data were collected</strong>, when Vungle chose to run A and B <em>in parallel within each day</em>. Good analysis starts at design, not at the formula sheet.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-3" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">How can the exact same 30 numbers say “B wins” one way and “no difference” the other? Which one is right?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> the paired test is the right one here, because the data <em>are</em> paired: A and B ran on the same days, so the days are linked, and the A/B series move together (<span class="math inline">\(r = 0.88\)</span>). The independent test throws that link away and treats day-to-day swings as random noise, which inflates the standard error and buries the $0.11 lift. Same numbers, but the wrong test answers the wrong question. Match the test to how the data were collected.</p>
</div>
</div>
</section></section>
<section>
<section id="comparing-two-proportions" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Comparing Two Proportions</h1>

</section>
<section id="vungles-other-metric-conversion-rate" class="slide level2 center">
<h2>Vungle’s Other Metric: Conversion Rate</h2>
<p><br></p>
<ul>
<li class="fragment"><p>eRPM is revenue per impression. Advertisers also watch the <strong>conversion rate</strong>: installs ÷ impressions.</p></li>
<li class="fragment"><p>The case: <em>“small improvements in the click-through or conversion rates could have a large effect on Vungle’s revenue.”</em></p></li>
<li class="fragment"><p>June 2014 totals (<code>vungle_daily.csv</code>):</p></li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Algorithm A</th>
<th style="text-align: right;">Algorithm B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Impressions</td>
<td style="text-align: right;">236,459,402</td>
<td style="text-align: right;">15,825,376</td>
</tr>
<tr class="even">
<td>Installs</td>
<td style="text-align: right;">951,666</td>
<td style="text-align: right;">56,031</td>
</tr>
<tr class="odd">
<td>Conversion rate <span class="math inline">\(\bar{p}\)</span></td>
<td style="text-align: right;"><strong>0.4025%</strong></td>
<td style="text-align: right;"><strong>0.3541%</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><strong>Question:</strong> does B convert impressions to installs at a different rate than A?</li>
</ul>
</section>
<section id="unit-of-observation-days-vs.-impressions" class="slide level2 center">
<h2>Unit of Observation: Days vs.&nbsp;Impressions</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Careful: the “sample size” just changed by seven orders of magnitude:</p>
<ul>
<li class="fragment">For <strong>eRPM</strong>, the unit was the <strong>day</strong>: <span class="math inline">\(n = 30\)</span> paired days.</li>
<li class="fragment">For <strong>conversion</strong>, the unit is the <strong>impression</strong>: each one is a Bernoulli trial (install / no install), so <span class="math inline">\(n_1 \approx 236\)</span>M and <span class="math inline">\(n_2 \approx 16\)</span>M.</li>
</ul></li>
<li class="fragment"><p>Large-sample conditions easily satisfied: <span class="math inline">\(n\bar{p} \geq 5\)</span> and <span class="math inline">\(n(1-\bar{p}) \geq 5\)</span> for both groups (e.g., <span class="math inline">\(n_2\bar{p}_2 = 56{,}031 \gg 5\)</span>).</p></li>
<li class="fragment"><p>Also note the <strong>traffic imbalance</strong>: A got ~15× B’s impressions (the 1/16 hash split). That is exactly why we compare <strong>rates</strong>, never raw counts: B’s 56K installs vs.&nbsp;A’s 952K says nothing by itself.</p></li>
<li class="fragment"><p><em>Honest caveat:</em> impressions within a day are not perfectly independent (time structure). Beyond today’s scope, but a good question to ask any A/B platform.</p></li>
</ul>
</section>
<section id="estimating-p_1---p_2" class="slide level2 center">
<h2>Estimating <span class="math inline">\(p_1 - p_2\)</span></h2>
<p><br></p>
<ul>
<li class="fragment"><p>Two independent large samples; observe <span class="math inline">\(\bar{p}_1 = x_1/n_1\)</span> and <span class="math inline">\(\bar{p}_2 = x_2/n_2\)</span>.</p></li>
<li class="fragment"><p>Point estimate: <span class="math inline">\(\bar{p}_1 - \bar{p}_2\)</span>.</p></li>
<li class="fragment"><p>Confidence interval, where each group keeps its <strong>own</strong> variance (do <strong>not</strong> pool for CIs):</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
(\bar{p}_1 - \bar{p}_2) \pm z_{\alpha/2}\sqrt{\frac{\bar{p}_1(1-\bar{p}_1)}{n_1} + \frac{\bar{p}_2(1-\bar{p}_2)}{n_2}}
\]</span></p>
</div>
</section>
<section id="testing-p_1---p_2-0-pool-under-h_0" class="slide level2 center">
<h2>Testing <span class="math inline">\(p_1 - p_2 = 0\)</span>: Pool Under <span class="math inline">\(H_0\)</span></h2>
<p><br></p>
<ul>
<li class="fragment">Under <span class="math inline">\(H_0\)</span> the two proportions are the <strong>same</strong> <span class="math inline">\(p\)</span>, so the best estimate of it uses <strong>all</strong> the data:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\bar{p} = \frac{x_1 + x_2}{n_1 + n_2}
\qquad\qquad
SE_{pool} = \sqrt{\bar{p}(1-\bar{p})\left(\frac{1}{n_1} + \frac{1}{n_2}\right)}
\]</span></p>
</div>
<ul>
<li class="fragment">Test statistic:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
z = \frac{\bar{p}_1 - \bar{p}_2}{SE_{pool}}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Decision rule and <span class="math inline">\(p\)</span>-value exactly as in the one-proportion <span class="math inline">\(z\)</span>-test (Topic 8); Excel: <code>=NORM.S.DIST</code>.</p></li>
<li class="fragment"><p><strong>Rule of thumb:</strong> pool under <span class="math inline">\(H_0\)</span> (testing); do <strong>not</strong> pool for confidence intervals.</p></li>
</ul>
</section>
<section id="do-it-in-excel-two-proportion-z-formula-cells" class="slide level2 center">
<h2>Do It in Excel: Two-Proportion <span class="math inline">\(z\)</span> (Formula Cells)</h2>
<div class="columns">
<div class="column r-fit-text" style="width:46%;">
<p><strong>Follow along (no ToolPak tool; five cells):</strong></p>
<ol type="1">
<li class="fragment">Enter <span class="math inline">\(x_1, n_1\)</span> (B installs, impressions) and <span class="math inline">\(x_2, n_2\)</span> (A).</li>
<li class="fragment">Pooled rate: <code>=(x1+x2)/(n1+n2)</code>.</li>
<li class="fragment">Pooled SE: <code>=SQRT(pbar*(1-pbar)*(1/n1+1/n2))</code>.</li>
<li class="fragment">Test statistic: <code>=(x1/n1 - x2/n2)/SE</code>.</li>
<li class="fragment"><span class="math inline">\(p\)</span>-value: <code>=2*(1-NORM.S.DIST(ABS(z),TRUE))</code> → read <span class="math inline">\(z = -29.56\)</span>, <span class="math inline">\(p &lt; 0.0001\)</span>.</li>
</ol>
<p>Worth mastering: most A/B metrics (click-through, conversion, churn) are <strong>proportions</strong>.</p>
</div><div class="column" style="width:54%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_prop_z.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="vungle-conversion-the-five-steps" class="slide level2 center">
<h2>Vungle Conversion: the Five Steps</h2>
<div class="r-fit-text">
<p><strong>1. Business context.</strong> Advertisers pay mostly per install; conversion rate signals how well ads match users.</p>
<p><strong>2. Hypotheses</strong> (two-tailed): <span class="math inline">\(H_0: p_B - p_A = 0\)</span> vs.&nbsp;<span class="math inline">\(H_a: p_B - p_A \neq 0\)</span>, <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p><strong>3. Test statistic.</strong></p>
<p><span class="math display">\[
\bar{p} = \frac{951{,}666 + 56{,}031}{236{,}459{,}402 + 15{,}825{,}376} = 0.3994\%,
\qquad SE_{pool} = 1.64 \times 10^{-5}
\]</span></p>
<p><span class="math display">\[
z = \frac{0.003541 - 0.004025}{0.0000164} = \mathbf{-29.56}
\]</span></p>
<p><strong>4. Decision.</strong> <span class="math inline">\(|z| = 29.56 \gg z_{0.025} = 1.96\)</span>; <span class="math inline">\(p\)</span>-value <span class="math inline">\(&lt; 0.0001\)</span> → <strong>reject <span class="math inline">\(H_0\)</span></strong> overwhelmingly.</p>
<p><strong>5. The Manager’s Translation.</strong> <em>B converts impressions to installs at a genuinely lower rate than A: 0.354% vs.&nbsp;0.403%, a 12% relative drop. This is not noise.</em></p>
</div>
</section>
<section id="the-surprise-b-converts-less-but-earns-more" class="slide level2 center">
<h2>The Surprise: B Converts Less but Earns More</h2>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Winner</th>
<th>Evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>eRPM (revenue per 1,000 impressions)</td>
<td><strong>B</strong></td>
<td>paired <span class="math inline">\(t = 3.33\)</span>, <span class="math inline">\(p = 0.0024\)</span></td>
</tr>
<tr class="even">
<td>Conversion rate (installs per impression)</td>
<td><strong>A</strong></td>
<td><span class="math inline">\(z = -29.56\)</span>, <span class="math inline">\(p &lt; 0.0001\)</span></td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment"><p>Both results are statistically decisive, and they <strong>point in opposite directions</strong>.</p></li>
<li class="fragment"><p>This is not a data error. It is the most realistic moment in this course: <strong>real decisions face multiple metrics that disagree.</strong></p></li>
<li class="fragment"><p>So which metric should drive the rollout?</p></li>
</ul>
</section>
<section id="make-the-call-which-metric-wins" class="slide level2 center">
<h2>Make the Call: Which Metric Wins?</h2>
<p><strong>The conflict you face as the manager:</strong> B <strong>earns more</strong> per impression (paired <span class="math inline">\(t = 3.33\)</span>) but <strong>converts fewer</strong> installs (<span class="math inline">\(z = -29.6\)</span>). Both results are statistically decisive.</p>
<p>Before the debrief, settle three questions:</p>
<ol type="1">
<li>Which metric should drive the decision for Vungle’s <strong>business model</strong>, and why?</li>
<li>What would you <strong>monitor</strong> after rollout, and why?</li>
<li>State the call in <strong>three sentences</strong>: the call, the number, the caveat.</li>
</ol>
<p>The metric that matches the business model wins, not the bigger number. We resolve it on the next slide, then land the full rollout call in the Debrief.</p>
</section>
<section id="reconciling-the-two-metrics" class="slide level2 center">
<h2>Reconciling the Two Metrics</h2>
<p><br></p>
<ul>
<li class="fragment"><p>eRPM rewards <strong>revenue per impression</strong>, not installs per impression.</p></li>
<li class="fragment"><p>The case tells us eRPM varied <strong>from $2 to $7 per campaign</strong>, and the vast majority of Vungle’s ads were <strong>CPI</strong>: advertisers pay per install, at very different prices.</p></li>
<li class="fragment"><p>So B apparently <strong>selects higher-value campaigns</strong>: fewer installs, but each install is worth more, a richer optimization target than raw conversion.</p></li>
<li class="fragment"><p>Analogy: a salesperson who closes fewer deals at much higher margins.</p></li>
<li class="fragment"><p><strong>The metric must match the business model.</strong> Vungle is a revenue-maximizing platform → eRPM is the right north star; conversion is a <em>health metric</em> to monitor.</p></li>
</ul>
</section>
<section id="statistical-vs.-practical-significance" class="slide level2 center">
<h2>Statistical vs.&nbsp;Practical Significance</h2>
<p><br></p>
<ul>
<li class="fragment"><p>With <span class="math inline">\(n\)</span> in the <strong>hundreds of millions</strong>, the conversion test was guaranteed to be “significant”: at this scale, even a microscopic difference produces a huge <span class="math inline">\(z\)</span>.</p></li>
<li class="fragment"><p><span class="math inline">\(z = -29.56\)</span> tells you the difference is <em>real</em>; it does <strong>not</strong> tell you the difference <em>matters</em>.</p></li>
<li class="fragment"><p>Always pair the test with the <strong>effect size</strong>: -0.048 percentage points (a 12% relative drop in conversion). That is the number the manager should debate.</p></li>
<li class="fragment"><p>Flip side from the equity example: small samples can make real effects invisible (low power). <strong>Large <span class="math inline">\(n\)</span>: everything is significant. Small <span class="math inline">\(n\)</span>: nothing is.</strong> Neither replaces judgment about magnitude.</p></li>
</ul>
</section>
<section id="a-question-that-often-comes-up-4" class="slide level2 center">
<h2>A Question That Often Comes Up</h2>
<div class="faq">
<p><strong>A question that often comes up at this point:</strong></p>
<p><span class="faq-q">If a <span class="math inline">\(z\)</span> of <span class="math inline">\(-29.6\)</span> does not settle the conversion question, what number should the manager actually act on?</span></p>
<div class="fragment faq-a">
<p><strong>Short answer:</strong> the effect size, not the <span class="math inline">\(z\)</span>. The <span class="math inline">\(z\)</span> only confirms the gap is not luck (with 252M trials, that was never in doubt). The number to debate is the size of the gap: <span class="math inline">\(-0.048\)</span> percentage points, a 12% relative drop in conversion. Then ask the business question the <span class="math inline">\(z\)</span> cannot: is a 12% conversion drop tolerable given B’s higher eRPM? That is a judgment call about magnitude, which is why we monitor conversion rather than block the rollout on it.</p>
</div>
</div>
</section></section>
<section>
<section id="debrief-the-rollout-call" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Debrief: The Rollout Call</h1>

</section>
<section id="three-tests-one-decision" class="slide level2 center">
<h2>Three Tests, One Decision</h2>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Result</th>
<th>Decision signal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Paired <span class="math inline">\(t\)</span>, eRPM (B vs.&nbsp;A)</td>
<td><span class="math inline">\(t = 3.33\)</span>, <span class="math inline">\(p = 0.0024\)</span></td>
<td>B earns more per impression. <strong>Roll out.</strong></td>
</tr>
<tr class="even">
<td>Independent <span class="math inline">\(t\)</span>, same data, wrong design</td>
<td><span class="math inline">\(t = 1.51\)</span>, <span class="math inline">\(p = 0.138\)</span></td>
<td>(Cautionary: wrong design would have hidden the lift.)</td>
</tr>
<tr class="odd">
<td>Two-proportion <span class="math inline">\(z\)</span>, conversion</td>
<td><span class="math inline">\(z = -29.56\)</span>, <span class="math inline">\(p &lt; 0.0001\)</span></td>
<td>B converts less. <strong>Monitor.</strong></td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li class="fragment"><strong>Your recommendation as the manager:</strong> roll out B. eRPM is the metric aligned with Vungle’s business model, the lift is statistically solid ($0.04–$0.18 per 1,000), and it is worth ≈ $26.5K/month on June’s traffic. Track the install funnel weekly post-rollout in case the lower conversion rate erodes advertiser satisfaction.</li>
</ul>
</section>
<section id="from-inference-to-decision-analysis" class="slide level2 center">
<h2>From Inference to Decision Analysis</h2>
<p><br></p>
<ul>
<li class="fragment"><p>In Topic 4 you computed expected values for <em>roll out / keep A / test first</em>. Today’s output feeds straight into that framework:</p>
<ul>
<li class="fragment">The CI <span class="math inline">\((\$0.043, \$0.181)\)</span> per 1,000 impressions is the <strong>range of payoffs</strong> for the “roll out” branch.</li>
<li class="fragment">The <span class="math inline">\(p\)</span>-value bounds the probability of the bad state (“B is not actually better”), the input Bayesian revision needs.</li>
</ul></li>
<li class="fragment"><p>This is the division of labor in analytics:</p>
<ul>
<li class="fragment"><strong>Inference</strong> (Topics 7–9): <em>what is true, and how sure are we?</em></li>
<li class="fragment"><strong>Decision analysis</strong> (Topic 4): <em>given that uncertainty, what should we do?</em></li>
</ul></li>
</ul>
</section>
<section id="two-population-tests-on-one-page-the-vungle-bridge-table" class="slide level2 center">
<h2>Two-Population Tests on One Page: the Vungle Bridge Table</h2>
<div class="r-fit-text">
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th><span class="math inline">\(H_0\)</span></th>
<th>Applied to Vungle</th>
<th>Statistic</th>
<th>Conclusion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Paired <span class="math inline">\(t\)</span></td>
<td><span class="math inline">\(\mu_d = 0\)</span></td>
<td>Daily eRPM, B - A, 30 paired days</td>
<td><span class="math inline">\(t = 3.33\)</span>, <span class="math inline">\(p = .0024\)</span></td>
<td>Reject: B earns more</td>
</tr>
<tr class="even">
<td>Welch <span class="math inline">\(t\)</span> (independent)</td>
<td><span class="math inline">\(\mu_1 - \mu_2 = 0\)</span></td>
<td>Same eRPM data, pairing ignored</td>
<td><span class="math inline">\(t = 1.51\)</span>, <span class="math inline">\(p = .138\)</span></td>
<td>Fail to reject: wrong design hides the lift</td>
</tr>
<tr class="odd">
<td>Pooled <span class="math inline">\(t\)</span></td>
<td><span class="math inline">\(\mu_1 - \mu_2 = 0\)</span></td>
<td>(Owner’s-equity anchor; equal-variance variant)</td>
<td><span class="math inline">\(t = -1.96\)</span>, <span class="math inline">\(p = .060\)</span></td>
<td>Fail to reject: low power at <span class="math inline">\(n = 15\)</span></td>
</tr>
<tr class="even">
<td>Two-sample <span class="math inline">\(z\)</span> (<span class="math inline">\(\sigma\)</span> known)</td>
<td><span class="math inline">\(\mu_1 - \mu_2 = 0\)</span></td>
<td>Rare; completeness of the decision tree</td>
<td>n/a</td>
<td>Use when <span class="math inline">\(\sigma_1, \sigma_2\)</span> truly known</td>
</tr>
<tr class="odd">
<td>Two-proportion <span class="math inline">\(z\)</span></td>
<td><span class="math inline">\(p_1 - p_2 = 0\)</span></td>
<td>Conversion: installs/impressions, 252M trials</td>
<td><span class="math inline">\(z = -29.56\)</span>, <span class="math inline">\(p &lt; .0001\)</span></td>
<td>Reject: B converts less</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="todays-question-todays-answer" class="slide level2 center">
<h2>Today’s Question, Today’s Answer</h2>
<p><br></p>
<p><strong>The question (Topic 9 of the ladder):</strong></p>
<blockquote>
<p><em>Is B really better than A?</em></p>
</blockquote>
<div class="fragment">
<p><br></p>
<p><strong>The answer we reached today:</strong></p>
<blockquote>
<p><strong>Yes, on the metric that pays the bills.</strong> Paired on 30 days, B’s mean daily eRPM beats A’s by <strong>$0.11</strong> (<span class="math inline">\(t = 3.33\)</span>, one-tail <span class="math inline">\(p = 0.0012\)</span>, 95% CI $0.04 to $0.18): a real lift, not noise. B converts fewer installs (<span class="math inline">\(z = -29.6\)</span>), but eRPM is Vungle’s north star, so the call is <strong>roll out B</strong> and monitor the install funnel.</p>
</blockquote>
</div>
</section>
<section id="the-managers-takeaway" class="slide level2 center">
<h2>The Manager’s Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> Algorithm B earns about <strong>$0.11 more per 1,000 impressions</strong> than A, and the paired test says that lift is real, not luck (<span class="math inline">\(p &lt; 0.01\)</span>): roll out B.</p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <span class="math inline">\(t = 3.33\)</span>, and where it came from: <span class="math inline">\(\bar{d}/(s_d/\sqrt{n})\)</span>.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> B’s conversion rate is <strong>lower</strong> (<span class="math inline">\(z = -29.6\)</span>); monitor the install funnel after rollout, because the eRPM advantage depends on high-value campaigns continuing to bid.</p></li>
<li class="fragment"><p><strong>Practice with the real data:</strong></p>
<ul>
<li class="fragment"><code>data/vungle_erpm_paired.csv</code> + ToolPak → reproduce <span class="math inline">\(t = 3.325\)</span> (paired) and <span class="math inline">\(t = 1.51\)</span> (unequal variances).</li>
<li class="fragment"><code>data/vungle_daily.csv</code> + five formula cells → reproduce <span class="math inline">\(z = -29.56\)</span>.</li>
<li class="fragment">Worked solutions: <code>data/vungle_ab_analysis.xlsx</code>.</li>
</ul></li>
</ul>
</section>
<section id="team-sprint-your-group-case" class="slide level2 center">
<h2>⏱️ Team Sprint: Your Group Case</h2>
<div class="sprint">
<p><strong>Now it’s your group’s turn.</strong> Today’s in-class group case is posted on <strong>Brightspace</strong> (<em>Topic 09 Group Case</em>): a separate business decision you make with today’s tools.</p>
<p><strong>What you’ll use:</strong> two-sample tests (paired <span class="math inline">\(t\)</span>, Welch <span class="math inline">\(t\)</span>, two-proportion <span class="math inline">\(z\)</span>). <strong>Excel:</strong> Analysis ToolPak → the matching <em>t-Test</em> tool, or formula cells for the proportion test.</p>
<p><strong>Submit one PDF per group before you leave:</strong> your decision plus the numbers behind it.</p>
</div>
</section></section>
<section>
<section id="wrap-up" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Wrap-up</h1>

</section>
<section id="summary" class="slide level2 center">
<h2>Summary</h2>
<p>Some key takeaways from this session:</p>
<ul>
<li><strong>Design comes first:</strong> matched (paired) samples reduce two-sample problems to one-sample problems on the differences, and remove extraneous unit-to-unit variation.</li>
<li>The paired <span class="math inline">\(t\)</span>, pooled <span class="math inline">\(t\)</span>, Welch <span class="math inline">\(t\)</span>, two-sample <span class="math inline">\(z\)</span>, and two-proportion <span class="math inline">\(z\)</span> all reuse the Topic 8 logic; only the parameter (a <strong>difference</strong>) and the standard error change.</li>
<li><strong>Default to Welch</strong> for independent means; <strong>pool only under <span class="math inline">\(H_0\)</span></strong> for proportion tests.</li>
<li>Same data, different design → different conclusion: Vungle’s lift is decisive paired (<span class="math inline">\(t = 3.33\)</span>) and invisible unpaired (<span class="math inline">\(t = 1.51\)</span>).</li>
<li>Statistical significance ≠ practical significance: with 252M impressions everything is “significant” (judge the <strong>effect size</strong>); with <span class="math inline">\(n = 15\)</span> per group, real effects can hide, so mind the <strong>power</strong>.</li>
<li>Test results are <strong>inputs to decisions</strong>, not decisions: the rollout call weighs the metric that matches the business model.</li>
<li><strong>Next time:</strong> we stop <em>comparing</em> and start <em>predicting</em> with <strong>Simple Regression</strong> (an auto-parts retailer choosing store sites).</li>
</ul>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Thank you!</h1>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Business Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>