<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Professor Davi Moreira ">
  <title>QM 6700: Business Analytics –  QM 6700: Business Analytics </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-113b5beb2a57b2deea58feb1108e76b2.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="font-size: 100%;"> QM 6700: Business Analytics </span></h1>
  <p class="subtitle"><span style="font-size: 150%;"> Multiple Regression </span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor<br>Davi Moreira<br> 
</div>
</div>
</div>

</section>
<section id="overview" class="slide level2 center">
<h2>Overview</h2>
<div class="columns">
<div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Case Spotlight: an auto-parts retailer choosing where to invest</li>
<li>One predictor to many: the multiple regression model</li>
<li>Least squares and the <strong>partial</strong> coefficient: “holding the others constant”</li>
<li>How well does the model fit? <span class="math inline">\(R^2\)</span> and <strong>adjusted</strong> <span class="math inline">\(R^2\)</span></li>
</ul>
</div><div class="column" style="width: 50%; text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Is the model useful? The overall <strong><span class="math inline">\(F\)</span>-test</strong></li>
<li>Which predictors matter? The individual <strong><span class="math inline">\(t\)</span>-tests</strong></li>
<li>A switch on or off: the <strong>dummy</strong> (indicator) variable</li>
<li>When predictors overlap: <strong>multicollinearity</strong></li>
<li>The investment call: demographics or service &amp; merchandising?</li>
</ul>
</div></div>
</section>
<section>
<section id="case-spotlight-auto-parts-retail" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Case Spotlight: Auto-Parts Retail</h1>

</section>
<section id="last-topic-we-predicted-with-one-variable.-now-we-have-four." class="slide level2 center">
<h2>Last Topic We Predicted with One Variable. Now We Have Four.</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Our client is a regional <strong>auto-parts retail chain</strong> — 45 stores, deciding where to put its next dollar.</p></li>
<li class="fragment"><p>Last time we found a single strong predictor of a store’s annual sales: its <strong>Yelp rating</strong>. Each extra star was worth roughly <strong>+$758K</strong> a year. A clean simple-regression story.</p></li>
<li class="fragment"><p>But a Yelp rating is a <em>symptom</em>, not a lever you can pull directly. The CFO’s real question is sharper:</p></li>
</ul>
<div class="fragment">
<blockquote>
<p>“We can invest in <strong>location</strong> (open stores in bigger, richer markets), in <strong>service</strong> (raise the customer experience), or in <strong>merchandising</strong> (pay for premium <strong>endcap</strong> shelf placement). <strong>Which actually drives sales — and where should the money go?</strong>”</p>
</blockquote>
</div>
<ul>
<li class="fragment">Answering that needs <strong>several predictors at once</strong> — and a way to isolate the effect of each one. That is today’s tool: <strong>multiple regression</strong>.</li>
</ul>
</section>
<section id="the-data-45-stores-four-candidate-drivers" class="slide level2 center">
<h2>The Data: 45 Stores, Four Candidate Drivers</h2>
<p><br></p>
<div style="font-size: 90%;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th>What it measures</th>
<th>The lever it represents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>sales2012_k</code></td>
<td>annual store sales ($ thousands)</td>
<td><strong>the outcome we want to grow</strong></td>
</tr>
<tr class="even">
<td><code>population_3mi</code></td>
<td>residents within 3 miles</td>
<td>location — market size</td>
</tr>
<tr class="odd">
<td><code>income_3mi</code></td>
<td>median household income within 3 miles</td>
<td>location — market wealth</td>
</tr>
<tr class="even">
<td><code>yelp_rating</code></td>
<td>average Yelp rating (1–5 stars)</td>
<td>service / customer experience</td>
</tr>
<tr class="odd">
<td><code>endcap</code></td>
<td>1 = premium endcap shelf placement, 0 = none</td>
<td>merchandising spend</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
<ul>
<li class="fragment"><p>Data: <code>data/autoparts.csv</code> — 45 rows, one per store. <code>endcap</code> is already coded <strong>0/1</strong>.</p></li>
<li class="fragment"><p><strong>The trap we will spring today:</strong> the two drivers a manager <em>expects</em> to dominate — population and income — turn out <strong>not</strong> to matter once service and merchandising are in the model.</p></li>
</ul>
</section>
<section id="how-todays-studio-runs" class="slide level2 center">
<h2>How Today’s Studio Runs</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Two lectures, two halves of the decision:</strong></p>
<ul>
<li class="fragment"><p><strong>Lecture 1 — Build &amp; read the model.</strong> Fit sales on all four drivers; interpret each <strong>partial</strong> coefficient (“holding the others constant”); judge overall fit with <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span>. Anchor: <strong>Butler Trucking</strong>.</p></li>
<li class="fragment"><p><strong>Lecture 2 — Test &amp; decide.</strong> Which drivers are <em>real</em> (<span class="math inline">\(F\)</span>-test vs.&nbsp;<span class="math inline">\(t\)</span>-tests)? Put a <strong>dollar value on an endcap</strong> with a dummy variable; check the predictors don’t overlap (multicollinearity); make the investment call.</p></li>
</ul></li>
<li class="fragment"><p>I demo each idea on a small textbook anchor → <strong>your team runs it on the auto-parts data</strong> → we debrief the recommendation together.</p></li>
<li class="fragment"><p>By the end, <strong>your team</strong> tells the CFO where to invest — with the regression to back it.</p></li>
</ul>
</section></section>
<section>
<section id="lecture-1-building-reading-the-model" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 1 — Building &amp; Reading the Model</h1>

</section>
<section id="the-brief-lecture-1" class="slide level2 center">
<h2>The Brief — Lecture 1</h2>
<p><br></p>
<blockquote>
<p>“Fit a model for store sales using <strong>all four</strong> drivers at once. For each driver, tell me its effect on sales <strong>holding the others fixed</strong> — and tell me how much of the sales story the model captures.”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p>Simple regression answered “does Yelp predict sales?” in isolation. But stores with high Yelp ratings might also sit in richer markets — so the simple slope can <strong>mix two effects together</strong>.</p></li>
<li class="fragment"><p>Multiple regression’s superpower: estimate the effect of <strong>each</strong> driver <strong>while statistically holding the others constant</strong> — the closest thing we have to a controlled comparison from observational data.</p></li>
<li class="fragment"><p>First we build the machine and learn to read its output. Testing and the dollar decision come in Lecture 2.</p></li>
</ul>
</section></section>
<section>
<section id="from-one-predictor-to-many" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>From One Predictor to Many</h1>

</section>
<section id="the-multiple-regression-model" class="slide level2 center">
<h2>The Multiple Regression Model</h2>
<p><br></p>
<ul>
<li class="fragment">With <span class="math inline">\(p\)</span> independent variables <span class="math inline">\(x_1, x_2, \ldots, x_p\)</span>, the <strong>population model</strong> is:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_p x_p + \epsilon
\]</span></p>
</div>
<ul>
<li class="fragment">The <strong>regression equation</strong> (the mean response) drops the error term:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
E(y) = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_p x_p
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Same error assumptions as before: <span class="math inline">\(E(\epsilon)=0\)</span>, constant variance <span class="math inline">\(\sigma^2\)</span>, independent errors, normally distributed.</p></li>
<li class="fragment"><p><span class="math inline">\(\beta_j\)</span> = the change in <span class="math inline">\(E(y)\)</span> for a <strong>one-unit increase in <span class="math inline">\(x_j\)</span> when all other variables are held constant.</strong> That phrase is the whole point of today.</p></li>
</ul>
</section>
<section id="a-plane-not-a-line" class="slide level2 center">
<h2>A Plane, Not a Line</h2>

<img data-src="figs/multiple_regression_plot.png" class="quarto-figure quarto-figure-center r-stretch" style="width:62.0%"><ul>
<li>With two predictors, <span class="math inline">\(E(y) = \beta_0 + \beta_1 x_1 + \beta_2 x_2\)</span> traces a <strong>plane</strong> in 3-D space; with <span class="math inline">\(p\)</span> predictors it is a <em>hyperplane</em> we can no longer draw — but the algebra is identical.</li>
<li>The vertical gap from a point to the plane is the error <span class="math inline">\(\epsilon\)</span>; least squares tilts the plane to make those gaps as small as possible.</li>
</ul>
</section>
<section id="estimating-the-coefficients-least-squares-again" class="slide level2 center">
<h2>Estimating the Coefficients: Least Squares Again</h2>
<p><br></p>
<ul>
<li class="fragment">The <strong>estimated</strong> equation replaces the unknown <span class="math inline">\(\beta\)</span>’s with sample estimates <span class="math inline">\(b\)</span>’s:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\hat{y} = b_0 + b_1 x_1 + b_2 x_2 + \cdots + b_p x_p
\]</span></p>
</div>
<ul>
<li class="fragment">Same criterion as simple regression — pick the <span class="math inline">\(b\)</span>’s that <strong>minimize the sum of squared residuals</strong>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\min \; SSE = \min \sum_{i=1}^{n} (y_i - \hat{y}_i)^2
\]</span></p>
</div>
<ul>
<li class="fragment">The closed-form solution needs matrix algebra, so we let <strong>Excel</strong> do the arithmetic. Our job is to <strong>read and interpret</strong> the output — that is where the business judgment lives.</li>
</ul>
</section>
<section id="the-partial-coefficient-the-key-idea" class="slide level2 center">
<h2>The Partial Coefficient — the Key Idea</h2>
<p><br></p>
<ul>
<li class="fragment"><p>In simple regression, <span class="math inline">\(b_1\)</span> was <em>the</em> effect of <span class="math inline">\(x\)</span> on <span class="math inline">\(y\)</span>.</p></li>
<li class="fragment"><p>In multiple regression, <span class="math inline">\(b_j\)</span> is a <strong>partial</strong> coefficient: the effect of <span class="math inline">\(x_j\)</span> on <span class="math inline">\(y\)</span> <strong>after the model has already accounted for every other predictor.</strong></p></li>
<li class="fragment"><p>Read every coefficient with the same clause attached:</p>
<ul>
<li class="fragment">“<span class="math inline">\(b_j\)</span> = the predicted change in <span class="math inline">\(y\)</span> for a one-unit increase in <span class="math inline">\(x_j\)</span>, <strong>holding all other variables constant.</strong>”</li>
</ul></li>
<li class="fragment"><p>This is why a predictor can look important alone yet vanish in the full model — its apparent effect was really the work of a variable it travels with. (We will watch exactly this happen to population and income.)</p></li>
</ul>
</section></section>
<section>
<section id="anchor-example-butler-trucking" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Anchor Example: Butler Trucking</h1>

</section>
<section id="butler-trucking-two-predictors-of-travel-time" class="slide level2 center">
<h2>Butler Trucking — Two Predictors of Travel Time</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Managers at <strong>Butler Trucking</strong> want better driver schedules. They believe a driver’s <strong>total daily travel time</strong> (<span class="math inline">\(y\)</span>, hours) depends on two things about the route:</p>
<ul>
<li class="fragment"><span class="math inline">\(x_1\)</span> = <strong>miles</strong> traveled</li>
<li class="fragment"><span class="math inline">\(x_2\)</span> = number of <strong>deliveries</strong> made</li>
</ul></li>
<li class="fragment"><p>Ten driving assignments were recorded. The proposed model:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon \qquad (n = 10,\; p = 2)
\]</span></p>
</div>
<ul>
<li class="fragment">A small, clean example — perfect for learning to read the output table before we scale up to 45 stores and four predictors.</li>
</ul>
</section>
<section id="butler-the-estimated-equation" class="slide level2 center">
<h2>Butler — the Estimated Equation</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><br></p>
<p><strong>Data → Data Analysis → Regression</strong></p>
<ul>
<li>Input Y Range: travel-time column</li>
<li>Input X Range: the <strong>two</strong> columns (miles, deliveries) together</li>
<li>Labels ✓, Confidence Level 95% ✓</li>
</ul>
<p><br></p>
<p>From the <strong>Coefficients</strong> column:</p>
<p><span class="math display">\[
\hat{y} = -0.869 + 0.0611\,x_1 + 0.923\,x_2
\]</span></p>
</div><div class="column" style="width:54%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_reg_butler_coefs.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="butler-reading-the-partial-coefficients" class="slide level2 center">
<h2>Butler — Reading the Partial Coefficients</h2>
<p><br></p>
<ul>
<li class="fragment"><p><span class="math inline">\(b_1 = +0.0611\)</span> (miles): each <strong>additional mile</strong> adds about <strong>0.061 hour</strong> (~3.7 min) to travel time — <strong>holding the number of deliveries constant.</strong></p></li>
<li class="fragment"><p><span class="math inline">\(b_2 = +0.923\)</span> (deliveries): each <strong>additional delivery</strong> adds about <strong>0.92 hour</strong> — <strong>holding miles constant.</strong></p></li>
<li class="fragment"><p><strong>Predict</strong> assignment #1 (<span class="math inline">\(x_1=100\)</span>, <span class="math inline">\(x_2=4\)</span>):</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\hat{y} = -0.869 + 0.0611(100) + 0.923(4) = 8.94 \text{ hours}
\]</span></p>
</div>
<ul>
<li class="fragment">Actual was <span class="math inline">\(9.3\)</span>, so the <strong>residual</strong> is <span class="math inline">\(9.3 - 8.94 = +0.36\)</span> hour: this route took slightly longer than the model expects.</li>
</ul>
</section></section>
<section>
<section id="how-well-does-the-model-fit" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>How Well Does the Model Fit?</h1>

</section>
<section id="partitioning-the-variation-sst-ssr-sse" class="slide level2 center">
<h2>Partitioning the Variation: SST = SSR + SSE</h2>
<p><br></p>
<ul>
<li class="fragment">Exactly as in simple regression, total variation in <span class="math inline">\(y\)</span> splits into explained + unexplained:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\underbrace{\sum (y_i - \bar{y})^2}_{SST \;(\text{total})} \;=\; \underbrace{\sum (\hat{y}_i - \bar{y})^2}_{SSR \;(\text{explained})} \;+\; \underbrace{\sum (y_i - \hat{y}_i)^2}_{SSE \;(\text{unexplained})}
\]</span></p>
</div>
<ul>
<li class="fragment">The <strong>multiple coefficient of determination</strong> is the explained share:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
R^2 = \frac{SSR}{SST} = 1 - \frac{SSE}{SST}
\]</span></p>
</div>
<ul>
<li class="fragment">For Butler: <span class="math inline">\(R^2 = 21.60 / 23.90 = 0.904\)</span> — miles and deliveries together explain about <strong>90%</strong> of the variation in travel time.</li>
</ul>
</section>
<section id="the-r2-trap-it-can-only-go-up" class="slide level2 center">
<h2>The <span class="math inline">\(R^2\)</span> Trap: It Can Only Go Up</h2>
<p><br></p>
<ul>
<li class="fragment"><p>Here is the catch that makes <span class="math inline">\(R^2\)</span> dangerous in multiple regression:</p>
<ul>
<li class="fragment"><strong>Adding <em>any</em> predictor — even a useless, random one — can only <em>increase</em> <span class="math inline">\(R^2\)</span> (never decrease it).</strong></li>
</ul></li>
<li class="fragment"><p>Why: a new variable gives least squares one more knob to fit noise, so <span class="math inline">\(SSE\)</span> shrinks and <span class="math inline">\(R^2\)</span> ticks up — whether or not the variable is real.</p></li>
<li class="fragment"><p>So a bigger <span class="math inline">\(R^2\)</span> does <strong>not</strong> mean a better model. If we chased <span class="math inline">\(R^2\)</span> alone, we would throw every variable we could find into the model.</p></li>
<li class="fragment"><p>We need a fit measure that <strong>charges a penalty</strong> for each predictor added. That is <strong>adjusted <span class="math inline">\(R^2\)</span>.</strong></p></li>
</ul>
</section>
<section id="adjusted-r2-pay-a-fee-per-predictor" class="slide level2 center">
<h2>Adjusted <span class="math inline">\(R^2\)</span> — Pay a Fee per Predictor</h2>
<div style="font-size: 90%;">
<ul>
<li class="fragment">Adjusted <span class="math inline">\(R^2\)</span> replaces the raw sums of squares with their <strong>per-degree-of-freedom</strong> versions:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
R^2_a = 1 - \frac{SSE/(n - p - 1)}{SST/(n - 1)} = 1 - (1 - R^2)\,\frac{n - 1}{n - p - 1}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>The penalty rises with <span class="math inline">\(p\)</span> (more predictors) and eases with <span class="math inline">\(n\)</span> (more data). Two consequences:</p>
<ul>
<li class="fragment"><span class="math inline">\(R^2_a \le R^2\)</span> <strong>always</strong>, and the gap widens as you add predictors.</li>
<li class="fragment"><span class="math inline">\(R^2_a\)</span> goes <strong>up only if a new predictor reduces the error variance <span class="math inline">\(s^2\)</span> (= MSE) more than the penalty costs.</strong></li>
</ul></li>
<li class="fragment"><p>That makes <span class="math inline">\(R^2_a\)</span> a real <strong>model-building criterion</strong>: compare candidate models, prefer the higher <span class="math inline">\(R^2_a\)</span>.</p></li>
<li class="fragment"><p>Butler: <span class="math inline">\(R^2 = 0.904\)</span> but <span class="math inline">\(R^2_a = 0.876\)</span> — the gap is the fee for using two predictors on only ten observations.</p></li>
</ul>
</div>
</section></section>
<section>
<section id="the-spine-model-all-four-drivers" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Spine Model: All Four Drivers</h1>

</section>
<section id="fitting-sales-on-all-four-drivers-in-excel" class="slide level2 center">
<h2>Fitting Sales on All Four Drivers in Excel</h2>
<div class="columns">
<div class="column" style="width:42%;">
<p><br></p>
<p><strong>Data → Data Analysis → Regression</strong></p>
<ul>
<li>Input Y Range: <code>sales2012_k</code></li>
<li>Input X Range: all <strong>four</strong> predictor columns (<code>population_3mi</code>, <code>income_3mi</code>, <code>yelp_rating</code>, <code>endcap</code>) — selected together</li>
<li>Labels ✓, Confidence Level 95% ✓</li>
</ul>
<p><br></p>
<p>The top block reports overall fit; we read it now and test it in Lecture 2.</p>
</div><div class="column" style="width:58%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_reg_full_stats.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-estimated-equation-for-store-sales" class="slide level2 center">
<h2>The Estimated Equation for Store Sales</h2>
<p><br></p>
<p>From the <strong>Coefficients</strong> column of the output:</p>
<div class="fragment">
<p><span class="math display">\[
\widehat{\text{sales}} = -52.1 + 0.00035\,\text{pop} + 0.0047\,\text{income} + 642.3\,\text{yelp} + 816.5\,\text{endcap}
\]</span></p>
</div>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Fit:</strong> <span class="math inline">\(R^2 = 0.932\)</span>, adjusted <span class="math inline">\(R^2 = 0.925\)</span> — the four drivers together explain about <strong>93%</strong> of the variation in store sales, and that holds up after the per-predictor penalty.</p></li>
<li class="fragment"><p>Standard error <span class="math inline">\(s = \$308.5\text{K}\)</span>: a rough “typical miss” of the model’s sales prediction.</p></li>
<li class="fragment"><p>Now the interpretation — and the surprise.</p></li>
</ul>
</section>
<section id="reading-the-partial-effects" class="slide level2 center">
<h2>Reading the Partial Effects</h2>

<img data-src="figs/autoparts_coef_effects.png" class="quarto-figure quarto-figure-center r-stretch" style="width:82.0%"><ul>
<li>Each <strong>Yelp star</strong> predicts <strong>+$642K</strong> in annual sales, holding location and merchandising fixed. An <strong>endcap</strong> predicts <strong>+$816K</strong>, holding everything else fixed.</li>
<li>The two location drivers (population, income) move the needle far less — we will test whether they matter at all next lecture.</li>
</ul>
</section>
<section id="the-surprise-bigger-market-more-sales" class="slide level2 center">
<h2>The Surprise: Bigger Market ≠ More Sales</h2>
<p><br></p>
<ul>
<li class="fragment"><p>A manager’s intuition says <strong>population</strong> and <strong>income</strong> should dominate — more people, more money, more sales.</p></li>
<li class="fragment"><p>But the partial coefficients say otherwise:</p>
<ul>
<li class="fragment"><strong>Population:</strong> <span class="math inline">\(+0.00035\)</span> → about <strong>+$0.35K per extra 1,000 residents</strong>. Essentially flat.</li>
<li class="fragment"><strong>Income:</strong> <span class="math inline">\(+0.0047\)</span> → about <strong>+$4.7K per extra $1,000 of median income</strong>. Small.</li>
</ul></li>
<li class="fragment"><p>Meanwhile <strong>service</strong> (Yelp) and <strong>merchandising</strong> (endcap) carry the model.</p></li>
<li class="fragment"><p><strong>Why the intuition fails:</strong> in simple regression a market-size variable can look strong because it travels with the variables that <em>really</em> matter. Once those are in the model, “holding the others constant” strips the borrowed credit away. We will confirm this with formal tests in Lecture 2.</p></li>
</ul>
</section>
<section id="team-sprint-1-build-read-the-model" class="slide level2 center">
<h2>⏱️ Team Sprint 1 — Build &amp; read the model</h2>
<div class="sprint">
<p><strong>Decide:</strong> what does each driver contribute to predicted store sales, holding the others constant?</p>
<p><strong>Data:</strong> <code>data/autoparts.csv</code> · <strong>Time:</strong> ~12 min</p>
<ol type="1">
<li>In Excel: <strong>Data → Data Analysis → Regression.</strong> Y = <code>sales2012_k</code>; X = the four columns <code>population_3mi</code>, <code>income_3mi</code>, <code>yelp_rating</code>, <code>endcap</code> (select together). Check <strong>Labels</strong> and <strong>Confidence Level 95%</strong>.</li>
<li>Write out the estimated equation <span class="math inline">\(\widehat{\text{sales}} = b_0 + b_1(\text{pop}) + \cdots\)</span> from the <strong>Coefficients</strong> column.</li>
<li>Record <span class="math inline">\(R^2\)</span> and <strong>Adjusted <span class="math inline">\(R^2\)</span></strong> from the top block. In one sentence, say what fraction of the sales story the model captures.</li>
<li>Translate the <strong>Yelp</strong> and <strong>endcap</strong> coefficients into plain dollars (“each extra star / an endcap is worth about $___K, holding the others fixed”).</li>
</ol>
<p><strong>Hand in (1 slide):</strong> the equation, <span class="math inline">\(R^2\)</span> vs.&nbsp;adjusted <span class="math inline">\(R^2\)</span>, and your dollar reading of the two biggest drivers.</p>
</div>
</section>
<section id="debrief-managers-takeaway-lecture-1" class="slide level2 center">
<h2>Debrief — Manager’s Takeaway (Lecture 1)</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> four drivers explain <strong>93%</strong> of store-sales variation, and the effects that matter are <strong>service (Yelp, +$642K/star)</strong> and <strong>merchandising (endcap, +$816K)</strong> — <em>not</em> the market-size variables a manager would bet on.</p></li>
<li class="fragment"><p><strong>One number:</strong> <strong>adjusted <span class="math inline">\(R^2 = 0.925\)</span></strong> — high fit that <em>survives</em> the penalty for using four predictors, so the model isn’t just padded with noise.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> “holding the others constant” is doing heavy lifting. A coefficient near zero (population, income) doesn’t prove the variable is irrelevant in the world — only that it adds little <strong>once the others are in.</strong> Next lecture we make that rigorous with the <span class="math inline">\(F\)</span>- and <span class="math inline">\(t\)</span>-tests.</p></li>
</ul>
</section>
<section id="carry-forward-to-lecture-2" class="slide level2 center">
<h2>Carry-forward (to Lecture 2)</h2>
<ul>
<li><p><strong>Your client (homework, part 1):</strong> fit a multiple regression for your team’s case with <strong>two or more</strong> predictors. Report the estimated equation, <span class="math inline">\(R^2\)</span>, and adjusted <span class="math inline">\(R^2\)</span>; interpret each coefficient with the “holding the others constant” clause.</p></li>
<li><p><strong>Next lecture:</strong> which of these drivers are <em>statistically real</em>? We separate the <strong>overall <span class="math inline">\(F\)</span>-test</strong> from the <strong>individual <span class="math inline">\(t\)</span>-tests</strong>, put a defensible <strong>dollar value on an endcap</strong> with a dummy variable, and make the investment call.</p></li>
</ul>
</section></section>
<section>
<section id="lecture-2-testing-the-investment-call" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Lecture 2 — Testing &amp; the Investment Call</h1>

</section>
<section id="the-brief-lecture-2" class="slide level2 center">
<h2>The Brief — Lecture 2</h2>
<p><br></p>
<blockquote>
<p>“The model fits well — but is each driver <em>real</em>, or could its coefficient be noise? Put a <strong>dollar figure on an endcap</strong> we can defend in a budget meeting. Then tell me: invest in <strong>location, service, or merchandising</strong>?”</p>
</blockquote>
<p><br></p>
<ul>
<li class="fragment"><p>A high <span class="math inline">\(R^2\)</span> tells us the model predicts well <strong>in aggregate</strong>. It does <strong>not</strong> tell us which individual coefficients we can trust.</p></li>
<li class="fragment"><p>Today we add the inference layer: an <strong>overall</strong> test (is the model useful at all?), <strong>individual</strong> tests (which predictors carry their weight?), the <strong>dummy variable</strong> that turns “has an endcap” into a dollar amount, and a <strong>multicollinearity</strong> check so we don’t get fooled by overlapping predictors.</p></li>
</ul>
</section></section>
<section>
<section id="is-the-model-useful-the-overall-f-test" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Is the Model Useful? The Overall <span class="math inline">\(F\)</span>-Test</h1>

</section>
<section id="f-vs.-t-different-jobs-now" class="slide level2 center">
<h2><span class="math inline">\(F\)</span> vs.&nbsp;<span class="math inline">\(t\)</span>: Different Jobs Now</h2>
<p><br></p>
<ul>
<li class="fragment"><p>In <strong>simple</strong> regression, the <span class="math inline">\(F\)</span>-test and the <span class="math inline">\(t\)</span>-test gave the <strong>same</strong> answer — there was only one predictor to judge.</p></li>
<li class="fragment"><p>In <strong>multiple</strong> regression they split into two distinct jobs:</p>
<ul>
<li class="fragment"><strong><span class="math inline">\(F\)</span>-test (overall):</strong> is the model <strong>as a whole</strong> useful — does <strong>at least one</strong> predictor carry information?</li>
<li class="fragment"><strong><span class="math inline">\(t\)</span>-tests (individual):</strong> taken <strong>one at a time</strong>, which specific predictors are pulling their weight?</li>
</ul></li>
<li class="fragment"><p>You always read them in that order: <strong><span class="math inline">\(F\)</span> first</strong> (is anything here?), then <strong><span class="math inline">\(t\)</span>’s</strong> (which things?).</p></li>
</ul>
</section>
<section id="the-f-test-hypotheses-and-statistic" class="slide level2 center">
<h2>The <span class="math inline">\(F\)</span>-Test — Hypotheses and Statistic</h2>
<p><br></p>
<ul>
<li class="fragment"><strong>Hypotheses</strong> — <span class="math inline">\(H_0\)</span> says <em>every</em> slope is zero (the model explains nothing):</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
H_0: \beta_1 = \beta_2 = \cdots = \beta_p = 0 \qquad H_a: \text{at least one } \beta_j \neq 0
\]</span></p>
</div>
<ul>
<li class="fragment"><strong>Test statistic</strong> — the ratio of explained to unexplained variation, each per degree of freedom:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
F = \frac{MSR}{MSE} = \frac{SSR/p}{SSE/(n - p - 1)} \;\sim\; F_{p,\; n-p-1} \text{ under } H_0
\]</span></p>
</div>
<ul>
<li class="fragment">Reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(F\)</span> is large (p-value <span class="math inline">\(\le \alpha\)</span>). In Excel this is the <strong>“Significance F”</strong> cell in the ANOVA block.</li>
</ul>
</section>
<section id="the-f-test-on-the-auto-parts-model" class="slide level2 center">
<h2>The <span class="math inline">\(F\)</span>-Test on the Auto-Parts Model</h2>
<p><br></p>
<p>From the ANOVA block (<span class="math inline">\(n = 45\)</span>, <span class="math inline">\(p = 4\)</span>):</p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Source</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">SS</th>
<th style="text-align: right;">MS</th>
<th style="text-align: right;"><span class="math inline">\(F\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regression</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">52,033,385</td>
<td style="text-align: right;">13,008,346</td>
<td style="text-align: right;"><strong>136.7</strong></td>
</tr>
<tr class="even">
<td>Residual</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">3,806,649</td>
<td style="text-align: right;">95,166</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">55,840,034</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p><span class="math display">\[
F = \frac{MSR}{MSE} = \frac{13{,}008{,}346}{95{,}166} = 136.7, \qquad \text{Significance } F \approx 3.4\times10^{-23}
\]</span></p>
</div>
<ul>
<li class="fragment"><span class="math inline">\(F = 136.7\)</span> with p-value far below any <span class="math inline">\(\alpha\)</span> → <strong>reject <span class="math inline">\(H_0\)</span></strong>: the model is overwhelmingly useful — <strong>at least one</strong> driver carries real information. Now, <em>which ones?</em></li>
</ul>
</section></section>
<section>
<section id="which-predictors-matter-the-t-tests" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Which Predictors Matter? The <span class="math inline">\(t\)</span>-Tests</h1>

</section>
<section id="the-individual-t-test" class="slide level2 center">
<h2>The Individual <span class="math inline">\(t\)</span>-Test</h2>
<p><br></p>
<ul>
<li class="fragment">For each predictor we ask: does it add information <strong>in the presence of all the others</strong>?</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
H_0: \beta_j = 0 \qquad H_a: \beta_j \neq 0 \qquad t = \frac{b_j}{s_{b_j}}, \quad df = n - p - 1
\]</span></p>
</div>
<ul>
<li class="fragment"><p><span class="math inline">\(s_{b_j}\)</span> is the standard error of the coefficient (Excel’s “Standard Error” column). Reject <span class="math inline">\(H_0\)</span> when the p-value <span class="math inline">\(\le \alpha\)</span>, i.e.&nbsp;roughly when <span class="math inline">\(|t| \gtrsim 2\)</span>.</p></li>
<li class="fragment"><p><strong>Critical subtlety:</strong> each <span class="math inline">\(t\)</span>-test is <em>conditional on the other predictors being in the model.</em> A predictor can be significant alone and insignificant here — because a teammate is already explaining its share.</p></li>
</ul>
</section>
<section id="reading-the-coefficient-table" class="slide level2 center">
<h2>Reading the Coefficient Table</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p><br></p>
<p>For each predictor, the output gives <strong>Coefficient</strong>, <strong>Std Error</strong>, <strong>t Stat</strong>, <strong>P-value</strong>, and a 95% CI.</p>
<ul>
<li><span class="math inline">\(|t| &gt; 2\)</span> (p &lt; 0.05) → <strong>significant</strong></li>
<li><span class="math inline">\(|t| &lt; 2\)</span> (p &gt; 0.05) → <strong>not significant</strong> <em>in this model</em></li>
</ul>
<p><br></p>
<p>Scan the <strong>t Stat</strong> column top to bottom and sort the drivers into “real” vs.&nbsp;“can’t tell.”</p>
</div><div class="column" style="width:60%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_reg_full_coefs.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-verdict-on-each-driver" class="slide level2 center">
<h2>The Verdict on Each Driver</h2>
<p><br></p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Driver</th>
<th style="text-align: right;">Coefficient</th>
<th style="text-align: right;"><span class="math inline">\(t\)</span></th>
<th style="text-align: right;">p-value</th>
<th>Significant?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Population</td>
<td style="text-align: right;">+0.00035</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">0.39</td>
<td><strong>No</strong></td>
</tr>
<tr class="even">
<td>Income</td>
<td style="text-align: right;">+0.0047</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">0.14</td>
<td><strong>No</strong></td>
</tr>
<tr class="odd">
<td>Yelp rating</td>
<td style="text-align: right;"><strong>+642.3</strong></td>
<td style="text-align: right;"><strong>16.5</strong></td>
<td style="text-align: right;">&lt; 0.0001</td>
<td><strong>Yes</strong></td>
</tr>
<tr class="even">
<td>Endcap</td>
<td style="text-align: right;"><strong>+816.5</strong></td>
<td style="text-align: right;"><strong>6.98</strong></td>
<td style="text-align: right;">&lt; 0.0001</td>
<td><strong>Yes</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p>The model is highly significant overall (<span class="math inline">\(F = 136.7\)</span>) — yet <strong>two of its four predictors are individually insignificant.</strong></p></li>
<li class="fragment"><p><strong>The lesson:</strong> a significant <span class="math inline">\(F\)</span> does <strong>not</strong> mean every variable matters. Here all the explanatory power comes from <strong>service (Yelp)</strong> and <strong>merchandising (endcap)</strong>; the location variables are statistical passengers.</p></li>
<li class="fragment"><p><em>Significance ≠ importance, and importance ≠ significance.</em> Judge each on its own evidence.</p></li>
</ul>
</section>
<section id="confirming-with-a-side-by-side-comparison" class="slide level2 center">
<h2>Confirming with a Side-by-Side Comparison</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p><br></p>
<p>Build models step by step and watch <strong>adjusted <span class="math inline">\(R^2\)</span></strong>:</p>
<ul>
<li><strong>Population + Income alone:</strong> the demographics explain almost <strong>nothing</strong>.</li>
<li><strong>Add Yelp:</strong> adjusted <span class="math inline">\(R^2\)</span> leaps.</li>
<li><strong>Add Endcap:</strong> it climbs again.</li>
</ul>
<p><br></p>
<p>The location variables a manager would buy first are the ones that move the model <strong>least</strong>.</p>
</div><div class="column" style="width:60%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/excel_model_comparison.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section></section>
<section>
<section id="the-dummy-variable-pricing-an-endcap" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>The Dummy Variable: Pricing an Endcap</h1>

</section>
<section id="a-switch-not-a-dial-encoding-has-an-endcap" class="slide level2 center">
<h2>A Switch, Not a Dial: Encoding “Has an Endcap”</h2>
<p><br></p>
<ul>
<li class="fragment"><p><code>endcap</code> isn’t a number you can have more or less of — it is a <strong>category</strong>: a store either has premium endcap placement or it doesn’t.</p></li>
<li class="fragment"><p>We encode it as a <strong>dummy (indicator) variable</strong>: <span class="math inline">\(1\)</span> = has an endcap, <span class="math inline">\(0\)</span> = none. The <span class="math inline">\(0\)</span> category is the <strong>reference</strong> (baseline) level.</p></li>
<li class="fragment"><p>Excel treats the 0/1 column <strong>like any other predictor</strong> — no special tool. Its coefficient has a special meaning:</p>
<ul>
<li class="fragment"><span class="math inline">\(b_{\text{endcap}}\)</span> = the <strong>average difference in sales between an endcap store and a non-endcap store, holding the other predictors constant.</strong></li>
</ul></li>
<li class="fragment"><p>In other words, the dummy coefficient is the <strong>dollar value of an endcap</strong> — exactly what the CFO asked for.</p></li>
</ul>
</section>
<section id="what-the-dummy-does-to-the-equation" class="slide level2 center">
<h2>What the Dummy Does to the Equation</h2>
<p><br></p>
<ul>
<li class="fragment">Split the fitted equation by the two values of the dummy (all else held fixed):</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\text{No endcap } (x=0): \quad \widehat{\text{sales}} = (b_0 + \cdots) + 642.3\,\text{yelp}
\]</span></p>
<p><span class="math display">\[
\text{Endcap } (x=1): \quad \widehat{\text{sales}} = (b_0 + 816.5 + \cdots) + 642.3\,\text{yelp}
\]</span></p>
</div>
<ul>
<li class="fragment"><p>Same slope on every other variable — only the <strong>intercept shifts up by $816.5K.</strong></p></li>
<li class="fragment"><p>A dummy gives the two groups <strong>parallel lines</strong>: identical response to Yelp, location, income — but a fixed <strong>level gap</strong> between them.</p></li>
</ul>
</section>
<section id="the-endcap-gap-drawn" class="slide level2 center">
<h2>The Endcap Gap, Drawn</h2>

<img data-src="figs/autoparts_endcap_dummy.png" class="quarto-figure quarto-figure-center r-stretch" style="width:74.0%"><ul>
<li>Two parallel lines, separated by a constant <strong>$816K</strong> — the endcap premium, holding population, income, and Yelp fixed.</li>
<li><span class="math inline">\(t = 6.98\)</span>, p &lt; 0.0001 → this gap is <strong>not</strong> noise. An endcap is a real, sizeable lever.</li>
</ul>
</section>
<section id="putting-a-defensible-number-on-the-decision" class="slide level2 center">
<h2>Putting a Defensible Number on the Decision</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Scenario:</strong> the chain plans a new store with <code>population_3mi = 120,000</code>, <code>income_3mi = 55,000</code>, <code>yelp_rating = 4.0</code>. Should it pay for endcap placement?</p></li>
<li class="fragment"><p>Plug into the fitted equation, once with <code>endcap = 0</code> and once with <code>endcap = 1</code>:</p></li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Configuration</th>
<th style="text-align: right;">Predicted annual sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Without endcap</td>
<td style="text-align: right;"><strong>$2,816K</strong></td>
</tr>
<tr class="even">
<td>With endcap</td>
<td style="text-align: right;"><strong>$3,632K</strong></td>
</tr>
<tr class="odd">
<td><strong>Lift from the endcap</strong></td>
<td style="text-align: right;"><strong>+$816K / year</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><strong>The decision rule:</strong> negotiate for the endcap <strong>if its annual cost is below ~$816K.</strong> If the placement leases for, say, $150K/year, that is a clear yes. The dummy turned a vague “merchandising matters” into a number you can put in a budget.</li>
</ul>
</section>
<section id="a-note-on-categories-with-more-than-two-levels" class="slide level2 center">
<h2>A Note on Categories with More Than Two Levels</h2>
<p><br></p>
<ul>
<li class="fragment"><p><code>endcap</code> had two levels → <strong>one</strong> dummy. The rule generalizes:</p>
<ul>
<li class="fragment">A categorical variable with <span class="math inline">\(k\)</span> levels needs <span class="math inline">\(\mathbf{k - 1}\)</span> dummy variables (one level is the reference).</li>
</ul></li>
<li class="fragment"><p>Example — three store <strong>formats</strong> (Standard, Express, Flagship): use <strong>two</strong> dummies (<code>Express</code> 0/1, <code>Flagship</code> 0/1); “Standard” is the reference. Each dummy coefficient is that format’s sales gap <strong>versus Standard</strong>.</p></li>
<li class="fragment"><p><strong>Do not</strong> encode categories as a single 1/2/3 number — that would falsely force the levels to be evenly spaced and ordered. Always use separate 0/1 columns.</p></li>
</ul>
</section></section>
<section>
<section id="when-predictors-overlap-multicollinearity" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>When Predictors Overlap: Multicollinearity</h1>

</section>
<section id="why-we-check-it" class="slide level2 center">
<h2>Why We Check It</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>Multicollinearity</strong> = two or more predictors are strongly correlated <em>with each other</em>.</p></li>
<li class="fragment"><p>When predictors overlap, the model struggles to credit the effect to one versus another. Symptoms:</p>
<ul>
<li class="fragment">coefficient <strong>standard errors inflate</strong> → wide CIs, small <span class="math inline">\(t\)</span>’s;</li>
<li class="fragment">coefficients become <strong>unstable</strong> and can flip sign;</li>
<li class="fragment">an <em>important</em> predictor can look insignificant — not because it’s useless, but because a correlated partner is absorbing its credit.</li>
</ul></li>
<li class="fragment"><p>It rarely hurts <strong>prediction</strong>, but it muddies <strong>interpretation</strong> — and interpretation is exactly what the CFO is buying.</p></li>
</ul>
</section>
<section id="detecting-it-correlations-and-vif" class="slide level2 center">
<h2>Detecting It: Correlations and VIF</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p><br></p>
<ul>
<li><p><strong>Quick look:</strong> the predictor <strong>correlation matrix</strong> (Data Analysis → Correlation). Flag any pair with <span class="math inline">\(|r| &gt; 0.7\)</span>.</p></li>
<li><p><strong>Formal measure:</strong> the <strong>Variance Inflation Factor</strong>,</p></li>
</ul>
<p><span class="math display">\[
VIF_j = \frac{1}{1 - R_j^2}
\]</span></p>
<p>where <span class="math inline">\(R_j^2\)</span> is from regressing <span class="math inline">\(x_j\)</span> on all the other predictors. <strong>Rule of thumb: investigate when VIF &gt; 5.</strong></p>
</div><div class="column" style="width:54%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/autoparts_predictor_corr.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="our-model-is-clean-so-the-verdict-stands" class="slide level2 center">
<h2>Our Model Is Clean — So the Verdict Stands</h2>
<p><br></p>
<ul>
<li class="fragment">For the auto-parts model every pairwise correlation is small (largest: income–endcap at <span class="math inline">\(-0.47\)</span>) and <strong>every VIF is below 1.7</strong> — far under the threshold of 5.</li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Predictor</th>
<th style="text-align: right;">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Population</td>
<td style="text-align: right;">1.17</td>
</tr>
<tr class="even">
<td>Income</td>
<td style="text-align: right;">1.49</td>
</tr>
<tr class="odd">
<td>Yelp rating</td>
<td style="text-align: right;">1.29</td>
</tr>
<tr class="even">
<td>Endcap</td>
<td style="text-align: right;">1.62</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p>So population and income are insignificant for an <strong>honest</strong> reason — they genuinely add little once service and merchandising are in the model. This is <strong>not</strong> a multicollinearity artifact; the verdict is trustworthy.</p></li>
<li class="fragment"><p><em>Contrast:</em> had population and income been highly correlated, we’d have to be cautious — their small <span class="math inline">\(t\)</span>’s could have been an overlap symptom rather than true irrelevance.</p></li>
</ul>
</section>
<section id="team-sprint-2-test-the-drivers-make-the-call" class="slide level2 center">
<h2>⏱️ Team Sprint 2 — Test the drivers &amp; make the call</h2>
<div class="sprint">
<p><strong>Decide:</strong> which drivers are <em>real</em>, what is an endcap worth, and where should the CFO invest?</p>
<p><strong>Data:</strong> <code>data/autoparts.csv</code> · <strong>Time:</strong> ~15 min</p>
<ol type="1">
<li>From your regression output, read <strong>Significance F</strong> (overall test) — is the model useful at all?</li>
<li>In the <strong>Coefficients</strong> table, mark each predictor <strong>significant</strong> (<span class="math inline">\(|t| &gt; 2\)</span>, p &lt; 0.05) or <strong>not</strong> — sort the four drivers into “real” vs.&nbsp;“can’t tell.”</li>
<li><strong>Price the endcap:</strong> predict sales for a planned store (<code>pop = 120,000</code>, <code>income = 55,000</code>, <code>yelp = 4.0</code>) with <code>endcap = 0</code> and with <code>endcap = 1</code>; the difference is the endcap’s dollar value.</li>
<li>State the investment call in <strong>three sentences</strong>: the lever to fund · the number · the caveat.</li>
</ol>
<p><strong>Hand in (1 slide):</strong> your significant-vs-not verdict, the endcap’s dollar value, and the CFO recommendation.</p>
</div>
</section>
<section id="debrief-managers-takeaway-lecture-2" class="slide level2 center">
<h2>Debrief — Manager’s Takeaway (Lecture 2)</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> the overall model is decisive (<span class="math inline">\(F = 136.7\)</span>), but only <strong>service (Yelp)</strong> and <strong>merchandising (endcap)</strong> survive their individual <span class="math inline">\(t\)</span>-tests — so the budget goes there, not into bigger-market real estate.</p></li>
<li class="fragment"><p><strong>One number:</strong> <strong>$816K</strong> — an endcap’s value, straight off the dummy coefficient; defensible against any lease under that figure.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> every coefficient is read “holding the other three constant” and the model is <em>descriptive</em> — pilot the endcap, then re-estimate before betting the chain on it.</p></li>
</ul>
</section></section>
<section>
<section id="debrief-the-investment-call" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Debrief — The Investment Call</h1>

</section>
<section id="the-whole-picture-on-one-page" class="slide level2 center">
<h2>The Whole Picture on One Page</h2>
<div class="r-fit-text">
<table class="caption-top">
<colgroup>
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Driver</th>
<th style="text-align: right;">Partial effect</th>
<th style="text-align: right;"><span class="math inline">\(t\)</span></th>
<th>Verdict</th>
<th>Investment read</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Population (3 mi)</td>
<td style="text-align: right;">+$0.35K / 1,000 residents</td>
<td style="text-align: right;">0.88</td>
<td>not significant</td>
<td>bigger market ≠ more sales here</td>
</tr>
<tr class="even">
<td>Income (3 mi)</td>
<td style="text-align: right;">+$4.7K / $1,000 income</td>
<td style="text-align: right;">1.50</td>
<td>not significant</td>
<td>richer market ≠ more sales here</td>
</tr>
<tr class="odd">
<td><strong>Yelp rating</strong></td>
<td style="text-align: right;"><strong>+$642K / star</strong></td>
<td style="text-align: right;"><strong>16.5</strong></td>
<td><strong>significant</strong></td>
<td><strong>invest in service / experience</strong></td>
</tr>
<tr class="even">
<td><strong>Endcap</strong></td>
<td style="text-align: right;"><strong>+$816K</strong></td>
<td style="text-align: right;"><strong>6.98</strong></td>
<td><strong>significant</strong></td>
<td><strong>buy the endcap placement</strong></td>
</tr>
</tbody>
</table>
<p>Model: <span class="math inline">\(R^2 = 0.932\)</span>, adjusted <span class="math inline">\(R^2 = 0.925\)</span>, overall <span class="math inline">\(F = 136.7\)</span> (p <span class="math inline">\(&lt; 10^{-22}\)</span>), <span class="math inline">\(s = \$308.5\)</span>K, all VIF <span class="math inline">\(&lt; 1.7\)</span>.</p>
</div>
<ul>
<li class="fragment"><strong>Recommendation to the CFO:</strong> stop chasing big, rich markets — <strong>location demographics don’t move sales</strong> in this chain. The money belongs in <strong>service quality</strong> (every Yelp star ≈ +$642K/yr) and in <strong>endcap merchandising</strong> (≈ +$816K/yr, well worth a sub-$816K lease). Both effects are statistically rock-solid and not a multicollinearity mirage.</li>
</ul>
</section>
<section id="f-vs.-t-the-lesson-that-travels" class="slide level2 center">
<h2><span class="math inline">\(F\)</span> vs.&nbsp;<span class="math inline">\(t\)</span> — the Lesson That Travels</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>The <span class="math inline">\(F\)</span>-test and the <span class="math inline">\(t\)</span>-tests answer different questions, and you need both:</strong></p>
<ul>
<li class="fragment"><span class="math inline">\(F\)</span> said the model <strong>as a whole</strong> is useful — but that alone could have tempted us to keep all four variables.</li>
<li class="fragment">The <span class="math inline">\(t\)</span>-tests revealed that <strong>half the predictors were dead weight</strong>, steering the budget toward the two that actually pay.</li>
</ul></li>
<li class="fragment"><p><strong>Significance is conditional.</strong> Every coefficient and every <span class="math inline">\(t\)</span> here means “…<em>holding the other three constant.</em>” Change the set of predictors and the story can change.</p></li>
<li class="fragment"><p><strong>Significance ≠ importance.</strong> With huge samples trivial effects turn “significant”; with small samples real effects can hide. Always pair the test with the <strong>dollar size</strong> of the effect — that is the number a manager decides on.</p></li>
</ul>
</section>
<section id="managers-takeaway" class="slide level2 center">
<h2>Manager’s Takeaway</h2>
<p><br></p>
<ul>
<li class="fragment"><p><strong>One sentence:</strong> for this 45-store chain, <strong>service and merchandising — not location demographics — drive sales</strong>, so invest in Yelp rating (+$642K/star) and endcap placement (+$816K), each statistically decisive.</p></li>
<li class="fragment"><p><strong>One number to remember:</strong> <strong>$816K</strong> — the value of an endcap, read straight off a dummy variable’s coefficient, holding everything else constant.</p></li>
<li class="fragment"><p><strong>One caveat:</strong> the model <em>describes</em> 45 existing stores; it does not <em>prove</em> that buying an endcap will <em>cause</em> +$816K at a brand-new store. Correlation control is the best we can do with observational data — pilot it, then re-estimate.</p></li>
<li class="fragment"><p><strong>Practice with the real data:</strong> <code>data/autoparts.csv</code> + Excel Regression → reproduce <span class="math inline">\(R^2 = 0.932\)</span>, <span class="math inline">\(F = 136.7\)</span>, the four coefficients, and the prediction. Worked solutions: <code>data/autoparts_regression.xlsx</code>.</p></li>
</ul>
</section>
<section id="summary" class="slide level2 center">
<h2>Summary</h2>
<p>Some key takeaways from this topic:</p>
<ul>
<li><strong>Multiple regression</strong> estimates the effect of each predictor <strong>holding the others constant</strong> — observational data’s closest move to a controlled comparison.</li>
<li>A <strong>partial coefficient</strong> can differ wildly from its simple-regression cousin: population and income looked plausible but added nothing once Yelp and endcap were in.</li>
<li><strong><span class="math inline">\(R^2\)</span> only ever rises</strong> when you add predictors → judge model size with <strong>adjusted <span class="math inline">\(R^2\)</span></strong>, which charges a fee per predictor.</li>
<li><strong><span class="math inline">\(F\)</span> first, then <span class="math inline">\(t\)</span>:</strong> <span class="math inline">\(F\)</span> asks “is the model useful at all?”; the <span class="math inline">\(t\)</span>-tests ask “which predictors carry their weight?” A significant <span class="math inline">\(F\)</span> does not bless every coefficient.</li>
<li>A <strong>dummy variable</strong> (0/1) prices a category — the endcap coefficient <em>is</em> the dollar value of an endcap; <span class="math inline">\(k\)</span> levels need <span class="math inline">\(k-1\)</span> dummies.</li>
<li><strong>Multicollinearity</strong> (overlapping predictors; check VIF &gt; 5) muddies interpretation; here every VIF &lt; 1.7, so the verdict holds.</li>
<li>Regression output is an <strong>input to a decision</strong>: translate coefficients into dollars and weigh them against costs.</li>
</ul>
</section>
<section id="carry-forward" class="slide level2 center">
<h2>Carry-forward</h2>
<ul>
<li><p><strong>Your client (homework, part 2):</strong> for your team’s case, run the <strong>overall <span class="math inline">\(F\)</span>-test</strong> and the <strong>individual <span class="math inline">\(t\)</span>-tests</strong>; if your case has a natural category, add a <strong>dummy</strong> and interpret its coefficient as a group difference. Check <strong>VIF</strong> for any predictors you suspect overlap. Close with a one-paragraph recommendation: which lever should the client pull, and what is it worth?</p></li>
<li><p><strong>Where we’ve been:</strong> from <em>comparing</em> two groups (inference) to <em>predicting</em> with one driver (simple regression) to <em>isolating many drivers at once</em> (today) — the analyst’s core toolkit for turning data into a defensible business decision.</p></li>
</ul>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Thank you!</h1>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Business Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>